<a href="https://colab.research.google.com/github/yaeji3630-hash/my-vercel-project/blob/main/%EC%9C%84%ED%97%98%EB%8F%84%EC%97%90%EB%94%B0%EB%A5%B8%EC%9D%B8%EB%A0%A5%EC%9E%AC%EB%B0%B0%EC%B9%983_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. 최종 분석 환경 구축**

1-1. Drive 연결 및 최종 파일 불러오기

In [ ]:
# =========================================================
# 1-1. Drive 연결 및 최종 분석 파일 확인
# =========================================================

from google.colab import drive
from pathlib import Path
import pandas as pd

# ---------------------------------------------------------
# 1. Google Drive 연결
# ---------------------------------------------------------

drive.mount("/content/drive")


# ---------------------------------------------------------
# 2. 프로젝트 경로 설정
# ---------------------------------------------------------

PROJECT_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도"
)

RAW_DIR = PROJECT_DIR / "01_원본데이터"
API_DIR = PROJECT_DIR / "02_API수집데이터"
PROCESSED_DIR = PROJECT_DIR / "03_전처리데이터"
RESULT_DIR = PROJECT_DIR / "04_분석결과"
VIS_DIR = PROJECT_DIR / "05_시각화"

for folder in [
    RAW_DIR,
    API_DIR,
    PROCESSED_DIR,
    RESULT_DIR,
    VIS_DIR
]:
    folder.mkdir(
        parents=True,
        exist_ok=True
    )


# ---------------------------------------------------------
# 3. 최종 분석 기준 파일 경로
# ---------------------------------------------------------

location_path = (
    PROCESSED_DIR /
    "대전_최종_물류거점_39개_좌표격자완료.csv"
)

forecast_path = (
    PROCESSED_DIR /
    "대전_43개물류창고_시간별체감온도예보_기상청공식.csv"
)

parcel_path = (
    RAW_DIR /
    "과학기술정보통신부 우정사업본부_전국 우편번호(배달지 기준)별 택배물량_20231231.csv"
)

monthly_path = (
    PROCESSED_DIR /
    "대전세종충남_1개월전망_20260723.csv"
)


# ---------------------------------------------------------
# 4. 필수 파일 존재 여부 확인
# ---------------------------------------------------------

required_files = {
    "최종 39개 물류거점": location_path,
    "시간별 체감온도 예보": forecast_path,
    "우편번호별 택배물량": parcel_path,
    "1개월 전망": monthly_path
}

print("[최종 분석 필수 파일 확인]")

all_exist = True

for name, path in required_files.items():

    exists = path.exists()

    print(
        f"{name}:",
        "정상" if exists else "없음"
    )

    print(
        "  경로:",
        path
    )

    if not exists:
        all_exist = False


# ---------------------------------------------------------
# 5. 최종 물류거점 파일 기본 검수
# ---------------------------------------------------------

if location_path.exists():

    locations = pd.read_csv(
        location_path,
        encoding="utf-8-sig",
        dtype={
            "분석거점ID": str,
            "우편번호": str
        }
    )

    print("\n[최종 물류거점 기본 검수]")

    print(
        "거점 수:",
        len(locations)
    )

    print(
        "분석거점ID 중복:",
        locations["분석거점ID"].duplicated().sum()
    )

    print(
        "좌표 미확보:",
        locations[
            ["위도", "경도"]
        ].isna().any(axis=1).sum()
    )

    print(
        "격자 미확보:",
        locations[
            ["격자X", "격자Y"]
        ].isna().any(axis=1).sum()
    )

    print(
        "우편번호 미확보:",
        locations["우편번호"].isna().sum()
    )

    print(
        "고유 기상청 격자 수:",
        locations[
            ["격자X", "격자Y"]
        ].drop_duplicates().shape[0]
    )

    display(
        locations.head()
    )


# ---------------------------------------------------------
# 6. 최종 확인
# ---------------------------------------------------------

if all_exist:

    print(
        "\n최종 분석 환경 구축 완료"
    )

else:

    print(
        "\n일부 필수 파일이 없어 경로 또는 파일명을 확인해야 합니다."
    )

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
[최종 분석 필수 파일 확인]
최종 39개 물류거점: 정상
  경로: /content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/대전_최종_물류거점_39개_좌표격자완료.csv
시간별 체감온도 예보: 정상
  경로: /content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/대전_43개물류창고_시간별체감온도예보_기상청공식.csv
우편번호별 택배물량: 정상
  경로: /content/drive/MyDrive/대전_물류창고_폭염위험도/01_원본데이터/과학기술정보통신부 우정사업본부_전국 우편번호(배달지 기준)별 택배물량_20231231.csv
1개월 전망: 정상
  경로: /content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/대전세종충남_1개월전망_20260723.csv

[최종 물류거점 기본 검수]
거점 수: 39
분석거점ID 중복: 0
좌표 미확보: 0
격자 미확보: 0
우편번호 미확보: 1
고유 기상청 격자 수: 11

,분석거점ID,대표거점명,대표주소,원본등록행수,원본_WARE_NO목록,원본_사업장명목록,원본_주소목록,우편번호,대표_보관면적,대표_일반면적,대표_냉동면적,원본_보관면적목록,원본_일반면적목록,원본_냉동면적목록,중복통합여부,위도,경도,격자X,격자Y,좌표연결등록행수
0,LOC_2000M63000000033,대전보세창고,대전광역시 대덕구 문평동로 41-16 (문평동),1,2000M63000000033,대전보세창고,대전광역시 대덕구 문평동로 41-16 (문평동),34302,NaN,NaN,NaN,NaN,NaN,NaN,개별,36.447477,127.400315,67,103,1
1,LOC_DONGWON_SANGSEO,동원로엑스 대전물류센터,대전광역시 대덕구 방두말1길 12,2,2006F63000000187 | 2025A63000000329,동원로엑스(주)대전물류센타 | 동원로엑스(주) 대전센터,"대전광역시 대덕구 방두말1길 12(상서동) | 대전광역시 대덕구 방두말1길 12, ...",34343,NaN,NaN,NaN,NaN,NaN,NaN,통합,36.429692,127.425247,68,102,2
2,LOC_2008A63000001455,씨제이대한통운(주),"대전광역시 대덕구 신탄진로 1, 대한통운 창고동 3층 (읍내동)",1,2008A63000001455,씨제이대한통운(주),"대전광역시 대덕구 신탄진로 1, 대한통운 창고동 3층 (읍내동)",34352,NaN,NaN,NaN,NaN,NaN,NaN,개별,36.383513,127.424394,68,101,1
3,LOC_2010A63000000160,(주)동원홈푸드,대전광역시 대덕구 대화로 36 (대화동),1,2010A63000000160,(주)동원홈푸드,대전광역시 대덕구 대화로 36 (대화동),34364,NaN,NaN,NaN,NaN,NaN,NaN,개별,36.367906,127.415692,68,101,1
4,LOC_CJ_MUNPYEONG,CJ대한통운 문평동 물류거점,대전광역시 대덕구 대덕대로1447번길 39,3,2010A63000001044 | 2010F63000000532 | 2012S630...,씨제이대한통운(주) | 씨제이대한통운(주) 문평동지점,대전광역시 대덕구 대덕대로1447번길 39 (문평동) | 대전광역시 대덕구 대덕대로...,34301,6486.0,26640.0,0.0,6486.0,26640.0,0.0,통합,36.449322,127.407882,68,103,3

최종 분석 환경 구축 완료

- 최종 거점: 39개
- 좌표 및 격자 11개
- 정상 연결 확인 완료

1-2. 최종 기상 및 물류 데이터 구조 통합 검수
- 데이터 병합 x
- 각 파일의 행 수, 열 이름, 기간, 중복, 핵심 결측치 확인

In [ ]:
# =========================================================
# 1-2. 최종 기상·물류 데이터 구조 통합 검수
# =========================================================

import pandas as pd

# ---------------------------------------------------------
# 1. 파일 불러오기
# ---------------------------------------------------------

locations = pd.read_csv(
    location_path,
    encoding="utf-8-sig",
    dtype={
        "분석거점ID": str,
        "우편번호": str
    }
)

forecast = pd.read_csv(
    forecast_path,
    encoding="utf-8-sig",
    dtype={"WARE_NO": str}
)

parcel = pd.read_csv(
    parcel_path,
    encoding="cp949",
    low_memory=False
)

monthly = pd.read_csv(
    monthly_path,
    encoding="utf-8-sig"
)


# ---------------------------------------------------------
# 2. 공통 구조 출력 함수
# ---------------------------------------------------------

def inspect_dataframe(name, df):

    print("\n" + "=" * 70)
    print(f"[{name}]")
    print("=" * 70)

    print("행 수:", len(df))
    print("열 수:", len(df.columns))
    print("열 이름:")
    print(df.columns.tolist())

    print("\n전체 중복 행 수:")
    print(df.duplicated().sum())

    print("\n결측치가 있는 열:")
    missing = df.isna().sum()
    missing = missing[missing > 0].sort_values(
        ascending=False
    )

    if len(missing) == 0:
        print("없음")
    else:
        print(missing.head(20))

    print("\n앞부분 확인:")
    display(df.head(3))


# ---------------------------------------------------------
# 3. 파일별 기본 구조 검수
# ---------------------------------------------------------

inspect_dataframe(
    "최종 39개 물류거점",
    locations
)

inspect_dataframe(
    "시간별 체감온도 단기예보",
    forecast
)

inspect_dataframe(
    "우편번호별 택배물량",
    parcel
)

inspect_dataframe(
    "1개월 전망",
    monthly
)


# ---------------------------------------------------------
# 4. 단기예보 핵심 시간열 자동 확인
# ---------------------------------------------------------

forecast_time_candidates = [
    "예보일시",
    "예측일시",
    "forecast_datetime",
    "일시",
    "datetime"
]

forecast_time_col = next(
    (
        col
        for col in forecast_time_candidates
        if col in forecast.columns
    ),
    None
)

print("\n" + "=" * 70)
print("[단기예보 시간 범위 검수]")
print("=" * 70)

print("확인된 시간 열:", forecast_time_col)

if forecast_time_col is not None:

    forecast[forecast_time_col] = pd.to_datetime(
        forecast[forecast_time_col],
        errors="coerce"
    )

    print(
        "시간 변환 실패:",
        forecast[forecast_time_col].isna().sum()
    )

    print(
        "최초 예보시각:",
        forecast[forecast_time_col].min()
    )

    print(
        "최종 예보시각:",
        forecast[forecast_time_col].max()
    )

    print(
        "고유 예보시각 수:",
        forecast[forecast_time_col].nunique()
    )


# ---------------------------------------------------------
# 5. 단기예보 창고·격자 연결 구조 확인
# ---------------------------------------------------------

print("\n" + "=" * 70)
print("[단기예보 연결키 검수]")
print("=" * 70)

for col in [
    "WARE_NO",
    "nx",
    "ny",
    "격자X",
    "격자Y"
]:

    if col in forecast.columns:

        print(
            f"{col} 고유값 수:",
            forecast[col].nunique(
                dropna=True
            )
        )

        print(
            f"{col} 결측:",
            forecast[col].isna().sum()
        )


# ---------------------------------------------------------
# 6. 체감온도 핵심 열 후보 확인
# ---------------------------------------------------------

heat_candidates = [
    "체감온도",
    "기상청_체감온도",
    "체감온도_공식",
    "feels_like"
]

temperature_candidates = [
    "기온",
    "TMP",
    "temperature"
]

humidity_candidates = [
    "습도",
    "REH",
    "humidity"
]

heat_col = next(
    (
        col
        for col in heat_candidates
        if col in forecast.columns
    ),
    None
)

temp_col = next(
    (
        col
        for col in temperature_candidates
        if col in forecast.columns
    ),
    None
)

humidity_col = next(
    (
        col
        for col in humidity_candidates
        if col in forecast.columns
    ),
    None
)

print("\n" + "=" * 70)
print("[단기예보 핵심 기상 열 확인]")
print("=" * 70)

print("체감온도 열:", heat_col)
print("기온 열:", temp_col)
print("습도 열:", humidity_col)

for label, col in [
    ("체감온도", heat_col),
    ("기온", temp_col),
    ("습도", humidity_col)
]:

    if col is not None:

        numeric = pd.to_numeric(
            forecast[col],
            errors="coerce"
        )

        print(
            f"\n{label} 결측:",
            numeric.isna().sum()
        )

        print(
            f"{label} 범위:",
            numeric.min(),
            "~",
            numeric.max()
        )


# ---------------------------------------------------------
# 7. 검수 완료 표시
# ---------------------------------------------------------

print("\n통합 전 데이터 구조 검수 완료")

======================================================================
[최종 39개 물류거점]
======================================================================
행 수: 39
열 수: 20
열 이름:
['분석거점ID', '대표거점명', '대표주소', '원본등록행수', '원본_WARE_NO목록', '원본_사업장명목록', '원본_주소목록', '우편번호', '대표_보관면적', '대표_일반면적', '대표_냉동면적', '원본_보관면적목록', '원본_일반면적목록', '원본_냉동면적목록', '중복통합여부', '위도', '경도', '격자X', '격자Y', '좌표연결등록행수']

전체 중복 행 수:
0

결측치가 있는 열:
대표_보관면적      13
대표_일반면적      13
대표_냉동면적      13
원본_일반면적목록    13
원본_보관면적목록    13
원본_냉동면적목록    13
우편번호          1
dtype: int64

앞부분 확인:

,분석거점ID,대표거점명,대표주소,원본등록행수,원본_WARE_NO목록,원본_사업장명목록,원본_주소목록,우편번호,대표_보관면적,대표_일반면적,대표_냉동면적,원본_보관면적목록,원본_일반면적목록,원본_냉동면적목록,중복통합여부,위도,경도,격자X,격자Y,좌표연결등록행수
0,LOC_2000M63000000033,대전보세창고,대전광역시 대덕구 문평동로 41-16 (문평동),1,2000M63000000033,대전보세창고,대전광역시 대덕구 문평동로 41-16 (문평동),34302,NaN,NaN,NaN,NaN,NaN,NaN,개별,36.447477,127.400315,67,103,1
1,LOC_DONGWON_SANGSEO,동원로엑스 대전물류센터,대전광역시 대덕구 방두말1길 12,2,2006F63000000187 | 2025A63000000329,동원로엑스(주)대전물류센타 | 동원로엑스(주) 대전센터,"대전광역시 대덕구 방두말1길 12(상서동) | 대전광역시 대덕구 방두말1길 12, ...",34343,NaN,NaN,NaN,NaN,NaN,NaN,통합,36.429692,127.425247,68,102,2
2,LOC_2008A63000001455,씨제이대한통운(주),"대전광역시 대덕구 신탄진로 1, 대한통운 창고동 3층 (읍내동)",1,2008A63000001455,씨제이대한통운(주),"대전광역시 대덕구 신탄진로 1, 대한통운 창고동 3층 (읍내동)",34352,NaN,NaN,NaN,NaN,NaN,NaN,개별,36.383513,127.424394,68,101,1

======================================================================
[시간별 체감온도 단기예보]
======================================================================
행 수: 2623
열 수: 35
열 이름:
['WARE_NO', 'COMPANY_NAME', 'COMPANY_ADDRESS', 'STORAGE_ITEM', 'STORAGE_AREA', 'GENERAL_AREA', 'FROZEN_AREA', '검색주소', '도로명주소', '지번주소', '우편번호', 'admCd', 'rnMgtSn', 'udrtYn', 'buldMnnm', 'buldSlno', '경도', '위도', '주소검색상태', '카카오검색주소', '카카오_도로명주소', '카카오_지번주소', '카카오_우편번호', '좌표검색상태', '지번표준검색주소', 'nx', 'ny', '발표시간', '예보일자', '예보시각', '예보일시', 'TMP', 'REH', '습구온도', '체감온도']

전체 중복 행 수:
0

결측치가 있는 열:
우편번호            2623
지번주소            2623
도로명주소           2623
buldMnnm        2623
udrtYn          2623
rnMgtSn         2623
admCd           2623
buldSlno        2623
주소검색상태          2623
GENERAL_AREA    1037
STORAGE_AREA    1037
FROZEN_AREA     1037
STORAGE_ITEM     915
카카오_우편번호         427
카카오_도로명주소        183
dtype: int64

앞부분 확인:

,WARE_NO,COMPANY_NAME,COMPANY_ADDRESS,STORAGE_ITEM,STORAGE_AREA,GENERAL_AREA,FROZEN_AREA,검색주소,도로명주소,지번주소,...,nx,ny,발표시간,예보일자,예보시각,예보일시,TMP,REH,습구온도,체감온도
0,2000M63000000033,대전보세창고,대전광역시 대덕구 문평동로 41-16 (문평동),일반,NaN,NaN,NaN,대전광역시 대덕구 문평동로 41-16 (문평동),NaN,NaN,...,67,103,2026072811,20260728,1200,2026-07-28 12:00:00,31.0,75.0,27.32,32.7
1,2000M63000000033,대전보세창고,대전광역시 대덕구 문평동로 41-16 (문평동),일반,NaN,NaN,NaN,대전광역시 대덕구 문평동로 41-16 (문평동),NaN,NaN,...,67,103,2026072811,20260728,1300,2026-07-28 13:00:00,32.0,70.0,27.46,33.3
2,2000M63000000033,대전보세창고,대전광역시 대덕구 문평동로 41-16 (문평동),일반,NaN,NaN,NaN,대전광역시 대덕구 문평동로 41-16 (문평동),NaN,NaN,...,67,103,2026072811,20260728,1400,2026-07-28 14:00:00,32.0,70.0,27.46,33.3

======================================================================
[우편번호별 택배물량]
======================================================================
행 수: 34502
열 수: 13
열 이름:
['우편번호', '1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월']

전체 중복 행 수:
0

결측치가 있는 열:
없음

앞부분 확인:

   우편번호   1월   2월    3월   4월   5월   6월   7월   8월   9월  10월  11월  12월
0  1000   98   84    94   80   70   81   65   87  101   72   87   91
1  1001  253  219   299  283  284  273  263  262  278  287  286  294
2  1002  723  707  1059  939  997  945  849  844  897  920  898  848

======================================================================
[1개월 전망]
======================================================================
행 수: 4
열 수: 15
열 이름:
['발표시각', '예보시작일', '예보종료일', '평년기온_하한', '평년기온_상한', '기온_낮음확률', '기온_비슷확률', '기온_높음확률', '평년강수량_하한', '평년강수량_상한', '강수_적음확률', '강수_비슷확률', '강수_많음확률', '주별전망', '평년보다_높은기온_가능성']

전체 중복 행 수:
0

결측치가 있는 열:
없음

앞부분 확인:

,발표시각,예보시작일,예보종료일,평년기온_하한,평년기온_상한,기온_낮음확률,기온_비슷확률,기온_높음확률,평년강수량_하한,평년강수량_상한,강수_적음확률,강수_비슷확률,강수_많음확률,주별전망,평년보다_높은기온_가능성
0,2026-07-23 11:00:00,2026-08-03,2026-08-09,25.9,27.3,10,30,60,20.9,51.0,30,50,20,"북태평양고기압의 영향을 받아 덥고 습하겠으며, 북쪽에서 다가오는 저기압의 영향을 받...",60
1,2026-07-23 11:00:00,2026-08-10,2026-08-16,25.2,26.8,10,40,50,12.6,67.2,40,40,20,"북태평양고기압의 영향을 받아 덥고 습하겠으며, 대기불안정에 의해 비가 내릴 때가 있겠음",50
2,2026-07-23 11:00:00,2026-08-17,2026-08-23,24.6,25.8,10,30,60,22.1,59.5,30,50,20,"북태평양고기압의 영향을 받아 덥고 습하겠으며, 서쪽에서 다가오는 저기압의 영향을 받...",60

======================================================================
[단기예보 시간 범위 검수]
======================================================================
확인된 시간 열: 예보일시
시간 변환 실패: 0
최초 예보시각: 2026-07-28 12:00:00
최종 예보시각: 2026-07-31 00:00:00
고유 예보시각 수: 61

======================================================================
[단기예보 연결키 검수]
======================================================================
WARE_NO 고유값 수: 43
WARE_NO 결측: 0
nx 고유값 수: 4
nx 결측: 0
ny 고유값 수: 6
ny 결측: 0

======================================================================
[단기예보 핵심 기상 열 확인]
======================================================================
체감온도 열: 체감온도
기온 열: TMP
습도 열: REH

체감온도 결측: 0
체감온도 범위: 25.3 ~ 34.3

기온 결측: 0
기온 범위: 22.0 ~ 33.0

습도 결측: 0
습도 범위: 60.0 ~ 100.0

통합 전 데이터 구조 검수 완료

- 최종 물류거점: 39개, 중복x
- 단기예보: 43개 원본 등록행 x 61시간 = 2,623행
- 예보 기간: 2026-07-28 12:00 ~ 2026-07-31 00:00
- 체감온도, 기온, 습도: 결측x
- 택배물량: 34,502개 우편번호, 원별 물량 결측x
- 1개월 전망: 4주 자료 정상

1-3. 43개 단기예보 39개 최종 분석 거점으로 통합

In [ ]:
# @title
# # =========================================================
# # 1-3. 43개 단기예보를 39개 최종 분석 거점으로 통합
# # =========================================================

# from pathlib import Path
# import pandas as pd
# import numpy as np

# # ---------------------------------------------------------
# # 1. 분석거점-원본 등록번호 대응표 생성
# #
# # 예:
# # LOC_CJ_MUNPYEONG
# # → 원본 WARE_NO 3개를 각각 행으로 분리
# # ---------------------------------------------------------

# location_map = (
#     locations[
#         [
#             "분석거점ID",
#             "대표거점명",
#             "대표주소",
#             "원본_WARE_NO목록",
#             "우편번호",
#             "위도",
#             "경도",
#             "격자X",
#             "격자Y"
#         ]
#     ]
#     .copy()
# )

# location_map["WARE_NO"] = (
#     location_map["원본_WARE_NO목록"]
#     .str.split(r"\s*\|\s*", regex=True)
# )

# location_map = location_map.explode(
#     "WARE_NO"
# )

# location_map["WARE_NO"] = (
#     location_map["WARE_NO"]
#     .astype(str)
#     .str.strip()
# )

# print("[거점 대응표 검수]")

# print(
#     "최종 분석 거점 수:",
#     location_map["분석거점ID"].nunique()
# )

# print(
#     "연결 대상 원본 WARE_NO 수:",
#     location_map["WARE_NO"].nunique()
# )

# print(
#     "WARE_NO 중복:",
#     location_map["WARE_NO"].duplicated().sum()
# )


# # ---------------------------------------------------------
# # 2. 예보 데이터 핵심 열 정리
# # ---------------------------------------------------------

# forecast["WARE_NO"] = (
#     forecast["WARE_NO"]
#     .astype(str)
#     .str.strip()
# )

# forecast["예보일시"] = pd.to_datetime(
#     forecast["예보일시"],
#     errors="coerce"
# )

# for col in [
#     "TMP",
#     "REH",
#     "습구온도",
#     "체감온도",
#     "nx",
#     "ny"
# ]:

#     forecast[col] = pd.to_numeric(
#         forecast[col],
#         errors="coerce"
#     )


# # ---------------------------------------------------------
# # 3. 43개 원본 예보에 최종 분석거점ID 연결
# # ---------------------------------------------------------

# forecast_linked = forecast.merge(
#     location_map[
#         [
#             "WARE_NO",
#             "분석거점ID",
#             "대표거점명",
#             "대표주소",
#             "우편번호",
#             "위도",
#             "경도",
#             "격자X",
#             "격자Y"
#         ]
#     ],
#     on="WARE_NO",
#     how="left",
#     validate="many_to_one"
# )

# print("\n[최종 거점 연결 검수]")

# print(
#     "예보 원본 행 수:",
#     len(forecast)
# )

# print(
#     "거점ID 미연결 행:",
#     forecast_linked["분석거점ID"].isna().sum()
# )

# print(
#     "연결된 원본 WARE_NO 수:",
#     forecast_linked["WARE_NO"].nunique()
# )

# print(
#     "연결된 최종 분석 거점 수:",
#     forecast_linked["분석거점ID"].nunique()
# )


# # ---------------------------------------------------------
# # 4. 동일 거점·동일 시각 내 예보값 일치 여부 검수
# #
# # 중복 등록행이 같은 물리적 거점이라면
# # 같은 시각의 기상값도 같아야 함
# # ---------------------------------------------------------

# consistency = (
#     forecast_linked
#     .groupby(
#         [
#             "분석거점ID",
#             "예보일시"
#         ],
#         as_index=False
#     )
#     .agg(
#         원본등록행수=(
#             "WARE_NO",
#             "nunique"
#         ),
#         TMP_고유값수=(
#             "TMP",
#             "nunique"
#         ),
#         REH_고유값수=(
#             "REH",
#             "nunique"
#         ),
#         체감온도_고유값수=(
#             "체감온도",
#             "nunique"
#         ),
#         nx_고유값수=(
#             "nx",
#             "nunique"
#         ),
#         ny_고유값수=(
#             "ny",
#             "nunique"
#         )
#     )
# )

# inconsistent = consistency[
#     (consistency["TMP_고유값수"] > 1)
#     | (consistency["REH_고유값수"] > 1)
#     | (consistency["체감온도_고유값수"] > 1)
#     | (consistency["nx_고유값수"] > 1)
#     | (consistency["ny_고유값수"] > 1)
# ].copy()

# print("\n[동일 거점 내 예보 일치 검수]")

# print(
#     "불일치 거점·시각 수:",
#     len(inconsistent)
# )

# if len(inconsistent) > 0:

#     display(
#         inconsistent.head(20)
#     )


# # ---------------------------------------------------------
# # 5. 39개 거점 × 61개 예보시각으로 통합
# #
# # 같은 물리적 거점의 중복 등록행은 제거하고,
# # 동일 거점·동일 시각당 1행만 유지
# # ---------------------------------------------------------

# forecast_39 = (
#     forecast_linked
#     .sort_values(
#         [
#             "분석거점ID",
#             "예보일시",
#             "WARE_NO"
#         ]
#     )
#     .groupby(
#         [
#             "분석거점ID",
#             "예보일시"
#         ],
#         as_index=False
#     )
#     .agg(
#         대표거점명=(
#             "대표거점명",
#             "first"
#         ),
#         대표주소=(
#             "대표주소",
#             "first"
#         ),
#         우편번호=(
#             "우편번호",
#             "first"
#         ),
#         위도=(
#             "위도_y",
#             "first"
#         ),
#         경도=(
#             "경도_y",
#             "first"
#         ),
#         격자X=(
#             "격자X",
#             "first"
#         ),
#         격자Y=(
#             "격자Y",
#             "first"
#         ),
#         발표시간=(
#             "발표시간",
#             "first"
#         ),
#         TMP=(
#             "TMP",
#             "mean"
#         ),
#         REH=(
#             "REH",
#             "mean"
#         ),
#         습구온도=(
#             "습구온도",
#             "mean"
#         ),
#         체감온도=(
#             "체감온도",
#             "mean"
#         ),
#         연결원본등록행수=(
#             "WARE_NO",
#             "nunique"
#         )
#     )
# )


# # ---------------------------------------------------------
# # 6. 최종 구조 검수
# # ---------------------------------------------------------

# expected_rows = (
#     locations["분석거점ID"].nunique()
#     * forecast["예보일시"].nunique()
# )

# print("\n[39개 거점 단기예보 통합 결과]")

# print(
#     "예상 행 수:",
#     expected_rows
# )

# print(
#     "실제 행 수:",
#     len(forecast_39)
# )

# print(
#     "최종 분석 거점 수:",
#     forecast_39["분석거점ID"].nunique()
# )

# print(
#     "고유 예보시각 수:",
#     forecast_39["예보일시"].nunique()
# )

# print(
#     "거점·예보시각 중복:",
#     forecast_39[
#         [
#             "분석거점ID",
#             "예보일시"
#         ]
#     ].duplicated().sum()
# )

# print(
#     "핵심 기상값 결측:",
#     forecast_39[
#         [
#             "TMP",
#             "REH",
#             "습구온도",
#             "체감온도"
#         ]
#     ].isna().any(axis=1).sum()
# )

# print(
#     "고유 기상청 격자 수:",
#     forecast_39[
#         [
#             "격자X",
#             "격자Y"
#         ]
#     ].drop_duplicates().shape[0]
# )

# print(
#     "체감온도 범위:",
#     round(forecast_39["체감온도"].min(), 1),
#     "~",
#     round(forecast_39["체감온도"].max(), 1)
# )


# # ---------------------------------------------------------
# # 7. 중복 통합 거점 확인
# # ---------------------------------------------------------

# print("\n[중복 등록행이 통합된 거점 확인]")

# display(
#     forecast_39[
#         forecast_39["연결원본등록행수"] > 1
#     ][
#         [
#             "분석거점ID",
#             "대표거점명",
#             "예보일시",
#             "TMP",
#             "REH",
#             "체감온도",
#             "연결원본등록행수"
#         ]
#     ]
#     .head(12)
# )


# # ---------------------------------------------------------
# # 8. 저장
# # ---------------------------------------------------------

# save_path = (
#     PROCESSED_DIR /
#     "대전_39개물류거점_시간별체감온도예보.csv"
# )

# forecast_39.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)

1-4. 열 이름 충돌을 방지한 39개 거점 단기예보 통합

In [ ]:
# @title
# # =========================================================
# # 1-4. 열 이름 충돌을 방지한 39개 거점 단기예보 통합
# # =========================================================

# import pandas as pd

# # ---------------------------------------------------------
# # 1. 최종 거점-원본 WARE_NO 대응표 재생성
# #
# # 병합 시 원본 예보 열과 충돌하지 않도록
# # 최종 거점 열 이름에 '거점_' 접두어를 붙임
# # ---------------------------------------------------------

# location_map = locations[
#     [
#         "분석거점ID",
#         "대표거점명",
#         "대표주소",
#         "원본_WARE_NO목록",
#         "우편번호",
#         "위도",
#         "경도",
#         "격자X",
#         "격자Y"
#     ]
# ].copy()

# location_map["WARE_NO"] = (
#     location_map["원본_WARE_NO목록"]
#     .str.split(r"\s*\|\s*", regex=True)
# )

# location_map = location_map.explode(
#     "WARE_NO"
# )

# location_map["WARE_NO"] = (
#     location_map["WARE_NO"]
#     .astype(str)
#     .str.strip()
# )

# location_map = location_map.rename(
#     columns={
#         "우편번호": "거점_우편번호",
#         "위도": "거점_위도",
#         "경도": "거점_경도",
#         "격자X": "거점_격자X",
#         "격자Y": "거점_격자Y"
#     }
# )


# # ---------------------------------------------------------
# # 2. 예보 자료 기본 형식 정리
# # ---------------------------------------------------------

# forecast["WARE_NO"] = (
#     forecast["WARE_NO"]
#     .astype(str)
#     .str.strip()
# )

# forecast["예보일시"] = pd.to_datetime(
#     forecast["예보일시"],
#     errors="coerce"
# )

# for col in [
#     "TMP",
#     "REH",
#     "습구온도",
#     "체감온도",
#     "nx",
#     "ny"
# ]:

#     forecast[col] = pd.to_numeric(
#         forecast[col],
#         errors="coerce"
#     )


# # ---------------------------------------------------------
# # 3. 예보 자료와 최종 거점 연결
# # ---------------------------------------------------------

# forecast_linked = forecast.merge(
#     location_map[
#         [
#             "WARE_NO",
#             "분석거점ID",
#             "대표거점명",
#             "대표주소",
#             "거점_우편번호",
#             "거점_위도",
#             "거점_경도",
#             "거점_격자X",
#             "거점_격자Y"
#         ]
#     ],
#     on="WARE_NO",
#     how="left",
#     validate="many_to_one"
# )


# # ---------------------------------------------------------
# # 4. 동일 거점·동일 시각 예보값 일치 검수
# # ---------------------------------------------------------

# consistency = (
#     forecast_linked
#     .groupby(
#         [
#             "분석거점ID",
#             "예보일시"
#         ],
#         as_index=False
#     )
#     .agg(
#         원본등록행수=(
#             "WARE_NO",
#             "nunique"
#         ),
#         TMP_고유값수=(
#             "TMP",
#             "nunique"
#         ),
#         REH_고유값수=(
#             "REH",
#             "nunique"
#         ),
#         체감온도_고유값수=(
#             "체감온도",
#             "nunique"
#         ),
#         nx_고유값수=(
#             "nx",
#             "nunique"
#         ),
#         ny_고유값수=(
#             "ny",
#             "nunique"
#         )
#     )
# )

# inconsistent = consistency[
#     (consistency["TMP_고유값수"] > 1)
#     | (consistency["REH_고유값수"] > 1)
#     | (consistency["체감온도_고유값수"] > 1)
#     | (consistency["nx_고유값수"] > 1)
#     | (consistency["ny_고유값수"] > 1)
# ].copy()


# # ---------------------------------------------------------
# # 5. 39개 거점 × 61시간으로 통합
# # ---------------------------------------------------------

# forecast_39 = (
#     forecast_linked
#     .sort_values(
#         [
#             "분석거점ID",
#             "예보일시",
#             "WARE_NO"
#         ]
#     )
#     .groupby(
#         [
#             "분석거점ID",
#             "예보일시"
#         ],
#         as_index=False
#     )
#     .agg(
#         대표거점명=(
#             "대표거점명",
#             "first"
#         ),
#         대표주소=(
#             "대표주소",
#             "first"
#         ),
#         우편번호=(
#             "거점_우편번호",
#             "first"
#         ),
#         위도=(
#             "거점_위도",
#             "first"
#         ),
#         경도=(
#             "거점_경도",
#             "first"
#         ),
#         격자X=(
#             "거점_격자X",
#             "first"
#         ),
#         격자Y=(
#             "거점_격자Y",
#             "first"
#         ),
#         발표시간=(
#             "발표시간",
#             "first"
#         ),
#         TMP=(
#             "TMP",
#             "mean"
#         ),
#         REH=(
#             "REH",
#             "mean"
#         ),
#         습구온도=(
#             "습구온도",
#             "mean"
#         ),
#         체감온도=(
#             "체감온도",
#             "mean"
#         ),
#         연결원본등록행수=(
#             "WARE_NO",
#             "nunique"
#         )
#     )
# )


# # ---------------------------------------------------------
# # 6. 최종 검수
# # ---------------------------------------------------------

# expected_rows = (
#     locations["분석거점ID"].nunique()
#     * forecast["예보일시"].nunique()
# )

# print("[39개 거점 단기예보 통합 결과]")

# print(
#     "거점ID 미연결 행:",
#     forecast_linked["분석거점ID"].isna().sum()
# )

# print(
#     "동일 거점 내 예보 불일치:",
#     len(inconsistent)
# )

# print(
#     "예상 행 수:",
#     expected_rows
# )

# print(
#     "실제 행 수:",
#     len(forecast_39)
# )

# print(
#     "최종 분석 거점 수:",
#     forecast_39["분석거점ID"].nunique()
# )

# print(
#     "고유 예보시각 수:",
#     forecast_39["예보일시"].nunique()
# )

# print(
#     "거점·예보시각 중복:",
#     forecast_39[
#         [
#             "분석거점ID",
#             "예보일시"
#         ]
#     ].duplicated().sum()
# )

# print(
#     "핵심 기상값 결측:",
#     forecast_39[
#         [
#             "TMP",
#             "REH",
#             "습구온도",
#             "체감온도"
#         ]
#     ].isna().any(axis=1).sum()
# )

# print(
#     "좌표 미확보:",
#     forecast_39[
#         [
#             "위도",
#             "경도"
#         ]
#     ].isna().any(axis=1).sum()
# )

# print(
#     "격자 미확보:",
#     forecast_39[
#         [
#             "격자X",
#             "격자Y"
#         ]
#     ].isna().any(axis=1).sum()
# )

# print(
#     "고유 기상청 격자 수:",
#     forecast_39[
#         [
#             "격자X",
#             "격자Y"
#         ]
#     ].drop_duplicates().shape[0]
# )

# print(
#     "우편번호 미확보 거점·시간 행:",
#     forecast_39["우편번호"].isna().sum()
# )

# print(
#     "체감온도 범위:",
#     round(forecast_39["체감온도"].min(), 1),
#     "~",
#     round(forecast_39["체감온도"].max(), 1)
# )


# # ---------------------------------------------------------
# # 7. 중복 등록행 통합 결과 확인
# # ---------------------------------------------------------

# print("\n[중복 등록행 통합 거점 예시]")

# display(
#     forecast_39[
#         forecast_39["연결원본등록행수"] > 1
#     ][
#         [
#             "분석거점ID",
#             "대표거점명",
#             "예보일시",
#             "TMP",
#             "REH",
#             "체감온도",
#             "연결원본등록행수"
#         ]
#     ]
#     .head(12)
# )


# # ---------------------------------------------------------
# # 8. 저장
# # ---------------------------------------------------------

# save_path = (
#     PROCESSED_DIR /
#     "대전_39개물류거점_시간별체감온도예보.csv"
# )

# forecast_39.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)

- 43개 원본 등록행이 39개 실제 분석 거점으로 정상 통합됨
- 39개 x 61시간 = 2,379행
- 거점 및 시간 중복 없음
- 기온, 습도, 체감온도 결측 없음
- 좌표 및 격자 결측 없음
- 중복으로 통합한 거점들의 예보값도 서로 일치함

# **1단계 결론**
- 원본 43개 물류창고 등록행의 중복을 정리해 39개 실제 분석 거점 확정
- 모든 거점에 좌표, 기상청 격자와 61시간 단기예보 중복 없이 연결
- 거점별 시간대 체감온도 위험을 분석할 수 있는 최종 기상 기반 완성

# **2. 물류부하 데이터 정제 및 거점 연결**

2-1. 우편번호 미확보 거점의 최근접 후보 검토
- 한솔로지스틱스 1개 거점은 우편번호 x -> 택배물량과 바로 연결 불가능
- 임의 값 x. 좌표상 가까운 기존 거점 5개의 주소, 우편번호, 거리 확인

In [ ]:
# @title
# # =========================================================
# # 2-1. 우편번호 미확보 거점의 최근접 후보 검토
# # =========================================================

# import pandas as pd
# import numpy as np

# # ---------------------------------------------------------
# # 1. 현재 최종 39개 거점 확인
# # ---------------------------------------------------------

# locations_check = locations.copy()

# locations_check["위도"] = pd.to_numeric(
#     locations_check["위도"],
#     errors="coerce"
# )

# locations_check["경도"] = pd.to_numeric(
#     locations_check["경도"],
#     errors="coerce"
# )

# locations_check["우편번호"] = (
#     locations_check["우편번호"]
#     .astype("string")
#     .str.replace(r"\.0$", "", regex=True)
#     .str.zfill(5)
# )

# missing_locations = locations_check[
#     locations_check["우편번호"].isna()
# ].copy()

# valid_locations = locations_check[
#     locations_check["우편번호"].notna()
# ].copy()

# print("[우편번호 결측 거점]")

# print(
#     "우편번호 미확보 거점 수:",
#     len(missing_locations)
# )

# display(
#     missing_locations[
#         [
#             "분석거점ID",
#             "대표거점명",
#             "대표주소",
#             "위도",
#             "경도",
#             "격자X",
#             "격자Y"
#         ]
#     ]
# )


# # ---------------------------------------------------------
# # 2. 좌표 사이 직선거리 계산 함수
# # ---------------------------------------------------------

# def haversine_km(lat1, lon1, lat2, lon2):

#     earth_radius = 6371.0

#     lat1 = np.radians(lat1)
#     lon1 = np.radians(lon1)
#     lat2 = np.radians(lat2)
#     lon2 = np.radians(lon2)

#     dlat = lat2 - lat1
#     dlon = lon2 - lon1

#     a = (
#         np.sin(dlat / 2) ** 2
#         + np.cos(lat1)
#         * np.cos(lat2)
#         * np.sin(dlon / 2) ** 2
#     )

#     return (
#         2
#         * earth_radius
#         * np.arcsin(np.sqrt(a))
#     )


# # ---------------------------------------------------------
# # 3. 결측 거점별 최근접 우편번호 보유 거점 5개 탐색
# # ---------------------------------------------------------

# candidate_rows = []

# for _, target in missing_locations.iterrows():

#     candidates = valid_locations.copy()

#     candidates["거리_km"] = haversine_km(
#         target["위도"],
#         target["경도"],
#         candidates["위도"],
#         candidates["경도"]
#     )

#     candidates = (
#         candidates
#         .sort_values("거리_km")
#         .head(5)
#     )

#     for rank, (_, candidate) in enumerate(
#         candidates.iterrows(),
#         start=1
#     ):

#         candidate_rows.append({
#             "미확보_분석거점ID": target["분석거점ID"],
#             "미확보_거점명": target["대표거점명"],
#             "미확보_주소": target["대표주소"],
#             "후보순위": rank,
#             "후보_분석거점ID": candidate["분석거점ID"],
#             "후보_거점명": candidate["대표거점명"],
#             "후보_주소": candidate["대표주소"],
#             "후보_우편번호": candidate["우편번호"],
#             "후보_격자X": candidate["격자X"],
#             "후보_격자Y": candidate["격자Y"],
#             "동일기상격자여부": (
#                 target["격자X"] == candidate["격자X"]
#                 and target["격자Y"] == candidate["격자Y"]
#             ),
#             "거리_km": round(
#                 candidate["거리_km"],
#                 3
#             )
#         })


# nearest_candidates = pd.DataFrame(
#     candidate_rows
# )

# print("\n[최근접 우편번호 후보]")

# display(nearest_candidates)


# # ---------------------------------------------------------
# # 4. 후보 우편번호가 택배물량 원자료에 존재하는지 확인
# # ---------------------------------------------------------

# parcel_zip_set = set(
#     parcel["우편번호"]
#     .astype(str)
#     .str.replace(r"\.0$", "", regex=True)
#     .str.zfill(5)
# )

# nearest_candidates[
#     "택배물량자료_존재"
# ] = nearest_candidates[
#     "후보_우편번호"
# ].isin(parcel_zip_set)

# print("\n[택배물량 자료 연결 가능 여부]")

# display(
#     nearest_candidates[
#         [
#             "미확보_거점명",
#             "후보순위",
#             "후보_거점명",
#             "후보_주소",
#             "후보_우편번호",
#             "거리_km",
#             "동일기상격자여부",
#             "택배물량자료_존재"
#         ]
#     ]
# )


# # ---------------------------------------------------------
# # 5. 결과 저장
# # ---------------------------------------------------------

# save_path = (
#     PROCESSED_DIR /
#     "우편번호미확보_거점_최근접후보.csv"
# )

# nearest_candidates.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)

- 한솔로지스틱스 주식회사와 한솔로지스틱스 신탄진CY가 동일 거점 가능성
- 두 등록행의 원본 주소, 좌표, 시설정보 직접 비교

2-2. 한솔로지스틱스 2개 거점의 동일 부지 여부 정밀 검수

In [ ]:
# @title
# # =========================================================
# # 2-2. 한솔로지스틱스 2개 거점의 동일 부지 여부 정밀 검수
# # =========================================================

# from pathlib import Path
# import pandas as pd
# import numpy as np

# # ---------------------------------------------------------
# # 1. 원본 43개 창고 좌표·격자 파일 불러오기
# # ---------------------------------------------------------

# source_path = (
#     PROCESSED_DIR /
#     "대전_물류창고_좌표_기상청격자.csv"
# )

# source_43 = pd.read_csv(
#     source_path,
#     encoding="utf-8-sig",
#     dtype={
#         "WARE_NO": str,
#         "우편번호": str,
#         "카카오_우편번호": str
#     }
# )

# # 검토 대상 등록번호
# target_ware_nos = [
#     "2016S63000000001",  # 우편번호 미확보 한솔로지스틱스
#     "2014M63000000423"   # 한솔로지스틱스 신탄진CY
# ]

# hansol = source_43[
#     source_43["WARE_NO"].isin(target_ware_nos)
# ].copy()

# print("[한솔로지스틱스 원본 등록행]")

# print("검토 대상 행 수:", len(hansol))

# # ---------------------------------------------------------
# # 2. 좌표 숫자형 변환
# # ---------------------------------------------------------

# hansol["위도"] = pd.to_numeric(
#     hansol["위도"],
#     errors="coerce"
# )

# hansol["경도"] = pd.to_numeric(
#     hansol["경도"],
#     errors="coerce"
# )


# # ---------------------------------------------------------
# # 3. 두 지점 사이 거리 계산
# # ---------------------------------------------------------

# def haversine_m(lat1, lon1, lat2, lon2):

#     earth_radius = 6371000.0

#     lat1, lon1, lat2, lon2 = map(
#         np.radians,
#         [lat1, lon1, lat2, lon2]
#     )

#     dlat = lat2 - lat1
#     dlon = lon2 - lon1

#     a = (
#         np.sin(dlat / 2) ** 2
#         + np.cos(lat1)
#         * np.cos(lat2)
#         * np.sin(dlon / 2) ** 2
#     )

#     return (
#         2
#         * earth_radius
#         * np.arcsin(np.sqrt(a))
#     )


# if len(hansol) == 2:

#     row1 = hansol.iloc[0]
#     row2 = hansol.iloc[1]

#     distance_m = haversine_m(
#         row1["위도"],
#         row1["경도"],
#         row2["위도"],
#         row2["경도"]
#     )

# else:

#     distance_m = np.nan


# # ---------------------------------------------------------
# # 4. 비교에 필요한 원본 정보 출력
# # ---------------------------------------------------------

# compare_cols = [
#     "WARE_NO",
#     "COMPANY_NAME",
#     "COMPANY_ADDRESS",
#     "검색주소",
#     "도로명주소",
#     "지번주소",
#     "카카오검색주소",
#     "카카오_도로명주소",
#     "카카오_지번주소",
#     "우편번호",
#     "카카오_우편번호",
#     "STORAGE_ITEM",
#     "STORAGE_AREA",
#     "GENERAL_AREA",
#     "FROZEN_AREA",
#     "위도",
#     "경도",
#     "nx",
#     "ny"
# ]

# compare_cols = [
#     col
#     for col in compare_cols
#     if col in hansol.columns
# ]

# print("\n[두 등록행 상세 비교]")

# display(
#     hansol[compare_cols].T
# )

# print(
#     "\n두 좌표 사이 거리:",
#     round(distance_m, 2),
#     "m"
# )


# # ---------------------------------------------------------
# # 5. 주요 조건 자동 비교
# # ---------------------------------------------------------

# if len(hansol) == 2:

#     same_grid = (
#         row1["nx"] == row2["nx"]
#         and row1["ny"] == row2["ny"]
#     )

#     same_company_keyword = (
#         "한솔로지스틱스" in str(row1["COMPANY_NAME"])
#         and "한솔로지스틱스" in str(row2["COMPANY_NAME"])
#     )

#     print("\n[동일 거점 판단 보조지표]")

#     print(
#         "동일 회사명 계열:",
#         same_company_keyword
#     )

#     print(
#         "동일 기상청 격자:",
#         same_grid
#     )

#     print(
#         "좌표 30m 이내:",
#         distance_m <= 30
#     )


# # ---------------------------------------------------------
# # 6. 검수 결과 저장
# # ---------------------------------------------------------

# save_path = (
#     PROCESSED_DIR /
#     "한솔로지스틱스_동일거점_정밀검수.csv"
# )

# hansol.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)

- 카카오 도로명 주소, 지번주소, 우편번호 동일
- 동일 물류거점으로 확정
- 최종 분석 거점 38개

2-3. 한솔로지스틱스 중복 통합 및 38개 최종 거점 생성

In [ ]:
# @title
# # =========================================================
# # 2-3. 한솔로지스틱스 중복 통합 및 38개 최종 거점 생성
# # =========================================================

# from pathlib import Path
# import pandas as pd
# import numpy as np

# PROCESSED_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
# )

# # ---------------------------------------------------------
# # 1. 기존 39개 최종 거점 불러오기
# # ---------------------------------------------------------

# path_39 = (
#     PROCESSED_DIR /
#     "대전_최종_물류거점_39개_좌표격자완료.csv"
# )

# locations_39 = pd.read_csv(
#     path_39,
#     encoding="utf-8-sig",
#     dtype={
#         "분석거점ID": str,
#         "우편번호": str
#     }
# )

# print("통합 전 거점 수:", len(locations_39))


# # ---------------------------------------------------------
# # 2. 한솔로지스틱스 통합 대상 정의
# # ---------------------------------------------------------

# target_ids = [
#     "LOC_2014M63000000423",
#     "LOC_2016S63000000001"
# ]

# target = locations_39[
#     locations_39["분석거점ID"].isin(target_ids)
# ].copy()

# others = locations_39[
#     ~locations_39["분석거점ID"].isin(target_ids)
# ].copy()

# print("한솔 통합 대상 수:", len(target))


# # ---------------------------------------------------------
# # 3. 보조 함수
# # ---------------------------------------------------------

# def unique_text(series):

#     values = (
#         series.dropna()
#         .astype(str)
#         .str.strip()
#     )

#     values = [
#         value
#         for value in values.unique()
#         if value
#     ]

#     return " | ".join(values)


# def max_valid(series):

#     numeric = pd.to_numeric(
#         series,
#         errors="coerce"
#     )

#     if numeric.notna().sum() == 0:
#         return np.nan

#     return numeric.max()


# # ---------------------------------------------------------
# # 4. 한솔 통합 거점 1행 생성
# # ---------------------------------------------------------

# hansol_row = {
#     "분석거점ID": "LOC_HANSOL_SINTANJIN",

#     "대표거점명": "한솔로지스틱스 신탄진CY",

#     "대표주소": (
#         "대전광역시 대덕구 평촌2길 59"
#     ),

#     "원본등록행수": int(
#         target["원본등록행수"].sum()
#     ),

#     "원본_WARE_NO목록": unique_text(
#         target["원본_WARE_NO목록"]
#     ),

#     "원본_사업장명목록": unique_text(
#         target["원본_사업장명목록"]
#     ),

#     "원본_주소목록": unique_text(
#         target["원본_주소목록"]
#     ),

#     "우편번호": "34341",

#     "대표_보관면적": max_valid(
#         target["대표_보관면적"]
#     ),

#     "대표_일반면적": max_valid(
#         target["대표_일반면적"]
#     ),

#     "대표_냉동면적": max_valid(
#         target["대표_냉동면적"]
#     ),

#     "원본_보관면적목록": unique_text(
#         target["원본_보관면적목록"]
#     ),

#     "원본_일반면적목록": unique_text(
#         target["원본_일반면적목록"]
#     ),

#     "원본_냉동면적목록": unique_text(
#         target["원본_냉동면적목록"]
#     ),

#     "중복통합여부": "통합",

#     # 동일 부지 좌표이므로 중앙값 사용
#     "위도": pd.to_numeric(
#         target["위도"],
#         errors="coerce"
#     ).median(),

#     "경도": pd.to_numeric(
#         target["경도"],
#         errors="coerce"
#     ).median(),

#     "격자X": pd.to_numeric(
#         target["격자X"],
#         errors="coerce"
#     ).iloc[0],

#     "격자Y": pd.to_numeric(
#         target["격자Y"],
#         errors="coerce"
#     ).iloc[0],

#     "좌표연결등록행수": int(
#         target["좌표연결등록행수"].sum()
#     )
# }


# # ---------------------------------------------------------
# # 5. 38개 최종 거점 생성
# # ---------------------------------------------------------

# locations_38 = pd.concat(
#     [
#         others,
#         pd.DataFrame([hansol_row])
#     ],
#     ignore_index=True
# )

# locations_38 = locations_38.sort_values(
#     "분석거점ID"
# ).reset_index(drop=True)


# # ---------------------------------------------------------
# # 6. 최소 검수
# # ---------------------------------------------------------

# print("\n[38개 최종 거점 검수]")

# print(
#     "최종 거점 수:",
#     len(locations_38)
# )

# print(
#     "분석거점ID 중복:",
#     locations_38[
#         "분석거점ID"
#     ].duplicated().sum()
# )

# print(
#     "우편번호 미확보:",
#     locations_38[
#         "우편번호"
#     ].isna().sum()
# )

# print(
#     "좌표 미확보:",
#     locations_38[
#         ["위도", "경도"]
#     ].isna().any(axis=1).sum()
# )

# print(
#     "격자 미확보:",
#     locations_38[
#         ["격자X", "격자Y"]
#     ].isna().any(axis=1).sum()
# )

# print(
#     "고유 기상청 격자 수:",
#     locations_38[
#         ["격자X", "격자Y"]
#     ].drop_duplicates().shape[0]
# )

# print(
#     "원본 등록행 수 합계:",
#     locations_38[
#         "원본등록행수"
#     ].sum()
# )


# # ---------------------------------------------------------
# # 7. 한솔 통합 결과 확인
# # ---------------------------------------------------------

# print("\n[한솔 통합 거점 확인]")

# display(
#     locations_38[
#         locations_38["분석거점ID"]
#         == "LOC_HANSOL_SINTANJIN"
#     ][
#         [
#             "분석거점ID",
#             "대표거점명",
#             "대표주소",
#             "원본등록행수",
#             "원본_WARE_NO목록",
#             "원본_사업장명목록",
#             "우편번호",
#             "위도",
#             "경도",
#             "격자X",
#             "격자Y"
#         ]
#     ]
# )


# # ---------------------------------------------------------
# # 8. 저장
# # ---------------------------------------------------------

# save_path = (
#     PROCESSED_DIR /
#     "대전_최종_물류거점_38개_좌표격자우편번호완료.csv"
# )

# locations_38.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)

- 최종 물류거점: 38개
- 원본 등록행 합계: 43개
- 우편번호, 좌표, 격자 미확보: 0개
- 고유 기상청 격자: 11개

2-4. 시간별 단기예보를 38개 최종 거점 기준으로 수정

In [ ]:
# @title
# # =========================================================
# # 2-4. 시간별 단기예보를 38개 최종 거점 기준으로 수정
# # =========================================================

# from pathlib import Path
# import pandas as pd
# import numpy as np

# PROCESSED_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
# )

# # ---------------------------------------------------------
# # 1. 기존 39개 거점 시간별 예보 불러오기
# # ---------------------------------------------------------

# forecast_39_path = (
#     PROCESSED_DIR /
#     "대전_39개물류거점_시간별체감온도예보.csv"
# )

# forecast_39 = pd.read_csv(
#     forecast_39_path,
#     encoding="utf-8-sig",
#     dtype={
#         "분석거점ID": str,
#         "우편번호": str
#     }
# )

# forecast_39["예보일시"] = pd.to_datetime(
#     forecast_39["예보일시"],
#     errors="coerce"
# )

# print("수정 전 거점 수:", forecast_39["분석거점ID"].nunique())
# print("수정 전 행 수:", len(forecast_39))


# # ---------------------------------------------------------
# # 2. 한솔로지스틱스 두 거점을 하나의 ID로 변경
# # ---------------------------------------------------------

# hansol_old_ids = [
#     "LOC_2014M63000000423",
#     "LOC_2016S63000000001"
# ]

# forecast_38_base = forecast_39.copy()

# forecast_38_base.loc[
#     forecast_38_base["분석거점ID"].isin(hansol_old_ids),
#     "분석거점ID"
# ] = "LOC_HANSOL_SINTANJIN"


# # ---------------------------------------------------------
# # 3. 한솔 통합 거점 정보 적용
# # ---------------------------------------------------------

# hansol_mask = (
#     forecast_38_base["분석거점ID"]
#     == "LOC_HANSOL_SINTANJIN"
# )

# forecast_38_base.loc[
#     hansol_mask,
#     "대표거점명"
# ] = "한솔로지스틱스 신탄진CY"

# forecast_38_base.loc[
#     hansol_mask,
#     "대표주소"
# ] = "대전광역시 대덕구 평촌2길 59"

# forecast_38_base.loc[
#     hansol_mask,
#     "우편번호"
# ] = "34341"

# # 2-3에서 산출한 최종 한솔 대표 좌표
# hansol_location = locations_38[
#     locations_38["분석거점ID"]
#     == "LOC_HANSOL_SINTANJIN"
# ].iloc[0]

# forecast_38_base.loc[
#     hansol_mask,
#     "위도"
# ] = hansol_location["위도"]

# forecast_38_base.loc[
#     hansol_mask,
#     "경도"
# ] = hansol_location["경도"]

# forecast_38_base.loc[
#     hansol_mask,
#     "격자X"
# ] = hansol_location["격자X"]

# forecast_38_base.loc[
#     hansol_mask,
#     "격자Y"
# ] = hansol_location["격자Y"]


# # ---------------------------------------------------------
# # 4. 동일 거점·동일 예보시각의 기상값 일치 여부 확인
# # ---------------------------------------------------------

# consistency = (
#     forecast_38_base
#     .groupby(
#         ["분석거점ID", "예보일시"],
#         as_index=False
#     )
#     .agg(
#         TMP_고유값수=("TMP", "nunique"),
#         REH_고유값수=("REH", "nunique"),
#         습구온도_고유값수=("습구온도", "nunique"),
#         체감온도_고유값수=("체감온도", "nunique")
#     )
# )

# inconsistent = consistency[
#     (consistency["TMP_고유값수"] > 1)
#     | (consistency["REH_고유값수"] > 1)
#     | (consistency["습구온도_고유값수"] > 1)
#     | (consistency["체감온도_고유값수"] > 1)
# ]

# print("\n[한솔 통합 전 예보 일치 검수]")

# print(
#     "동일 거점·시각 기상값 불일치:",
#     len(inconsistent)
# )


# # ---------------------------------------------------------
# # 5. 38개 거점 × 예보시각으로 재통합
# # ---------------------------------------------------------

# forecast_38 = (
#     forecast_38_base
#     .groupby(
#         ["분석거점ID", "예보일시"],
#         as_index=False
#     )
#     .agg(
#         대표거점명=("대표거점명", "first"),
#         대표주소=("대표주소", "first"),
#         우편번호=("우편번호", "first"),
#         위도=("위도", "first"),
#         경도=("경도", "first"),
#         격자X=("격자X", "first"),
#         격자Y=("격자Y", "first"),
#         발표시간=("발표시간", "first"),
#         TMP=("TMP", "mean"),
#         REH=("REH", "mean"),
#         습구온도=("습구온도", "mean"),
#         체감온도=("체감온도", "mean"),
#         연결원본등록행수=("연결원본등록행수", "sum")
#     )
# )


# # ---------------------------------------------------------
# # 6. 최종 검수
# # ---------------------------------------------------------

# expected_rows = (
#     locations_38["분석거점ID"].nunique()
#     * forecast_38["예보일시"].nunique()
# )

# print("\n[38개 거점 시간별 예보 수정 결과]")

# print(
#     "예상 행 수:",
#     expected_rows
# )

# print(
#     "실제 행 수:",
#     len(forecast_38)
# )

# print(
#     "최종 분석 거점 수:",
#     forecast_38["분석거점ID"].nunique()
# )

# print(
#     "고유 예보시각 수:",
#     forecast_38["예보일시"].nunique()
# )

# print(
#     "거점·예보시각 중복:",
#     forecast_38[
#         ["분석거점ID", "예보일시"]
#     ].duplicated().sum()
# )

# print(
#     "핵심 기상값 결측:",
#     forecast_38[
#         ["TMP", "REH", "습구온도", "체감온도"]
#     ].isna().any(axis=1).sum()
# )

# print(
#     "우편번호 미확보:",
#     forecast_38["우편번호"].isna().sum()
# )

# print(
#     "좌표 미확보:",
#     forecast_38[
#         ["위도", "경도"]
#     ].isna().any(axis=1).sum()
# )

# print(
#     "격자 미확보:",
#     forecast_38[
#         ["격자X", "격자Y"]
#     ].isna().any(axis=1).sum()
# )

# print(
#     "고유 기상청 격자 수:",
#     forecast_38[
#         ["격자X", "격자Y"]
#     ].drop_duplicates().shape[0]
# )

# print(
#     "체감온도 범위:",
#     round(forecast_38["체감온도"].min(), 1),
#     "~",
#     round(forecast_38["체감온도"].max(), 1)
# )


# # ---------------------------------------------------------
# # 7. 한솔 통합 예보 확인
# # ---------------------------------------------------------

# print("\n[한솔 통합 거점 예보 확인]")

# display(
#     forecast_38[
#         forecast_38["분석거점ID"]
#         == "LOC_HANSOL_SINTANJIN"
#     ][
#         [
#             "분석거점ID",
#             "대표거점명",
#             "예보일시",
#             "TMP",
#             "REH",
#             "체감온도",
#             "우편번호",
#             "연결원본등록행수"
#         ]
#     ].head(10)
# )


# # ---------------------------------------------------------
# # 8. 저장
# # ---------------------------------------------------------

# save_path = (
#     PROCESSED_DIR /
#     "대전_38개물류거점_시간별체감온도예보.csv"
# )

# forecast_38.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)

2-5. 38개 거점과 우편번호별 택배물량 연결 검수

In [ ]:
# =========================================================
# 2-5. 38개 거점과 우편번호별 택배물량 연결 검수
# =========================================================

from pathlib import Path
import pandas as pd
import numpy as np

PROCESSED_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
)

# ---------------------------------------------------------
# 1. 38개 최종 거점 파일 불러오기
# ---------------------------------------------------------

location_path = (
    PROCESSED_DIR /
    "대전_최종_물류거점_38개_좌표격자우편번호완료.csv"
)

locations_38 = pd.read_csv(
    location_path,
    encoding="utf-8-sig",
    dtype={
        "분석거점ID": str,
        "우편번호": str
    }
)

# 우편번호를 5자리 문자열로 통일
locations_38["우편번호"] = (
    locations_38["우편번호"]
    .astype("string")
    .str.replace(r"\.0$", "", regex=True)
    .str.zfill(5)
)


# ---------------------------------------------------------
# 2. 우편번호별 택배물량 형식 정리
# ---------------------------------------------------------

parcel_clean = parcel.copy()

parcel_clean["우편번호"] = (
    parcel_clean["우편번호"]
    .astype("string")
    .str.replace(r"\.0$", "", regex=True)
    .str.zfill(5)
)

month_cols = [
    "1월", "2월", "3월", "4월",
    "5월", "6월", "7월", "8월",
    "9월", "10월", "11월", "12월"
]

for col in month_cols:

    parcel_clean[col] = pd.to_numeric(
        parcel_clean[col],
        errors="coerce"
    )


# ---------------------------------------------------------
# 3. 우편번호별 물량 자료 기본 검수
# ---------------------------------------------------------

print("[택배물량 원자료 검수]")

print(
    "전체 우편번호 수:",
    parcel_clean["우편번호"].nunique()
)

print(
    "우편번호 중복:",
    parcel_clean["우편번호"].duplicated().sum()
)

print(
    "월별 물량 결측 행:",
    parcel_clean[month_cols].isna().any(axis=1).sum()
)


# ---------------------------------------------------------
# 4. 38개 거점에 우편번호별 택배물량 연결
# ---------------------------------------------------------

location_parcel = locations_38.merge(
    parcel_clean[
        ["우편번호"] + month_cols
    ],
    on="우편번호",
    how="left",
    validate="many_to_one"
)


# ---------------------------------------------------------
# 5. 같은 우편번호를 공유하는 거점 수 계산
# ---------------------------------------------------------

zip_location_count = (
    location_parcel
    .groupby(
        "우편번호"
    )["분석거점ID"]
    .transform("nunique")
)

location_parcel[
    "동일우편번호_거점수"
] = zip_location_count


# ---------------------------------------------------------
# 6. 여름철 물량 파생변수 생성
#
# 6~9월 합계와 월평균을 우선 생성
# 아직 거점별 배분은 하지 않음
# ---------------------------------------------------------

summer_cols = [
    "6월",
    "7월",
    "8월",
    "9월"
]

location_parcel[
    "여름철_택배물량합계"
] = location_parcel[
    summer_cols
].sum(axis=1)

location_parcel[
    "여름철_월평균택배물량"
] = location_parcel[
    summer_cols
].mean(axis=1)


# ---------------------------------------------------------
# 7. 연결 결과 검수
# ---------------------------------------------------------

print("\n[38개 거점 택배물량 연결 결과]")

print(
    "최종 거점 수:",
    len(location_parcel)
)

print(
    "택배물량 미연결 거점:",
    location_parcel[
        month_cols
    ].isna().all(axis=1).sum()
)

print(
    "연결된 고유 우편번호 수:",
    location_parcel[
        "우편번호"
    ].nunique()
)

print(
    "같은 우편번호를 공유하는 거점 수:",
    (
        location_parcel[
            "동일우편번호_거점수"
        ] > 1
    ).sum()
)

print(
    "복수 거점이 존재하는 우편번호 수:",
    location_parcel.loc[
        location_parcel[
            "동일우편번호_거점수"
        ] > 1,
        "우편번호"
    ].nunique()
)

print(
    "여름철 물량 범위:",
    int(
        location_parcel[
            "여름철_택배물량합계"
        ].min()
    ),
    "~",
    int(
        location_parcel[
            "여름철_택배물량합계"
        ].max()
    )
)


# ---------------------------------------------------------
# 8. 동일 우편번호 공유 거점 출력
# ---------------------------------------------------------

shared_zip = (
    location_parcel[
        location_parcel[
            "동일우편번호_거점수"
        ] > 1
    ]
    .sort_values(
        [
            "우편번호",
            "대표거점명"
        ]
    )
)

print("\n[동일 우편번호 공유 거점]")

if len(shared_zip) == 0:

    print("없음")

else:

    display(
        shared_zip[
            [
                "분석거점ID",
                "대표거점명",
                "대표주소",
                "우편번호",
                "동일우편번호_거점수",
                "대표_보관면적",
                "6월",
                "7월",
                "8월",
                "9월",
                "여름철_택배물량합계"
            ]
        ]
    )


# ---------------------------------------------------------
# 9. 물량 미연결 거점이 있으면 출력
# ---------------------------------------------------------

unmatched = location_parcel[
    location_parcel[
        month_cols
    ].isna().all(axis=1)
]

print("\n[택배물량 미연결 거점]")

if len(unmatched) == 0:

    print("없음")

else:

    display(
        unmatched[
            [
                "분석거점ID",
                "대표거점명",
                "대표주소",
                "우편번호"
            ]
        ]
    )


# ---------------------------------------------------------
# 10. 연결 결과 저장
# ---------------------------------------------------------

save_path = (
    PROCESSED_DIR /
    "대전_38개물류거점_우편번호별택배물량연결.csv"
)

location_parcel.to_csv(
    save_path,
    index=False,
    encoding="utf-8-sig"
)

print("\n저장 완료:")
print(save_path)

[택배물량 원자료 검수]
전체 우편번호 수: 34502
우편번호 중복: 0
월별 물량 결측 행: 0

[38개 거점 택배물량 연결 결과]
최종 거점 수: 38
택배물량 미연결 거점: 0
연결된 고유 우편번호 수: 23
같은 우편번호를 공유하는 거점 수: 23
복수 거점이 존재하는 우편번호 수: 8
여름철 물량 범위: 108 ~ 9268

[동일 우편번호 공유 거점]

,분석거점ID,대표거점명,대표주소,우편번호,동일우편번호_거점수,대표_보관면적,6월,7월,8월,9월,여름철_택배물량합계
26,LOC_2023S63000000002,(주)비지에프로지스 대전센터,대전광역시 유성구 대정동 301-2 (주)비지에프리테일대전물류센터,34219,5,0.0,1207,1169,1105,1118,4599
11,LOC_2012S63000000015,(주)한진 대전지점,대전광역시 유성구 대정동 301-1 (주)한진대전택배터미널,34219,5,17816.0,1207,1169,1105,1118,4599
12,LOC_2012S63000000016,대신정기화물(주),대전광역시 유성구 대정동 302번지 3호,34219,5,3963.0,1207,1169,1105,1118,4599
31,LOC_2025A63000000415,백년축산,"대전광역시 유성구 대정북로 68, 대정동창고시설 B101호 (대정동)",34219,5,NaN,1207,1169,1105,1118,4599
27,LOC_2023S63000000003,쿠팡로지스틱스서비스 유한회사 대전1모바일캠프,대전광역시 유성구 대정동 302-1 오성철강(주) 가동,34219,5,0.0,1207,1169,1105,1118,4599
34,LOC_CJ_MUNPYEONG,CJ대한통운 문평동 물류거점,대전광역시 대덕구 대덕대로1447번길 39,34301,2,6486.0,199,155,164,357,875
18,LOC_2019S63000000001,롯데글로벌로지스(주),대전광역시 대덕구 문평동 78-4 롯데제과(주),34301,2,0.0,199,155,164,357,875
8,LOC_2012S63000000010,한솔로지스틱스(주) 대전센타,대전광역시 대덕구 신일동 1674번지 2호,34326,2,170395.0,153,142,146,122,563
9,LOC_2012S63000000011,한솔로지스틱스(주) 신탄진센타,대전광역시 대덕구 신일동 1691번지,34326,2,50445.0,153,142,146,122,563
36,LOC_DONGWON_SANGSEO,동원로엑스 대전물류센터,대전광역시 대덕구 방두말1길 12,34343,2,NaN,45,42,31,49,167
20,LOC_2020S63000000001,동원로엑스(주),대전광역시 대덕구 상서동 171-1,34343,2,2698.0,45,42,31,49,167
1,LOC_2008A63000001455,씨제이대한통운(주),"대전광역시 대덕구 신탄진로 1, 대한통운 창고동 3층 (읍내동)",34352,2,NaN,73,46,58,73,250
5,LOC_2012S63000000007,씨제이대한통운(주) 읍내동지점,대전광역시 대덕구 읍내동 100번지,34352,2,53372.0,73,46,58,73,250
7,LOC_2012S63000000009,롯데글로벌로지스주식회사,대전광역시 대덕구 대화동 40번지 40호,34365,2,14969.0,277,232,243,259,1011
16,LOC_2018S63000000003,주식회사 넥센,대전광역시 대덕구 대화동 40-30 넥센타이어,34365,2,0.0,277,232,243,259,1011
21,LOC_2021S63000000001,(주)에이치씨인터내셔널,대전광역시 동구 구도동 345번지,34708,5,0.0,116,94,100,143,453
14,LOC_2015S63000000003,대전물류(주),대전광역시 동구 구도동 380번지,34708,5,6599.8,116,94,100,143,453
32,LOC_2025S63000000001,로젠주식회사,대전광역시 동구 구도동 368번지,34708,5,0.0,116,94,100,143,453
15,LOC_2015S63000000005,주식회사 대승물산,대전광역시 동구 구도동 341번지,34708,5,4951.5,116,94,100,143,453
35,LOC_COUPANG_GUDO,쿠팡 구도동 물류거점,대전광역시 동구 안골로 33,34708,5,0.0,116,94,100,143,453
30,LOC_2024S63000000001,CJ대한통운(주) 대전생수센터,대전광역시 동구 하소동 913번지 대전킴벌리하소동창고 1동,34712,3,0.0,274,264,250,292,1080
25,LOC_2023S63000000001,도시산업개발,대전광역시 동구 하소동 894-1,34712,3,0.0,274,264,250,292,1080
24,LOC_2022S63000000004,주식회사 베니스,대전광역시 동구 하소동 926번지,34712,3,0.0,274,264,250,292,1080

[택배물량 미연결 거점]
없음

저장 완료:
/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/대전_38개물류거점_우편번호별택배물량연결.csv

- 38개 거점 모두 택배물량 연결 성공
- 고유 우편번호: 23개
- 8개 우편번호 여러 물류거점이 존재
- 총 23개 거점이 동일 우편번호의 물량을 공유
- 미연결 거점: 0개

2-6. 동일 우편번호 내 보관면적 활용 가능성 검수
- 다음 기준 중 어느 것이 타당한지 결정
1) 모든 거점에 정상 면적이 있으면 면적 비례
2) 일부만 면적이 있으면 면적 비례를 그대로 사용하지 않음
3) 면적정보가 불완전하면 균등 배분을 기본값으로 사용
4) 이후 면적 가중 배분을 민감도 분석으로 비교

- 보관면적을 물량 배분에 사용할 수 있는지 검사하는 단계
- 일반적으로 창고가 클수록 많은 물량을 처리할 가능성이 있기 때문

In [ ]:
# @title
# # =========================================================
# # 2-6. 동일 우편번호 내 보관면적 활용 가능성 검수
# # =========================================================

# import pandas as pd
# import numpy as np

# # ---------------------------------------------------------
# # 1. 2-5 결과자료 복사
# # ---------------------------------------------------------

# parcel_area_check = location_parcel.copy()

# parcel_area_check["대표_보관면적"] = pd.to_numeric(
#     parcel_area_check["대표_보관면적"],
#     errors="coerce"
# )

# # 0 이하 면적은 실제 면적 0으로 단정하지 않고
# # 분석상 '유효 면적정보 없음'으로 구분
# parcel_area_check["유효보관면적"] = (
#     parcel_area_check["대표_보관면적"]
#     .where(
#         parcel_area_check["대표_보관면적"] > 0
#     )
# )


# # ---------------------------------------------------------
# # 2. 우편번호별 면적정보 보유 현황 집계
# # ---------------------------------------------------------

# zip_area_summary = (
#     parcel_area_check
#     .groupby(
#         "우편번호",
#         as_index=False
#     )
#     .agg(
#         거점수=(
#             "분석거점ID",
#             "nunique"
#         ),
#         유효면적보유거점수=(
#             "유효보관면적",
#             "count"
#         ),
#         유효면적미보유거점수=(
#             "유효보관면적",
#             lambda x: x.isna().sum()
#         ),
#         총유효보관면적=(
#             "유효보관면적",
#             "sum"
#         ),
#         여름철_우편번호물량=(
#             "여름철_택배물량합계",
#             "first"
#         )
#     )
# )

# zip_area_summary["면적정보완전여부"] = np.where(
#     zip_area_summary["거점수"]
#     == zip_area_summary["유효면적보유거점수"],
#     "완전",
#     "불완전"
# )

# zip_area_summary["유효면적보유율"] = (
#     zip_area_summary["유효면적보유거점수"]
#     / zip_area_summary["거점수"]
# )


# # ---------------------------------------------------------
# # 3. 복수 거점 우편번호만 확인
# # ---------------------------------------------------------

# shared_zip_area = (
#     zip_area_summary[
#         zip_area_summary["거점수"] > 1
#     ]
#     .sort_values(
#         [
#             "면적정보완전여부",
#             "거점수",
#             "우편번호"
#         ],
#         ascending=[
#             True,
#             False,
#             True
#         ]
#     )
# )

# print("[복수 거점 우편번호 면적자료 검수]")

# print(
#     "복수 거점 우편번호 수:",
#     len(shared_zip_area)
# )

# print(
#     "면적정보가 완전한 우편번호 수:",
#     (
#         shared_zip_area["면적정보완전여부"]
#         == "완전"
#     ).sum()
# )

# print(
#     "면적정보가 불완전한 우편번호 수:",
#     (
#         shared_zip_area["면적정보완전여부"]
#         == "불완전"
#     ).sum()
# )

# display(
#     shared_zip_area[
#         [
#             "우편번호",
#             "거점수",
#             "유효면적보유거점수",
#             "유효면적미보유거점수",
#             "유효면적보유율",
#             "총유효보관면적",
#             "여름철_우편번호물량",
#             "면적정보완전여부"
#         ]
#     ]
# )


# # ---------------------------------------------------------
# # 4. 복수 거점별 개별 면적정보 확인
# # ---------------------------------------------------------

# shared_detail = (
#     parcel_area_check[
#         parcel_area_check[
#             "동일우편번호_거점수"
#         ] > 1
#     ]
#     .merge(
#         shared_zip_area[
#             [
#                 "우편번호",
#                 "면적정보완전여부",
#                 "유효면적보유율"
#             ]
#         ],
#         on="우편번호",
#         how="left"
#     )
#     .sort_values(
#         [
#             "우편번호",
#             "유효보관면적",
#             "대표거점명"
#         ],
#         ascending=[
#             True,
#             False,
#             True
#         ],
#         na_position="last"
#     )
# )

# print("\n[복수 거점별 보관면적 상세]")

# display(
#     shared_detail[
#         [
#             "분석거점ID",
#             "대표거점명",
#             "우편번호",
#             "동일우편번호_거점수",
#             "대표_보관면적",
#             "유효보관면적",
#             "면적정보완전여부",
#             "유효면적보유율",
#             "여름철_택배물량합계"
#         ]
#     ]
# )


# # ---------------------------------------------------------
# # 5. 배분방식 잠정 판정
# #
# # 단독 우편번호:
# #   물량 100% 배정
# #
# # 복수 우편번호 + 면적 완전:
# #   면적비례 가능
# #
# # 복수 우편번호 + 면적 불완전:
# #   균등배분 권장
# # ---------------------------------------------------------

# zip_area_summary["권장배분방식"] = np.select(
#     [
#         zip_area_summary["거점수"] == 1,

#         (
#             (zip_area_summary["거점수"] > 1)
#             & (
#                 zip_area_summary[
#                     "면적정보완전여부"
#                 ] == "완전"
#             )
#         )
#     ],
#     [
#         "단독거점_전량배정",
#         "면적비례배분가능"
#     ],
#     default="균등배분권장"
# )

# print("\n[권장 배분방식 요약]")

# print(
#     zip_area_summary[
#         "권장배분방식"
#     ].value_counts()
# )


# # ---------------------------------------------------------
# # 6. 결과 저장
# # ---------------------------------------------------------

# summary_path = (
#     PROCESSED_DIR /
#     "대전_우편번호별_보관면적활용가능성.csv"
# )

# detail_path = (
#     PROCESSED_DIR /
#     "대전_복수거점우편번호_보관면적상세.csv"
# )

# zip_area_summary.to_csv(
#     summary_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# shared_detail.to_csv(
#     detail_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(summary_path)
# print(detail_path)

- 우편번호가 단독인 거점 15곳: 물류 전량 배정
- 복수거점인 우편번호는 총 8곳
- 그 중 면적정보가 완전한 곳은 1곳: 면적 비례하여 물류량 배분
- 그 외 7곳의 거점: 균등하게 배분

2-7. 우편번호별 택배물량의 38개 거점 배분

In [ ]:
# @title
# # =========================================================
# # 2-7. 우편번호별 택배물량의 38개 거점 배분
# # =========================================================

# import pandas as pd
# import numpy as np

# # ---------------------------------------------------------
# # 1. 2-5 연결 결과 복사
# # ---------------------------------------------------------

# parcel_alloc = location_parcel.copy()

# parcel_alloc["대표_보관면적"] = pd.to_numeric(
#     parcel_alloc["대표_보관면적"],
#     errors="coerce"
# )

# parcel_alloc["유효보관면적"] = (
#     parcel_alloc["대표_보관면적"]
#     .where(
#         parcel_alloc["대표_보관면적"] > 0
#     )
# )

# month_cols = [
#     "1월", "2월", "3월", "4월",
#     "5월", "6월", "7월", "8월",
#     "9월", "10월", "11월", "12월"
# ]


# # ---------------------------------------------------------
# # 2. 우편번호별 면적정보 완전성 다시 연결
# # ---------------------------------------------------------

# allocation_info = zip_area_summary[
#     [
#         "우편번호",
#         "거점수",
#         "유효면적보유거점수",
#         "면적정보완전여부",
#         "총유효보관면적",
#         "권장배분방식"
#     ]
# ].copy()

# parcel_alloc = parcel_alloc.merge(
#     allocation_info,
#     on="우편번호",
#     how="left",
#     validate="many_to_one"
# )


# # ---------------------------------------------------------
# # 3. 거점별 배분비율 산출
# #
# # 단독 거점:
# #   1.0
# #
# # 복수 거점 + 면적정보 완전:
# #   거점면적 / 해당 우편번호 총면적
# #
# # 복수 거점 + 면적정보 불완전:
# #   1 / 거점수
# # ---------------------------------------------------------

# single_mask = (
#     parcel_alloc["거점수"] == 1
# )

# area_mask = (
#     (parcel_alloc["거점수"] > 1)
#     & (
#         parcel_alloc["면적정보완전여부"]
#         == "완전"
#     )
# )

# equal_mask = (
#     (parcel_alloc["거점수"] > 1)
#     & (
#         parcel_alloc["면적정보완전여부"]
#         == "불완전"
#     )
# )

# parcel_alloc["물량배분비율"] = np.nan
# parcel_alloc["물량배분방식"] = pd.NA

# # 단독 거점
# parcel_alloc.loc[
#     single_mask,
#     "물량배분비율"
# ] = 1.0

# parcel_alloc.loc[
#     single_mask,
#     "물량배분방식"
# ] = "단독거점_전량배정"

# # 면적비례
# parcel_alloc.loc[
#     area_mask,
#     "물량배분비율"
# ] = (
#     parcel_alloc.loc[
#         area_mask,
#         "유효보관면적"
#     ]
#     / parcel_alloc.loc[
#         area_mask,
#         "총유효보관면적"
#     ]
# )

# parcel_alloc.loc[
#     area_mask,
#     "물량배분방식"
# ] = "면적비례배분"

# # 균등배분
# parcel_alloc.loc[
#     equal_mask,
#     "물량배분비율"
# ] = (
#     1
#     / parcel_alloc.loc[
#         equal_mask,
#         "거점수"
#     ]
# )

# parcel_alloc.loc[
#     equal_mask,
#     "물량배분방식"
# ] = "균등배분"


# # ---------------------------------------------------------
# # 4. 월별 거점 배분 물량 계산
# # ---------------------------------------------------------

# allocated_month_cols = []

# for col in month_cols:

#     new_col = f"{col}_거점배분물량"

#     parcel_alloc[new_col] = (
#         parcel_alloc[col]
#         * parcel_alloc["물량배분비율"]
#     )

#     allocated_month_cols.append(new_col)


# # ---------------------------------------------------------
# # 5. 여름철 거점 배분 물량 계산
# # ---------------------------------------------------------

# summer_alloc_cols = [
#     "6월_거점배분물량",
#     "7월_거점배분물량",
#     "8월_거점배분물량",
#     "9월_거점배분물량"
# ]

# parcel_alloc[
#     "여름철_거점배분물량합계"
# ] = parcel_alloc[
#     summer_alloc_cols
# ].sum(axis=1)

# parcel_alloc[
#     "여름철_거점월평균물량"
# ] = parcel_alloc[
#     summer_alloc_cols
# ].mean(axis=1)


# # ---------------------------------------------------------
# # 6. 우편번호별 배분비율 합계 검수
# # ---------------------------------------------------------

# ratio_check = (
#     parcel_alloc
#     .groupby(
#         "우편번호",
#         as_index=False
#     )
#     .agg(
#         거점수=(
#             "분석거점ID",
#             "nunique"
#         ),
#         배분비율합계=(
#             "물량배분비율",
#             "sum"
#         )
#     )
# )

# ratio_check["배분비율오차"] = (
#     ratio_check["배분비율합계"]
#     - 1
# ).abs()

# print("[배분비율 검수]")

# print(
#     "배분비율 합계가 1이 아닌 우편번호:",
#     (
#         ratio_check["배분비율오차"]
#         > 1e-10
#     ).sum()
# )

# print(
#     "최대 배분비율 오차:",
#     ratio_check["배분비율오차"].max()
# )


# # ---------------------------------------------------------
# # 7. 월별 원본 물량과 배분 후 물량 보존 검수
# # ---------------------------------------------------------

# volume_check_rows = []

# for col in month_cols:

#     allocated_col = f"{col}_거점배분물량"

#     original_total = (
#         parcel_alloc[
#             ["우편번호", col]
#         ]
#         .drop_duplicates(
#             subset=["우편번호"]
#         )[col]
#         .sum()
#     )

#     allocated_total = (
#         parcel_alloc[
#             allocated_col
#         ].sum()
#     )

#     volume_check_rows.append({
#         "월": col,
#         "원본_우편번호물량합계": original_total,
#         "거점배분후물량합계": allocated_total,
#         "차이": allocated_total - original_total
#     })


# volume_check = pd.DataFrame(
#     volume_check_rows
# )

# print("\n[월별 물량 보존 검수]")

# display(volume_check)

# print(
#     "물량 보존 오차 최대값:",
#     volume_check["차이"].abs().max()
# )


# # ---------------------------------------------------------
# # 8. 배분방식별 거점 수 확인
# # ---------------------------------------------------------

# print("\n[거점별 물량 배분방식]")

# print(
#     parcel_alloc[
#         "물량배분방식"
#     ].value_counts()
# )


# # ---------------------------------------------------------
# # 9. 면적비례가 적용된 34326 확인
# # ---------------------------------------------------------

# print("\n[면적비례배분 적용 거점]")

# display(
#     parcel_alloc[
#         parcel_alloc[
#             "물량배분방식"
#         ] == "면적비례배분"
#     ][
#         [
#             "분석거점ID",
#             "대표거점명",
#             "우편번호",
#             "유효보관면적",
#             "총유효보관면적",
#             "물량배분비율",
#             "6월",
#             "6월_거점배분물량",
#             "여름철_거점배분물량합계"
#         ]
#     ]
# )


# # ---------------------------------------------------------
# # 10. 균등배분 예시 확인
# # ---------------------------------------------------------

# print("\n[균등배분 적용 거점 예시]")

# display(
#     parcel_alloc[
#         parcel_alloc[
#             "물량배분방식"
#         ] == "균등배분"
#     ][
#         [
#             "분석거점ID",
#             "대표거점명",
#             "우편번호",
#             "거점수",
#             "물량배분비율",
#             "여름철_택배물량합계",
#             "여름철_거점배분물량합계"
#         ]
#     ]
#     .head(15)
# )


# # ---------------------------------------------------------
# # 11. 결과 저장
# # ---------------------------------------------------------

# save_path = (
#     PROCESSED_DIR /
#     "대전_38개물류거점_택배물량배분완료.csv"
# )

# parcel_alloc.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# check_path = (
#     PROCESSED_DIR /
#     "대전_택배물량_배분보존검수.csv"
# )

# volume_check.to_csv(
#     check_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)
# print(check_path)

- 23개 우편번호 모두 배분비율 합계가 정확히 1
- 월별 원본 물량과 배분 후 물량이 보존됨
- 최대오차는 극미한 수치. 실질적으로 0
- 단독 전량배정:15개 거점
- 균등배분: 21개 거점
- 면적비례배분: 2개 거점

물류량 배분 추가 설명
- 실제 창고별 물류량 데이터를 구할 수 없음
- 지역 택배수요를 거점별로 합리적으로 나누는 방법을 사용함
- 즉 각 물류창고의 실제 처리 물량x

우리가 가진 데이터 형태
- 우편번호 34219 지역의 7월 택배물량은 1,169건
- 우편번호 34219 안에는 물류거점 5곳이 존재함
- 따라서 1,169건을 5개의 물류거점에 적절하게 나누는 작업 필요

2-6과 2-7의 차이
- 2-6은 우편번호(23개) 기준
- 2-7은 물류거점(38개) 기준
- 23개의 우편번호 안에 38개의 물류거점 존재

총 38개 물류거점은 23개 우편번호에 분포. 이 중15개 우편번호는 하나의 거점을 가지고 있어 해당 지역 물량을 전량 배분. 복수 거점을 가진 8개 우편번호 중 21 거점을 가진 7개의 우편번호는 면적정보가 불완전하여 균등 배분. 2개의 거점을 가진 1개의 우편번호는 면적비례 배분.

2-8. 7월 월간 택배수요를 거점별 일평균 물류부하로 변환
- 앞에서 나눈 월간 물량을 실제 예보 분석에 쓸 수 있는 하루 단위 지표로 변경

In [ ]:
# @title
# # =========================================================
# # 2-8. 7월 월간 택배수요를 거점별 일평균 물류부하로 변환
# # =========================================================

# from pathlib import Path
# import pandas as pd
# import numpy as np

# PROCESSED_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
# )

# # ---------------------------------------------------------
# # 1. 2-7 결과 불러오기
# # ---------------------------------------------------------

# parcel_alloc_path = (
#     PROCESSED_DIR /
#     "대전_38개물류거점_택배물량배분완료.csv"
# )

# parcel_alloc = pd.read_csv(
#     parcel_alloc_path,
#     encoding="utf-8-sig",
#     dtype={
#         "분석거점ID": str,
#         "우편번호": str
#     }
# )

# parcel_alloc["7월_거점배분물량"] = pd.to_numeric(
#     parcel_alloc["7월_거점배분물량"],
#     errors="coerce"
# )

# print("불러온 거점 수:", len(parcel_alloc))


# # ---------------------------------------------------------
# # 2. 7월 거점별 일평균 물류부하 산출
# #
# # 우편번호별 2023년 7월 택배수요를
# # 31일로 나누어 하루 평균 대리변수로 사용
# # ---------------------------------------------------------

# JULY_DAYS = 31

# parcel_alloc[
#     "7월_거점일평균물류부하"
# ] = (
#     parcel_alloc["7월_거점배분물량"]
#     / JULY_DAYS
# )


# # ---------------------------------------------------------
# # 3. 물류부하 상대지수 생성
# #
# # 실제 창고 처리량이 아니므로 절대값뿐 아니라
# # 38개 거점 평균을 1로 둔 상대부하지수도 생성
# # ---------------------------------------------------------

# mean_daily_load = parcel_alloc[
#     "7월_거점일평균물류부하"
# ].mean()

# parcel_alloc[
#     "거점상대물류부하지수"
# ] = (
#     parcel_alloc["7월_거점일평균물류부하"]
#     / mean_daily_load
# )

# parcel_alloc[
#     "거점물류부하백분위"
# ] = (
#     parcel_alloc[
#         "7월_거점일평균물류부하"
#     ]
#     .rank(
#         method="average",
#         pct=True
#     )
#     * 100
# )


# # ---------------------------------------------------------
# # 4. 일평균 변환 보존 검수
# # ---------------------------------------------------------

# original_july_total = parcel_alloc[
#     "7월_거점배분물량"
# ].sum()

# restored_july_total = (
#     parcel_alloc[
#         "7월_거점일평균물류부하"
#     ].sum()
#     * JULY_DAYS
# )

# print("\n[7월 일평균 물류부하 변환 검수]")

# print(
#     "최종 거점 수:",
#     parcel_alloc["분석거점ID"].nunique()
# )

# print(
#     "7월 배분물량 결측:",
#     parcel_alloc[
#         "7월_거점배분물량"
#     ].isna().sum()
# )

# print(
#     "일평균 물류부하 결측:",
#     parcel_alloc[
#         "7월_거점일평균물류부하"
#     ].isna().sum()
# )

# print(
#     "7월 원본 거점배분물량 합계:",
#     round(original_july_total, 6)
# )

# print(
#     "일평균 × 31일 복원 합계:",
#     round(restored_july_total, 6)
# )

# print(
#     "물량 복원 차이:",
#     round(
#         restored_july_total
#         - original_july_total,
#         12
#     )
# )

# print(
#     "거점 일평균 물류부하 범위:",
#     round(
#         parcel_alloc[
#             "7월_거점일평균물류부하"
#         ].min(),
#         3
#     ),
#     "~",
#     round(
#         parcel_alloc[
#             "7월_거점일평균물류부하"
#         ].max(),
#         3
#     )
# )

# print(
#     "상대물류부하지수 평균:",
#     round(
#         parcel_alloc[
#             "거점상대물류부하지수"
#         ].mean(),
#         6
#     )
# )


# # ---------------------------------------------------------
# # 5. 물류부하 상위 거점 확인
# # ---------------------------------------------------------

# top_load = (
#     parcel_alloc[
#         [
#             "분석거점ID",
#             "대표거점명",
#             "우편번호",
#             "물량배분방식",
#             "7월_거점배분물량",
#             "7월_거점일평균물류부하",
#             "거점상대물류부하지수",
#             "거점물류부하백분위"
#         ]
#     ]
#     .sort_values(
#         "7월_거점일평균물류부하",
#         ascending=False
#     )
# )

# print("\n[7월 일평균 물류부하 상위 10개 거점]")

# display(
#     top_load.head(10)
# )


# # ---------------------------------------------------------
# # 6. 결과 저장
# # ---------------------------------------------------------

# save_path = (
#     PROCESSED_DIR /
#     "대전_38개물류거점_7월일평균물류부하.csv"
# )

# parcel_alloc.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)

- 최종 거점 수 38개
- 결측값 0개
- 7월 물량 합계 7,428건: 23개 우편번호의 7월 택배물량. 38개 거점에 배분
- 일평균물류부하: 7월 물량을 31일로 나누어 거점별 하루 평균 물류부하 산출
- 거점 간 비교를 위해 전체 평균 1로 설정 후 상대지수와 백분위 생성
- 이 값은 실제 창고 처리량x. 지역 택배수요를 기반으로 추정한 상대적 물류부하

2-9. 시간별 기상예보와 거점별 하루 물류부하 결함

In [ ]:
# @title
# =========================================================
# 2-9. 시간별 기상예보와 거점별 하루 물류부하 결합
#
# 분석 방향:
# 시간대별 실제 기상예보 + 거점별 하루 평균 물류부하
#
# 시간대별 물류량은 임의로 추정하지 않음
# =========================================================

from pathlib import Path
import pandas as pd
import numpy as np

PROCESSED_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
)


# ---------------------------------------------------------
# 1. 38개 거점 시간별 기상예보 불러오기
# ---------------------------------------------------------

forecast_path = (
    PROCESSED_DIR /
    "대전_38개물류거점_시간별체감온도예보.csv"
)

forecast_38 = pd.read_csv(
    forecast_path,
    encoding="utf-8-sig",
    dtype={
        "분석거점ID": str,
        "우편번호": str
    }
)

forecast_38["예보일시"] = pd.to_datetime(
    forecast_38["예보일시"],
    errors="coerce"
)


# ---------------------------------------------------------
# 2. 거점별 하루 평균 물류부하 불러오기
# ---------------------------------------------------------

daily_load_path = (
    PROCESSED_DIR /
    "대전_38개물류거점_7월일평균물류부하.csv"
)

daily_load = pd.read_csv(
    daily_load_path,
    encoding="utf-8-sig",
    dtype={
        "분석거점ID": str,
        "우편번호": str
    }
)

daily_load["7월_거점일평균물류부하"] = pd.to_numeric(
    daily_load["7월_거점일평균물류부하"],
    errors="coerce"
)

daily_load["거점상대물류부하지수"] = pd.to_numeric(
    daily_load["거점상대물류부하지수"],
    errors="coerce"
)

daily_load["거점물류부하백분위"] = pd.to_numeric(
    daily_load["거점물류부하백분위"],
    errors="coerce"
)


# ---------------------------------------------------------
# 3. 결합에 필요한 물류부하 열만 선택
#
# 기상예보 파일에 이미 거점명·주소·좌표가 있으므로
# 중복 열이 생기지 않도록 물류부하 관련 열만 가져옴
# ---------------------------------------------------------

load_cols = [
    "분석거점ID",
    "물량배분방식",
    "물량배분비율",
    "7월_거점배분물량",
    "7월_거점일평균물류부하",
    "거점상대물류부하지수",
    "거점물류부하백분위"
]

daily_load_for_merge = daily_load[
    load_cols
].copy()


# ---------------------------------------------------------
# 4. 시간별 기상예보에 거점별 하루 물류부하 연결
#
# 같은 거점의 하루 물류부하는 모든 시간대에 동일하게 연결됨
# 시간에 따라 변하는 값: TMP, REH, 체감온도
# 거점별로 고정되는 값: 하루 물류부하
# ---------------------------------------------------------

risk_base = forecast_38.merge(
    daily_load_for_merge,
    on="분석거점ID",
    how="left",
    validate="many_to_one"
)


# ---------------------------------------------------------
# 5. 날짜·시간 파생변수 생성
# ---------------------------------------------------------

risk_base["예보날짜"] = (
    risk_base["예보일시"].dt.date
)

risk_base["예보시간"] = (
    risk_base["예보일시"].dt.hour
)

risk_base["요일"] = (
    risk_base["예보일시"]
    .dt.day_name()
    .map({
        "Monday": "월",
        "Tuesday": "화",
        "Wednesday": "수",
        "Thursday": "목",
        "Friday": "금",
        "Saturday": "토",
        "Sunday": "일"
    })
)


# ---------------------------------------------------------
# 6. 분석 구조 검수
# ---------------------------------------------------------

expected_rows = (
    forecast_38["분석거점ID"].nunique()
    * forecast_38["예보일시"].nunique()
)

print("[시간별 기상예보 + 하루 물류부하 결합 결과]")

print(
    "예상 행 수:",
    expected_rows
)

print(
    "실제 행 수:",
    len(risk_base)
)

print(
    "최종 거점 수:",
    risk_base["분석거점ID"].nunique()
)

print(
    "고유 예보시각 수:",
    risk_base["예보일시"].nunique()
)

print(
    "거점·예보시각 중복:",
    risk_base[
        ["분석거점ID", "예보일시"]
    ].duplicated().sum()
)

print(
    "예보일시 결측:",
    risk_base["예보일시"].isna().sum()
)

print(
    "핵심 기상값 결측:",
    risk_base[
        ["TMP", "REH", "체감온도"]
    ].isna().any(axis=1).sum()
)

print(
    "하루 물류부하 미연결:",
    risk_base[
        "7월_거점일평균물류부하"
    ].isna().sum()
)

print(
    "상대물류부하지수 미연결:",
    risk_base[
        "거점상대물류부하지수"
    ].isna().sum()
)

print(
    "예보 기간:",
    risk_base["예보일시"].min(),
    "~",
    risk_base["예보일시"].max()
)

print(
    "체감온도 범위:",
    round(risk_base["체감온도"].min(), 1),
    "~",
    round(risk_base["체감온도"].max(), 1)
)

print(
    "거점별 하루 물류부하 범위:",
    round(
        risk_base[
            "7월_거점일평균물류부하"
        ].min(),
        3
    ),
    "~",
    round(
        risk_base[
            "7월_거점일평균물류부하"
        ].max(),
        3
    )
)


# ---------------------------------------------------------
# 7. 한 거점에서 시간별 기상값과
#    고정된 하루 물류부하가 함께 연결됐는지 확인
# ---------------------------------------------------------

sample_location_id = (
    daily_load
    .sort_values(
        "7월_거점일평균물류부하",
        ascending=False
    )
    .iloc[0]["분석거점ID"]
)

print("\n[물류부하 상위 거점 결합 예시]")

display(
    risk_base[
        risk_base["분석거점ID"]
        == sample_location_id
    ][
        [
            "분석거점ID",
            "대표거점명",
            "예보일시",
            "TMP",
            "REH",
            "체감온도",
            "7월_거점일평균물류부하",
            "거점상대물류부하지수",
            "거점물류부하백분위"
        ]
    ].head(15)
)


# ---------------------------------------------------------
# 8. 거점별 물류부하가 시간에 따라
#    잘못 달라지지 않는지 검수
# ---------------------------------------------------------

load_consistency = (
    risk_base
    .groupby(
        "분석거점ID"
    )[
        "7월_거점일평균물류부하"
    ]
    .nunique()
)

print("\n[거점별 하루 물류부하 일관성 검수]")

print(
    "시간에 따라 물류부하가 달라진 거점 수:",
    (load_consistency > 1).sum()
)


# ---------------------------------------------------------
# 9. 저장
# ---------------------------------------------------------

save_path = (
    PROCESSED_DIR /
    "대전_38개물류거점_시간별기상_하루물류부하결합.csv"
)

risk_base.to_csv(
    save_path,
    index=False,
    encoding="utf-8-sig"
)

print("\n저장 완료:")
print(save_path)

[시간별 기상예보 + 하루 물류부하 결합 결과]
예상 행 수: 2318
실제 행 수: 2318
최종 거점 수: 38
고유 예보시각 수: 61
거점·예보시각 중복: 0
예보일시 결측: 0
핵심 기상값 결측: 0
하루 물류부하 미연결: 0
상대물류부하지수 미연결: 0
예보 기간: 2026-07-28 12:00:00 ~ 2026-07-31 00:00:00
체감온도 범위: 25.3 ~ 34.3
거점별 하루 물류부하 범위: 0.548 ~ 73.258

[물류부하 상위 거점 결합 예시]

,분석거점ID,대표거점명,예보일시,TMP,REH,체감온도,7월_거점일평균물류부하,거점상대물류부하지수,거점물류부하백분위
2013,LOC_2026C63000000024,머크 주식회사 대전 바이오프로세싱생산센터,2026-07-28 12:00:00,31.0,75.0,32.7,73.258065,11.617932,100.0
2014,LOC_2026C63000000024,머크 주식회사 대전 바이오프로세싱생산센터,2026-07-28 13:00:00,32.0,70.0,33.3,73.258065,11.617932,100.0
2015,LOC_2026C63000000024,머크 주식회사 대전 바이오프로세싱생산센터,2026-07-28 14:00:00,32.0,70.0,33.3,73.258065,11.617932,100.0
2016,LOC_2026C63000000024,머크 주식회사 대전 바이오프로세싱생산센터,2026-07-28 15:00:00,32.0,70.0,33.3,73.258065,11.617932,100.0
2017,LOC_2026C63000000024,머크 주식회사 대전 바이오프로세싱생산센터,2026-07-28 16:00:00,32.0,70.0,33.3,73.258065,11.617932,100.0
2018,LOC_2026C63000000024,머크 주식회사 대전 바이오프로세싱생산센터,2026-07-28 17:00:00,31.0,75.0,32.7,73.258065,11.617932,100.0
2019,LOC_2026C63000000024,머크 주식회사 대전 바이오프로세싱생산센터,2026-07-28 18:00:00,30.0,75.0,31.7,73.258065,11.617932,100.0
2020,LOC_2026C63000000024,머크 주식회사 대전 바이오프로세싱생산센터,2026-07-28 19:00:00,28.0,80.0,30.0,73.258065,11.617932,100.0
2021,LOC_2026C63000000024,머크 주식회사 대전 바이오프로세싱생산센터,2026-07-28 20:00:00,27.0,85.0,29.4,73.258065,11.617932,100.0
2022,LOC_2026C63000000024,머크 주식회사 대전 바이오프로세싱생산센터,2026-07-28 21:00:00,26.0,90.0,28.7,73.258065,11.617932,100.0
2023,LOC_2026C63000000024,머크 주식회사 대전 바이오프로세싱생산센터,2026-07-28 22:00:00,26.0,95.0,29.1,73.258065,11.617932,100.0
2024,LOC_2026C63000000024,머크 주식회사 대전 바이오프로세싱생산센터,2026-07-28 23:00:00,25.0,95.0,28.0,73.258065,11.617932,100.0
2025,LOC_2026C63000000024,머크 주식회사 대전 바이오프로세싱생산센터,2026-07-29 00:00:00,25.0,95.0,28.0,73.258065,11.617932,100.0
2026,LOC_2026C63000000024,머크 주식회사 대전 바이오프로세싱생산센터,2026-07-29 01:00:00,25.0,95.0,28.0,73.258065,11.617932,100.0
2027,LOC_2026C63000000024,머크 주식회사 대전 바이오프로세싱생산센터,2026-07-29 02:00:00,25.0,95.0,28.0,73.258065,11.617932,100.0

[거점별 하루 물류부하 일관성 검수]
시간에 따라 물류부하가 달라진 거점 수: 0

저장 완료:
/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/대전_38개물류거점_시간별기상_하루물류부하결합.csv

- 38개 거점 x 61개 예보시각 = 2,318행
- 중복, 결측 0개
- 같은 거점의 하루 물류부하는 시간대별 산출x
- 기온, 습도, 체감온도는 시간대별 산출o

# **2단계 결론**
- 우편번호별 택배물량을 38개 물류거점에 중복 없이 배분
- 배분한 물량을 7월 일평균 물류부하로 변환
- 일평균 물류부화와 시간별 기상예보 연결
- 3단계에서 실제 시간별 체감온도와 거점별 하루 물류부하를 결합한 위험도 계산

# **3. 시간대별 폭염위험 산출**

3-1. 최신 단기예보 갱신

3-1. 체감온도 기준 시간별 기상위험 등급 설정

In [ ]:
# =========================================================
# 3-1. 체감온도 기준 시간별 작업 기상위험 등급 설정
#
# 주의:
# 이 등급은 기상청 공식 폭염특보를 직접 판정하는 것이 아니라,
# 사업장 폭염 대응기준을 참고한 시간별 작업위험 분류임
#
# 33℃ 미만      : 낮음
# 33~35℃ 미만   : 주의
# 35~38℃ 미만   : 경고
# 38℃ 이상      : 매우 위험
# =========================================================

from pathlib import Path
import pandas as pd
import numpy as np

PROCESSED_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
)


# ---------------------------------------------------------
# 1. 2-9 결합 결과 불러오기
# ---------------------------------------------------------

risk_base_path = (
    PROCESSED_DIR /
    "대전_38개물류거점_시간별기상_하루물류부하결합.csv"
)

risk_weather = pd.read_csv(
    risk_base_path,
    encoding="utf-8-sig",
    dtype={
        "분석거점ID": str,
        "우편번호": str
    }
)

risk_weather["예보일시"] = pd.to_datetime(
    risk_weather["예보일시"],
    errors="coerce"
)

risk_weather["체감온도"] = pd.to_numeric(
    risk_weather["체감온도"],
    errors="coerce"
)


# ---------------------------------------------------------
# 2. 체감온도 기준 시간별 작업 기상위험 등급 설정
#
# 33℃ 미만      : 낮음
# 33~35℃ 미만   : 주의
# 35~38℃ 미만   : 경고
# 38℃ 이상      : 매우 위험
# ---------------------------------------------------------

temperature_bins = [
    -np.inf,
    33,
    35,
    38,
    np.inf
]

weather_labels = [
    "낮음",
    "주의",
    "경고",
    "매우 위험"
]

risk_weather["기상위험등급"] = pd.cut(
    risk_weather["체감온도"],
    bins=temperature_bins,
    labels=weather_labels,
    right=False,
    ordered=True
)


# ---------------------------------------------------------
# 3. 기상위험점수 부여
#
# 낮음      : 1점
# 주의      : 2점
# 경고      : 3점
# 매우 위험 : 4점
# ---------------------------------------------------------

weather_score_map = {
    "낮음": 1,
    "주의": 2,
    "경고": 3,
    "매우 위험": 4
}

risk_weather["기상위험점수"] = (
    risk_weather["기상위험등급"]
    .astype("string")
    .map(weather_score_map)
    .astype("Int64")
)


# ---------------------------------------------------------
# 4. 날짜·시간 정보 생성
# ---------------------------------------------------------

risk_weather["예보날짜"] = (
    risk_weather["예보일시"].dt.date
)

risk_weather["예보시간"] = (
    risk_weather["예보일시"].dt.hour
)


# ---------------------------------------------------------
# 5. 기본 검수
# ---------------------------------------------------------

print("[시간별 작업 기상위험 등급 산출 결과]")

print(
    "전체 행 수:",
    len(risk_weather)
)

print(
    "최종 거점 수:",
    risk_weather["분석거점ID"].nunique()
)

print(
    "고유 예보시각 수:",
    risk_weather["예보일시"].nunique()
)

print(
    "예보일시 결측:",
    risk_weather["예보일시"].isna().sum()
)

print(
    "체감온도 결측:",
    risk_weather["체감온도"].isna().sum()
)

print(
    "기상위험등급 결측:",
    risk_weather["기상위험등급"].isna().sum()
)

print(
    "기상위험점수 결측:",
    risk_weather["기상위험점수"].isna().sum()
)

print(
    "체감온도 범위:",
    round(risk_weather["체감온도"].min(), 1),
    "~",
    round(risk_weather["체감온도"].max(), 1)
)


# ---------------------------------------------------------
# 6. 기상위험등급별 행 수와 비율
# ---------------------------------------------------------

weather_summary = (
    risk_weather["기상위험등급"]
    .value_counts(
        sort=False,
        dropna=False
    )
    .rename_axis("기상위험등급")
    .reset_index(name="행수")
)

weather_summary["비율_pct"] = (
    weather_summary["행수"]
    / len(risk_weather)
    * 100
).round(2)

print("\n[기상위험등급별 분포]")

display(weather_summary)


# ---------------------------------------------------------
# 7. 예보시각별 기상위험 요약
#
# 각 시간에 대전 38개 거점 중:
# - 최고 체감온도
# - 평균 체감온도
# - 가장 높은 위험등급
# - 주의 이상 거점 수
# - 경고 이상 거점 수
# 를 계산함
# ---------------------------------------------------------

hourly_weather_summary = (
    risk_weather
    .groupby(
        "예보일시",
        as_index=False
    )
    .agg(
        최고체감온도=(
            "체감온도",
            "max"
        ),
        평균체감온도=(
            "체감온도",
            "mean"
        ),
        최고기상위험점수=(
            "기상위험점수",
            "max"
        ),
        주의이상_거점수=(
            "기상위험점수",
            lambda x: (x >= 2).sum()
        ),
        경고이상_거점수=(
            "기상위험점수",
            lambda x: (x >= 3).sum()
        ),
        매우위험_거점수=(
            "기상위험점수",
            lambda x: (x >= 4).sum()
        )
    )
)

score_to_grade = {
    1: "낮음",
    2: "주의",
    3: "경고",
    4: "매우 위험"
}

hourly_weather_summary["최고기상위험등급"] = (
    hourly_weather_summary["최고기상위험점수"]
    .map(score_to_grade)
)


# ---------------------------------------------------------
# 8. 위험도가 높은 예보시각 확인
# ---------------------------------------------------------

print("\n[최고 체감온도 상위 15개 예보시각]")

display(
    hourly_weather_summary
    .sort_values(
        [
            "최고기상위험점수",
            "최고체감온도"
        ],
        ascending=False
    )
    .head(15)
)


# ---------------------------------------------------------
# 9. 날짜별 기상위험 요약
#
# 주의이상_거점시간수:
# 하루 동안 38개 거점에서 발생한
# '주의 이상' 시간별 기록의 총개수
# ---------------------------------------------------------

daily_weather_summary = (
    risk_weather
    .groupby(
        "예보날짜",
        as_index=False
    )
    .agg(
        일최고체감온도=(
            "체감온도",
            "max"
        ),
        일평균체감온도=(
            "체감온도",
            "mean"
        ),
        일최고기상위험점수=(
            "기상위험점수",
            "max"
        ),
        주의이상_거점시간수=(
            "기상위험점수",
            lambda x: (x >= 2).sum()
        ),
        경고이상_거점시간수=(
            "기상위험점수",
            lambda x: (x >= 3).sum()
        ),
        매우위험_거점시간수=(
            "기상위험점수",
            lambda x: (x >= 4).sum()
        )
    )
)

daily_weather_summary["일최고기상위험등급"] = (
    daily_weather_summary["일최고기상위험점수"]
    .map(score_to_grade)
)

print("\n[날짜별 기상위험 요약]")

display(daily_weather_summary)


# ---------------------------------------------------------
# 10. 등급 경계값이 정확히 적용됐는지 검수
# ---------------------------------------------------------

boundary_check = pd.DataFrame({
    "체감온도_예시": [
        32.9,
        33.0,
        34.9,
        35.0,
        37.9,
        38.0
    ]
})

boundary_check["적용등급"] = pd.cut(
    boundary_check["체감온도_예시"],
    bins=temperature_bins,
    labels=weather_labels,
    right=False,
    ordered=True
)

print("\n[체감온도 경계값 적용 확인]")

display(boundary_check)


# ---------------------------------------------------------
# 11. 저장
# ---------------------------------------------------------

risk_path = (
    PROCESSED_DIR /
    "대전_38개물류거점_시간별작업기상위험등급.csv"
)

hourly_path = (
    PROCESSED_DIR /
    "대전_예보시각별_작업기상위험요약.csv"
)

daily_path = (
    PROCESSED_DIR /
    "대전_날짜별_작업기상위험요약.csv"
)

risk_weather.to_csv(
    risk_path,
    index=False,
    encoding="utf-8-sig"
)

hourly_weather_summary.to_csv(
    hourly_path,
    index=False,
    encoding="utf-8-sig"
)

daily_weather_summary.to_csv(
    daily_path,
    index=False,
    encoding="utf-8-sig"
)

print("\n저장 완료:")
print(risk_path)
print(hourly_path)
print(daily_path)

[시간별 작업 기상위험 등급 산출 결과]
전체 행 수: 2318
최종 거점 수: 38
고유 예보시각 수: 61
예보일시 결측: 0
체감온도 결측: 0
기상위험등급 결측: 0
기상위험점수 결측: 0
체감온도 범위: 25.3 ~ 34.3

[기상위험등급별 분포]

  기상위험등급    행수  비율_pct
0     낮음  2094   90.34
1     주의   224    9.66
2     경고     0    0.00
3  매우 위험     0    0.00

[최고 체감온도 상위 15개 예보시각]

,예보일시,최고체감온도,평균체감온도,최고기상위험점수,주의이상_거점수,경고이상_거점수,매우위험_거점수,최고기상위험등급
1,2026-07-28 13:00:00,34.3,33.436842,2,35,0,0,주의
2,2026-07-28 14:00:00,34.3,33.189474,2,18,0,0,주의
3,2026-07-28 15:00:00,34.3,33.147368,2,18,0,0,주의
25,2026-07-29 13:00:00,34.3,33.363158,2,35,0,0,주의
26,2026-07-29 14:00:00,34.3,33.215789,2,12,0,0,주의
4,2026-07-28 16:00:00,33.9,33.063158,2,17,0,0,주의
27,2026-07-29 15:00:00,33.9,33.121053,2,11,0,0,주의
28,2026-07-29 16:00:00,33.9,32.963158,2,5,0,0,주의
50,2026-07-30 14:00:00,33.9,32.931579,2,5,0,0,주의
51,2026-07-30 15:00:00,33.9,33.373684,2,29,0,0,주의
52,2026-07-30 16:00:00,33.9,33.010526,2,13,0,0,주의
53,2026-07-30 17:00:00,33.9,32.810526,2,10,0,0,주의
5,2026-07-28 17:00:00,33.3,32.615789,2,11,0,0,주의
29,2026-07-29 17:00:00,33.3,32.331579,2,1,0,0,주의
49,2026-07-30 13:00:00,33.3,32.321053,2,2,0,0,주의

[날짜별 기상위험 요약]

,예보날짜,일최고체감온도,일평균체감온도,일최고기상위험점수,주의이상_거점시간수,경고이상_거점시간수,매우위험_거점시간수,일최고기상위험등급
0,2026-07-28,34.3,31.387061,2,99,0,0,주의
1,2026-07-29,34.3,29.727741,2,64,0,0,주의
2,2026-07-30,33.9,29.424013,2,61,0,0,주의
3,2026-07-31,28.0,27.628947,1,0,0,0,낮음

[체감온도 경계값 적용 확인]

   체감온도_예시   적용등급
0     32.9     낮음
1     33.0     주의
2     34.9     주의
3     35.0     경고
4     37.9     경고
5     38.0  매우 위험

저장 완료:
/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/대전_38개물류거점_시간별작업기상위험등급.csv
/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/대전_예보시각별_작업기상위험요약.csv
/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/대전_날짜별_작업기상위험요약.csv

- 전체 2,318행, 38개 물류 거점, 61개 예보시각
- 결측 0개
- 체감온도 측정 기간: 260728 12:00 ~ 260731 00:00
- 체감온도 25.3℃ ~ 34.3℃
- 낮음: 2,094건(90.34%)
- 주의: 224건(9.66%)
- 경고, 매우 위험: 0건

3-2. 거점별 하루 물류부하 등급 설정

In [ ]:
# =========================================================
# 3-2. 거점별 하루 물류부하 등급 설정
#
# 목적:
# 우편번호별 택배수요를 배분하여 산출한
# 거점별 하루 평균 물류부하를 상대적 백분위로 구분함
#
# 50백분위 미만       : 낮음
# 50~75백분위 미만    : 보통
# 75백분위 이상       : 높음
#
# 주의:
# 실제 물류창고 처리량이 아니라
# 거점별 상대적 물류부하 대리변수임
# =========================================================

from pathlib import Path
import pandas as pd
import numpy as np

PROCESSED_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
)


# ---------------------------------------------------------
# 1. 거점별 하루 평균 물류부하 자료 불러오기
# ---------------------------------------------------------

daily_load_path = (
    PROCESSED_DIR /
    "대전_38개물류거점_7월일평균물류부하.csv"
)

load_grade = pd.read_csv(
    daily_load_path,
    encoding="utf-8-sig",
    dtype={
        "분석거점ID": str,
        "우편번호": str
    }
)


# ---------------------------------------------------------
# 2. 분석에 필요한 숫자형 열 변환
# ---------------------------------------------------------

numeric_cols = [
    "7월_거점배분물량",
    "7월_거점일평균물류부하",
    "거점상대물류부하지수",
    "거점물류부하백분위"
]

for col in numeric_cols:
    if col in load_grade.columns:
        load_grade[col] = pd.to_numeric(
            load_grade[col],
            errors="coerce"
        )


# ---------------------------------------------------------
# 3. 필수 열 존재 여부 확인
# ---------------------------------------------------------

required_cols = [
    "분석거점ID",
    "7월_거점일평균물류부하",
    "거점물류부하백분위"
]

missing_cols = [
    col for col in required_cols
    if col not in load_grade.columns
]

if missing_cols:
    raise KeyError(
        "필수 열이 없습니다: "
        + ", ".join(missing_cols)
    )


# ---------------------------------------------------------
# 4. 백분위 기준 물류부하 등급 설정
#
# 동일한 백분위값은 같은 등급으로 분류되므로,
# 같은 물류부하를 가진 거점이 서로 다른 등급으로
# 나뉘지 않도록 함
# ---------------------------------------------------------

conditions = [
    load_grade["거점물류부하백분위"] < 50,

    (
        (load_grade["거점물류부하백분위"] >= 50)
        & (load_grade["거점물류부하백분위"] < 75)
    ),

    load_grade["거점물류부하백분위"] >= 75
]

load_grade["물류부하등급"] = np.select(
    conditions,
    [
        "낮음",
        "보통",
        "높음"
    ],
    default=pd.NA
)


# ---------------------------------------------------------
# 5. 물류부하 점수 부여
#
# 낮음 : 1점
# 보통 : 2점
# 높음 : 3점
# ---------------------------------------------------------

load_score_map = {
    "낮음": 1,
    "보통": 2,
    "높음": 3
}

load_grade["물류부하점수"] = (
    load_grade["물류부하등급"]
    .map(load_score_map)
    .astype("Int64")
)


# ---------------------------------------------------------
# 6. 시각화용 등급 순서 설정
# ---------------------------------------------------------

load_order = [
    "낮음",
    "보통",
    "높음"
]

load_grade["물류부하등급"] = pd.Categorical(
    load_grade["물류부하등급"],
    categories=load_order,
    ordered=True
)


# ---------------------------------------------------------
# 7. 기본 검수
# ---------------------------------------------------------

print("[거점별 하루 물류부하 등급 산출 결과]")

print(
    "전체 행 수:",
    len(load_grade)
)

print(
    "고유 거점 수:",
    load_grade["분석거점ID"].nunique()
)

print(
    "분석거점ID 중복:",
    load_grade["분석거점ID"].duplicated().sum()
)

print(
    "하루 물류부하 결측:",
    load_grade[
        "7월_거점일평균물류부하"
    ].isna().sum()
)

print(
    "물류부하백분위 결측:",
    load_grade[
        "거점물류부하백분위"
    ].isna().sum()
)

print(
    "물류부하등급 결측:",
    load_grade[
        "물류부하등급"
    ].isna().sum()
)

print(
    "물류부하점수 결측:",
    load_grade[
        "물류부하점수"
    ].isna().sum()
)

print(
    "하루 물류부하 범위:",
    round(
        load_grade[
            "7월_거점일평균물류부하"
        ].min(),
        3
    ),
    "~",
    round(
        load_grade[
            "7월_거점일평균물류부하"
        ].max(),
        3
    )
)


# ---------------------------------------------------------
# 8. 물류부하 등급별 분포 요약
# ---------------------------------------------------------

load_summary = (
    load_grade
    .groupby(
        "물류부하등급",
        observed=False,
        as_index=False
    )
    .agg(
        거점수=(
            "분석거점ID",
            "nunique"
        ),
        최소_일평균물류부하=(
            "7월_거점일평균물류부하",
            "min"
        ),
        최대_일평균물류부하=(
            "7월_거점일평균물류부하",
            "max"
        ),
        최소_백분위=(
            "거점물류부하백분위",
            "min"
        ),
        최대_백분위=(
            "거점물류부하백분위",
            "max"
        )
    )
)

load_summary["거점비율_pct"] = (
    load_summary["거점수"]
    / load_grade["분석거점ID"].nunique()
    * 100
).round(2)

print("\n[물류부하등급별 분포]")

display(load_summary)


# ---------------------------------------------------------
# 9. 물류부하 상위 거점 확인
# ---------------------------------------------------------

display_cols = [
    col for col in [
        "분석거점ID",
        "대표거점명",
        "우편번호",
        "물량배분방식",
        "7월_거점일평균물류부하",
        "거점상대물류부하지수",
        "거점물류부하백분위",
        "물류부하등급",
        "물류부하점수"
    ]
    if col in load_grade.columns
]

print("\n[물류부하 상위 15개 거점]")

display(
    load_grade
    .sort_values(
        [
            "거점물류부하백분위",
            "7월_거점일평균물류부하"
        ],
        ascending=False
    )[display_cols]
    .head(15)
)


# ---------------------------------------------------------
# 10. 같은 물류부하가 서로 다른 등급으로
#     분리됐는지 검수
# ---------------------------------------------------------

tie_check = (
    load_grade
    .groupby(
        "7월_거점일평균물류부하",
        dropna=False
    )["물류부하등급"]
    .nunique()
)

split_tie_count = (
    tie_check > 1
).sum()

print(
    "\n동일 물류부하가 서로 다른 등급으로 "
    "분리된 값의 수:",
    split_tie_count
)


# ---------------------------------------------------------
# 11. 등급 경계값 적용 확인
# ---------------------------------------------------------

boundary_check = pd.DataFrame({
    "물류부하백분위_예시": [
        49.9,
        50.0,
        74.9,
        75.0,
        100.0
    ]
})

boundary_conditions = [
    boundary_check["물류부하백분위_예시"] < 50,

    (
        (boundary_check["물류부하백분위_예시"] >= 50)
        & (boundary_check["물류부하백분위_예시"] < 75)
    ),

    boundary_check["물류부하백분위_예시"] >= 75
]

boundary_check["적용등급"] = np.select(
    boundary_conditions,
    [
        "낮음",
        "보통",
        "높음"
    ],
    default=pd.NA
)

print("\n[물류부하 경계값 적용 확인]")

display(boundary_check)


# ---------------------------------------------------------
# 12. 저장
# ---------------------------------------------------------

save_path = (
    PROCESSED_DIR /
    "대전_38개물류거점_하루물류부하등급.csv"
)

summary_path = (
    PROCESSED_DIR /
    "대전_물류부하등급별_분포요약.csv"
)

load_grade.to_csv(
    save_path,
    index=False,
    encoding="utf-8-sig"
)

load_summary.to_csv(
    summary_path,
    index=False,
    encoding="utf-8-sig"
)

print("\n저장 완료:")
print(save_path)
print(summary_path)

[거점별 하루 물류부하 등급 산출 결과]
전체 행 수: 38
고유 거점 수: 38
분석거점ID 중복: 0
하루 물류부하 결측: 0
물류부하백분위 결측: 0
물류부하등급 결측: 0
물류부하점수 결측: 0
하루 물류부하 범위: 0.548 ~ 73.258

[물류부하등급별 분포]

  물류부하등급  거점수  최소_일평균물류부하  최대_일평균물류부하     최소_백분위      최대_백분위  거점비율_pct
0     낮음   19    0.548387    2.838710   2.631579   47.368421     50.00
1     보통    7    3.534319    5.967742  52.631579   68.421053     18.42
2     높음   12    7.541935   73.258065  76.315789  100.000000     31.58

[물류부하 상위 15개 거점]

,분석거점ID,대표거점명,우편번호,물량배분방식,7월_거점일평균물류부하,거점상대물류부하지수,거점물류부하백분위,물류부하등급,물류부하점수
33,LOC_2026C63000000024,머크 주식회사 대전 바이오프로세싱생산센터,34002,단독거점_전량배정,73.258065,11.617932,100.000000,높음,3
17,LOC_2019A63000001505,엘리트,35057,단독거점_전량배정,19.451613,3.084814,97.368421,높음,3
6,LOC_2012S63000000008,한국농수산식품유통공사,34346,단독거점_전량배정,18.225806,2.890415,94.736842,높음,3
19,LOC_2020F63000001114,대전광역시서구전통시장상인협동조합,35294,단독거점_전량배정,11.645161,1.846796,92.105263,높음,3
23,LOC_2022S63000000003,쿠팡로지스틱스서비스 유한회사 대전2미니캠프,34344,단독거점_전량배정,8.000000,1.268713,89.473684,높음,3
10,LOC_2012S63000000014,(주)한진 대전중부지점,34366,단독거점_전량배정,7.645161,1.212439,86.842105,높음,3
29,LOC_2024A63000001623,주식회사 해우미트,34439,단독거점_전량배정,7.580645,1.202208,84.210526,높음,3
11,LOC_2012S63000000015,(주)한진 대전지점,34219,균등배분,7.541935,1.196069,76.315789,높음,3
12,LOC_2012S63000000016,대신정기화물(주),34219,균등배분,7.541935,1.196069,76.315789,높음,3
26,LOC_2023S63000000002,(주)비지에프로지스 대전센터,34219,균등배분,7.541935,1.196069,76.315789,높음,3
27,LOC_2023S63000000003,쿠팡로지스틱스서비스 유한회사 대전1모바일캠프,34219,균등배분,7.541935,1.196069,76.315789,높음,3
31,LOC_2025A63000000415,백년축산,34219,균등배분,7.541935,1.196069,76.315789,높음,3
28,LOC_2024A63000000374,(주)블랙해머,35023,단독거점_전량배정,5.967742,0.946419,68.421053,보통,2
2,LOC_2010A63000000160,(주)동원홈푸드,34364,단독거점_전량배정,5.129032,0.813409,65.789474,보통,2
22,LOC_2022S63000000002,쿠팡로지스틱스서비스 유한회사 대전2캠프,34369,단독거점_전량배정,4.935484,0.782714,63.157895,보통,2

동일 물류부하가 서로 다른 등급으로 분리된 값의 수: 0

[물류부하 경계값 적용 확인]

   물류부하백분위_예시 적용등급
0        49.9   낮음
1        50.0   보통
2        74.9   보통
3        75.0   높음
4       100.0   높음

저장 완료:
/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/대전_38개물류거점_하루물류부하등급.csv
/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/대전_물류부하등급별_분포요약.csv

- 낮음: 19개(50.00%)
- 보통: 7개(18.42%)
- 높음: 12개(31.58%)

3-3. 시간별 예보를 2시간 단위 위험 블록으로 변환

In [ ]:
# =========================================================
# 3-3. 시간별 예보를 2시간 단위 위험 블록으로 변환
#
# 입력:
# 대전_38개물류거점_시간별작업기상위험등급.csv
#
# 출력:
# 1) 대전_38개물류거점_2시간단위_작업기상위험.csv
# 2) 대전_2시간단위_작업기상위험등급별_요약.csv
#
# 수정 사항:
# - 예시표를 만들 때 먼저 블록시작일시로 정렬한 후
#   출력 열을 선택하도록 순서를 수정
# - 기존 저장 파일명과 핵심 열 이름은 유지
# =========================================================

from pathlib import Path

import numpy as np
import pandas as pd

from IPython.display import display


# ---------------------------------------------------------
# 1. 폴더와 파일 경로
# ---------------------------------------------------------

PROJECT_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도"
)

PROCESSED_DIR = (
    PROJECT_DIR
    / "03_전처리데이터"
)

RESULT_DIR = (
    PROJECT_DIR
    / "04_분석결과"
)

PROCESSED_DIR.mkdir(
    parents=True,
    exist_ok=True
)

RESULT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


INPUT_PATH = (
    PROCESSED_DIR
    / "대전_38개물류거점_시간별작업기상위험등급.csv"
)

OUTPUT_PATH = (
    PROCESSED_DIR
    / "대전_38개물류거점_2시간단위_작업기상위험.csv"
)

SUMMARY_PATH = (
    RESULT_DIR
    / "대전_2시간단위_작업기상위험등급별_요약.csv"
)


if not INPUT_PATH.exists():
    raise FileNotFoundError(
        "3-2 결과 파일을 찾을 수 없습니다.\n"
        f"확인 경로: {INPUT_PATH}"
    )


# ---------------------------------------------------------
# 2. 시간별 기상위험 자료 불러오기
# ---------------------------------------------------------

hourly_df = pd.read_csv(
    INPUT_PATH,
    encoding="utf-8-sig"
)

print("[3-2 시간별 기상위험 자료 불러오기]")

print(
    "전체 행 수:",
    len(hourly_df)
)

print(
    "전체 열 수:",
    len(hourly_df.columns)
)


# ---------------------------------------------------------
# 3. 필수 열 확인
# ---------------------------------------------------------

required_columns = [
    "분석거점ID",
    "대표거점명",
    "예보일시",
    "체감온도",
    "기상위험등급"
]

missing_columns = [
    column
    for column in required_columns
    if column not in hourly_df.columns
]

if missing_columns:
    raise KeyError(
        "3-3 실행에 필요한 열이 없습니다:\n"
        + ", ".join(missing_columns)
    )


# ---------------------------------------------------------
# 4. 날짜·수치 형식 정리
# ---------------------------------------------------------

hourly_df[
    "예보일시"
] = pd.to_datetime(
    hourly_df[
        "예보일시"
    ],
    errors="coerce"
)

hourly_df[
    "체감온도"
] = pd.to_numeric(
    hourly_df[
        "체감온도"
    ],
    errors="coerce"
)


# 기상위험점수가 없는 경우 등급으로 생성
risk_score_map = {
    "낮음": 1,
    "주의": 2,
    "경고": 3,
    "매우 위험": 4
}

if (
    "기상위험점수"
    not in hourly_df.columns
):

    hourly_df[
        "기상위험점수"
    ] = (
        hourly_df[
            "기상위험등급"
        ]
        .map(
            risk_score_map
        )
    )


hourly_df[
    "기상위험점수"
] = pd.to_numeric(
    hourly_df[
        "기상위험점수"
    ],
    errors="coerce"
)


# ---------------------------------------------------------
# 5. 입력자료 기본 검수
# ---------------------------------------------------------

datetime_missing = (
    hourly_df[
        "예보일시"
    ]
    .isna()
    .sum()
)

temperature_missing = (
    hourly_df[
        "체감온도"
    ]
    .isna()
    .sum()
)

risk_missing = (
    hourly_df[
        "기상위험등급"
    ]
    .isna()
    .sum()
)

score_missing = (
    hourly_df[
        "기상위험점수"
    ]
    .isna()
    .sum()
)


if datetime_missing > 0:
    raise ValueError(
        f"예보일시 결측이 {datetime_missing}개 있습니다."
    )

if temperature_missing > 0:
    raise ValueError(
        f"체감온도 결측이 {temperature_missing}개 있습니다."
    )

if risk_missing > 0:
    raise ValueError(
        f"기상위험등급 결측이 {risk_missing}개 있습니다."
    )

if score_missing > 0:
    raise ValueError(
        f"기상위험점수 결측이 {score_missing}개 있습니다."
    )


# 거점·시간 중복 확인
hourly_duplicate_count = (
    hourly_df
    .duplicated(
        subset=[
            "분석거점ID",
            "예보일시"
        ]
    )
    .sum()
)

if hourly_duplicate_count > 0:
    raise ValueError(
        "시간별 자료에 거점·예보일시 중복이 "
        f"{hourly_duplicate_count}개 있습니다."
    )


# ---------------------------------------------------------
# 6. 2시간 블록 시작·종료 시각 생성
#
# 예:
# 08:00, 09:00 → 08:00~10:00
# 10:00, 11:00 → 10:00~12:00
# ---------------------------------------------------------

hourly_df[
    "블록시작일시"
] = (
    hourly_df[
        "예보일시"
    ]
    .dt.floor(
        "2h"
    )
)

hourly_df[
    "블록종료일시"
] = (
    hourly_df[
        "블록시작일시"
    ]
    + pd.Timedelta(
        hours=2
    )
)


# ---------------------------------------------------------
# 7. 시간대 문자열 생성
# ---------------------------------------------------------

def make_time_label(
    start_datetime,
    end_datetime
):
    """
    블록 시작·종료 시각을 08:00~10:00 형태로 표시함.
    자정을 넘는 블록도 22:00~00:00으로 표시함.
    """

    start_text = (
        start_datetime
        .strftime(
            "%H:%M"
        )
    )

    end_text = (
        end_datetime
        .strftime(
            "%H:%M"
        )
    )

    return (
        f"{start_text}~{end_text}"
    )


# ---------------------------------------------------------
# 8. 거점·2시간 블록별 집계
#
# 같은 블록의 두 시간 중 체감온도가 가장 높은 값을
# 해당 블록의 대표 체감온도로 사용함.
# ---------------------------------------------------------

group_columns = [
    "분석거점ID",
    "대표거점명",
    "블록시작일시",
    "블록종료일시"
]


# 좌표·격자 등 유지할 수 있는 고정정보 열
optional_fixed_columns = [
    "주소",
    "도로명주소",
    "지번주소",
    "위도",
    "경도",
    "격자X",
    "격자Y",
    "nx",
    "ny"
]

existing_fixed_columns = [
    column
    for column in optional_fixed_columns
    if column in hourly_df.columns
]


aggregation_rules = {
    # 블록 내 가장 높은 체감온도 사용
    "체감온도": "max",

    # 블록 내 가장 높은 위험점수 사용
    "기상위험점수": "max",

    # 실제 포함된 시간 수
    "예보일시": "nunique"
}


# 거점의 고정정보는 첫 번째 값 유지
for column in existing_fixed_columns:

    aggregation_rules[
        column
    ] = "first"


two_hour_df = (
    hourly_df
    .groupby(
        group_columns,
        as_index=False
    )
    .agg(
        aggregation_rules
    )
)


two_hour_df = two_hour_df.rename(
    columns={
        "체감온도":
            "블록최고체감온도",

        "기상위험점수":
            "블록기상위험점수",

        "예보일시":
            "블록내시간수"
    }
)


# ---------------------------------------------------------
# 9. 블록 위험등급 재산출
#
# 2시간 중 최고 체감온도를 기준으로 동일한 임계값 적용
# ---------------------------------------------------------

risk_conditions = [
    (
        two_hour_df[
            "블록최고체감온도"
        ] < 33
    ),

    (
        two_hour_df[
            "블록최고체감온도"
        ] >= 33
    )
    & (
        two_hour_df[
            "블록최고체감온도"
        ] < 35
    ),

    (
        two_hour_df[
            "블록최고체감온도"
        ] >= 35
    )
    & (
        two_hour_df[
            "블록최고체감온도"
        ] < 38
    ),

    (
        two_hour_df[
            "블록최고체감온도"
        ] >= 38
    )
]

risk_choices = [
    "낮음",
    "주의",
    "경고",
    "매우 위험"
]


two_hour_df[
    "블록기상위험등급"
] = np.select(
    risk_conditions,
    risk_choices,
    default="확인 필요"
)


two_hour_df[
    "블록기상위험점수"
] = (
    two_hour_df[
        "블록기상위험등급"
    ]
    .map(
        risk_score_map
    )
)


# ---------------------------------------------------------
# 10. 완전·부분 블록 구분
#
# 2시간 블록 안에 시간별 자료가 2개 있으면 완전,
# 1개만 있으면 부분으로 표시
# ---------------------------------------------------------

two_hour_df[
    "완전블록여부"
] = np.where(
    two_hour_df[
        "블록내시간수"
    ] == 2,
    "완전",
    "부분"
)


# ---------------------------------------------------------
# 11. 날짜와 근무조 생성
#
# 이 단계의 기준날짜는 블록 시작일 기준임.
# 야간근무의 정확한 시작 날짜는 다음 단계에서 보정함.
# ---------------------------------------------------------

two_hour_df[
    "기준날짜"
] = (
    two_hour_df[
        "블록시작일시"
    ]
    .dt.normalize()
)


two_hour_df[
    "시작시간"
] = (
    two_hour_df[
        "블록시작일시"
    ]
    .dt.hour
)


# 낮: 08:00~20:00
# 밤: 20:00~다음 날 08:00
two_hour_df[
    "근무조"
] = np.where(
    (
        two_hour_df[
            "시작시간"
        ] >= 8
    )
    & (
        two_hour_df[
            "시작시간"
        ] < 20
    ),
    "낮",
    "밤"
)


two_hour_df[
    "시간대"
] = two_hour_df.apply(
    lambda row:
        make_time_label(
            row[
                "블록시작일시"
            ],
            row[
                "블록종료일시"
            ]
        ),
    axis=1
)


# ---------------------------------------------------------
# 12. 최종 정렬
# ---------------------------------------------------------

two_hour_df = (
    two_hour_df
    .sort_values(
        [
            "분석거점ID",
            "블록시작일시"
        ]
    )
    .reset_index(
        drop=True
    )
)


# ---------------------------------------------------------
# 13. 생성 결과 검수
# ---------------------------------------------------------

total_rows = len(
    two_hour_df
)

site_count = (
    two_hour_df[
        "분석거점ID"
    ]
    .nunique()
)

unique_block_count = (
    two_hour_df[
        "블록시작일시"
    ]
    .nunique()
)

block_duplicate_count = (
    two_hour_df
    .duplicated(
        subset=[
            "분석거점ID",
            "블록시작일시"
        ]
    )
    .sum()
)

block_temperature_missing = (
    two_hour_df[
        "블록최고체감온도"
    ]
    .isna()
    .sum()
)

block_risk_missing = (
    two_hour_df[
        "블록기상위험등급"
    ]
    .isna()
    .sum()
)


print(
    "\n[2시간 단위 기상위험 블록 생성 결과]"
)

print(
    "전체 행 수:",
    total_rows
)

print(
    "고유 거점 수:",
    site_count
)

print(
    "고유 2시간 블록 수:",
    unique_block_count
)

print(
    "거점·블록 중복:",
    block_duplicate_count
)

print(
    "블록최고체감온도 결측:",
    block_temperature_missing
)

print(
    "블록기상위험등급 결측:",
    block_risk_missing
)

print(
    "체감온도 범위:",
    round(
        two_hour_df[
            "블록최고체감온도"
        ].min(),
        1
    ),
    "~",
    round(
        two_hour_df[
            "블록최고체감온도"
        ].max(),
        1
    )
)


# 핵심 검수에서 문제가 있으면 중단
if block_duplicate_count > 0:
    raise ValueError(
        "2시간 자료에 거점·블록 중복이 있습니다."
    )

if block_temperature_missing > 0:
    raise ValueError(
        "블록최고체감온도에 결측이 있습니다."
    )

if block_risk_missing > 0:
    raise ValueError(
        "블록기상위험등급에 결측이 있습니다."
    )


# ---------------------------------------------------------
# 14. 완전·부분 블록 분포
# ---------------------------------------------------------

block_completion_summary = (
    two_hour_df[
        "완전블록여부"
    ]
    .value_counts()
    .reindex(
        [
            "완전",
            "부분"
        ],
        fill_value=0
    )
    .rename_axis(
        "완전블록여부"
    )
    .reset_index(
        name="거점블록수"
    )
)


print(
    "\n[완전·부분 블록 분포]"
)

display(
    block_completion_summary
)


# ---------------------------------------------------------
# 15. 위험등급별 분포
# ---------------------------------------------------------

risk_order = [
    "낮음",
    "주의",
    "경고",
    "매우 위험"
]


risk_count = (
    two_hour_df[
        "블록기상위험등급"
    ]
    .value_counts()
    .reindex(
        risk_order,
        fill_value=0
    )
)


risk_min = (
    two_hour_df
    .groupby(
        "블록기상위험등급"
    )[
        "블록최고체감온도"
    ]
    .min()
    .reindex(
        risk_order
    )
)


risk_max = (
    two_hour_df
    .groupby(
        "블록기상위험등급"
    )[
        "블록최고체감온도"
    ]
    .max()
    .reindex(
        risk_order
    )
)


risk_summary = pd.DataFrame({
    "블록기상위험등급":
        risk_order,

    "거점블록수":
        risk_count.values,

    "최소체감온도":
        risk_min.values,

    "최대체감온도":
        risk_max.values
})


risk_summary[
    "비율_pct"
] = (
    risk_summary[
        "거점블록수"
    ]
    / len(
        two_hour_df
    )
    * 100
).round(
    2
)


print(
    "\n[2시간 블록 위험등급별 분포]"
)

display(
    risk_summary
)


# ---------------------------------------------------------
# 16. 날짜·근무조별 블록 수
#
# 참고:
# 야간 00:00~08:00의 근무조 기준날짜는
# 다음 3-4 단계에서 앞날로 정확히 보정함.
# ---------------------------------------------------------

date_shift_summary = (
    two_hour_df
    .groupby(
        [
            "기준날짜",
            "근무조",
            "완전블록여부"
        ],
        as_index=False
    )
    .agg(
        고유시간블록수=(
            "블록시작일시",
            "nunique"
        ),

        거점블록수=(
            "분석거점ID",
            "size"
        )
    )
    .sort_values(
        [
            "기준날짜",
            "근무조",
            "완전블록여부"
        ]
    )
    .reset_index(
        drop=True
    )
)


print(
    "\n[날짜·근무조별 블록 수]"
)

display(
    date_shift_summary
)


# ---------------------------------------------------------
# 17. 예시 거점의 2시간 단위 위험표
#
# 오류 수정:
# ① 블록시작일시가 존재하는 전체 자료에서 먼저 정렬
# ② 정렬한 뒤 화면에 표시할 열만 선택
# ---------------------------------------------------------

print(
    "\n[예시 거점의 2시간 단위 위험표]"
)


sample_site = (
    two_hour_df[
        "대표거점명"
    ]
    .dropna()
    .iloc[0]
)


sample_cols = [
    "대표거점명",
    "기준날짜",
    "근무조",
    "시간대",
    "블록최고체감온도",
    "블록기상위험등급",
    "완전블록여부"
]


sample_table = (
    two_hour_df.loc[
        two_hour_df[
            "대표거점명"
        ] == sample_site
    ]
    # 먼저 블록 시작시각으로 정렬
    .sort_values(
        "블록시작일시"
    )
    # 정렬 후 표시할 열만 선택
    [
        sample_cols
    ]
    .reset_index(
        drop=True
    )
)


display(
    sample_table
)


# ---------------------------------------------------------
# 18. 결과 저장
# ---------------------------------------------------------

two_hour_df.to_csv(
    OUTPUT_PATH,
    index=False,
    encoding="utf-8-sig"
)


risk_summary.to_csv(
    SUMMARY_PATH,
    index=False,
    encoding="utf-8-sig"
)


print(
    "\n저장 완료:"
)

print(
    OUTPUT_PATH
)

print(
    SUMMARY_PATH
)

[3-2 시간별 기상위험 자료 불러오기]
전체 행 수: 2318
전체 열 수: 26

[2시간 단위 기상위험 블록 생성 결과]
전체 행 수: 1178
고유 거점 수: 38
고유 2시간 블록 수: 31
거점·블록 중복: 0
블록최고체감온도 결측: 0
블록기상위험등급 결측: 0
체감온도 범위: 26.0 ~ 34.3

[완전·부분 블록 분포]

  완전블록여부  거점블록수
0     완전   1140
1     부분     38

[2시간 블록 위험등급별 분포]

  블록기상위험등급  거점블록수  최소체감온도  최대체감온도  비율_pct
0       낮음    996    26.0    32.9   84.55
1       주의    182    33.3    34.3   15.45
2       경고      0     NaN     NaN    0.00
3    매우 위험      0     NaN     NaN    0.00

[날짜·근무조별 블록 수]

        기준날짜 근무조 완전블록여부  고유시간블록수  거점블록수
0 2026-07-28   낮     완전        4    152
1 2026-07-28   밤     완전        2     76
2 2026-07-29   낮     완전        6    228
3 2026-07-29   밤     완전        6    228
4 2026-07-30   낮     완전        6    228
5 2026-07-30   밤     완전        6    228
6 2026-07-31   밤     부분        1     38

[예시 거점의 2시간 단위 위험표]

     대표거점명       기준날짜 근무조          시간대  블록최고체감온도 블록기상위험등급 완전블록여부
0   대전보세창고 2026-07-28   낮  12:00~14:00      33.3       주의     완전
1   대전보세창고 2026-07-28   낮  14:00~16:00      33.3       주의     완전
2   대전보세창고 2026-07-28   낮  16:00~18:00      33.3       주의     완전
3   대전보세창고 2026-07-28   낮  18:00~20:00      31.7       낮음     완전
4   대전보세창고 2026-07-28   밤  20:00~22:00      29.7       낮음     완전
5   대전보세창고 2026-07-28   밤  22:00~00:00      29.1       낮음     완전
6   대전보세창고 2026-07-29   밤  00:00~02:00      28.0       낮음     완전
7   대전보세창고 2026-07-29   밤  02:00~04:00      28.0       낮음     완전
8   대전보세창고 2026-07-29   밤  04:00~06:00      27.0       낮음     완전
9   대전보세창고 2026-07-29   밤  06:00~08:00      28.0       낮음     완전
10  대전보세창고 2026-07-29   낮  08:00~10:00      30.8       낮음     완전
11  대전보세창고 2026-07-29   낮  10:00~12:00      32.1       낮음     완전
12  대전보세창고 2026-07-29   낮  12:00~14:00      33.3       주의     완전
13  대전보세창고 2026-07-29   낮  14:00~16:00      33.3       주의     완전
14  대전보세창고 2026-07-29   낮  16:00~18:00      33.3       주의     완전
15  대전보세창고 2026-07-29   낮  18:00~20:00      32.3       낮음     완전
16  대전보세창고 2026-07-29   밤  20:00~22:00      29.4       낮음     완전
17  대전보세창고 2026-07-29   밤  22:00~00:00      29.1       낮음     완전
18  대전보세창고 2026-07-30   밤  00:00~02:00      28.0       낮음     완전
19  대전보세창고 2026-07-30   밤  02:00~04:00      27.0       낮음     완전
20  대전보세창고 2026-07-30   밤  04:00~06:00      27.0       낮음     완전
21  대전보세창고 2026-07-30   밤  06:00~08:00      27.0       낮음     완전
22  대전보세창고 2026-07-30   낮  08:00~10:00      29.4       낮음     완전
23  대전보세창고 2026-07-30   낮  10:00~12:00      31.7       낮음     완전
24  대전보세창고 2026-07-30   낮  12:00~14:00      33.3       주의     완전
25  대전보세창고 2026-07-30   낮  14:00~16:00      33.9       주의     완전
26  대전보세창고 2026-07-30   낮  16:00~18:00      33.9       주의     완전
27  대전보세창고 2026-07-30   낮  18:00~20:00      32.3       낮음     완전
28  대전보세창고 2026-07-30   밤  20:00~22:00      29.4       낮음     완전
29  대전보세창고 2026-07-30   밤  22:00~00:00      29.1       낮음     완전
30  대전보세창고 2026-07-31   밤  00:00~02:00      28.0       낮음     부분

저장 완료:
/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/대전_38개물류거점_2시간단위_작업기상위험.csv
/content/drive/MyDrive/대전_물류창고_폭염위험도/04_분석결과/대전_2시간단위_작업기상위험등급별_요약.csv

3-3-1. 예시 거점 표 출력 및 결과 저장 수정

In [ ]:
# =========================================================
# 3-3-1. 2시간 단위 분석자료 메모리 복구
#
# 오류 원인:
# - 런타임 재시작으로 two_hour_risk 변수가 사라짐
# - 3-3에서는 실제로 block_risk 변수명을 사용함
#
# 코드 상태:
# - 기존 3-3-1 완전 대체
# - 최종 유지
# - 3-3 전체 재실행 불필요
# =========================================================

from pathlib import Path
import pandas as pd
from IPython.display import display


# ---------------------------------------------------------
# 1. 저장된 2시간 단위 결과파일 경로
# ---------------------------------------------------------

PROJECT_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도"
)

INPUT_FILE = (
    PROJECT_DIR
    / "03_전처리데이터"
    / "대전_38개물류거점_2시간단위_작업기상위험.csv"
)


# ---------------------------------------------------------
# 2. 기존 메모리 변수가 있으면 재사용,
#    없으면 저장파일에서 복구
# ---------------------------------------------------------

if "block_risk" in globals():

    two_hour_risk = block_risk.copy()

    load_method = (
        "현재 런타임의 block_risk 변수를 복사했습니다."
    )

elif "two_hour_risk" in globals():

    block_risk = two_hour_risk.copy()

    load_method = (
        "현재 런타임의 two_hour_risk 변수를 복사했습니다."
    )

else:

    if not INPUT_FILE.exists():

        raise FileNotFoundError(
            "저장된 2시간 단위 분석파일을 찾을 수 없습니다.\n"
            f"확인 경로: {INPUT_FILE}\n\n"
            "구글 드라이브가 연결되어 있는지 확인해주세요."
        )

    two_hour_risk = pd.read_csv(
        INPUT_FILE,
        encoding="utf-8-sig"
    )

    block_risk = two_hour_risk.copy()

    load_method = (
        "저장된 CSV 파일에서 분석자료를 복구했습니다."
    )


# ---------------------------------------------------------
# 3. 날짜·시간 열 형식 복구
# ---------------------------------------------------------

datetime_candidates = [
    "블록시작일시",
    "블록종료일시",
    "예보일시"
]

for column in datetime_candidates:

    if column in two_hour_risk.columns:

        two_hour_risk[column] = pd.to_datetime(
            two_hour_risk[column],
            errors="coerce"
        )

        block_risk[column] = two_hour_risk[
            column
        ].copy()


# ---------------------------------------------------------
# 4. 복구 결과 검수
# ---------------------------------------------------------

print("[3-3-1 실행 완료]")
print(load_method)

print(
    "\n자료 크기:",
    two_hour_risk.shape
)

print(
    "전체 행 수:",
    len(two_hour_risk)
)

if "거점명" in two_hour_risk.columns:

    print(
        "물류거점 수:",
        two_hour_risk["거점명"].nunique()
    )

if "기상위험등급" in two_hour_risk.columns:

    print(
        "\n[기상위험등급 분포]"
    )

    risk_order = [
        "낮음",
        "주의",
        "경고",
        "매우 위험"
    ]

    risk_summary = (
        two_hour_risk[
            "기상위험등급"
        ]
        .value_counts()
        .reindex(
            risk_order,
            fill_value=0
        )
        .rename_axis(
            "기상위험등급"
        )
        .reset_index(
            name="건수"
        )
    )

    risk_summary[
        "비율_pct"
    ] = (
        risk_summary["건수"]
        / len(two_hour_risk)
        * 100
    ).round(2)

    display(risk_summary)


# ---------------------------------------------------------
# 5. 두 변수명이 모두 정상 생성되었는지 확인
# ---------------------------------------------------------

print(
    "\nblock_risk 생성 여부:",
    "block_risk" in globals()
)

print(
    "two_hour_risk 생성 여부:",
    "two_hour_risk" in globals()
)

print(
    "두 변수의 행 수 일치 여부:",
    len(block_risk) == len(two_hour_risk)
)


display(
    two_hour_risk.head()
)

[3-3-1 실행 완료]
현재 런타임의 block_risk 변수를 복사했습니다.

자료 크기: (1178, 17)
전체 행 수: 1178

block_risk 생성 여부: True
two_hour_risk 생성 여부: True
두 변수의 행 수 일치 여부: True

,분석거점ID,대표거점명,블록시작일시,블록종료일시,블록최고체감온도,블록기상위험점수,블록내시간수,위도,경도,격자X,격자Y,블록기상위험등급,완전블록여부,기준날짜,시작시간,근무조,시간대
0,LOC_2000M63000000033,대전보세창고,2026-07-28 12:00:00,2026-07-28 14:00:00,33.3,2,2,36.447477,127.400315,67,103,주의,완전,2026-07-28,12,낮,12:00~14:00
1,LOC_2000M63000000033,대전보세창고,2026-07-28 14:00:00,2026-07-28 16:00:00,33.3,2,2,36.447477,127.400315,67,103,주의,완전,2026-07-28,14,낮,14:00~16:00
2,LOC_2000M63000000033,대전보세창고,2026-07-28 16:00:00,2026-07-28 18:00:00,33.3,2,2,36.447477,127.400315,67,103,주의,완전,2026-07-28,16,낮,16:00~18:00
3,LOC_2000M63000000033,대전보세창고,2026-07-28 18:00:00,2026-07-28 20:00:00,31.7,1,2,36.447477,127.400315,67,103,낮음,완전,2026-07-28,18,낮,18:00~20:00
4,LOC_2000M63000000033,대전보세창고,2026-07-28 20:00:00,2026-07-28 22:00:00,29.7,1,2,36.447477,127.400315,67,103,낮음,완전,2026-07-28,20,밤,20:00~22:00

- 낮 근무조: 08:00 ~ 20:00
- 밤 근무조: 20:00 ~ 익일 08:00
- 3-3-1 셀에서 7월 29일 00:00 ~ 08:00 이 밤 근무조로 표시 -> 다음 셀에서 수정

3-3-2. 밤 근무조 기준날짜 보정

In [ ]:
# =========================================================
# 3-3-2. 밤 근무조 기준날짜 보정
#
# 목적:
# 밤 근무조를 당일 20:00~익일 08:00로 묶기 위해
# 자정 이후 00:00~08:00 블록의 근무조 기준날짜를
# 하루 전 날짜로 조정함
#
# 예:
# 2026-07-29 00:00~02:00
# → 2026-07-28 밤 근무조에 포함
# =========================================================

from pathlib import Path
import pandas as pd
import numpy as np

PROCESSED_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
)


# ---------------------------------------------------------
# 1. 기존 2시간 단위 결과 불러오기
# ---------------------------------------------------------

input_path = (
    PROCESSED_DIR /
    "대전_38개물류거점_2시간단위_작업기상위험.csv"
)

shift_risk = pd.read_csv(
    input_path,
    encoding="utf-8-sig",
    dtype={
        "분석거점ID": str,
        "우편번호": str
    }
)


# ---------------------------------------------------------
# 2. 날짜·시간 형식 변환
# ---------------------------------------------------------

datetime_cols = [
    "블록시작일시",
    "블록종료일시"
]

for col in datetime_cols:
    shift_risk[col] = pd.to_datetime(
        shift_risk[col],
        errors="coerce"
    )

if shift_risk[datetime_cols].isna().any().any():
    raise ValueError(
        "블록 시작·종료일시 변환 과정에서 결측이 발생했습니다."
    )


# ---------------------------------------------------------
# 3. 근무조 기준날짜 생성
#
# 낮 근무조:
# 해당 날짜 08:00~20:00
#
# 밤 근무조:
# 해당 날짜 20:00~익일 08:00
#
# 자정 이후 00:00~08:00은
# 전날 시작한 밤 근무조에 포함
# ---------------------------------------------------------

start_hour = (
    shift_risk["블록시작일시"]
    .dt.hour
)

shift_risk["근무조"] = np.where(
    (start_hour >= 8) & (start_hour < 20),
    "낮",
    "밤"
)

shift_risk["근무조기준날짜"] = (
    shift_risk["블록시작일시"]
    .dt.normalize()
)

after_midnight_mask = (
    start_hour < 8
)

shift_risk.loc[
    after_midnight_mask,
    "근무조기준날짜"
] = (
    shift_risk.loc[
        after_midnight_mask,
        "근무조기준날짜"
    ]
    - pd.Timedelta(days=1)
)

shift_risk["근무조기준날짜"] = (
    shift_risk["근무조기준날짜"]
    .dt.date
)


# ---------------------------------------------------------
# 4. 완전한 근무조 여부 확인
#
# 낮·밤 모두 정상적으로는 거점당 6개 블록
# 부분 예보가 있는 경우 6개보다 적을 수 있음
# ---------------------------------------------------------

shift_block_count = (
    shift_risk
    .groupby(
        [
            "분석거점ID",
            "근무조기준날짜",
            "근무조"
        ]
    )["블록시작일시"]
    .transform("nunique")
)

shift_risk["근무조블록수"] = shift_block_count

shift_risk["완전근무조여부"] = np.where(
    (
        (shift_risk["근무조블록수"] == 6)
        & (shift_risk["완전블록여부"] == "완전")
    ),
    "완전",
    "부분"
)


# ---------------------------------------------------------
# 5. 기본 검수
# ---------------------------------------------------------

print("[밤 근무조 기준날짜 보정 결과]")

print(
    "전체 행 수:",
    len(shift_risk)
)

print(
    "고유 거점 수:",
    shift_risk["분석거점ID"].nunique()
)

print(
    "근무조기준날짜 결측:",
    shift_risk["근무조기준날짜"].isna().sum()
)

print(
    "거점·블록 중복:",
    shift_risk.duplicated(
        subset=[
            "분석거점ID",
            "블록시작일시"
        ]
    ).sum()
)


# ---------------------------------------------------------
# 6. 날짜·근무조별 블록 수 확인
# ---------------------------------------------------------

shift_summary = (
    shift_risk
    .groupby(
        [
            "근무조기준날짜",
            "근무조",
            "완전근무조여부"
        ],
        as_index=False
    )
    .agg(
        고유시간블록수=(
            "블록시작일시",
            "nunique"
        ),
        거점블록수=(
            "분석거점ID",
            "size"
        )
    )
)

print("\n[근무조 기준날짜별 블록 수]")

display(shift_summary)


# ---------------------------------------------------------
# 7. 백년축산 밤 근무조 예시 확인
# ---------------------------------------------------------

sample = shift_risk.copy()

if "대표거점명" in sample.columns:
    sample = sample[
        sample["대표거점명"]
        .astype(str)
        .str.contains(
            "백년축산",
            na=False
        )
    ]

sample_dates = sorted(
    sample["근무조기준날짜"]
    .dropna()
    .unique()
)

if sample_dates:
    sample_date = sample_dates[0]

    sample_night = (
        sample[
            (sample["근무조기준날짜"] == sample_date)
            & (sample["근무조"] == "밤")
        ]
        .sort_values("블록시작일시")
    )

    display_cols = [
        col for col in [
            "근무조기준날짜",
            "근무조",
            "시간대",
            "블록시작일시",
            "대표거점명",
            "블록최고체감온도",
            "블록기상위험등급",
            "완전블록여부",
            "완전근무조여부"
        ]
        if col in sample_night.columns
    ]

    print(
        f"\n[백년축산 {sample_date} 밤 근무조 예시]"
    )

    display(
        sample_night[display_cols]
    )


# ---------------------------------------------------------
# 8. 저장
# ---------------------------------------------------------

save_path = (
    PROCESSED_DIR /
    "대전_38개물류거점_2시간단위_근무조기준_작업기상위험.csv"
)

summary_path = (
    PROCESSED_DIR /
    "대전_근무조기준날짜별_블록수요약.csv"
)

shift_risk.to_csv(
    save_path,
    index=False,
    encoding="utf-8-sig"
)

shift_summary.to_csv(
    summary_path,
    index=False,
    encoding="utf-8-sig"
)

print("\n저장 완료:")
print(save_path)
print(summary_path)

[밤 근무조 기준날짜 보정 결과]
전체 행 수: 1178
고유 거점 수: 38
근무조기준날짜 결측: 0
거점·블록 중복: 0

[근무조 기준날짜별 블록 수]

      근무조기준날짜 근무조 완전근무조여부  고유시간블록수  거점블록수
0  2026-07-28   낮      부분        4    152
1  2026-07-28   밤      완전        6    228
2  2026-07-29   낮      완전        6    228
3  2026-07-29   밤      완전        6    228
4  2026-07-30   낮      완전        6    228
5  2026-07-30   밤      부분        3    114

[백년축산 2026-07-28 밤 근무조 예시]

,근무조기준날짜,근무조,시간대,블록시작일시,대표거점명,블록최고체감온도,블록기상위험등급,완전블록여부,완전근무조여부
965,2026-07-28,밤,20:00~22:00,2026-07-28 20:00:00,백년축산,29.4,낮음,완전,완전
966,2026-07-28,밤,22:00~00:00,2026-07-28 22:00:00,백년축산,29.1,낮음,완전,완전
967,2026-07-28,밤,00:00~02:00,2026-07-29 00:00:00,백년축산,28.0,낮음,완전,완전
968,2026-07-28,밤,02:00~04:00,2026-07-29 02:00:00,백년축산,28.0,낮음,완전,완전
969,2026-07-28,밤,04:00~06:00,2026-07-29 04:00:00,백년축산,27.0,낮음,완전,완전
970,2026-07-28,밤,06:00~08:00,2026-07-29 06:00:00,백년축산,28.0,낮음,완전,완전

저장 완료:
/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/대전_38개물류거점_2시간단위_근무조기준_작업기상위험.csv
/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/대전_근무조기준날짜별_블록수요약.csv

- 전체 1,178행과 38개 거점 그대로 유지. 결측, 중복 없음
- 3-3-1 셀 오류 수정 완료
- 7/28 낮은 예보가 12:00부터 시작이라 '부분'으로 표시
- 7/30 밤은 예보 종료가 있어 '부분'으로 표시

3-4. 위험등급별 기준 배치비율 설정 및 정수 인원배분 검증

In [ ]:
# =========================================================
# 3-4. 위험등급별 기준 배치비율 설정 및
#      정수 인원배분 방식 검증
#
# 목적:
# 1) 기상위험등급별 업무 배치비율을 설정함
# 2) 사용자가 입력한 총인원을 정수 인원으로 자동 배분함
# 3) 총인원이 비율에 나누어떨어지지 않더라도
#    배치 합계가 입력 인원과 정확히 일치하도록 함
#
# 작업 구분:
# - 상하차
# - 분류
# - 검수
# - 휴식 및 대기
#
# 배치 제한:
# 총인원 4명 미만은 네 작업을 동시에 운영할 수 없으므로
# 정상 배치 대신 '배치 제한'으로 표시함
# =========================================================

from pathlib import Path
import pandas as pd
import numpy as np

PROCESSED_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
)


# ---------------------------------------------------------
# 1. 위험등급별 기준 배치비율 설정
#
# 체감온도 위험이 높아질수록:
# - 상하차 비율 감소
# - 휴식 및 대기 비율 증가
# - 분류와 검수는 비교적 안정적으로 유지
# ---------------------------------------------------------

ratio_table = pd.DataFrame({
    "블록기상위험등급": [
        "낮음",
        "주의",
        "경고",
        "매우 위험"
    ],
    "상하차비율": [
        0.40,
        0.30,
        0.20,
        0.10
    ],
    "분류비율": [
        0.30,
        0.30,
        0.30,
        0.25
    ],
    "검수비율": [
        0.15,
        0.15,
        0.15,
        0.15
    ],
    "휴식및대기비율": [
        0.15,
        0.25,
        0.35,
        0.50
    ]
})


# ---------------------------------------------------------
# 2. 비율 합계 검수
# ---------------------------------------------------------

ratio_cols = [
    "상하차비율",
    "분류비율",
    "검수비율",
    "휴식및대기비율"
]

ratio_table["비율합계"] = (
    ratio_table[ratio_cols]
    .sum(axis=1)
)

if not np.allclose(
    ratio_table["비율합계"],
    1.0
):
    raise ValueError(
        "위험등급별 배치비율 합계가 100%가 아닙니다."
    )

print("[위험등급별 기준 인력배치 비율]")

display(
    ratio_table.assign(
        상하차비율_pct=(
            ratio_table["상하차비율"] * 100
        ).round(1),
        분류비율_pct=(
            ratio_table["분류비율"] * 100
        ).round(1),
        검수비율_pct=(
            ratio_table["검수비율"] * 100
        ).round(1),
        휴식및대기비율_pct=(
            ratio_table["휴식및대기비율"] * 100
        ).round(1)
    )[
        [
            "블록기상위험등급",
            "상하차비율_pct",
            "분류비율_pct",
            "검수비율_pct",
            "휴식및대기비율_pct"
        ]
    ]
)


# ---------------------------------------------------------
# 3. 위험등급별 동률 우선순위 설정
#
# 정수 배분 과정에서 두 작업의 배정 필요도가 같을 경우
# 위험등급에 따라 우선적으로 1명을 배정할 작업 순서임
# ---------------------------------------------------------

tie_priority = {
    "낮음": [
        "상하차",
        "분류",
        "검수",
        "휴식 및 대기"
    ],
    "주의": [
        "휴식 및 대기",
        "검수",
        "분류",
        "상하차"
    ],
    "경고": [
        "휴식 및 대기",
        "검수",
        "분류",
        "상하차"
    ],
    "매우 위험": [
        "휴식 및 대기",
        "검수",
        "분류",
        "상하차"
    ]
}


# ---------------------------------------------------------
# 4. 정수 인원배분 함수
#
# 방식:
# - 총인원 4명 이상이면 각 작업에 최소 1명 우선 배치
# - 남은 인원은 목표 비율과의 차이가 가장 작아지는
#   작업에 1명씩 추가 배정
# - 최종 합계는 입력 총인원과 반드시 일치
# ---------------------------------------------------------

def allocate_workers(
    total_workers,
    risk_grade
):
    """
    총근무인원과 기상위험등급을 입력받아
    네 업무의 정수 배치인원을 반환함.
    """

    # 입력값 확인
    if (
        not isinstance(
            total_workers,
            (int, np.integer)
        )
        or total_workers < 1
    ):
        raise ValueError(
            "총근무인원은 1명 이상의 정수여야 합니다."
        )

    if risk_grade not in ratio_table[
        "블록기상위험등급"
    ].tolist():
        raise ValueError(
            f"정의되지 않은 위험등급입니다: {risk_grade}"
        )

    tasks = [
        "상하차",
        "분류",
        "검수",
        "휴식 및 대기"
    ]

    ratio_row = (
        ratio_table.loc[
            ratio_table[
                "블록기상위험등급"
            ] == risk_grade
        ]
        .iloc[0]
    )

    ratios = {
        "상하차": ratio_row["상하차비율"],
        "분류": ratio_row["분류비율"],
        "검수": ratio_row["검수비율"],
        "휴식 및 대기": ratio_row[
            "휴식및대기비율"
        ]
    }

    # 4명 미만은 네 작업 동시 운영 불가
    if total_workers < 4:
        return {
            "총근무인원": total_workers,
            "상하차": 0,
            "분류": 0,
            "검수": 0,
            "휴식 및 대기": 0,
            "배치상태": "배치 제한"
        }

    # 각 작업 최소 1명 배치
    allocation = {
        task: 1
        for task in tasks
    }

    # 목표 인원
    target = {
        task: total_workers * ratios[task]
        for task in tasks
    }

    remaining = total_workers - 4

    # 우선순위 순서를 숫자로 변환
    priority_rank = {
        task: rank
        for rank, task in enumerate(
            tie_priority[risk_grade]
        )
    }

    # 남은 인원을 한 명씩 배치
    for _ in range(remaining):

        candidate_scores = []

        for task in tasks:

            # 현재 배치에서 1명을 추가했을 때
            # 목표값과의 제곱오차 증가량
            additional_error = (
                2 * (
                    allocation[task]
                    - target[task]
                )
                + 1
            )

            candidate_scores.append(
                (
                    additional_error,
                    priority_rank[task],
                    task
                )
            )

        # 오차가 가장 적고,
        # 동률이면 위험등급별 우선순위가 높은 작업 선택
        selected_task = min(
            candidate_scores
        )[2]

        allocation[selected_task] += 1

    result = {
        "총근무인원": total_workers,
        "상하차": allocation["상하차"],
        "분류": allocation["분류"],
        "검수": allocation["검수"],
        "휴식 및 대기": allocation[
            "휴식 및 대기"
        ],
        "배치상태": "배치 가능"
    }

    return result


# ---------------------------------------------------------
# 5. 주요 인원수 예시 검증
# ---------------------------------------------------------

example_worker_counts = [
    1,
    2,
    3,
    4,
    5,
    7,
    13,
    20,
    30
]

example_results = []

for risk_grade in ratio_table[
    "블록기상위험등급"
]:

    for worker_count in example_worker_counts:

        allocation_result = allocate_workers(
            worker_count,
            risk_grade
        )

        allocation_result[
            "블록기상위험등급"
        ] = risk_grade

        example_results.append(
            allocation_result
        )

example_df = pd.DataFrame(
    example_results
)

example_df["배치합계"] = (
    example_df[
        [
            "상하차",
            "분류",
            "검수",
            "휴식 및 대기"
        ]
    ]
    .sum(axis=1)
)

example_df["합계일치여부"] = np.where(
    example_df["배치상태"] == "배치 제한",
    "제한",
    np.where(
        example_df["배치합계"]
        == example_df["총근무인원"],
        "일치",
        "불일치"
    )
)

example_df = example_df[
    [
        "블록기상위험등급",
        "총근무인원",
        "상하차",
        "분류",
        "검수",
        "휴식 및 대기",
        "배치합계",
        "배치상태",
        "합계일치여부"
    ]
]

print("\n[주요 인원수별 정수 배치 예시]")

display(example_df)


# ---------------------------------------------------------
# 6. 4명부터 1,000명까지 전체 검수
#
# 모든 위험등급과 모든 인원수에서:
# - 배치합계가 입력인원과 같은지
# - 음수 인원이 없는지
# - 각 작업에 최소 1명이 있는지 확인
# ---------------------------------------------------------

validation_results = []

for risk_grade in ratio_table[
    "블록기상위험등급"
]:

    for worker_count in range(
        4,
        1001
    ):

        result = allocate_workers(
            worker_count,
            risk_grade
        )

        allocated_values = [
            result["상하차"],
            result["분류"],
            result["검수"],
            result["휴식 및 대기"]
        ]

        validation_results.append({
            "블록기상위험등급": risk_grade,
            "총근무인원": worker_count,
            "합계일치": (
                sum(allocated_values)
                == worker_count
            ),
            "음수없음": all(
                value >= 0
                for value in allocated_values
            ),
            "최소1명충족": all(
                value >= 1
                for value in allocated_values
            )
        })

validation_df = pd.DataFrame(
    validation_results
)

validation_summary = pd.DataFrame({
    "검사항목": [
        "전체 검증 조합 수",
        "합계 불일치 수",
        "음수 발생 수",
        "최소 1명 미충족 수"
    ],
    "결과": [
        len(validation_df),
        (
            ~validation_df["합계일치"]
        ).sum(),
        (
            ~validation_df["음수없음"]
        ).sum(),
        (
            ~validation_df["최소1명충족"]
        ).sum()
    ]
})

print(
    "\n[4명~1,000명 정수 배치 전체 검수]"
)

display(validation_summary)


# ---------------------------------------------------------
# 7. 13명 배치 결과 별도 확인
# ---------------------------------------------------------

thirteen_results = []

for risk_grade in ratio_table[
    "블록기상위험등급"
]:

    result = allocate_workers(
        13,
        risk_grade
    )

    result[
        "블록기상위험등급"
    ] = risk_grade

    thirteen_results.append(result)

thirteen_df = pd.DataFrame(
    thirteen_results
)

thirteen_df["배치합계"] = (
    thirteen_df[
        [
            "상하차",
            "분류",
            "검수",
            "휴식 및 대기"
        ]
    ]
    .sum(axis=1)
)

print("\n[총인원 13명 배치 결과]")

display(
    thirteen_df[
        [
            "블록기상위험등급",
            "총근무인원",
            "상하차",
            "분류",
            "검수",
            "휴식 및 대기",
            "배치합계",
            "배치상태"
        ]
    ]
)


# ---------------------------------------------------------
# 8. 저장
# ---------------------------------------------------------

ratio_save_path = (
    PROCESSED_DIR /
    "위험등급별_기준인력배치비율.csv"
)

example_save_path = (
    PROCESSED_DIR /
    "위험등급별_정수인원배치_검증예시.csv"
)

ratio_table.to_csv(
    ratio_save_path,
    index=False,
    encoding="utf-8-sig"
)

example_df.to_csv(
    example_save_path,
    index=False,
    encoding="utf-8-sig"
)

print("\n저장 완료:")
print(ratio_save_path)
print(example_save_path)

[위험등급별 기준 인력배치 비율]

  블록기상위험등급  상하차비율_pct  분류비율_pct  검수비율_pct  휴식및대기비율_pct
0       낮음       40.0      30.0      15.0         15.0
1       주의       30.0      30.0      15.0         25.0
2       경고       20.0      30.0      15.0         35.0
3    매우 위험       10.0      25.0      15.0         50.0

[주요 인원수별 정수 배치 예시]

   블록기상위험등급  총근무인원  상하차  분류  검수  휴식 및 대기  배치합계   배치상태 합계일치여부
0        낮음      1    0   0   0        0     0  배치 제한     제한
1        낮음      2    0   0   0        0     0  배치 제한     제한
2        낮음      3    0   0   0        0     0  배치 제한     제한
3        낮음      4    1   1   1        1     4  배치 가능     일치
4        낮음      5    2   1   1        1     5  배치 가능     일치
5        낮음      7    3   2   1        1     7  배치 가능     일치
6        낮음     13    5   4   2        2    13  배치 가능     일치
7        낮음     20    8   6   3        3    20  배치 가능     일치
8        낮음     30   12   9   5        4    30  배치 가능     일치
9        주의      1    0   0   0        0     0  배치 제한     제한
10       주의      2    0   0   0        0     0  배치 제한     제한
11       주의      3    0   0   0        0     0  배치 제한     제한
12       주의      4    1   1   1        1     4  배치 가능     일치
13       주의      5    1   2   1        1     5  배치 가능     일치
14       주의      7    2   2   1        2     7  배치 가능     일치
15       주의     13    4   4   2        3    13  배치 가능     일치
16       주의     20    6   6   3        5    20  배치 가능     일치
17       주의     30    9   9   4        8    30  배치 가능     일치
18       경고      1    0   0   0        0     0  배치 제한     제한
19       경고      2    0   0   0        0     0  배치 제한     제한
20       경고      3    0   0   0        0     0  배치 제한     제한
21       경고      4    1   1   1        1     4  배치 가능     일치
22       경고      5    1   1   1        2     5  배치 가능     일치
23       경고      7    1   2   1        3     7  배치 가능     일치
24       경고     13    3   4   2        4    13  배치 가능     일치
25       경고     20    4   6   3        7    20  배치 가능     일치
26       경고     30    6   9   4       11    30  배치 가능     일치
27    매우 위험      1    0   0   0        0     0  배치 제한     제한
28    매우 위험      2    0   0   0        0     0  배치 제한     제한
29    매우 위험      3    0   0   0        0     0  배치 제한     제한
30    매우 위험      4    1   1   1        1     4  배치 가능     일치
31    매우 위험      5    1   1   1        2     5  배치 가능     일치
32    매우 위험      7    1   2   1        3     7  배치 가능     일치
33    매우 위험     13    1   3   2        7    13  배치 가능     일치
34    매우 위험     20    2   5   3       10    20  배치 가능     일치
35    매우 위험     30    3   7   5       15    30  배치 가능     일치

[4명~1,000명 정수 배치 전체 검수]

          검사항목    결과
0   전체 검증 조합 수  3988
1     합계 불일치 수     0
2      음수 발생 수     0
3  최소 1명 미충족 수     0

[총인원 13명 배치 결과]

  블록기상위험등급  총근무인원  상하차  분류  검수  휴식 및 대기  배치합계   배치상태
0       낮음     13    5   4   2        2    13  배치 가능
1       주의     13    4   4   2        3    13  배치 가능
2       경고     13    3   4   2        4    13  배치 가능
3    매우 위험     13    1   3   2        7    13  배치 가능

저장 완료:
/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/위험등급별_기준인력배치비율.csv
/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/위험등급별_정수인원배치_검증예시.csv

- 위험등급별 비율 합계 모두 100%
- 합계 불일치, 음수, 최소 1명 미충족이 모두 0건
- 위험도가 높을수록 상하차 인원은 줄고 휴식 인원이 증가하는 방향 정상 반영

- 3-5. 운영자 입력 위젯 생서 및 작동 확인

In [ ]:
# =========================================================
# 3-5. 운영자 입력 위젯 생성 및 작동 확인
#
# 목적:
# 코드 안에서 값을 직접 수정하지 않고,
# Colab 출력창에서 거점·날짜·근무조를 선택하고
# 총근무인원을 입력할 수 있는 화면을 생성함
#
# 이번 단계에서는 입력 위젯이 정상적으로 표시되고
# 선택값이 올바르게 전달되는지만 확인함
# =========================================================

from pathlib import Path
import pandas as pd
import ipywidgets as widgets

from IPython.display import display, clear_output


PROCESSED_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
)


# ---------------------------------------------------------
# 1. 근무조 기준 기상위험 자료 불러오기
# ---------------------------------------------------------

weather_path = (
    PROCESSED_DIR /
    "대전_38개물류거점_2시간단위_근무조기준_작업기상위험.csv"
)

weather_df = pd.read_csv(
    weather_path,
    encoding="utf-8-sig",
    dtype={
        "분석거점ID": str,
        "우편번호": str
    }
)

weather_df["근무조기준날짜"] = pd.to_datetime(
    weather_df["근무조기준날짜"],
    errors="coerce"
).dt.normalize()

weather_df["블록시작일시"] = pd.to_datetime(
    weather_df["블록시작일시"],
    errors="coerce"
)

if weather_df["근무조기준날짜"].isna().any():
    raise ValueError(
        "근무조기준날짜 변환 과정에서 결측이 발생했습니다."
    )


# ---------------------------------------------------------
# 2. 드롭다운 선택목록 생성
# ---------------------------------------------------------

site_options = sorted(
    weather_df["대표거점명"]
    .dropna()
    .astype(str)
    .str.strip()
    .unique()
    .tolist()
)

date_options = sorted(
    weather_df["근무조기준날짜"]
    .dropna()
    .dt.strftime("%Y-%m-%d")
    .unique()
    .tolist()
)

if len(site_options) == 0:
    raise ValueError(
        "선택 가능한 물류거점이 없습니다."
    )

if len(date_options) == 0:
    raise ValueError(
        "선택 가능한 날짜가 없습니다."
    )


# ---------------------------------------------------------
# 3. 입력 위젯 생성
# ---------------------------------------------------------

site_dropdown = widgets.Dropdown(
    options=site_options,
    value=(
        "백년축산"
        if "백년축산" in site_options
        else site_options[0]
    ),
    description="근무거점:",
    style={
        "description_width": "100px"
    },
    layout=widgets.Layout(
        width="500px"
    )
)

date_dropdown = widgets.Dropdown(
    options=date_options,
    value=date_options[0],
    description="날짜:",
    style={
        "description_width": "100px"
    },
    layout=widgets.Layout(
        width="300px"
    )
)

shift_dropdown = widgets.Dropdown(
    options=[
        ("낮 근무조", "낮"),
        ("밤 근무조", "밤")
    ],
    value="낮",
    description="근무조:",
    style={
        "description_width": "100px"
    },
    layout=widgets.Layout(
        width="300px"
    )
)

worker_input = widgets.BoundedIntText(
    value=13,
    min=1,
    max=1000,
    step=1,
    description="총근무인원:",
    style={
        "description_width": "100px"
    },
    layout=widgets.Layout(
        width="300px"
    )
)

confirm_button = widgets.Button(
    description="입력값 확인",
    button_style="primary",
    icon="check",
    layout=widgets.Layout(
        width="180px"
    )
)

output_area = widgets.Output()


# ---------------------------------------------------------
# 4. 날짜 또는 근무조 변경 시
#    실제 선택 가능한 조합인지 확인
# ---------------------------------------------------------

def update_available_dates(*args):

    selected_site = site_dropdown.value
    selected_shift = shift_dropdown.value

    available = (
        weather_df.loc[
            (
                weather_df["대표거점명"]
                .astype(str)
                .str.strip()
                == selected_site
            )
            & (
                weather_df["근무조"]
                == selected_shift
            ),
            "근무조기준날짜"
        ]
        .dropna()
        .dt.strftime("%Y-%m-%d")
        .drop_duplicates()
        .sort_values()
        .tolist()
    )

    current_date = date_dropdown.value

    date_dropdown.options = available

    if len(available) == 0:
        date_dropdown.value = None
    elif current_date in available:
        date_dropdown.value = current_date
    else:
        date_dropdown.value = available[0]


site_dropdown.observe(
    update_available_dates,
    names="value"
)

shift_dropdown.observe(
    update_available_dates,
    names="value"
)


# ---------------------------------------------------------
# 5. 버튼 클릭 시 선택값 출력
# ---------------------------------------------------------

def confirm_inputs(button):

    with output_area:

        clear_output()

        if date_dropdown.value is None:
            print(
                "선택한 거점과 근무조에 해당하는 날짜가 없습니다."
            )
            return

        worker_count = worker_input.value

        print("[운영자 입력값 확인]")
        print("근무거점:", site_dropdown.value)
        print("근무조 기준날짜:", date_dropdown.value)
        print("근무조:", shift_dropdown.value)
        print("총근무인원:", worker_count)

        if worker_count < 4:
            print(
                "\n주의: 총인원 4명 미만은 "
                "네 작업범주의 동시 운영이 제한됩니다."
            )
        else:
            print(
                "\n입력값이 정상적으로 전달되었습니다."
            )


confirm_button.on_click(
    confirm_inputs
)


# ---------------------------------------------------------
# 6. 입력 화면 표시
# ---------------------------------------------------------

input_panel = widgets.VBox([
    widgets.HTML(
        value=(
            "<h3>대전 물류거점 폭염 대응 "
            "인력배치 입력</h3>"
        )
    ),
    site_dropdown,
    date_dropdown,
    shift_dropdown,
    worker_input,
    confirm_button,
    output_area
])

display(input_panel)

# 현재 거점·근무조 조건에 맞게 날짜목록 초기화
update_available_dates()

VBox(children=(HTML(value='<h3>대전 물류거점 폭염 대응 인력배치 입력</h3>'), Dropdown(description='근무거점:', index=22, layout=La…

- 입력값 정상 출력 확인
- 드롭다운, 숫자입력, 버튼 연결 정상 작동

3-6. 입력 위젯과 2시간 단위 인력배치표 연결

In [ ]:
# =========================================================
# 3-6. 입력 위젯과 2시간 단위 인력배치표 연결
#
# 기능:
# 1) 근무거점·날짜·낮/밤·총인원 입력
# 2) 해당 조건의 2시간 단위 체감온도와 위험등급 조회
# 3) 위험등급별 기준비율에 따라 정수 인원 배치
# 4) 위험등급별 색상표 출력
# 5) 결과 CSV 저장
#
# 주의:
# 이 코드는 바로 앞의 3-5 입력 위젯 코드 실행 후 사용함
# =========================================================

from pathlib import Path
import pandas as pd
import numpy as np
import ipywidgets as widgets

from IPython.display import display, clear_output


PROCESSED_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
)


# ---------------------------------------------------------
# 1. 3-5 위젯 실행 여부 확인
# ---------------------------------------------------------

required_widget_names = [
    "site_dropdown",
    "date_dropdown",
    "shift_dropdown",
    "worker_input",
    "confirm_button",
    "output_area",
    "weather_df"
]

missing_widgets = [
    name for name in required_widget_names
    if name not in globals()
]

if missing_widgets:
    raise NameError(
        "3-5 입력 위젯을 먼저 실행해야 합니다.\n"
        "없는 변수: "
        + ", ".join(missing_widgets)
    )


# ---------------------------------------------------------
# 2. 위험등급별 기준 인력배치비율 불러오기
# ---------------------------------------------------------

ratio_path = (
    PROCESSED_DIR /
    "위험등급별_기준인력배치비율.csv"
)

ratio_table = pd.read_csv(
    ratio_path,
    encoding="utf-8-sig"
)

ratio_cols = [
    "상하차비율",
    "분류비율",
    "검수비율",
    "휴식및대기비율"
]

if not np.allclose(
    ratio_table[ratio_cols].sum(axis=1),
    1.0
):
    raise ValueError(
        "위험등급별 인력배치비율의 합계가 100%가 아닙니다."
    )


# ---------------------------------------------------------
# 3. 거점별 물류부하 자료 불러오기
# ---------------------------------------------------------

load_path = (
    PROCESSED_DIR /
    "대전_38개물류거점_하루물류부하등급.csv"
)

load_df = pd.read_csv(
    load_path,
    encoding="utf-8-sig",
    dtype={
        "분석거점ID": str,
        "우편번호": str
    }
)


# ---------------------------------------------------------
# 4. 정수 배분 시 동률 우선순위
# ---------------------------------------------------------

tie_priority = {
    "낮음": [
        "상하차",
        "분류",
        "검수",
        "휴식 및 대기"
    ],
    "주의": [
        "휴식 및 대기",
        "검수",
        "분류",
        "상하차"
    ],
    "경고": [
        "휴식 및 대기",
        "검수",
        "분류",
        "상하차"
    ],
    "매우 위험": [
        "휴식 및 대기",
        "검수",
        "분류",
        "상하차"
    ]
}


# ---------------------------------------------------------
# 5. 정수 인원배분 함수
# ---------------------------------------------------------

def allocate_workers(
    total_workers,
    risk_grade
):
    """
    총근무인원과 위험등급을 이용하여
    네 작업의 정수 배치인원을 계산함.
    """

    tasks = [
        "상하차",
        "분류",
        "검수",
        "휴식 및 대기"
    ]

    if total_workers < 4:
        return {
            "상하차": 0,
            "분류": 0,
            "검수": 0,
            "휴식 및 대기": 0,
            "배치합계": 0,
            "배치상태": "배치 제한"
        }

    ratio_row = ratio_table.loc[
        ratio_table["블록기상위험등급"]
        == risk_grade
    ]

    if ratio_row.empty:
        raise ValueError(
            f"기준 배치비율이 없는 위험등급입니다: {risk_grade}"
        )

    ratio_row = ratio_row.iloc[0]

    ratios = {
        "상하차": ratio_row["상하차비율"],
        "분류": ratio_row["분류비율"],
        "검수": ratio_row["검수비율"],
        "휴식 및 대기": ratio_row[
            "휴식및대기비율"
        ]
    }

    # 네 범주에 최소 1명씩 우선 배치
    allocation = {
        task: 1
        for task in tasks
    }

    # 비율상 목표 인원
    target = {
        task: total_workers * ratios[task]
        for task in tasks
    }

    priority_rank = {
        task: rank
        for rank, task in enumerate(
            tie_priority[risk_grade]
        )
    }

    remaining = total_workers - 4

    # 남은 인원을 목표비율과 가장 가깝게 배정
    for _ in range(remaining):

        candidates = []

        for task in tasks:

            additional_error = (
                2 * (
                    allocation[task]
                    - target[task]
                )
                + 1
            )

            candidates.append(
                (
                    additional_error,
                    priority_rank[task],
                    task
                )
            )

        selected_task = min(
            candidates
        )[2]

        allocation[selected_task] += 1

    return {
        "상하차": allocation["상하차"],
        "분류": allocation["분류"],
        "검수": allocation["검수"],
        "휴식 및 대기": allocation[
            "휴식 및 대기"
        ],
        "배치합계": sum(
            allocation.values()
        ),
        "배치상태": "배치 가능"
    }


# ---------------------------------------------------------
# 6. 위험등급별 운영권고
# ---------------------------------------------------------

advice_map = {
    "낮음": (
        "일반 운영 및 고온 시간 이전 작업 선처리"
    ),
    "주의": (
        "상하차 교대 운영 및 순환휴식 확대"
    ),
    "경고": (
        "상하차 인원 축소 및 고온노출 시간 제한"
    ),
    "매우 위험": (
        "상하차 최소화 및 작업 중단 검토"
    )
}


# ---------------------------------------------------------
# 7. 위험등급별 색상 함수
# ---------------------------------------------------------

risk_colors = {
    "낮음": "#d9ead3",
    "주의": "#fff2cc",
    "경고": "#fce5cd",
    "매우 위험": "#f4cccc"
}


def color_risk_rows(row):

    risk_grade = row["위험등급"]

    background = risk_colors.get(
        risk_grade,
        "#ffffff"
    )

    return [
        f"background-color: {background}; "
        "color: #000000;"
        for _ in row
    ]


# ---------------------------------------------------------
# 8. 버튼 클릭 시 실제 배치표 생성
# ---------------------------------------------------------

def create_staffing_table(button):

    with output_area:

        clear_output()

        selected_site = site_dropdown.value
        selected_date = date_dropdown.value
        selected_shift = shift_dropdown.value
        total_workers = worker_input.value

        # 입력값 검수
        if selected_date is None:
            print(
                "선택한 조건에 해당하는 날짜가 없습니다."
            )
            return

        if total_workers < 1:
            print(
                "총근무인원은 1명 이상이어야 합니다."
            )
            return

        if total_workers < 4:
            print(
                "[배치 제한]\n"
                "총근무인원이 4명 미만이므로 "
                "상하차·분류·검수·휴식 및 대기 "
                "네 범주를 동시에 운영할 수 없습니다."
            )
            return

        selected_date_value = pd.to_datetime(
            selected_date
        ).normalize()

        # 선택 조건에 맞는 기상위험 자료
        selected_df = weather_df.loc[
            (
                weather_df["대표거점명"]
                .astype(str)
                .str.strip()
                == str(selected_site).strip()
            )
            & (
                weather_df["근무조기준날짜"]
                == selected_date_value
            )
            & (
                weather_df["근무조"]
                == selected_shift
            )
        ].copy()

        if selected_df.empty:
            print(
                "입력한 조건에 해당하는 "
                "기상예보 자료가 없습니다."
            )
            return

        selected_df = selected_df.sort_values(
            "블록시작일시"
        ).reset_index(drop=True)

        # 거점별 물류부하 정보 결합
        load_keep_candidates = [
            "분석거점ID",
            "하루평균물류부하",
            "일평균물류부하",
            "상대물류부하",
            "물류부하백분위",
            "물류부하등급"
        ]

        load_keep_cols = [
            col for col in load_keep_candidates
            if col in load_df.columns
        ]

        if "분석거점ID" in load_keep_cols:

            selected_df = selected_df.merge(
                load_df[
                    load_keep_cols
                ].drop_duplicates(
                    subset=["분석거점ID"]
                ),
                on="분석거점ID",
                how="left",
                validate="many_to_one"
            )

        # 각 2시간 블록의 인력배치 계산
        allocation_rows = []

        for _, row in selected_df.iterrows():

            result = allocate_workers(
                total_workers,
                row["블록기상위험등급"]
            )

            allocation_rows.append(
                result
            )

        allocation_df = pd.DataFrame(
            allocation_rows
        )

        selected_df = pd.concat(
            [
                selected_df.reset_index(drop=True),
                allocation_df.reset_index(drop=True)
            ],
            axis=1
        )

        selected_df["운영권고"] = (
            selected_df[
                "블록기상위험등급"
            ]
            .map(advice_map)
        )

        selected_df["합계일치여부"] = np.where(
            selected_df["배치합계"]
            == total_workers,
            "일치",
            "불일치"
        )

        # 근무조 자료 완전성 확인
        block_count = selected_df[
            "블록시작일시"
        ].nunique()

        complete_shift = (
            block_count == 6
            and (
                selected_df["완전블록여부"]
                == "완전"
            ).all()
        )

        shift_status = (
            "완전"
            if complete_shift
            else "부분"
        )

        # 입력 및 검수 결과 출력
        print("[운영자 입력 조건]")
        print("근무거점:", selected_site)
        print("근무조 기준날짜:", selected_date)
        print("근무조:", selected_shift)
        print("총근무인원:", total_workers)
        print("근무조 자료상태:", shift_status)
        print("2시간 블록 수:", block_count)

        mismatch_count = (
            selected_df[
                "합계일치여부"
            ]
            == "불일치"
        ).sum()

        print(
            "인원합계 불일치:",
            mismatch_count
        )

        if shift_status == "부분":
            print(
                "\n※ 일부 시간대 예보만 존재하여 "
                "부분 배치표로 출력되었습니다."
            )

        # 화면 출력용 열 구성
        result_table = selected_df.rename(
            columns={
                "블록최고체감온도":
                    "대표체감온도(℃)",
                "블록기상위험등급":
                    "위험등급"
            }
        )

        display_cols = [
            "시간대",
            "대표체감온도(℃)",
            "위험등급"
        ]

        for col in [
            "물류부하등급",
            "상대물류부하",
            "물류부하백분위"
        ]:
            if col in result_table.columns:
                display_cols.append(col)

        display_cols += [
            "상하차",
            "분류",
            "검수",
            "휴식 및 대기",
            "배치합계",
            "운영권고"
        ]

        result_table = result_table[
            display_cols
        ]

        # 표 제목
        print(
            f"\n[{selected_site} · "
            f"{selected_date} · "
            f"{selected_shift} 근무조 "
            f"{total_workers}명 인력배치표]"
        )

        # 위험등급별 행 색상 적용
        styled_table = (
            result_table.style
            .apply(
                color_risk_rows,
                axis=1
            )
            .format({
                "대표체감온도(℃)": "{:.1f}"
            })
            .set_properties(
                **{
                    "text-align": "center",
                    "border": "1px solid #cccccc"
                }
            )
            .set_table_styles([
                {
                    "selector": "th",
                    "props": [
                        (
                            "background-color",
                            "#eeeeee"
                        ),
                        (
                            "color",
                            "#000000"
                        ),
                        (
                            "text-align",
                            "center"
                        ),
                        (
                            "border",
                            "1px solid #cccccc"
                        )
                    ]
                }
            ])
        )

        display(
            styled_table
        )

        # -------------------------------------------------
        # 9. 결과 저장
        # -------------------------------------------------

        safe_site_name = (
            str(selected_site)
            .replace("/", "_")
            .replace("\\", "_")
            .replace(" ", "_")
        )

        save_path = (
            PROCESSED_DIR /
            (
                f"인력배치표_{safe_site_name}_"
                f"{selected_date}_"
                f"{selected_shift}_"
                f"{total_workers}명.csv"
            )
        )

        selected_df.to_csv(
            save_path,
            index=False,
            encoding="utf-8-sig"
        )

        print("\n저장 완료:")
        print(save_path)


# ---------------------------------------------------------
# 10. 기존 버튼 동작을 새 기능으로 교체
# ---------------------------------------------------------

confirm_button.description = "인력배치표 생성"
confirm_button.icon = "table"

# 기존 3-5의 입력값 확인 기능 제거
confirm_button._click_handlers.callbacks = []

# 새 배치표 생성 기능 연결
confirm_button.on_click(
    create_staffing_table
)


# ---------------------------------------------------------
# 11. 변경 완료 안내
# ---------------------------------------------------------

with output_area:

    clear_output()

    print(
        "입력 조건을 선택한 뒤 "
        "'인력배치표 생성' 버튼을 눌러주세요."
    )

- 3-5 출력 버튼 "입력값 확인" -> "인력배치표 생성"으로 변경

3-6-1. 입력 위젯 다시 표시

In [ ]:
# =========================================================
# 3-6-1. 입력 위젯 다시 표시
#
# 3-6에서는 기존 위젯의 기능만 변경했기 때문에
# 현재 셀 아래에 입력화면을 다시 표시함
# =========================================================

from IPython.display import display

display(input_panel)

VBox(children=(HTML(value='<h3>대전 물류거점 폭염 대응 인력배치 입력</h3>'), Dropdown(description='근무거점:', index=22, layout=La…

- 물류부하등급은 아직 인력배치 위험도에 직접 반영x
- 3-7에서 기상위험 + 물류부하등급 결합하여 최종 등급 생성

3-7. 기상위험과 일평균 물류부하를 결합한 종합위험 인력배치

In [ ]:
# =========================================================
# 3-7. 기상위험 + 거점별 일평균 물류부하 결합
#      종합운영위험 기반 인력배치표 생성
#
# 분석 구조:
# ① 시간대별 기상위험등급
# ② 거점별 일평균 물류부하등급
#                ↓
# ③ 시간대별 종합운영위험등급
#                ↓
# ④ 종합위험등급에 따른 인력 재배치
#
# 출력:
# - 거점, 날짜, 근무조, 총인원
# - 물류부하등급 및 물류부하 수치: 표 위에 1회 표시
# - 시간대별 체감온도·기상위험·종합위험·인력배치
# - 종합위험등급별 행 색상
# =========================================================

from pathlib import Path

import numpy as np
import pandas as pd
import ipywidgets as widgets

from IPython.display import display, clear_output


PROCESSED_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
)


# ---------------------------------------------------------
# 1. 이전 단계 실행 여부 확인
#
# 3-5 입력 위젯과 3-6 인력배분 함수가
# 메모리에 존재해야 함
# ---------------------------------------------------------

required_names = [
    "site_dropdown",
    "date_dropdown",
    "shift_dropdown",
    "worker_input",
    "confirm_button",
    "output_area",
    "input_panel",
    "weather_df",
    "load_df",
    "allocate_workers"
]

missing_names = [
    name
    for name in required_names
    if name not in globals()
]

if missing_names:
    raise NameError(
        "3-5와 3-6 코드를 먼저 실행해야 합니다.\n"
        "없는 변수: "
        + ", ".join(missing_names)
    )


# ---------------------------------------------------------
# 2. 기상위험 × 물류부하 결합 기준
#
# 기상위험은 시간대별 체감온도로 산출
# 물류부하는 거점별 일평균 물류부하등급 사용
#
# 물류부하가 높으면 같은 더위에서도
# 작업 강도와 운영부담이 더 큰 것으로 반영
# ---------------------------------------------------------

combined_risk_matrix = {
    # 기상위험 낮음
    ("낮음", "낮음"): "낮음",
    ("낮음", "보통"): "낮음",
    ("낮음", "높음"): "주의",

    # 기상위험 주의
    ("주의", "낮음"): "주의",
    ("주의", "보통"): "주의",
    ("주의", "높음"): "경고",

    # 기상위험 경고
    ("경고", "낮음"): "경고",
    ("경고", "보통"): "경고",
    ("경고", "높음"): "매우 위험",

    # 기상위험 매우 위험
    ("매우 위험", "낮음"): "매우 위험",
    ("매우 위험", "보통"): "매우 위험",
    ("매우 위험", "높음"): "매우 위험"
}


# ---------------------------------------------------------
# 3. 종합운영위험등급별 색상
#
# 낮음       : 초록
# 주의       : 노랑
# 경고       : 주황
# 매우 위험  : 빨강
# ---------------------------------------------------------

risk_colors = {
    "낮음": "#d9ead3",
    "주의": "#fff2cc",
    "경고": "#f9cb9c",
    "매우 위험": "#ea9999"
}


def color_combined_risk_rows(row):
    """
    종합운영위험등급에 따라
    표의 전체 행 배경색을 지정함.
    """

    grade = row["종합운영위험등급"]

    background = risk_colors.get(
        grade,
        "#ffffff"
    )

    return [
        (
            f"background-color: {background}; "
            "color: #000000;"
        )
        for _ in row
    ]


# ---------------------------------------------------------
# 4. 색상 범례
# ---------------------------------------------------------

risk_legend = widgets.HTML(
    value="""
    <div style="
        margin:12px 0;
        padding:10px;
        border:1px solid #cccccc;
        border-radius:6px;
        display:inline-block;
    ">
        <b>종합운영위험등급 색상</b><br><br>

        <span style="
            background:#d9ead3;
            padding:5px 12px;
            margin-right:5px;
            border:1px solid #aaaaaa;
        ">낮음</span>

        <span style="
            background:#fff2cc;
            padding:5px 12px;
            margin-right:5px;
            border:1px solid #aaaaaa;
        ">주의</span>

        <span style="
            background:#f9cb9c;
            padding:5px 12px;
            margin-right:5px;
            border:1px solid #aaaaaa;
        ">경고</span>

        <span style="
            background:#ea9999;
            padding:5px 12px;
            border:1px solid #aaaaaa;
        ">매우 위험</span>
    </div>
    """
)


# ---------------------------------------------------------
# 5. 종합운영위험등급별 운영권고
# ---------------------------------------------------------

advice_map = {
    "낮음": (
        "일반 운영 및 작업상태 점검"
    ),

    "주의": (
        "상하차 교대 운영 및 순환휴식 확대"
    ),

    "경고": (
        "상하차 인원 축소 및 저위험 시간대로 작업 분산"
    ),

    "매우 위험": (
        "상하차 최소화, 강제 휴식 확대 및 작업 중단 검토"
    )
}


# ---------------------------------------------------------
# 6. 첫 번째로 존재하는 물류부하 수치 열 찾기
# ---------------------------------------------------------

load_value_candidates = [
    "일평균물류부하",
    "하루평균물류부하",
    "7월일평균물류부하",
    "일평균택배물량",
    "하루물류부하"
]

relative_load_candidates = [
    "상대물류부하",
    "상대물류부하지수",
    "물류부하지수"
]

percentile_candidates = [
    "물류부하백분위",
    "물류부하퍼센타일"
]


def find_first_existing_column(
    dataframe,
    candidates
):
    """
    후보 열 중 실제 데이터에 존재하는
    첫 번째 열 이름을 반환함.
    """

    for column in candidates:
        if column in dataframe.columns:
            return column

    return None


# ---------------------------------------------------------
# 7. 종합위험 인력배치표 생성 함수
# ---------------------------------------------------------

def create_combined_risk_staffing_table(
    button
):

    with output_area:

        clear_output()

        # -----------------------------------------------
        # 7-1. 운영자 입력값 가져오기
        # -----------------------------------------------

        selected_site = (
            site_dropdown.value
        )

        selected_date = (
            date_dropdown.value
        )

        selected_shift = (
            shift_dropdown.value
        )

        total_workers = (
            worker_input.value
        )


        # -----------------------------------------------
        # 7-2. 입력값 검수
        # -----------------------------------------------

        if selected_date is None:
            print(
                "선택한 조건에 해당하는 날짜가 없습니다."
            )
            return

        if (
            not isinstance(
                total_workers,
                (int, np.integer)
            )
            or total_workers < 1
        ):
            print(
                "총근무인원은 1명 이상의 정수여야 합니다."
            )
            return

        if total_workers < 4:
            print(
                "[배치 제한]\n"
                "총근무인원이 4명 미만이므로 "
                "상하차·분류·검수·휴식 및 대기 "
                "네 작업범주를 동시에 배치하기 어렵습니다."
            )
            return

        selected_date_value = (
            pd.to_datetime(
                selected_date,
                errors="coerce"
            )
            .normalize()
        )

        if pd.isna(
            selected_date_value
        ):
            print(
                "선택 날짜를 날짜형식으로 변환하지 못했습니다."
            )
            return


        # -----------------------------------------------
        # 7-3. 선택 조건에 맞는 기상자료 추출
        # -----------------------------------------------

        selected_df = weather_df.loc[
            (
                weather_df[
                    "대표거점명"
                ]
                .astype(str)
                .str.strip()
                == str(
                    selected_site
                ).strip()
            )
            & (
                weather_df[
                    "근무조기준날짜"
                ]
                == selected_date_value
            )
            & (
                weather_df[
                    "근무조"
                ]
                == selected_shift
            )
        ].copy()

        if selected_df.empty:
            print(
                "입력한 거점·날짜·근무조에 해당하는 "
                "기상예보 자료가 없습니다."
            )
            return

        selected_df = (
            selected_df
            .sort_values(
                "블록시작일시"
            )
            .reset_index(
                drop=True
            )
        )


        # -----------------------------------------------
        # 7-4. 거점별 물류부하 자료 결합
        # -----------------------------------------------

        load_keep_candidates = [
            "분석거점ID",
            "물류부하등급",
            "일평균물류부하",
            "하루평균물류부하",
            "7월일평균물류부하",
            "일평균택배물량",
            "하루물류부하",
            "상대물류부하",
            "상대물류부하지수",
            "물류부하지수",
            "물류부하백분위",
            "물류부하퍼센타일"
        ]

        load_keep_cols = [
            column
            for column in load_keep_candidates
            if column in load_df.columns
        ]

        if (
            "분석거점ID"
            not in load_keep_cols
        ):
            raise KeyError(
                "물류부하 자료에 분석거점ID 열이 없습니다."
            )

        if (
            "물류부하등급"
            not in load_keep_cols
        ):
            raise KeyError(
                "물류부하 자료에 물류부하등급 열이 없습니다."
            )

        selected_df = selected_df.merge(
            load_df[
                load_keep_cols
            ].drop_duplicates(
                subset=[
                    "분석거점ID"
                ]
            ),
            on="분석거점ID",
            how="left",
            validate="many_to_one"
        )

        if (
            selected_df[
                "물류부하등급"
            ].isna().any()
        ):
            raise ValueError(
                "선택한 거점의 물류부하등급이 없습니다."
            )

        # 같은 거점 안에서는 물류부하등급이
        # 하나로 유지되는지 확인
        unique_load_grades = (
            selected_df[
                "물류부하등급"
            ]
            .dropna()
            .unique()
            .tolist()
        )

        if len(
            unique_load_grades
        ) != 1:
            raise ValueError(
                "한 거점에 물류부하등급이 "
                "둘 이상 연결되었습니다: "
                + str(
                    unique_load_grades
                )
            )

        load_grade = (
            unique_load_grades[0]
        )


        # -----------------------------------------------
        # 7-5. 시간대별 종합운영위험등급 산출
        # -----------------------------------------------

        selected_df[
            "종합운영위험등급"
        ] = selected_df.apply(
            lambda row:
                combined_risk_matrix.get(
                    (
                        row[
                            "블록기상위험등급"
                        ],
                        row[
                            "물류부하등급"
                        ]
                    )
                ),
            axis=1
        )

        if (
            selected_df[
                "종합운영위험등급"
            ].isna().any()
        ):

            undefined_pairs = (
                selected_df.loc[
                    selected_df[
                        "종합운영위험등급"
                    ].isna(),
                    [
                        "블록기상위험등급",
                        "물류부하등급"
                    ]
                ]
                .drop_duplicates()
            )

            raise ValueError(
                "종합운영위험 기준표에 정의되지 않은 "
                "조합이 있습니다.\n"
                + undefined_pairs.to_string(
                    index=False
                )
            )


        # -----------------------------------------------
        # 7-6. 종합운영위험 기준 인력배치
        # -----------------------------------------------

        allocation_rows = []

        for _, row in selected_df.iterrows():

            allocation_result = (
                allocate_workers(
                    total_workers,
                    row[
                        "종합운영위험등급"
                    ]
                )
            )

            allocation_rows.append(
                allocation_result
            )

        allocation_df = pd.DataFrame(
            allocation_rows
        )

        selected_df = pd.concat(
            [
                selected_df.reset_index(
                    drop=True
                ),
                allocation_df.reset_index(
                    drop=True
                )
            ],
            axis=1
        )


        # -----------------------------------------------
        # 7-7. 배치합계 열 확인 및 생성
        # -----------------------------------------------

        if (
            "배치합계"
            not in selected_df.columns
        ):

            selected_df[
                "배치합계"
            ] = (
                selected_df[
                    [
                        "상하차",
                        "분류",
                        "검수",
                        "휴식 및 대기"
                    ]
                ]
                .sum(
                    axis=1
                )
            )


        # -----------------------------------------------
        # 7-8. 운영권고 및 합계 검수
        # -----------------------------------------------

        selected_df[
            "운영권고"
        ] = (
            selected_df[
                "종합운영위험등급"
            ]
            .map(
                advice_map
            )
        )

        selected_df[
            "합계일치여부"
        ] = np.where(
            selected_df[
                "배치합계"
            ]
            == total_workers,
            "일치",
            "불일치"
        )

        block_count = (
            selected_df[
                "블록시작일시"
            ]
            .nunique()
        )

        complete_block_condition = (
            selected_df[
                "완전블록여부"
            ]
            == "완전"
        ).all()

        shift_status = (
            "완전"
            if (
                block_count == 6
                and complete_block_condition
            )
            else "부분"
        )

        mismatch_count = (
            selected_df[
                "합계일치여부"
            ]
            == "불일치"
        ).sum()


        # -----------------------------------------------
        # 7-9. 물류부하 수치 열 확인
        # -----------------------------------------------

        load_value_col = (
            find_first_existing_column(
                selected_df,
                load_value_candidates
            )
        )

        relative_load_col = (
            find_first_existing_column(
                selected_df,
                relative_load_candidates
            )
        )

        percentile_col = (
            find_first_existing_column(
                selected_df,
                percentile_candidates
            )
        )


        # -----------------------------------------------
        # 7-10. 표 상단 고정정보 출력
        # -----------------------------------------------

        print(
            "[운영자 입력 조건]"
        )

        print(
            "근무거점:",
            selected_site
        )

        print(
            "근무조 기준날짜:",
            selected_date
        )

        print(
            "근무조:",
            selected_shift
        )

        print(
            "총근무인원:",
            total_workers
        )

        print(
            "거점 물류부하등급:",
            load_grade
        )

        if (
            load_value_col
            is not None
        ):

            load_value = (
                selected_df[
                    load_value_col
                ]
                .iloc[0]
            )

            if pd.notna(
                load_value
            ):
                print(
                    f"{load_value_col}:",
                    round(
                        float(
                            load_value
                        ),
                        3
                    )
                )

        if (
            relative_load_col
            is not None
        ):

            relative_load_value = (
                selected_df[
                    relative_load_col
                ]
                .iloc[0]
            )

            if pd.notna(
                relative_load_value
            ):
                print(
                    f"{relative_load_col}:",
                    round(
                        float(
                            relative_load_value
                        ),
                        3
                    )
                )

        if (
            percentile_col
            is not None
        ):

            percentile_value = (
                selected_df[
                    percentile_col
                ]
                .iloc[0]
            )

            if pd.notna(
                percentile_value
            ):
                print(
                    f"{percentile_col}:",
                    round(
                        float(
                            percentile_value
                        ),
                        2
                    )
                )

        print(
            "근무조 자료상태:",
            shift_status
        )

        print(
            "2시간 블록 수:",
            block_count
        )

        print(
            "인원합계 불일치:",
            mismatch_count
        )

        if (
            shift_status
            == "부분"
        ):
            print(
                "\n※ 일부 시간대 예보만 존재하여 "
                "부분 배치표로 출력되었습니다."
            )


        # -----------------------------------------------
        # 7-11. 선택 근무조 종합위험 분포
        # -----------------------------------------------

        risk_order = [
            "낮음",
            "주의",
            "경고",
            "매우 위험"
        ]

        risk_distribution = (
            selected_df[
                "종합운영위험등급"
            ]
            .value_counts()
            .reindex(
                risk_order,
                fill_value=0
            )
            .rename_axis(
                "종합운영위험등급"
            )
            .reset_index(
                name="2시간블록수"
            )
        )

        print(
            "\n[선택 근무조 종합위험 분포]"
        )

        display(
            risk_distribution
        )

        display(
            risk_legend
        )


        # -----------------------------------------------
        # 7-12. 최종 시간대별 인력배치표
        #
        # 물류부하등급과 수치는 표 안에서 제외
        # 상단 고정정보에만 한 번 표시
        # -----------------------------------------------

        result_table = (
            selected_df
            .rename(
                columns={
                    "블록최고체감온도":
                        "대표체감온도(℃)",

                    "블록기상위험등급":
                        "기상위험등급"
                }
            )
        )

        display_cols = [
            "시간대",
            "대표체감온도(℃)",
            "기상위험등급",
            "종합운영위험등급",
            "상하차",
            "분류",
            "검수",
            "휴식 및 대기",
            "배치합계",
            "운영권고"
        ]

        result_table = (
            result_table[
                display_cols
            ]
            .copy()
        )

        print(
            f"\n[{selected_site} · "
            f"{selected_date} · "
            f"{selected_shift} 근무조 · "
            f"{total_workers}명 종합위험 인력배치표]"
        )

        styled_table = (
            result_table
            .style
            .apply(
                color_combined_risk_rows,
                axis=1
            )
            .format({
                "대표체감온도(℃)":
                    "{:.1f}"
            })
            .set_properties(
                **{
                    "text-align":
                        "center",

                    "border":
                        "1px solid #cccccc"
                }
            )
            .set_table_styles([
                {
                    "selector": "th",
                    "props": [
                        (
                            "background-color",
                            "#eeeeee"
                        ),
                        (
                            "color",
                            "#000000"
                        ),
                        (
                            "text-align",
                            "center"
                        ),
                        (
                            "border",
                            "1px solid #cccccc"
                        )
                    ]
                }
            ])
        )

        display(
            styled_table
        )


        # -----------------------------------------------
        # 7-13. 결과 저장
        # -----------------------------------------------

        safe_site_name = (
            str(
                selected_site
            )
            .replace(
                "/",
                "_"
            )
            .replace(
                "\\",
                "_"
            )
            .replace(
                " ",
                "_"
            )
        )

        save_path = (
            PROCESSED_DIR
            /
            (
                "종합위험_인력배치표_"
                f"{safe_site_name}_"
                f"{selected_date}_"
                f"{selected_shift}_"
                f"{total_workers}명.csv"
            )
        )

        selected_df.to_csv(
            save_path,
            index=False,
            encoding="utf-8-sig"
        )

        print(
            "\n저장 완료:"
        )

        print(
            save_path
        )


# ---------------------------------------------------------
# 8. 기존 버튼 기능을 종합위험 모델로 교체
# ---------------------------------------------------------

confirm_button.description = (
    "종합위험 배치표 생성"
)

confirm_button.icon = "table"

# 기존 버튼 클릭 기능 제거
confirm_button._click_handlers.callbacks = []

# 새로운 종합위험 배치표 생성 기능 연결
confirm_button.on_click(
    create_combined_risk_staffing_table
)


# ---------------------------------------------------------
# 9. 안내문 초기화 후 입력 화면 다시 표시
# ---------------------------------------------------------

with output_area:

    clear_output()

    print(
        "근무거점·날짜·근무조·총인원을 선택한 뒤 "
        "'종합위험 배치표 생성' 버튼을 눌러주세요."
    )

display(
    input_panel
)

VBox(children=(HTML(value='<h3>대전 물류거점 폭염 대응 인력배치 입력</h3>'), Dropdown(description='근무거점:', index=22, layout=La…

- 출력 정상
- 3-7-1에 수정할 내용
1) 입력창 사라지지 않고 유지
2) 표 바로 상단에 물류부하등급 표시
3) 드롭다운 변경 가능하도록

3-7-1. 입력창 고정 및 표 상단 정보 표시 수정

In [ ]:
# =========================================================
# 3-7-1. 입력창 고정 및 표 상단 정보 표시 수정
#
# 수정 내용:
# 1) 입력 위젯과 결과 출력영역을 분리
# 2) 결과를 생성해도 입력창은 계속 유지
# 3) 표 바로 위에 거점·날짜·근무조·근무인원·
#    물류부하등급을 한 줄로 표시
# 4) 조건을 변경해 반복 실행 가능
#
# 기존 3-5, 3-6, 3-7 실행 후 사용
# =========================================================

from pathlib import Path

import numpy as np
import pandas as pd
import ipywidgets as widgets

from IPython.display import display, clear_output


PROCESSED_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
)


# ---------------------------------------------------------
# 1. 이전 단계 실행 여부 확인
# ---------------------------------------------------------

required_names = [
    "site_dropdown",
    "date_dropdown",
    "shift_dropdown",
    "worker_input",
    "confirm_button",
    "weather_df",
    "load_df",
    "allocate_workers",
    "combined_risk_matrix",
    "risk_colors",
    "advice_map"
]

missing_names = [
    name
    for name in required_names
    if name not in globals()
]

if missing_names:
    raise NameError(
        "3-5, 3-6, 3-7 코드를 먼저 실행해야 합니다.\n"
        "없는 변수: "
        + ", ".join(missing_names)
    )


# ---------------------------------------------------------
# 2. 결과 전용 출력영역 생성
#
# 입력창과 분리되어 있으므로 결과를 지워도
# 입력 드롭다운과 인원 입력칸은 유지됨
# ---------------------------------------------------------

fixed_result_output = widgets.Output()


# ---------------------------------------------------------
# 3. 종합위험 색상 적용 함수
# ---------------------------------------------------------

def color_combined_rows(row):

    grade = row[
        "종합운영위험등급"
    ]

    background = risk_colors.get(
        grade,
        "#ffffff"
    )

    return [
        (
            f"background-color: {background}; "
            "color: #000000;"
        )
        for _ in row
    ]


# ---------------------------------------------------------
# 4. 물류부하 수치 열 탐색 함수
# ---------------------------------------------------------

def find_first_column(
    dataframe,
    candidates
):

    for column in candidates:

        if column in dataframe.columns:
            return column

    return None


# ---------------------------------------------------------
# 5. 종합위험 인력배치표 생성 함수
# ---------------------------------------------------------

def create_fixed_combined_table(button):

    # 입력창은 그대로 두고
    # 결과영역만 새 결과로 교체
    with fixed_result_output:

        clear_output(wait=True)

        selected_site = (
            site_dropdown.value
        )

        selected_date = (
            date_dropdown.value
        )

        selected_shift = (
            shift_dropdown.value
        )

        total_workers = (
            worker_input.value
        )


        # -----------------------------------------------
        # 5-1. 입력값 검수
        # -----------------------------------------------

        if selected_date is None:

            print(
                "선택한 조건에 해당하는 날짜가 없습니다."
            )

            return

        if (
            not isinstance(
                total_workers,
                (int, np.integer)
            )
            or total_workers < 1
        ):

            print(
                "총근무인원은 1명 이상의 정수여야 합니다."
            )

            return

        if total_workers < 4:

            print(
                "[배치 제한]\n"
                "총근무인원이 4명 미만이므로 "
                "상하차·분류·검수·휴식 및 대기 "
                "네 작업을 동시에 배치할 수 없습니다."
            )

            return


        selected_date_value = (
            pd.to_datetime(
                selected_date,
                errors="coerce"
            )
            .normalize()
        )


        # -----------------------------------------------
        # 5-2. 선택 조건의 기상자료 추출
        # -----------------------------------------------

        selected_df = weather_df.loc[
            (
                weather_df[
                    "대표거점명"
                ]
                .astype(str)
                .str.strip()
                == str(
                    selected_site
                ).strip()
            )
            & (
                weather_df[
                    "근무조기준날짜"
                ]
                == selected_date_value
            )
            & (
                weather_df[
                    "근무조"
                ]
                == selected_shift
            )
        ].copy()

        if selected_df.empty:

            print(
                "선택한 거점·날짜·근무조에 "
                "해당하는 예보자료가 없습니다."
            )

            return


        selected_df = (
            selected_df
            .sort_values(
                "블록시작일시"
            )
            .reset_index(
                drop=True
            )
        )


        # -----------------------------------------------
        # 5-3. 거점별 물류부하 결합
        # -----------------------------------------------

        load_keep_candidates = [
            "분석거점ID",
            "물류부하등급",
            "일평균물류부하",
            "하루평균물류부하",
            "7월일평균물류부하",
            "일평균택배물량",
            "하루물류부하",
            "상대물류부하",
            "상대물류부하지수",
            "물류부하지수",
            "물류부하백분위",
            "물류부하퍼센타일"
        ]

        load_keep_cols = [
            column
            for column in load_keep_candidates
            if column in load_df.columns
        ]

        if (
            "분석거점ID"
            not in load_keep_cols
            or "물류부하등급"
            not in load_keep_cols
        ):

            raise KeyError(
                "물류부하 자료에서 분석거점ID 또는 "
                "물류부하등급 열을 찾지 못했습니다."
            )


        selected_df = selected_df.merge(
            load_df[
                load_keep_cols
            ].drop_duplicates(
                subset=[
                    "분석거점ID"
                ]
            ),
            on="분석거점ID",
            how="left",
            validate="many_to_one"
        )


        if (
            selected_df[
                "물류부하등급"
            ].isna().any()
        ):

            raise ValueError(
                "선택한 거점의 물류부하등급이 없습니다."
            )


        unique_load_grades = (
            selected_df[
                "물류부하등급"
            ]
            .dropna()
            .unique()
            .tolist()
        )

        if len(
            unique_load_grades
        ) != 1:

            raise ValueError(
                "선택한 거점에 둘 이상의 물류부하등급이 "
                "연결되었습니다: "
                + str(
                    unique_load_grades
                )
            )


        load_grade = (
            unique_load_grades[0]
        )


        # -----------------------------------------------
        # 5-4. 시간대별 종합운영위험 산출
        # -----------------------------------------------

        selected_df[
            "종합운영위험등급"
        ] = selected_df.apply(
            lambda row:
                combined_risk_matrix.get(
                    (
                        row[
                            "블록기상위험등급"
                        ],
                        row[
                            "물류부하등급"
                        ]
                    )
                ),
            axis=1
        )


        if (
            selected_df[
                "종합운영위험등급"
            ].isna().any()
        ):

            undefined_pairs = (
                selected_df.loc[
                    selected_df[
                        "종합운영위험등급"
                    ].isna(),
                    [
                        "블록기상위험등급",
                        "물류부하등급"
                    ]
                ]
                .drop_duplicates()
            )

            raise ValueError(
                "정의되지 않은 종합위험 조합이 있습니다.\n"
                + undefined_pairs.to_string(
                    index=False
                )
            )


        # -----------------------------------------------
        # 5-5. 종합운영위험 기준 인력배치
        # -----------------------------------------------

        allocation_rows = []

        for _, row in selected_df.iterrows():

            allocation_rows.append(
                allocate_workers(
                    total_workers,
                    row[
                        "종합운영위험등급"
                    ]
                )
            )


        allocation_df = pd.DataFrame(
            allocation_rows
        )


        selected_df = pd.concat(
            [
                selected_df.reset_index(
                    drop=True
                ),
                allocation_df.reset_index(
                    drop=True
                )
            ],
            axis=1
        )


        if (
            "배치합계"
            not in selected_df.columns
        ):

            selected_df[
                "배치합계"
            ] = (
                selected_df[
                    [
                        "상하차",
                        "분류",
                        "검수",
                        "휴식 및 대기"
                    ]
                ]
                .sum(
                    axis=1
                )
            )


        selected_df[
            "운영권고"
        ] = (
            selected_df[
                "종합운영위험등급"
            ]
            .map(
                advice_map
            )
        )


        # -----------------------------------------------
        # 5-6. 결과 검수
        # -----------------------------------------------

        selected_df[
            "합계일치여부"
        ] = np.where(
            selected_df[
                "배치합계"
            ] == total_workers,
            "일치",
            "불일치"
        )


        block_count = (
            selected_df[
                "블록시작일시"
            ]
            .nunique()
        )


        complete_shift = (
            block_count == 6
            and (
                selected_df[
                    "완전블록여부"
                ]
                == "완전"
            ).all()
        )


        shift_status = (
            "완전"
            if complete_shift
            else "부분"
        )


        mismatch_count = (
            selected_df[
                "합계일치여부"
            ]
            .eq(
                "불일치"
            )
            .sum()
        )


        # -----------------------------------------------
        # 5-7. 표 바로 위 고정정보 표시
        # -----------------------------------------------

        header_html = widgets.HTML(
            value=f"""
            <div style="
                margin:8px 0 12px 0;
                padding:12px 14px;
                border:1px solid #bdbdbd;
                border-radius:7px;
                background:#f7f7f7;
                color:#000000;
                font-size:14px;
            ">
                <b>근무거점</b>: {selected_site}
                &nbsp;&nbsp; | &nbsp;&nbsp;
                <b>날짜</b>: {selected_date}
                &nbsp;&nbsp; | &nbsp;&nbsp;
                <b>근무조</b>: {selected_shift}
                &nbsp;&nbsp; | &nbsp;&nbsp;
                <b>근무인원</b>: {total_workers}명
                &nbsp;&nbsp; | &nbsp;&nbsp;
                <b>물류부하등급</b>: {load_grade}
            </div>
            """
        )

        display(
            header_html
        )


        # -----------------------------------------------
        # 5-8. 자료 검수 정보
        # -----------------------------------------------

        print(
            f"근무조 자료상태: {shift_status}"
        )

        print(
            f"2시간 블록 수: {block_count}"
        )

        print(
            f"인원합계 불일치: {mismatch_count}"
        )


        if shift_status == "부분":

            print(
                "※ 일부 시간대 예보만 존재하여 "
                "부분 배치표로 출력되었습니다."
            )


        # -----------------------------------------------
        # 5-9. 물류부하 수치 간단 표시
        # -----------------------------------------------

        load_value_col = find_first_column(
            selected_df,
            [
                "일평균물류부하",
                "하루평균물류부하",
                "7월일평균물류부하",
                "일평균택배물량",
                "하루물류부하"
            ]
        )


        relative_load_col = find_first_column(
            selected_df,
            [
                "상대물류부하",
                "상대물류부하지수",
                "물류부하지수"
            ]
        )


        load_detail_parts = []

        if load_value_col is not None:

            value = (
                selected_df[
                    load_value_col
                ]
                .iloc[0]
            )

            if pd.notna(
                value
            ):

                load_detail_parts.append(
                    f"{load_value_col}: "
                    f"{float(value):.3f}"
                )


        if relative_load_col is not None:

            value = (
                selected_df[
                    relative_load_col
                ]
                .iloc[0]
            )

            if pd.notna(
                value
            ):

                load_detail_parts.append(
                    f"{relative_load_col}: "
                    f"{float(value):.3f}"
                )


        if load_detail_parts:

            print(
                "물류부하 세부정보:",
                " / ".join(
                    load_detail_parts
                )
            )


        # -----------------------------------------------
        # 5-10. 색상 범례
        # -----------------------------------------------

        legend_html = widgets.HTML(
            value="""
            <div style="
                margin:10px 0 12px 0;
            ">
                <b>종합운영위험등급</b>
                &nbsp;

                <span style="
                    background:#d9ead3;
                    padding:4px 10px;
                    border:1px solid #aaaaaa;
                ">낮음</span>

                <span style="
                    background:#fff2cc;
                    padding:4px 10px;
                    border:1px solid #aaaaaa;
                ">주의</span>

                <span style="
                    background:#f9cb9c;
                    padding:4px 10px;
                    border:1px solid #aaaaaa;
                ">경고</span>

                <span style="
                    background:#ea9999;
                    padding:4px 10px;
                    border:1px solid #aaaaaa;
                ">매우 위험</span>
            </div>
            """
        )

        display(
            legend_html
        )


        # -----------------------------------------------
        # 5-11. 최종 인력배치표
        # -----------------------------------------------

        result_table = (
            selected_df
            .rename(
                columns={
                    "블록최고체감온도":
                        "대표체감온도(℃)",

                    "블록기상위험등급":
                        "기상위험등급"
                }
            )
        )


        display_cols = [
            "시간대",
            "대표체감온도(℃)",
            "기상위험등급",
            "종합운영위험등급",
            "상하차",
            "분류",
            "검수",
            "휴식 및 대기",
            "배치합계",
            "운영권고"
        ]


        result_table = (
            result_table[
                display_cols
            ]
            .copy()
        )


        styled_table = (
            result_table
            .style
            .apply(
                color_combined_rows,
                axis=1
            )
            .format({
                "대표체감온도(℃)":
                    "{:.1f}"
            })
            .set_properties(
                **{
                    "text-align":
                        "center",

                    "border":
                        "1px solid #cccccc"
                }
            )
            .set_table_styles([
                {
                    "selector": "th",
                    "props": [
                        (
                            "background-color",
                            "#eeeeee"
                        ),
                        (
                            "color",
                            "#000000"
                        ),
                        (
                            "text-align",
                            "center"
                        ),
                        (
                            "border",
                            "1px solid #cccccc"
                        )
                    ]
                }
            ])
        )


        display(
            styled_table
        )


        # -----------------------------------------------
        # 5-12. 저장
        # -----------------------------------------------

        safe_site_name = (
            str(
                selected_site
            )
            .replace(
                "/",
                "_"
            )
            .replace(
                "\\",
                "_"
            )
            .replace(
                " ",
                "_"
            )
        )


        save_path = (
            PROCESSED_DIR
            /
            (
                "종합위험_인력배치표_"
                f"{safe_site_name}_"
                f"{selected_date}_"
                f"{selected_shift}_"
                f"{total_workers}명.csv"
            )
        )


        selected_df.to_csv(
            save_path,
            index=False,
            encoding="utf-8-sig"
        )


        print(
            "\n저장 완료:"
        )

        print(
            save_path
        )


# ---------------------------------------------------------
# 6. 기존 버튼 기능을 새 함수로 교체
# ---------------------------------------------------------

confirm_button.description = (
    "종합위험 배치표 생성"
)

confirm_button.icon = "table"

confirm_button._click_handlers.callbacks = []

confirm_button.on_click(
    create_fixed_combined_table
)


# ---------------------------------------------------------
# 7. 입력창 고정형 화면 구성
#
# 결과 출력영역은 입력창 아래에 별도로 배치됨
# ---------------------------------------------------------

fixed_input_panel = widgets.VBox([
    widgets.HTML(
        value=(
            "<h3>대전 물류거점 폭염 대응 "
            "인력배치 모델</h3>"
        )
    ),

    site_dropdown,
    date_dropdown,
    shift_dropdown,
    worker_input,
    confirm_button
])


fixed_model_screen = widgets.VBox([
    fixed_input_panel,
    fixed_result_output
])


# ---------------------------------------------------------
# 8. 최종 입력화면 표시
# ---------------------------------------------------------

display(
    fixed_model_screen
)

VBox(children=(VBox(children=(HTML(value='<h3>대전 물류거점 폭염 대응 인력배치 모델</h3>'), Dropdown(description='근무거점:', inde…

- 첫 출력은 정상 출력
- 입력값 수정 후 재생성이 안됨
- 3-7-2에서 수정

3-7-2. 반복 재생성 오류 수정

In [ ]:
# =========================================================
# 3-7-2. 입력값 변경 후 반복 재생성 오류 수정
#
# 수정 내용:
# 1) 결과영역 내부의 widgets.HTML 사용을 제거
# 2) 일반 HTML 출력으로 변경
# 3) 결과영역만 매번 초기화
# 4) 실행 중 버튼 중복 클릭 방지
# 5) 오류 발생 시 결과창에 오류 원인 표시
#
# 기존 3-7-1 실행 후 이 셀만 추가 실행
# =========================================================

from pathlib import Path
import html
import traceback

import numpy as np
import pandas as pd
import ipywidgets as widgets

from IPython.display import display, clear_output, HTML


PROCESSED_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
)


# ---------------------------------------------------------
# 1. 필수 변수 확인
# ---------------------------------------------------------

required_names = [
    "site_dropdown",
    "date_dropdown",
    "shift_dropdown",
    "worker_input",
    "confirm_button",
    "weather_df",
    "load_df",
    "allocate_workers",
    "combined_risk_matrix",
    "risk_colors",
    "advice_map"
]

missing_names = [
    name
    for name in required_names
    if name not in globals()
]

if missing_names:
    raise NameError(
        "이전 코드를 먼저 실행해야 합니다.\n"
        "없는 변수: "
        + ", ".join(missing_names)
    )


# ---------------------------------------------------------
# 2. 반복 실행용 결과영역을 새로 생성
# ---------------------------------------------------------

repeat_result_output = widgets.Output()


# ---------------------------------------------------------
# 3. 존재하는 첫 번째 열 찾기
# ---------------------------------------------------------

def find_existing_column(
    dataframe,
    candidates
):
    for column in candidates:
        if column in dataframe.columns:
            return column

    return None


# ---------------------------------------------------------
# 4. 종합위험 색상 함수
# ---------------------------------------------------------

def apply_combined_risk_color(row):

    risk_grade = row[
        "종합운영위험등급"
    ]

    background = risk_colors.get(
        risk_grade,
        "#ffffff"
    )

    return [
        (
            f"background-color: {background}; "
            "color: #000000;"
        )
        for _ in row
    ]


# ---------------------------------------------------------
# 5. 반복 실행 가능한 배치표 생성 함수
# ---------------------------------------------------------

def create_repeatable_staffing_table(button):

    # 실행 중 중복 클릭 방지
    confirm_button.disabled = True
    original_description = confirm_button.description
    confirm_button.description = "생성 중..."

    try:

        with repeat_result_output:

            # 이전 결과만 제거
            clear_output(wait=False)

            # -------------------------------------------
            # 5-1. 입력값
            # -------------------------------------------

            selected_site = site_dropdown.value
            selected_date = date_dropdown.value
            selected_shift = shift_dropdown.value
            total_workers = worker_input.value


            # -------------------------------------------
            # 5-2. 입력 검수
            # -------------------------------------------

            if selected_date is None:
                print(
                    "선택한 조건에 해당하는 날짜가 없습니다."
                )
                return

            if (
                not isinstance(
                    total_workers,
                    (int, np.integer)
                )
                or total_workers < 1
            ):
                print(
                    "총근무인원은 1명 이상의 정수여야 합니다."
                )
                return

            if total_workers < 4:
                print(
                    "[배치 제한]\n"
                    "총근무인원이 4명 미만이므로 "
                    "네 작업범주를 동시에 운영하기 어렵습니다."
                )
                return

            selected_date_value = pd.to_datetime(
                selected_date,
                errors="coerce"
            )

            if pd.isna(selected_date_value):
                print(
                    "날짜를 올바르게 변환하지 못했습니다."
                )
                return

            selected_date_value = (
                selected_date_value.normalize()
            )


            # -------------------------------------------
            # 5-3. 선택 조건의 기상자료
            # -------------------------------------------

            selected_df = weather_df.loc[
                (
                    weather_df[
                        "대표거점명"
                    ]
                    .astype(str)
                    .str.strip()
                    == str(
                        selected_site
                    ).strip()
                )
                & (
                    weather_df[
                        "근무조기준날짜"
                    ]
                    == selected_date_value
                )
                & (
                    weather_df[
                        "근무조"
                    ]
                    == selected_shift
                )
            ].copy()

            if selected_df.empty:
                print(
                    "선택한 거점·날짜·근무조에 "
                    "해당하는 자료가 없습니다."
                )
                return

            selected_df = (
                selected_df
                .sort_values(
                    "블록시작일시"
                )
                .reset_index(
                    drop=True
                )
            )


            # -------------------------------------------
            # 5-4. 물류부하 자료 결합
            # -------------------------------------------

            load_keep_candidates = [
                "분석거점ID",
                "물류부하등급",
                "일평균물류부하",
                "하루평균물류부하",
                "7월일평균물류부하",
                "일평균택배물량",
                "하루물류부하",
                "상대물류부하",
                "상대물류부하지수",
                "물류부하지수",
                "물류부하백분위",
                "물류부하퍼센타일"
            ]

            load_keep_cols = [
                column
                for column in load_keep_candidates
                if column in load_df.columns
            ]

            if "분석거점ID" not in load_keep_cols:
                raise KeyError(
                    "물류부하 자료에 분석거점ID가 없습니다."
                )

            if "물류부하등급" not in load_keep_cols:
                raise KeyError(
                    "물류부하 자료에 물류부하등급이 없습니다."
                )

            selected_df = selected_df.merge(
                load_df[
                    load_keep_cols
                ].drop_duplicates(
                    subset=[
                        "분석거점ID"
                    ]
                ),
                on="분석거점ID",
                how="left",
                validate="many_to_one"
            )

            if (
                selected_df[
                    "물류부하등급"
                ].isna().any()
            ):
                raise ValueError(
                    "선택한 거점의 물류부하등급이 없습니다."
                )

            unique_load_grades = (
                selected_df[
                    "물류부하등급"
                ]
                .dropna()
                .astype(str)
                .unique()
                .tolist()
            )

            if len(unique_load_grades) != 1:
                raise ValueError(
                    "선택한 거점에 둘 이상의 "
                    "물류부하등급이 연결됐습니다: "
                    + str(unique_load_grades)
                )

            load_grade = unique_load_grades[0]


            # -------------------------------------------
            # 5-5. 종합운영위험 계산
            # -------------------------------------------

            selected_df[
                "종합운영위험등급"
            ] = selected_df.apply(
                lambda row: combined_risk_matrix.get(
                    (
                        row[
                            "블록기상위험등급"
                        ],
                        row[
                            "물류부하등급"
                        ]
                    )
                ),
                axis=1
            )

            if (
                selected_df[
                    "종합운영위험등급"
                ].isna().any()
            ):

                undefined_pairs = (
                    selected_df.loc[
                        selected_df[
                            "종합운영위험등급"
                        ].isna(),
                        [
                            "블록기상위험등급",
                            "물류부하등급"
                        ]
                    ]
                    .drop_duplicates()
                )

                raise ValueError(
                    "정의되지 않은 종합위험 조합입니다.\n"
                    + undefined_pairs.to_string(
                        index=False
                    )
                )


            # -------------------------------------------
            # 5-6. 인력 배치
            # -------------------------------------------

            allocation_rows = []

            for _, row in selected_df.iterrows():

                allocation_rows.append(
                    allocate_workers(
                        total_workers,
                        row[
                            "종합운영위험등급"
                        ]
                    )
                )

            allocation_df = pd.DataFrame(
                allocation_rows
            )

            selected_df = pd.concat(
                [
                    selected_df.reset_index(
                        drop=True
                    ),
                    allocation_df.reset_index(
                        drop=True
                    )
                ],
                axis=1
            )

            if (
                "배치합계"
                not in selected_df.columns
            ):
                selected_df[
                    "배치합계"
                ] = (
                    selected_df[
                        [
                            "상하차",
                            "분류",
                            "검수",
                            "휴식 및 대기"
                        ]
                    ]
                    .sum(axis=1)
                )

            selected_df[
                "운영권고"
            ] = (
                selected_df[
                    "종합운영위험등급"
                ]
                .map(advice_map)
            )


            # -------------------------------------------
            # 5-7. 검수
            # -------------------------------------------

            block_count = (
                selected_df[
                    "블록시작일시"
                ]
                .nunique()
            )

            complete_shift = (
                block_count == 6
                and (
                    selected_df[
                        "완전블록여부"
                    ]
                    == "완전"
                ).all()
            )

            shift_status = (
                "완전"
                if complete_shift
                else "부분"
            )

            mismatch_count = (
                selected_df[
                    "배치합계"
                ]
                .ne(total_workers)
                .sum()
            )


            # -------------------------------------------
            # 5-8. 표 상단 정보
            # -------------------------------------------

            header_text = f"""
            <div style="
                margin: 8px 0 12px 0;
                padding: 12px 14px;
                border: 1px solid #bdbdbd;
                border-radius: 7px;
                background-color: #f7f7f7;
                color: #000000;
                font-size: 14px;
            ">
                <b>근무거점</b>:
                {html.escape(str(selected_site))}
                &nbsp;&nbsp; | &nbsp;&nbsp;

                <b>날짜</b>:
                {html.escape(str(selected_date))}
                &nbsp;&nbsp; | &nbsp;&nbsp;

                <b>근무조</b>:
                {html.escape(str(selected_shift))}
                &nbsp;&nbsp; | &nbsp;&nbsp;

                <b>근무인원</b>:
                {int(total_workers)}명
                &nbsp;&nbsp; | &nbsp;&nbsp;

                <b>물류부하등급</b>:
                {html.escape(str(load_grade))}
            </div>
            """

            display(
                HTML(header_text)
            )


            # -------------------------------------------
            # 5-9. 자료상태
            # -------------------------------------------

            print(
                f"근무조 자료상태: {shift_status}"
            )

            print(
                f"2시간 블록 수: {block_count}"
            )

            print(
                f"인원합계 불일치: {mismatch_count}"
            )

            if shift_status == "부분":
                print(
                    "※ 일부 시간대 자료만 존재하여 "
                    "부분 배치표로 출력됐습니다."
                )


            # -------------------------------------------
            # 5-10. 색상 범례
            # -------------------------------------------

            legend_text = """
            <div style="margin: 12px 0;">
                <b>종합운영위험등급</b>
                &nbsp;

                <span style="
                    background:#d9ead3;
                    padding:4px 10px;
                    border:1px solid #aaaaaa;
                ">낮음</span>

                <span style="
                    background:#fff2cc;
                    padding:4px 10px;
                    border:1px solid #aaaaaa;
                ">주의</span>

                <span style="
                    background:#f9cb9c;
                    padding:4px 10px;
                    border:1px solid #aaaaaa;
                ">경고</span>

                <span style="
                    background:#ea9999;
                    padding:4px 10px;
                    border:1px solid #aaaaaa;
                ">매우 위험</span>
            </div>
            """

            display(
                HTML(legend_text)
            )


            # -------------------------------------------
            # 5-11. 최종 표
            # -------------------------------------------

            result_table = selected_df.rename(
                columns={
                    "블록최고체감온도":
                        "대표체감온도(℃)",

                    "블록기상위험등급":
                        "기상위험등급"
                }
            )

            result_table = result_table[
                [
                    "시간대",
                    "대표체감온도(℃)",
                    "기상위험등급",
                    "종합운영위험등급",
                    "상하차",
                    "분류",
                    "검수",
                    "휴식 및 대기",
                    "배치합계",
                    "운영권고"
                ]
            ].copy()

            styled_table = (
                result_table
                .style
                .apply(
                    apply_combined_risk_color,
                    axis=1
                )
                .format({
                    "대표체감온도(℃)":
                        "{:.1f}"
                })
                .set_properties(
                    **{
                        "text-align":
                            "center",

                        "border":
                            "1px solid #cccccc"
                    }
                )
                .set_table_styles([
                    {
                        "selector": "th",
                        "props": [
                            (
                                "background-color",
                                "#eeeeee"
                            ),
                            (
                                "color",
                                "#000000"
                            ),
                            (
                                "text-align",
                                "center"
                            ),
                            (
                                "border",
                                "1px solid #cccccc"
                            )
                        ]
                    }
                ])
            )

            display(
                styled_table
            )


            # -------------------------------------------
            # 5-12. 저장
            # -------------------------------------------

            safe_site_name = (
                str(selected_site)
                .replace("/", "_")
                .replace("\\", "_")
                .replace(" ", "_")
            )

            save_path = (
                PROCESSED_DIR
                /
                (
                    "종합위험_인력배치표_"
                    f"{safe_site_name}_"
                    f"{selected_date}_"
                    f"{selected_shift}_"
                    f"{total_workers}명.csv"
                )
            )

            selected_df.to_csv(
                save_path,
                index=False,
                encoding="utf-8-sig"
            )

            print("\n저장 완료:")
            print(save_path)


    except Exception as error:

        with repeat_result_output:

            print(
                "\n[배치표 생성 중 오류 발생]"
            )

            print(
                f"{type(error).__name__}: {error}"
            )

            print(
                "\n오류 위치 확인용 상세 내용:"
            )

            traceback.print_exc()


    finally:

        confirm_button.disabled = False
        confirm_button.description = (
            original_description
        )


# ---------------------------------------------------------
# 6. 버튼 기능 교체
# ---------------------------------------------------------

confirm_button.description = (
    "종합위험 배치표 생성"
)

confirm_button.icon = "table"

confirm_button._click_handlers.callbacks = []

confirm_button.on_click(
    create_repeatable_staffing_table
)


# ---------------------------------------------------------
# 7. 새 고정형 화면 구성
# ---------------------------------------------------------

repeat_input_panel = widgets.VBox([
    widgets.HTML(
        value=(
            "<h3>대전 물류거점 폭염 대응 "
            "인력배치 모델</h3>"
        )
    ),
    site_dropdown,
    date_dropdown,
    shift_dropdown,
    worker_input,
    confirm_button
])

repeat_model_screen = widgets.VBox([
    repeat_input_panel,
    repeat_result_output
])


# ---------------------------------------------------------
# 8. 화면 표시
# ---------------------------------------------------------

display(
    repeat_model_screen
)

VBox(children=(VBox(children=(HTML(value='<h3>대전 물류거점 폭염 대응 인력배치 모델</h3>'), Dropdown(description='근무거점:', inde…

# **3단계 결론**
- 시간별 기상예보와 거점별 물류부하 결합
- 근무거점, 날짜, 낮/밤 근무조, 근무인원을 입력하면 2시간 단위로 인력배치를 출력하는 모델 구축
- 위험등급에 따라 초록, 노랑, 주황, 빨강으로 표시

# **4. 모델 검증 및 실제 데이터 기반 결과 분석**

4-1. STCS 과거 체감온도 자료 불러오기 및 구조 검수
- 현재 예보에서 나오지 않은 경고, 매우 위험 사례 확인
- 위험등급 경계가 정확이 적용됐는지 검증
- 33℃ 미만: 낮음
- 33℃ 이상 35℃ 미만: 주의
- 35℃ 이상 38℃ 미만: 경고
- 38℃ 이상: 매우 위험

- 7개 파일 모두 실제 경로에서 정상 존재 확인

In [ ]:
# =========================================================
# 4-1. STCS 파일 위치 자동 복구
#
# 오류 원인:
# - 런타임 재시작으로 stcs_file_paths,
#   found_file_df 변수가 사라짐
#
# 코드 상태:
# - 기존 4-1 완전 대체
# - 최종 유지
# - 앞 단계 변수에 의존하지 않음
# =========================================================

from pathlib import Path
import pandas as pd
from IPython.display import display


# ---------------------------------------------------------
# 1. 검색 시작 경로
# ---------------------------------------------------------

DRIVE_ROOT = Path(
    "/content/drive/MyDrive"
)

if not DRIVE_ROOT.exists():

    raise FileNotFoundError(
        "구글 드라이브가 연결되어 있지 않습니다.\n"
        "먼저 drive.mount('/content/drive')를 실행해주세요."
    )


# ---------------------------------------------------------
# 2. 검색 대상 확장자
# ---------------------------------------------------------

target_extensions = {
    ".csv",
    ".txt",
    ".dat",
    ".xls",
    ".xlsx"
}


# ---------------------------------------------------------
# 3. 후보 파일 전체 검색
# ---------------------------------------------------------

all_candidates = []

for file_path in DRIVE_ROOT.rglob("*"):

    if (
        file_path.is_file()
        and file_path.suffix.lower() in target_extensions
    ):

        file_name_lower = file_path.name.lower()

        keyword_score = 0

        # STCS 또는 체감온도 관련 키워드 점수 부여
        if "stcs" in file_name_lower:
            keyword_score += 5

        if "체감온도" in file_path.name:
            keyword_score += 4

        if "대전" in file_path.name:
            keyword_score += 2

        if any(
            str(year) in file_path.name
            for year in range(2020, 2027)
        ):
            keyword_score += 1

        if keyword_score > 0:

            all_candidates.append(
                {
                    "파일명": file_path.name,
                    "전체경로": str(file_path),
                    "확장자": file_path.suffix.lower(),
                    "검색점수": keyword_score,
                    "파일크기_KB": round(
                        file_path.stat().st_size / 1024,
                        2
                    )
                }
            )


# ---------------------------------------------------------
# 4. 검색 결과 검수
# ---------------------------------------------------------

if not all_candidates:

    raise FileNotFoundError(
        "구글 드라이브 전체에서 STCS 또는 체감온도 관련 "
        "파일을 찾지 못했습니다.\n"
        "파일명에 STCS, 체감온도, 대전, 연도 정보가 있는지 "
        "확인해주세요."
    )


found_file_df = pd.DataFrame(
    all_candidates
).sort_values(
    by=[
        "검색점수",
        "파일명"
    ],
    ascending=[
        False,
        True
    ]
).reset_index(
    drop=True
)


# ---------------------------------------------------------
# 5. STCS 원본으로 판단되는 파일만 추출
# ---------------------------------------------------------

stcs_mask = (
    found_file_df["파일명"]
    .str.lower()
    .str.contains(
        "stcs",
        na=False
    )
    |
    found_file_df["파일명"]
    .str.contains(
        "체감온도",
        na=False
    )
)


stcs_candidates_df = found_file_df[
    stcs_mask
].copy()


# 연도별 원본만 우선 선택
year_mask = stcs_candidates_df[
    "파일명"
].str.contains(
    r"202[0-6]",
    regex=True,
    na=False
)


yearly_stcs_df = stcs_candidates_df[
    year_mask
].copy()


if len(yearly_stcs_df) > 0:

    selected_df = yearly_stcs_df.copy()

else:

    selected_df = stcs_candidates_df.copy()


# ---------------------------------------------------------
# 6. 통합 산출물 제외
# ---------------------------------------------------------

exclude_keywords = [
    "통합원본",
    "과거기상위험등급",
    "연도별요약",
    "전체위험등급분포",
    "연도별위험등급분포"
]


exclude_mask = pd.Series(
    False,
    index=selected_df.index
)


for keyword in exclude_keywords:

    exclude_mask = (
        exclude_mask
        |
        selected_df["파일명"]
        .str.contains(
            keyword,
            na=False
        )
    )


selected_df = selected_df[
    ~exclude_mask
].copy()


# ---------------------------------------------------------
# 7. 연도 추출 및 경로 목록 생성
# ---------------------------------------------------------

selected_df[
    "연도"
] = selected_df[
    "파일명"
].str.extract(
    r"(202[0-6])"
)


selected_df = selected_df.sort_values(
    by=[
        "연도",
        "파일명"
    ],
    na_position="last"
).reset_index(
    drop=True
)


stcs_file_paths = [
    Path(path)
    for path in selected_df["전체경로"].tolist()
]


# ---------------------------------------------------------
# 8. 결과 출력
# ---------------------------------------------------------

print("[4-1 실행 완료]")
print(
    "STCS 후보 파일 수:",
    len(stcs_file_paths)
)

print(
    "\n[선택된 STCS 파일]"
)

display(
    selected_df[
        [
            "연도",
            "파일명",
            "확장자",
            "파일크기_KB",
            "전체경로"
        ]
    ]
)


print(
    "\nstcs_file_paths 생성 여부:",
    "stcs_file_paths" in globals()
)

print(
    "found_file_df 생성 여부:",
    "found_file_df" in globals()
)


# ---------------------------------------------------------
# 9. 연도별 파일 존재 여부 확인
# ---------------------------------------------------------

expected_years = [
    str(year)
    for year in range(2020, 2027)
]


found_years = sorted(
    selected_df[
        "연도"
    ]
    .dropna()
    .unique()
    .tolist()
)


missing_years = [
    year
    for year in expected_years
    if year not in found_years
]


print(
    "\n확인된 연도:",
    found_years
)

print(
    "누락 연도:",
    missing_years
)


if missing_years:

    print(
        "\n주의: 일부 연도 파일이 자동 검색되지 않았습니다."
    )

else:

    print(
        "\n2020~2026년 STCS 파일이 모두 확인되었습니다."
    )

[4-1 실행 완료]
STCS 후보 파일 수: 9

[선택된 STCS 파일]

,연도,파일명,확장자,파일크기_KB,전체경로
0,2020,STCS_체감온도_2020년도.xls,.xls,4.05,/content/drive/MyDrive/대전_물류창고_폭염...
1,2020,대전_STCS_2020_2026_6월9월_과거기상위험드...,.csv,87.74,/content/drive/MyDrive/대전_물류창고_폭염...
2,2020,대전_STCS_체감온도_2020_2026_통합원본.csv,.csv,89.30,/content/drive/MyDrive/대전_물류창고_폭염...
3,2021,STCS_체감온도_2021년도.xls,.xls,4.01,/content/drive/MyDrive/대전_물류창고_폭염...
4,2022,STCS_체감온도_2022년도.xls,.xls,4.03,/content/drive/MyDrive/대전_물류창고_폭염...
5,2023,STCS_체감온도_2023년도.xls,.xls,4.04,/content/drive/MyDrive/대전_물류창고_폭염...
6,2024,STCS_체감온도_2024년도.xls,.xls,4.06,/content/drive/MyDrive/대전_물류창고_폭염...
7,2025,STCS_체감온도_2025년도.xls,.xls,4.03,/content/drive/MyDrive/대전_물류창고_폭염...
8,2026,STCS_체감온도_2026년도.xls,.xls,2.31,/content/drive/MyDrive/대전_물류창고_폭염...

stcs_file_paths 생성 여부: True
found_file_df 생성 여부: True

확인된 연도: ['2020', '2021', '2022', '2023', '2024', '2025', '2026']
누락 연도: []

2020~2026년 STCS 파일이 모두 확인되었습니다.

4-2. STCS 탭 구분 자료 불러오기 및 연도별 통합

In [ ]:
# =========================================================
# 4-2. 2020~2026년 STCS 통합자료 복구 및 검수
#
# 목적:
# 1. 기존에 정상 저장된 통합 CSV를 직접 불러오기
# 2. 런타임 재시작 후 stcs_integrated 변수 복구
# 3. 연도별 행 수와 전체 1,004행 여부 검수
#
# 코드 상태:
# - 기존 4-2 완전 대체
# - 최종 유지
# - 4-1 실행 불필요
# - 원본 .xls 재판독 불필요
# =========================================================

from pathlib import Path

import pandas as pd
from IPython.display import display


# ---------------------------------------------------------
# 1. 통합파일 경로
# ---------------------------------------------------------

PROJECT_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도"
)

INPUT_FILE = (
    PROJECT_DIR
    / "03_전처리데이터"
    / "대전_STCS_체감온도_2020_2026_통합원본.csv"
)


if not INPUT_FILE.exists():

    raise FileNotFoundError(
        "기존에 저장된 STCS 통합파일을 찾을 수 없습니다.\n"
        f"확인 경로: {INPUT_FILE}"
    )


# ---------------------------------------------------------
# 2. 통합자료 불러오기
# ---------------------------------------------------------

stcs_integrated = pd.read_csv(
    INPUT_FILE,
    encoding="utf-8-sig"
)


# ---------------------------------------------------------
# 3. 열 이름 정리
# ---------------------------------------------------------

stcs_integrated.columns = [
    str(column).strip()
    for column in stcs_integrated.columns
]


# ---------------------------------------------------------
# 4. 자료연도 열 확인 및 숫자형 변환
# ---------------------------------------------------------

if "자료연도" not in stcs_integrated.columns:

    raise KeyError(
        "통합자료에 '자료연도' 열이 없습니다.\n"
        f"현재 열 이름: {stcs_integrated.columns.tolist()}"
    )


stcs_integrated["자료연도"] = pd.to_numeric(
    stcs_integrated["자료연도"],
    errors="coerce"
)


if stcs_integrated["자료연도"].isna().any():

    raise ValueError(
        "자료연도 열에 숫자로 변환되지 않는 값이 있습니다."
    )


stcs_integrated["자료연도"] = (
    stcs_integrated["자료연도"]
    .astype(int)
)


# ---------------------------------------------------------
# 5. 날짜 열이 있으면 날짜형으로 복구
# ---------------------------------------------------------

date_candidates = [
    "일시",
    "날짜",
    "기준일",
    "관측일자"
]


for column in date_candidates:

    if column in stcs_integrated.columns:

        stcs_integrated[column] = pd.to_datetime(
            stcs_integrated[column],
            errors="coerce"
        )


# ---------------------------------------------------------
# 6. 연도별 행 수 검수
# ---------------------------------------------------------

year_summary = (
    stcs_integrated
    .groupby("자료연도")
    .size()
    .reindex(
        range(2020, 2027),
        fill_value=0
    )
    .rename_axis("자료연도")
    .reset_index(name="행수")
)


expected_rows = {
    2020: 153,
    2021: 153,
    2022: 153,
    2023: 153,
    2024: 153,
    2025: 153,
    2026: 86
}


year_summary["예상행수"] = (
    year_summary["자료연도"]
    .map(expected_rows)
)


year_summary["행수일치"] = (
    year_summary["행수"]
    == year_summary["예상행수"]
)


# ---------------------------------------------------------
# 7. 중복 및 결측 검수
# ---------------------------------------------------------

duplicate_count = int(
    stcs_integrated.duplicated().sum()
)

year_missing_count = int(
    stcs_integrated["자료연도"]
    .isna()
    .sum()
)


# ---------------------------------------------------------
# 8. 결과 출력
# ---------------------------------------------------------

print("[4-2 실행 완료]")

print(
    "복구 방식: 기존 통합 CSV 직접 불러오기"
)

print(
    "통합자료 크기:",
    stcs_integrated.shape
)

print(
    "전체 행 수:",
    len(stcs_integrated)
)

print(
    "수록 연도:",
    sorted(
        stcs_integrated[
            "자료연도"
        ]
        .unique()
        .tolist()
    )
)

print(
    "완전 중복 행 수:",
    duplicate_count
)

print(
    "자료연도 결측 수:",
    year_missing_count
)


print("\n[연도별 행 수 검수]")

display(
    year_summary
)


print("\n[통합자료 앞부분]")

display(
    stcs_integrated.head()
)


print("\n[통합자료 열 이름]")

print(
    stcs_integrated.columns.tolist()
)


# ---------------------------------------------------------
# 9. 최종 정상 여부 확인
# ---------------------------------------------------------

total_row_check = (
    len(stcs_integrated) == 1004
)

year_check = (
    year_summary["행수일치"].all()
)


print("\n[최종 검수]")

print(
    "전체 1,004행 여부:",
    total_row_check
)

print(
    "연도별 예상 행 수 일치:",
    year_check
)

print(
    "stcs_integrated 변수 생성 여부:",
    "stcs_integrated" in globals()
)


if not total_row_check:

    raise ValueError(
        "통합자료 전체 행 수가 예상값 1,004행과 다릅니다."
    )


if not year_check:

    raise ValueError(
        "일부 연도의 행 수가 기존 정상 결과와 다릅니다."
    )


print(
    "\n2020~2026년 STCS 통합자료가 정상적으로 복구되었습니다."
)

[4-2 실행 완료]
복구 방식: 기존 통합 CSV 직접 불러오기
통합자료 크기: (1004, 6)
전체 행 수: 1004
수록 연도: [2020, 2021, 2022, 2023, 2024, 2025, 2026]
완전 중복 행 수: 0
자료연도 결측 수: 0

[연도별 행 수 검수]

   자료연도   행수  예상행수  행수일치
0  2020  153   153  True
1  2021  153   153  True
2  2022  153   153  True
3  2023  153   153  True
4  2024  153   153  True
5  2025  153   153  True
6  2026   86    86  True

[통합자료 앞부분]

           일자  기온(°C)  습도(%rh)  체감온도(°C)  자료연도                          원본파일명
0  2020-05-01    29.0     47.9      28.9  2020  STCS_체감온도_2020년도.xls
1  2020-05-02    26.5     49.7      26.6  2020  STCS_체감온도_2020년도.xls
2  2020-05-03    22.3     78.5      24.6  2020  STCS_체감온도_2020년도.xls
3  2020-05-04    26.9     58.0      27.7  2020  STCS_체감온도_2020년도.xls
4  2020-05-05    22.2     62.0      23.4  2020  STCS_체감온도_2020년도.xls

[통합자료 열 이름]
['일자', '기온(°C)', '습도(%rh)', '체감온도(°C)', '자료연도', '원본파일명']

[최종 검수]
전체 1,004행 여부: True
연도별 예상 행 수 일치: True
stcs_integrated 변수 생성 여부: True

2020~2026년 STCS 통합자료가 정상적으로 복구되었습니다.

- 2020 ~ 2025: 각 153일
- 2026년: 7월 25일까지 86일
- 통합 행 수: 1,004행
- 주요 열: 일자, 기온(℃), 습도(%) 체감온도(℃)
- 중복 연도, 읽기 실패 x
- 통합 파일 정상 저장
- STCS 자료 5월 1일부터 수집 -> 분석 기준에 맞게 6월 1일 ~ 9월 30일만 사용

4-3. 과거 체감온도 위험등급 적용 및 연도별 검증
- 일별 물량 적용x
- 순수 체감온도 위험등급만 적용

In [ ]:
# =========================================================
# 4-3. 2020~2026년 과거 체감온도 위험등급 산출
#
# 수정 내용:
# 1. stcs_all 변수 없음 오류 해결
# 2. 저장된 통합 CSV를 직접 불러와 단독 실행
# 3. stcs_integrated와 stcs_all 변수 모두 복구
# 4. 6~9월 자료만 추출
# 5. 체감온도 기준 과거 기상위험등급 산출
# 6. 전체·연도별 분포와 요약표 저장
#
# 코드 상태:
# - 기존 4-3 완전 대체
# - 최종 유지
# - 4-2 실행 여부와 관계없이 단독 실행 가능
# =========================================================

from pathlib import Path

import numpy as np
import pandas as pd
from IPython.display import display


# ---------------------------------------------------------
# 1. 경로 설정
# ---------------------------------------------------------

PROJECT_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도"
)

INPUT_FILE = (
    PROJECT_DIR
    / "03_전처리데이터"
    / "대전_STCS_체감온도_2020_2026_통합원본.csv"
)

OUTPUT_DIR = (
    PROJECT_DIR
    / "03_전처리데이터"
)

OUTPUT_RISK_FILE = (
    OUTPUT_DIR
    / "대전_STCS_2020_2026_6월9월_과거기상위험등급.csv"
)

OUTPUT_TOTAL_FILE = (
    OUTPUT_DIR
    / "대전_과거체감온도_전체위험등급분포.csv"
)

OUTPUT_YEAR_RISK_FILE = (
    OUTPUT_DIR
    / "대전_과거체감온도_연도별위험등급분포.csv"
)

OUTPUT_YEAR_SUMMARY_FILE = (
    OUTPUT_DIR
    / "대전_과거체감온도_연도별요약.csv"
)


if not INPUT_FILE.exists():

    raise FileNotFoundError(
        "STCS 통합파일을 찾을 수 없습니다.\n"
        f"확인 경로: {INPUT_FILE}"
    )


# ---------------------------------------------------------
# 2. 통합자료 직접 불러오기
# ---------------------------------------------------------

stcs_integrated = pd.read_csv(
    INPUT_FILE,
    encoding="utf-8-sig"
)

stcs_integrated.columns = [
    str(column).strip()
    for column in stcs_integrated.columns
]

# 이전 코드와의 호환을 위해 두 변수명 모두 생성
stcs_all = stcs_integrated.copy()


print("[통합자료 불러오기 완료]")

print(
    "자료 크기:",
    stcs_all.shape
)

print(
    "열 이름:",
    stcs_all.columns.tolist()
)


# ---------------------------------------------------------
# 3. 날짜 열 자동 확인
# ---------------------------------------------------------

date_candidates = [
    "일시",
    "날짜",
    "기준일",
    "관측일자",
    "관측일",
    "년월일",
    "일자",
    "date",
    "Date"
]


date_column = None


for column in date_candidates:

    if column in stcs_all.columns:

        converted = pd.to_datetime(
            stcs_all[column],
            errors="coerce"
        )

        if converted.notna().sum() > 0:

            date_column = column
            stcs_all[column] = converted
            break


# 후보명으로 찾지 못하면 모든 열을 날짜형으로 시험
if date_column is None:

    for column in stcs_all.columns:

        if column in [
            "자료연도",
            "원본파일명"
        ]:
            continue

        converted = pd.to_datetime(
            stcs_all[column],
            errors="coerce"
        )

        valid_ratio = (
            converted.notna().mean()
        )

        if valid_ratio >= 0.8:

            date_column = column
            stcs_all[column] = converted
            break


if date_column is None:

    raise KeyError(
        "날짜 열을 자동으로 찾지 못했습니다.\n"
        f"현재 열 이름: {stcs_all.columns.tolist()}"
    )


# ---------------------------------------------------------
# 4. 체감온도 열 자동 확인
# ---------------------------------------------------------

temperature_candidates = [
    "체감온도",
    "체감온도(℃)",
    "체감온도(°C)",
    "일최고체감온도",
    "최고체감온도",
    "STCS",
    "stcs"
]


temperature_column = None


for column in temperature_candidates:

    if column in stcs_all.columns:

        converted = pd.to_numeric(
            stcs_all[column],
            errors="coerce"
        )

        if converted.notna().sum() > 0:

            temperature_column = column
            stcs_all[column] = converted
            break


# 후보명으로 찾지 못하면 이름에 '체감' 또는 'STCS' 포함 여부 확인
if temperature_column is None:

    for column in stcs_all.columns:

        column_text = str(column).lower()

        if (
            "체감" in column_text
            or "stcs" in column_text
        ):

            converted = pd.to_numeric(
                stcs_all[column],
                errors="coerce"
            )

            if converted.notna().sum() > 0:

                temperature_column = column
                stcs_all[column] = converted
                break


if temperature_column is None:

    raise KeyError(
        "체감온도 열을 자동으로 찾지 못했습니다.\n"
        f"현재 열 이름: {stcs_all.columns.tolist()}"
    )


print(
    "\n확인된 날짜 열:",
    date_column
)

print(
    "확인된 체감온도 열:",
    temperature_column
)


# ---------------------------------------------------------
# 5. 분석용 표준 열 생성
# ---------------------------------------------------------

historical_risk = stcs_all.copy()


historical_risk[
    "기준날짜"
] = pd.to_datetime(
    historical_risk[date_column],
    errors="coerce"
)


historical_risk[
    "체감온도"
] = pd.to_numeric(
    historical_risk[temperature_column],
    errors="coerce"
)


# 자료연도가 없거나 결측이면 날짜에서 추출
if "자료연도" not in historical_risk.columns:

    historical_risk[
        "자료연도"
    ] = historical_risk[
        "기준날짜"
    ].dt.year

else:

    historical_risk[
        "자료연도"
    ] = pd.to_numeric(
        historical_risk["자료연도"],
        errors="coerce"
    )

    historical_risk[
        "자료연도"
    ] = historical_risk[
        "자료연도"
    ].fillna(
        historical_risk[
            "기준날짜"
        ].dt.year
    )


# ---------------------------------------------------------
# 6. 2020~2026년 6~9월 자료 추출
# ---------------------------------------------------------

historical_risk = historical_risk[
    historical_risk[
        "자료연도"
    ].between(
        2020,
        2026
    )
    &
    historical_risk[
        "기준날짜"
    ].dt.month.between(
        6,
        9
    )
].copy()


# 날짜 또는 체감온도 결측 행 제외
historical_risk = historical_risk.dropna(
    subset=[
        "기준날짜",
        "체감온도"
    ]
).copy()


historical_risk[
    "자료연도"
] = historical_risk[
    "자료연도"
].astype(int)


historical_risk = (
    historical_risk
    .sort_values(
        by=[
            "기준날짜",
            "자료연도"
        ]
    )
    .reset_index(
        drop=True
    )
)


# ---------------------------------------------------------
# 7. 체감온도 기반 기상위험등급 함수
# ---------------------------------------------------------

def classify_weather_risk(apparent_temperature):

    if pd.isna(apparent_temperature):
        return np.nan

    if apparent_temperature < 33:
        return "낮음"

    if apparent_temperature < 35:
        return "주의"

    if apparent_temperature < 38:
        return "경고"

    return "매우 위험"


historical_risk[
    "기상위험등급"
] = historical_risk[
    "체감온도"
].apply(
    classify_weather_risk
)


# ---------------------------------------------------------
# 8. 중복·결측 검수
# ---------------------------------------------------------

duplicate_count = int(
    historical_risk[
        [
            "기준날짜"
        ]
    ].duplicated().sum()
)

temperature_missing_count = int(
    historical_risk[
        "체감온도"
    ].isna().sum()
)

risk_missing_count = int(
    historical_risk[
        "기상위험등급"
    ].isna().sum()
)


# ---------------------------------------------------------
# 9. 전체 위험등급 분포
# ---------------------------------------------------------

risk_order = [
    "낮음",
    "주의",
    "경고",
    "매우 위험"
]


overall_risk_summary = (
    historical_risk[
        "기상위험등급"
    ]
    .value_counts()
    .reindex(
        risk_order,
        fill_value=0
    )
    .rename_axis(
        "기상위험등급"
    )
    .reset_index(
        name="일수"
    )
)


overall_risk_summary[
    "비율_pct"
] = (
    overall_risk_summary[
        "일수"
    ]
    / len(historical_risk)
    * 100
).round(2)


# ---------------------------------------------------------
# 10. 연도별 위험등급 분포
# ---------------------------------------------------------

yearly_risk_summary = (
    historical_risk
    .groupby(
        [
            "자료연도",
            "기상위험등급"
        ]
    )
    .size()
    .unstack(
        fill_value=0
    )
    .reindex(
        columns=risk_order,
        fill_value=0
    )
    .reset_index()
)


yearly_risk_summary[
    "전체일수"
] = yearly_risk_summary[
    risk_order
].sum(
    axis=1
)


# ---------------------------------------------------------
# 11. 연도별 체감온도 요약
# ---------------------------------------------------------

yearly_temperature_summary = (
    historical_risk
    .groupby(
        "자료연도"
    )
    .agg(
        분석일수=(
            "기준날짜",
            "count"
        ),

        평균체감온도=(
            "체감온도",
            "mean"
        ),

        최저체감온도=(
            "체감온도",
            "min"
        ),

        최고체감온도=(
            "체감온도",
            "max"
        ),

        주의이상일수=(
            "기상위험등급",
            lambda series: series.isin(
                [
                    "주의",
                    "경고",
                    "매우 위험"
                ]
            ).sum()
        ),

        경고이상일수=(
            "기상위험등급",
            lambda series: series.isin(
                [
                    "경고",
                    "매우 위험"
                ]
            ).sum()
        )
    )
    .reset_index()
)


for column in [
    "평균체감온도",
    "최저체감온도",
    "최고체감온도"
]:

    yearly_temperature_summary[
        column
    ] = yearly_temperature_summary[
        column
    ].round(1)


yearly_temperature_summary[
    "주의이상비율_pct"
] = (
    yearly_temperature_summary[
        "주의이상일수"
    ]
    / yearly_temperature_summary[
        "분석일수"
    ]
    * 100
).round(2)


yearly_temperature_summary[
    "경고이상비율_pct"
] = (
    yearly_temperature_summary[
        "경고이상일수"
    ]
    / yearly_temperature_summary[
        "분석일수"
    ]
    * 100
).round(2)


# ---------------------------------------------------------
# 12. 결과 출력
# ---------------------------------------------------------

print("\n[4-3 실행 완료]")

print(
    "분석기간:",
    historical_risk[
        "기준날짜"
    ].min(),
    "~",
    historical_risk[
        "기준날짜"
    ].max()
)

print(
    "분석 행 수:",
    len(historical_risk)
)

print(
    "중복 날짜 수:",
    duplicate_count
)

print(
    "체감온도 결측 수:",
    temperature_missing_count
)

print(
    "위험등급 결측 수:",
    risk_missing_count
)


print("\n[전체 과거 기상위험등급 분포]")

display(
    overall_risk_summary
)


print("\n[연도별 기상위험등급 분포]")

display(
    yearly_risk_summary
)


print("\n[연도별 체감온도 요약]")

display(
    yearly_temperature_summary
)


# ---------------------------------------------------------
# 13. 기존 변수명 호환
# ---------------------------------------------------------

stcs_historical_risk = historical_risk.copy()

# 과거 코드에서 사용할 가능성이 있는 변수명도 복구
historical_weather_risk = historical_risk.copy()


print(
    "\nstcs_all 변수 생성 여부:",
    "stcs_all" in globals()
)

print(
    "historical_risk 변수 생성 여부:",
    "historical_risk" in globals()
)

print(
    "stcs_historical_risk 변수 생성 여부:",
    "stcs_historical_risk" in globals()
)


# ---------------------------------------------------------
# 14. 결과 저장
# ---------------------------------------------------------

historical_risk.to_csv(
    OUTPUT_RISK_FILE,
    index=False,
    encoding="utf-8-sig"
)

overall_risk_summary.to_csv(
    OUTPUT_TOTAL_FILE,
    index=False,
    encoding="utf-8-sig"
)

yearly_risk_summary.to_csv(
    OUTPUT_YEAR_RISK_FILE,
    index=False,
    encoding="utf-8-sig"
)

yearly_temperature_summary.to_csv(
    OUTPUT_YEAR_SUMMARY_FILE,
    index=False,
    encoding="utf-8-sig"
)


print("\n[저장 완료]")

print(OUTPUT_RISK_FILE)
print(OUTPUT_TOTAL_FILE)
print(OUTPUT_YEAR_RISK_FILE)
print(OUTPUT_YEAR_SUMMARY_FILE)

[통합자료 불러오기 완료]
자료 크기: (1004, 6)
열 이름: ['일자', '기온(°C)', '습도(%rh)', '체감온도(°C)', '자료연도', '원본파일명']

확인된 날짜 열: 일자
확인된 체감온도 열: 체감온도(°C)

[4-3 실행 완료]
분석기간: 2020-06-01 00:00:00 ~ 2026-07-25 00:00:00
분석 행 수: 787
중복 날짜 수: 0
체감온도 결측 수: 0
위험등급 결측 수: 0

[전체 과거 기상위험등급 분포]

  기상위험등급   일수  비율_pct
0     낮음  595   75.60
1     주의  148   18.81
2     경고   44    5.59
3  매우 위험    0    0.00

[연도별 기상위험등급 분포]

기상위험등급  자료연도   낮음  주의  경고  매우 위험  전체일수
0       2020   98  19   5      0   122
1       2021   92  17  13      0   122
2       2022  103  18   1      0   122
3       2023  100  18   4      0   122
4       2024   80  33   9      0   122
5       2025   78  34  10      0   122
6       2026   44   9   2      0    55

[연도별 체감온도 요약]

   자료연도  분석일수  평균체감온도  최저체감온도  최고체감온도  주의이상일수  경고이상일수  주의이상비율_pct  경고이상비율_pct
0  2020   122    29.9    23.2    36.0      24       5       19.67        4.10
1  2021   122    30.6    23.8    36.0      30      13       24.59       10.66
2  2022   122    29.6    21.1    35.1      19       1       15.57        0.82
3  2023   122    29.9    23.2    35.3      22       4       18.03        3.28
4  2024   122    31.3    24.2    35.9      42       9       34.43        7.38
5  2025   122    31.0    23.6    36.2      44      10       36.07        8.20
6  2026    55    30.2    23.8    35.3      11       2       20.00        3.64

stcs_all 변수 생성 여부: True
historical_risk 변수 생성 여부: True
stcs_historical_risk 변수 생성 여부: True

[저장 완료]
/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/대전_STCS_2020_2026_6월9월_과거기상위험등급.csv
/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/대전_과거체감온도_전체위험등급분포.csv
/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/대전_과거체감온도_연도별위험등급분포.csv
/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/대전_과거체감온도_연도별요약.csv

- 분석 대상 787일
- 일자 중복, 주요 변수 결측 0건
- 낮음 595일(75.6%)
- 주의 148일(18.81%)
- 경고 44일(5.59%)
- 매우 위험 0일
- 최고 체감온도 36.2℃

4-4. 위험등급 경계값 및 분류 로직 기능 검증
- 위험 기준 경계값이 올바른 등급으로 분류되는지 확인

In [ ]:
# =========================================================
# 4-4. 위험등급 경계값 및 분류 로직 기능 검증
#
# 목적:
# - 33℃, 35℃, 38℃ 경계에서
#   위험등급이 의도한 대로 분류되는지 확인
# - 실제 자료에 없었던 38℃ 이상 상황도
#   모델이 정상 처리하는지 검증
#
# 코드 유지 여부:
# - 최종 유지
# =========================================================

import numpy as np
import pandas as pd

from IPython.display import display


# ---------------------------------------------------------
# 1. 위험등급 분류 함수 정의
# ---------------------------------------------------------

def classify_weather_risk(apparent_temperature):
    """
    체감온도에 따른 기상위험등급 분류

    33℃ 미만          : 낮음
    33℃ 이상 35℃ 미만 : 주의
    35℃ 이상 38℃ 미만 : 경고
    38℃ 이상          : 매우 위험
    """

    if pd.isna(apparent_temperature):
        return "결측"

    if apparent_temperature < 33:
        return "낮음"

    elif apparent_temperature < 35:
        return "주의"

    elif apparent_temperature < 38:
        return "경고"

    else:
        return "매우 위험"


# ---------------------------------------------------------
# 2. 경계값 전후 시험자료 생성
# ---------------------------------------------------------

boundary_test_values = [
    np.nan,
    32.9,
    33.0,
    33.1,
    34.9,
    35.0,
    35.1,
    37.9,
    38.0,
    38.1
]


expected_labels = [
    "결측",
    "낮음",
    "주의",
    "주의",
    "주의",
    "경고",
    "경고",
    "경고",
    "매우 위험",
    "매우 위험"
]


boundary_validation = pd.DataFrame({
    "시험체감온도(°C)":
        boundary_test_values,

    "기대등급":
        expected_labels
})


boundary_validation[
    "실제분류등급"
] = boundary_validation[
    "시험체감온도(°C)"
].apply(
    classify_weather_risk
)


boundary_validation[
    "일치여부"
] = (
    boundary_validation[
        "기대등급"
    ]
    == boundary_validation[
        "실제분류등급"
    ]
)


# ---------------------------------------------------------
# 3. 검증 결과 출력
# ---------------------------------------------------------

print(
    "[위험등급 경계값 기능 검증]"
)

display(
    boundary_validation
)


total_test_count = len(
    boundary_validation
)

matched_test_count = int(
    boundary_validation[
        "일치여부"
    ].sum()
)

failed_test_count = (
    total_test_count
    - matched_test_count
)


print(
    "\n[검증 결과 요약]"
)

print(
    "전체 시험 수:",
    total_test_count
)

print(
    "정상 분류 수:",
    matched_test_count
)

print(
    "오분류 수:",
    failed_test_count
)


# ---------------------------------------------------------
# 4. 모든 시험 통과 여부 확인
# ---------------------------------------------------------

if failed_test_count == 0:

    print(
        "\n모든 경계값이 의도한 위험등급으로 "
        "정상 분류되었습니다."
    )

else:

    print(
        "\n경계값 분류 오류가 발견되었습니다."
    )

    display(
        boundary_validation[
            boundary_validation[
                "일치여부"
            ] == False
        ]
    )


# ---------------------------------------------------------
# 5. 실제 과거자료에 동일 함수 재적용해 기존 결과와 비교
# ---------------------------------------------------------

if "historical_risk" not in globals():

    raise NameError(
        "4-3을 먼저 실행해야 합니다.\n"
        "historical_risk 변수가 없습니다."
    )


historical_function_check = (
    historical_risk[
        [
            "일자",
            "체감온도(°C)",
            "기상위험등급"
        ]
    ]
    .copy()
)


historical_function_check[
    "함수재분류등급"
] = historical_function_check[
    "체감온도(°C)"
].apply(
    classify_weather_risk
)


# 범주형 자료를 문자열로 변환해 비교
historical_function_check[
    "기존등급문자"
] = historical_function_check[
    "기상위험등급"
].astype(
    str
)


historical_function_check[
    "일치여부"
] = (
    historical_function_check[
        "기존등급문자"
    ]
    == historical_function_check[
        "함수재분류등급"
    ]
)


historical_mismatch_count = int(
    (
        historical_function_check[
            "일치여부"
        ] == False
    ).sum()
)


print(
    "\n[과거 787일 재분류 일치 검증]"
)

print(
    "검증 행 수:",
    len(
        historical_function_check
    )
)

print(
    "기존 등급과 불일치 수:",
    historical_mismatch_count
)


if historical_mismatch_count == 0:

    print(
        "과거자료의 모든 위험등급이 "
        "분류 함수와 일치합니다."
    )

else:

    display(
        historical_function_check[
            historical_function_check[
                "일치여부"
            ] == False
        ].head(
            20
        )
    )

[위험등급 경계값 기능 검증]

   시험체감온도(°C)   기대등급 실제분류등급  일치여부
0         NaN     결측     결측  True
1        32.9     낮음     낮음  True
2        33.0     주의     주의  True
3        33.1     주의     주의  True
4        34.9     주의     주의  True
5        35.0     경고     경고  True
6        35.1     경고     경고  True
7        37.9     경고     경고  True
8        38.0  매우 위험  매우 위험  True
9        38.1  매우 위험  매우 위험  True

[검증 결과 요약]
전체 시험 수: 10
정상 분류 수: 10
오분류 수: 0

모든 경계값이 의도한 위험등급으로 정상 분류되었습니다.

[과거 787일 재분류 일치 검증]
검증 행 수: 787
기존 등급과 불일치 수: 0
과거자료의 모든 위험등급이 분류 함수와 일치합니다.

- 경계값 테스트 10개 모두 정상
- 과거 787일 기존 결과와 함수 재분류 결과 불일치 0건

# **4단계 결론**
- 미래예보 분석에서 경고 및 매우 위험 등급이 나타나지 않은 원인을 확인하기 위한 과정
- 동일 위험등급 기준을 2020 ~ 2026 과거 체감온도 자료에 적용
- 과거 자료에서 경고 등급 44일 발생
- 따라서 미래예보에 경고 및 매우 위험 등급이 나타나지 않은 것은 분석 오류x
- 해당 예보기간의 체감온도가 경고 기준에 도달하지 않았기 때문으로 판단