<a href="https://colab.research.google.com/github/yaeji3630-hash/my-vercel-project/blob/main/%EC%9C%84%ED%97%98%EB%8F%84%EC%97%90%EB%94%B0%EB%A5%B8%EC%9D%B8%EB%A0%A5%EC%9E%AC%EB%B0%B0%EC%B9%981.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. 분석 환경 및 데이터 영구저장 구축**

1-1. Google Drive 연결 및 프로젝트 폴더 생성

In [ ]:
# @title
# =========================================================
# 1-1. Google Drive 연결 및 프로젝트 폴더 생성
# =========================================================

from google.colab import drive
from pathlib import Path

# Google Drive 연결
drive.mount('/content/drive')

# 프로젝트 기본 폴더
PROJECT_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도"
)

# 분석 단계별 저장 폴더
RAW_DIR = PROJECT_DIR / "01_원본데이터"
API_DIR = PROJECT_DIR / "02_API수집데이터"
PROCESSED_DIR = PROJECT_DIR / "03_전처리데이터"
RESULT_DIR = PROJECT_DIR / "04_분석결과"
FIGURE_DIR = PROJECT_DIR / "05_시각화"

# 폴더 생성
for folder in [
    PROJECT_DIR,
    RAW_DIR,
    API_DIR,
    PROCESSED_DIR,
    RESULT_DIR,
    FIGURE_DIR
]:
    folder.mkdir(parents=True, exist_ok=True)

# 생성 결과 확인
print("프로젝트 경로:", PROJECT_DIR)

print("\n생성된 폴더")
print("01_원본데이터 :", RAW_DIR)
print("02_API수집데이터 :", API_DIR)
print("03_전처리데이터 :", PROCESSED_DIR)
print("04_분석결과 :", RESULT_DIR)
print("05_시각화 :", FIGURE_DIR)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
프로젝트 경로: /content/drive/MyDrive/대전_물류창고_폭염위험도

생성된 폴더
01_원본데이터 : /content/drive/MyDrive/대전_물류창고_폭염위험도/01_원본데이터
02_API수집데이터 : /content/drive/MyDrive/대전_물류창고_폭염위험도/02_API수집데이터
03_전처리데이터 : /content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터
04_분석결과 : /content/drive/MyDrive/대전_물류창고_폭염위험도/04_분석결과
05_시각화 : /content/drive/MyDrive/대전_물류창고_폭염위험도/05_시각화

1-2. 분석에 필요한 원본파일 Google Drive 영구저장

In [ ]:
# @title
# # =========================================================
# # 1-2. 분석용 원본파일 Google Drive 영구저장
# # =========================================================

# from google.colab import files
# from pathlib import Path

# # 1-1에서 만든 원본데이터 저장 폴더
# RAW_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/01_원본데이터"
# )

# RAW_DIR.mkdir(parents=True, exist_ok=True)

# print("분석에 사용할 원본파일들을 여러 개 선택해 주세요.")

# # 여러 파일 동시 업로드 가능
# uploaded = files.upload()

# print("\n[Google Drive 저장 결과]")

# for filename, file_data in uploaded.items():

#     save_path = RAW_DIR / filename

#     # 동일한 파일명이 있으면 현재 업로드 파일로 갱신
#     with open(save_path, "wb") as f:
#         f.write(file_data)

#     size_mb = save_path.stat().st_size / (1024 ** 2)

#     print(
#         f"✓ {filename}"
#         f" | {size_mb:.2f} MB"
#     )

# print("\n총 저장 파일 수:", len(uploaded))
# print("저장 위치:", RAW_DIR)

1-3. Google Drive 영구저장 파일 검수
- 저장한 파일이 실제 드라이브에 존재하는지 확인

In [ ]:
# @title
# =========================================================
# 1-3. Google Drive 영구저장 파일 검수
# =========================================================

from pathlib import Path
import pandas as pd

RAW_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도/01_원본데이터"
)

records = []

for file_path in sorted(RAW_DIR.iterdir()):

    if file_path.is_file():

        size_bytes = file_path.stat().st_size

        records.append({
            "파일명": file_path.name,
            "파일크기_Bytes": size_bytes,
            "파일크기_KB": round(size_bytes / 1024, 2),
            "정상저장": "정상" if size_bytes > 0 else "확인필요"
        })

check_df = pd.DataFrame(records)

print("저장 파일 수:", len(check_df))
print("0 byte 파일 수:", (check_df["파일크기_Bytes"] == 0).sum())

display(check_df)

저장 파일 수: 24
0 byte 파일 수: 0

,파일명,파일크기_Bytes,파일크기_KB,정상저장
0,STCS_체감온도_2020년도.xls,4148,4.05,정상
1,STCS_체감온도_2021년도.xls,4108,4.01,정상
2,STCS_체감온도_2022년도.xls,4126,4.03,정상
3,STCS_체감온도_2023년도.xls,4134,4.04,정상
4,STCS_체감온도_2024년도.xls,4162,4.06,정상
5,STCS_체감온도_2025년도.xls,4124,4.03,정상
6,STCS_체감온도_2026년도.xls,2363,2.31,정상
7,과학기술정보통신부 우정사업본부_전국...,1883487,1839.34,정상
8,국토교통부_법정동코드_20250805.csv,2278551,2225.15,정상
9,대전_5개구_제조업체_통합정리.xlsx,231892,226.46,정상
10,대전_기상청_시간자료_2021.csv,146070,142.65,정상
11,대전_기상청_시간자료_2022.csv,146621,143.18,정상
12,대전_기상청_시간자료_2023.csv,145310,141.90,정상
13,대전_기상청_시간자료_2024.csv,146407,142.98,정상
14,대전_기상청_시간자료_2025.csv,146373,142.94,정상
15,대전_기상청_시간자료_2026.csv,64035,62.53,정상
16,대전_물류창고_상세정보_20260721.xlsx,10306,10.06,정상
17,대전광역시_공장현황_20221231.csv,29898,29.20,정상
18,대전광역시_산업단지 입주기업 현황_20...,174452,170.36,정상
19,대전광역시_산업단지 현황_20221231.csv,638,0.62,정상
20,대전광역시_창고업등록 현황_20230628.csv,3757,3.67,정상
21,전국_물류창고_목록.xlsx,243128,237.43,정상
22,통계_지역별물류창고업등록현황_260721...,12288,12.00,정상
23,한국도로공사_구간교통량(월별 및 차종...,265486,259.26,정상

# **1단계 결론**
- 분석 환경 및 원본 데이터 영구저장 구축 완료

# **2. 원본데이터 구조 및 품질 검수**

2-1. 핵심 원본파일 일괄 구조, 결측 확인
- 파일이 정상적으로 읽히는지
- 행/열 수
- 열 이름
- 결측치 총 개수
- 중복 행 수

In [ ]:
# =========================================================
# 2-1. 핵심 원본자료 일괄 구조·결측 확인
# =========================================================

from pathlib import Path
import pandas as pd

RAW_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도/01_원본데이터"
)

# ---------------------------------------------------------
# 1. 핵심 파일 목록
# ---------------------------------------------------------

files_to_check = {
    "물류창고": RAW_DIR / "대전_물류창고_상세정보_20260721.xlsx",
    "택배물량": RAW_DIR / "과학기술정보통신부 우정사업본부_전국 우편번호(배달지 기준)별 택배물량_20231231.csv",
    "교통량": RAW_DIR / "한국도로공사_구간교통량(월별 및 차종별)_20241231.csv",
    "법정동코드": RAW_DIR / "국토교통부_법정동코드_20250805.csv",
}

for year in range(2021, 2027):
    files_to_check[f"시간기상_{year}"] = (
        RAW_DIR / f"대전_기상청_시간자료_{year}.csv"
    )

for year in range(2020, 2027):
    files_to_check[f"체감온도_{year}"] = (
        RAW_DIR / f"STCS_체감온도_{year}년도.xls"
    )


# ---------------------------------------------------------
# 2. 파일 자동 읽기 함수
# ---------------------------------------------------------

def read_file(path):

    suffix = path.suffix.lower()

    if suffix in [".xlsx", ".xls"]:
        return pd.read_excel(path)

    elif suffix == ".csv":

        # 공공데이터에서 자주 쓰이는 인코딩 순차 시도
        for enc in ["utf-8-sig", "cp949", "euc-kr", "utf-8"]:
            try:
                return pd.read_csv(path, encoding=enc)
            except:
                continue

        raise ValueError(f"CSV 인코딩 확인 필요: {path.name}")

    else:
        raise ValueError(f"지원하지 않는 형식: {path.name}")


# ---------------------------------------------------------
# 3. 전체 파일 일괄 검수
# ---------------------------------------------------------

summary = []
loaded_data = {}

for name, path in files_to_check.items():

    try:
        df = read_file(path)

        loaded_data[name] = df

        summary.append({
            "데이터": name,
            "행수": len(df),
            "열수": len(df.columns),
            "결측총수": int(df.isna().sum().sum()),
            "중복행수": int(df.duplicated().sum()),
            "상태": "정상"
        })

    except Exception as e:

        summary.append({
            "데이터": name,
            "행수": None,
            "열수": None,
            "결측총수": None,
            "중복행수": None,
            "상태": f"오류: {str(e)[:80]}"
        })


summary_df = pd.DataFrame(summary)

print("[핵심 원본자료 통합 검수 결과]")
display(summary_df)

print("\n[각 데이터 열 이름]")

for name, df in loaded_data.items():

    print(f"\n▶ {name}")
    print(df.columns.tolist())

[핵심 원본자료 통합 검수 결과]

,데이터,행수,열수,결측총수,중복행수,상태
0,물류창고,43.0,12.0,101.0,0.0,정상
1,택배물량,34502.0,13.0,0.0,0.0,정상
2,교통량,2808.0,16.0,0.0,0.0,정상
3,법정동코드,49861.0,3.0,0.0,0.0,정상
4,시간기상_2021,2928.0,10.0,5856.0,0.0,정상
5,시간기상_2022,2928.0,10.0,5856.0,0.0,정상
6,시간기상_2023,2928.0,10.0,5874.0,0.0,정상
7,시간기상_2024,2928.0,10.0,5856.0,0.0,정상
8,시간기상_2025,2928.0,10.0,5853.0,0.0,정상
9,시간기상_2026,1282.0,10.0,2564.0,0.0,정상
10,체감온도_2020,NaN,NaN,NaN,NaN,"오류: Excel file format cannot be determined, yo..."
11,체감온도_2021,NaN,NaN,NaN,NaN,"오류: Excel file format cannot be determined, yo..."
12,체감온도_2022,NaN,NaN,NaN,NaN,"오류: Excel file format cannot be determined, yo..."
13,체감온도_2023,NaN,NaN,NaN,NaN,"오류: Excel file format cannot be determined, yo..."
14,체감온도_2024,NaN,NaN,NaN,NaN,"오류: Excel file format cannot be determined, yo..."
15,체감온도_2025,NaN,NaN,NaN,NaN,"오류: Excel file format cannot be determined, yo..."
16,체감온도_2026,NaN,NaN,NaN,NaN,"오류: Excel file format cannot be determined, yo..."

[각 데이터 열 이름]

▶ 물류창고
['PRESIDENT_NAME', 'STORAGE_ITEM', 'FROZEN_AREA', 'RNUM', 'COMPANY_NAME', 'FROZEN_WING_COUNT', 'GENERAL_WING_COUNT', 'GENERAL_AREA', 'COMPANY_TEL', 'COMPANY_ADDRESS', 'WARE_NO', 'STORAGE_AREA']

▶ 택배물량
['우편번호', '1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월']

▶ 교통량
['구간', '차종', '1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월', '연 일평균', '전년 일평균']

▶ 법정동코드
['법정동코드', '법정동명', '폐지여부']

▶ 시간기상_2021
['지점', '지점명', '일시', '기온(°C)', '기온 QC플래그', '풍속(m/s)', '습도(%)', '습도 QC플래그', '증기압(hPa)', '이슬점온도(°C)']

▶ 시간기상_2022
['지점', '지점명', '일시', '기온(°C)', '기온 QC플래그', '풍속(m/s)', '습도(%)', '습도 QC플래그', '증기압(hPa)', '이슬점온도(°C)']

▶ 시간기상_2023
['지점', '지점명', '일시', '기온(°C)', '기온 QC플래그', '풍속(m/s)', '습도(%)', '습도 QC플래그', '증기압(hPa)', '이슬점온도(°C)']

▶ 시간기상_2024
['지점', '지점명', '일시', '기온(°C)', '기온 QC플래그', '풍속(m/s)', '습도(%)', '습도 QC플래그', '증기압(hPa)', '이슬점온도(°C)']

▶ 시간기상_2025
['지점', '지점명', '일시', '기온(°C)', '기온 QC플래그', '풍속(m/s)', '습도(%)', '습도 QC플래그', '증기압(hPa)', '이슬점온도(°C)']

▶ 시간기상_2026
['지점', '지점명', '일시', '기온(°C)', '기온 QC플래그', '풍속(m/s)', '습도(%)', '습도 QC플래그', '증기압(hPa)', '이슬점온도(°C)']

1) 물류창고
- 43개 창고, 12개 변수
- 중복행 0
- 결측 101개가 있지만 FROZEN_AREA, GENERAL_AREA, 전화번호 같은 일부 열에서 생긴 가능성
- 핵심 COMPANY_NAME, COMPANY_ADDRESS, STORAGE_AREA 중심으로 사용
2) 택배물량
- 34,502개 우편번호
- 1~12월 물량
- 결측 0, 중복 0
- 우편번호와 연결하여 지역별 물류수요 대리지표로 활용
3) 교통량
- 2,808행
- 차종 + 월별 교통량
- 결측 0, 중복 0
- 시간대별 교통량 API를 받아서 시간 분포로 활용
4) 법정동 코드
- 49,861개
- 결측 0, 중복 0
5) 2021~2026 시간별 기상자료
- 분석변수 기온, 습도, 풍속
- 기상자료 통합 시 분석 변수 골라서 정제 예정
6) 체감온도 파일
- 오류. 2-2번 코드에서 수정

2-2. 체감온도 2020~2026 일괄 변환 및 통합
- 체감온도 7개를 한번에 읽고 6~9월만 남겨서 데이터 통합 후 Drive 저장

In [ ]:
# @title
# # =========================================================
# # 2-2. 체감온도 2020~2026 일괄 변환·통합
# # =========================================================

# from pathlib import Path
# import pandas as pd
# import io

# RAW_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/01_원본데이터"
# )

# PROCESSED_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
# )

# PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

# all_feels = []

# for year in range(2020, 2027):

#     path = RAW_DIR / f"STCS_체감온도_{year}년도.xls"

#     # 실제 파일은 CP949 인코딩의 탭 구분 텍스트 형식
#     with open(path, "r", encoding="cp949") as f:
#         lines = f.readlines()

#     # '일자'로 시작하는 실제 데이터 헤더 위치 찾기
#     header_idx = next(
#         i for i, line in enumerate(lines)
#         if line.startswith("일자")
#     )

#     # 실제 데이터 부분만 읽기
#     df = pd.read_csv(
#         io.StringIO("".join(lines[header_idx:])),
#         sep="\t"
#     )

#     # 날짜 형식 변환
#     df["일자"] = pd.to_datetime(df["일자"])

#     # 분석기간인 6~9월만 사용
#     df = df[
#         df["일자"].dt.month.between(6, 9)
#     ].copy()

#     df["연도"] = year

#     all_feels.append(df)

# # 연도 통합
# feels_df = pd.concat(
#     all_feels,
#     ignore_index=True
# )

# # 날짜순 정렬
# feels_df = feels_df.sort_values(
#     "일자"
# ).reset_index(drop=True)

# # ---------------------------------------------------------
# # 최소 품질 확인
# # ---------------------------------------------------------

# print("전체 행 수:", len(feels_df))
# print(
#     "기간:",
#     feels_df["일자"].min(),
#     "~",
#     feels_df["일자"].max()
# )

# print("\n연도별 행 수:")
# print(
#     feels_df.groupby("연도")
#     .size()
# )

# print("\n핵심 변수 결측치:")
# print(
#     feels_df[
#         ["기온(°C)", "습도(%rh)", "체감온도(°C)"]
#     ].isna().sum()
# )

# # ---------------------------------------------------------
# # Google Drive 저장
# # ---------------------------------------------------------

# save_path = (
#     PROCESSED_DIR /
#     "대전_체감온도_2020_2026_6월9월.csv"
# )

# feels_df.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)

# display(feels_df.head())

- 총 787일
- 2020~2025년: 매년 6/1 ~ 9/30 122일 완전 확보
- 2026년: 6/1 ~ 7/25일 55일
- 기온, 습도, 체감온도 결측 0
- 통합 파일까지 03_전처리데이터에 영구 저장

2-3. 2021~2026 시간별 기상자료 통합 및 정제
- 6개 연도 파일을 합치고 실제 사용할 4가지 변수만 남김
- 일시, 기온, 습도, 풍속
- QC 플래그, 증기압, 이슬점 필요X -> 제거

In [ ]:
# @title
# # =========================================================
# # 2-3. 2021~2026 시간별 기상자료 통합·정제
# # =========================================================

# from pathlib import Path
# import pandas as pd

# RAW_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/01_원본데이터"
# )

# PROCESSED_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
# )

# weather_list = []

# # ---------------------------------------------------------
# # 1. 2021~2026 시간별 기상자료 일괄 불러오기
# # ---------------------------------------------------------

# for year in range(2021, 2027):

#     path = RAW_DIR / f"대전_기상청_시간자료_{year}.csv"

#     # 공공데이터 인코딩 대응
#     try:
#         df = pd.read_csv(path, encoding="cp949")
#     except:
#         df = pd.read_csv(path, encoding="utf-8-sig")

#     # 분석에 필요한 변수만 선택
#     df = df[
#         [
#             "지점",
#             "지점명",
#             "일시",
#             "기온(°C)",
#             "습도(%)",
#             "풍속(m/s)"
#         ]
#     ].copy()

#     df["연도"] = year

#     weather_list.append(df)


# # ---------------------------------------------------------
# # 2. 전체 연도 통합
# # ---------------------------------------------------------

# weather_df = pd.concat(
#     weather_list,
#     ignore_index=True
# )

# weather_df["일시"] = pd.to_datetime(
#     weather_df["일시"]
# )

# weather_df = weather_df.sort_values(
#     "일시"
# ).reset_index(drop=True)


# # ---------------------------------------------------------
# # 3. 분석 핵심 변수 상태 확인
# #    - 기온·습도: 핵심
# #    - 풍속: 보조변수이므로 결측을 인위적으로 보간하지 않음
# # ---------------------------------------------------------

# print("[핵심·보조 변수 결측치]")

# print(
#     weather_df[
#         ["기온(°C)", "습도(%)", "풍속(m/s)"]
#     ].isna().sum()
# )


# print("\n전체 행 수:", len(weather_df))

# print(
#     "기간:",
#     weather_df["일시"].min(),
#     "~",
#     weather_df["일시"].max()
# )


# print("\n연도별 행 수:")

# print(
#     weather_df.groupby("연도").size()
# )


# # ---------------------------------------------------------
# # 4. 중복 시간 확인
# # ---------------------------------------------------------

# duplicate_time = weather_df["일시"].duplicated().sum()

# print("\n중복 일시 수:", duplicate_time)


# # ---------------------------------------------------------
# # 5. 전처리 데이터 Google Drive 영구저장
# # ---------------------------------------------------------

# save_path = (
#     PROCESSED_DIR /
#     "대전_시간기상_2021_2026_통합정제.csv"
# )

# weather_df.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)

- 기온 결측: 0
- 습도 결측: 0
- 풍속 결측: 18
- 중복 일시: 0
- 전체 15,922시간
- 2021 ~ 2025년: 매년 2,928시간. 6 ~ 9월 전체 확인
- 2026년: 6/1 ~ 7/24 09시까지 확인

2-4. 물류창고 핵심정보 정제
- 43개 물류창고에서 죄종 분석에 필요한 정보만 정리
- 주소, 창고명, 면적, 보관품목 중심
- 주소 결측 창고 확인

In [ ]:
# @title
# # =========================================================
# # 2-4. 물류창고 핵심정보 정제
# # =========================================================

# from pathlib import Path
# import pandas as pd

# RAW_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/01_원본데이터"
# )

# PROCESSED_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
# )

# # ---------------------------------------------------------
# # 1. 물류창고 원본 불러오기
# # ---------------------------------------------------------

# warehouse_path = RAW_DIR / "대전_물류창고_상세정보_20260721.xlsx"

# warehouse_df = pd.read_excel(warehouse_path)


# # ---------------------------------------------------------
# # 2. 분석에 필요한 핵심 열만 선택
# # ---------------------------------------------------------

# warehouse_clean = warehouse_df[
#     [
#         "WARE_NO",
#         "COMPANY_NAME",
#         "COMPANY_ADDRESS",
#         "STORAGE_ITEM",
#         "STORAGE_AREA",
#         "GENERAL_AREA",
#         "FROZEN_AREA"
#     ]
# ].copy()


# # ---------------------------------------------------------
# # 3. 문자열 기본 정리
# # ---------------------------------------------------------

# for col in [
#     "COMPANY_NAME",
#     "COMPANY_ADDRESS",
#     "STORAGE_ITEM"
# ]:
#     warehouse_clean[col] = (
#         warehouse_clean[col]
#         .astype("string")
#         .str.strip()
#     )


# # ---------------------------------------------------------
# # 4. 최소 품질 확인
# # ---------------------------------------------------------

# print("물류창고 수:", len(warehouse_clean))
# print(
#     "주소 결측:",
#     warehouse_clean["COMPANY_ADDRESS"].isna().sum()
# )
# print(
#     "창고명 결측:",
#     warehouse_clean["COMPANY_NAME"].isna().sum()
# )
# print(
#     "중복 주소 수:",
#     warehouse_clean["COMPANY_ADDRESS"].duplicated().sum()
# )

# print("\n핵심 열 결측:")
# print(
#     warehouse_clean[
#         [
#             "COMPANY_NAME",
#             "COMPANY_ADDRESS",
#             "STORAGE_AREA",
#             "GENERAL_AREA",
#             "FROZEN_AREA"
#         ]
#     ].isna().sum()
# )


# # ---------------------------------------------------------
# # 5. 전처리 파일 저장
# # ---------------------------------------------------------

# save_path = (
#     PROCESSED_DIR /
#     "대전_물류창고_핵심정보_정제.csv"
# )

# warehouse_clean.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)

- 물류창고 43개
- 창고명 및 주소 결측 0, 중복 주소 0
- 면적 관련 변수만 17개 결측

2-5. 물류창고 주소 정제 및 좌표 API 입력정보 준비
- 도로명주소 검색 API로 주소를 표준화
- 좌표 API에 필요한 값을 받은 뒤 좌표 API 호출 구조 준비

In [ ]:
# @title
# # =========================================================
# # 2-5. 물류창고 주소 정제 및 좌표 API 입력정보 준비
# # =========================================================

# from pathlib import Path
# import pandas as pd
# import re

# PROCESSED_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
# )

# warehouse_path = (
#     PROCESSED_DIR /
#     "대전_물류창고_핵심정보_정제.csv"
# )

# warehouse_loc = pd.read_csv(
#     warehouse_path,
#     encoding="utf-8-sig"
# )

# # ---------------------------------------------------------
# # 1. 주소 기본 정제
# # ---------------------------------------------------------

# def clean_address(addr):
#     addr = str(addr).strip()

#     # 연속 공백 정리
#     addr = re.sub(r"\s+", " ", addr)

#     # 괄호 앞뒤 불필요한 공백 정리
#     addr = re.sub(r"\s+\(", " (", addr)

#     return addr


# warehouse_loc["검색주소"] = (
#     warehouse_loc["COMPANY_ADDRESS"]
#     .apply(clean_address)
# )

# # ---------------------------------------------------------
# # 2. API 결과 저장용 열 생성
# # ---------------------------------------------------------

# new_cols = [
#     "도로명주소",
#     "지번주소",
#     "우편번호",
#     "admCd",
#     "rnMgtSn",
#     "udrtYn",
#     "buldMnnm",
#     "buldSlno",
#     "경도",
#     "위도",
#     "주소검색상태"
# ]

# for col in new_cols:
#     warehouse_loc[col] = pd.NA


# # ---------------------------------------------------------
# # 3. 최소 확인
# # ---------------------------------------------------------

# print("전체 창고 수:", len(warehouse_loc))
# print(
#     "검색주소 결측:",
#     warehouse_loc["검색주소"].isna().sum()
# )

# print("\n주소 예시:")
# display(
#     warehouse_loc[
#         ["COMPANY_NAME", "COMPANY_ADDRESS", "검색주소"]
#     ].head()
# )


# # ---------------------------------------------------------
# # 4. 저장
# # ---------------------------------------------------------

# save_path = (
#     PROCESSED_DIR /
#     "대전_물류창고_주소API준비.csv"
# )

# warehouse_loc.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)

- 전체 창고: 43개
- 검색주소 결측: 0개
- 예시 주소들도 도로명주소 형태로 정상
- API 입력용 전처리 파일까지 저장 완료

2-6. 카카오 Local API를 이용한 물류창고 위경도 수집
- 43개 물류창고 주소를 카카오에 보내 창고별 위경도와 표준 도로명 주소 확보

In [ ]:
# @title
# # =========================================================
# # 2-6. 카카오 Local API를 이용한 물류창고 위도·경도 수집
# # =========================================================

# from pathlib import Path
# import pandas as pd
# import requests
# import getpass
# import time
# import re

# PROCESSED_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
# )

# API_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/02_API수집데이터"
# )

# API_DIR.mkdir(parents=True, exist_ok=True)

# # ---------------------------------------------------------
# # 1. 2-5에서 만든 주소 데이터 불러오기
# # ---------------------------------------------------------

# path = PROCESSED_DIR / "대전_물류창고_주소API준비.csv"

# warehouse_loc = pd.read_csv(
#     path,
#     encoding="utf-8-sig"
# )

# # ---------------------------------------------------------
# # 2. Kakao REST API 키 입력
# # ---------------------------------------------------------

# KAKAO_REST_KEY = getpass.getpass(
#     "Kakao REST API 키를 입력하세요: "
# )

# headers = {
#     "Authorization": f"KakaoAK {KAKAO_REST_KEY}"
# }

# url = "https://dapi.kakao.com/v2/local/search/address.json"


# # ---------------------------------------------------------
# # 3. 상세 건물명 등을 제거한 보조 검색주소 생성
# #    예: ", 대한통운 창고동 3층 (읍내동)" 등 제거
# # ---------------------------------------------------------

# def simplify_address(addr):

#     addr = str(addr).strip()

#     # 괄호 이하 제거
#     addr = re.sub(r"\s*\(.*?\)\s*", "", addr)

#     # 쉼표 이후 상세 건물 정보 제거
#     addr = addr.split(",")[0]

#     addr = re.sub(r"\s+", " ", addr).strip()

#     return addr


# warehouse_loc["카카오검색주소"] = (
#     warehouse_loc["검색주소"]
#     .apply(simplify_address)
# )


# # ---------------------------------------------------------
# # 4. 주소 → 위도·경도 변환
# # ---------------------------------------------------------

# results = []

# for idx, row in warehouse_loc.iterrows():

#     query = row["카카오검색주소"]

#     try:

#         response = requests.get(
#             url,
#             headers=headers,
#             params={"query": query},
#             timeout=10
#         )

#         response.raise_for_status()

#         data = response.json()
#         docs = data.get("documents", [])

#         if len(docs) > 0:

#             doc = docs[0]

#             road = doc.get("road_address")
#             jibun = doc.get("address")

#             results.append({
#                 "경도": float(doc["x"]),
#                 "위도": float(doc["y"]),

#                 "카카오_도로명주소":
#                     road.get("address_name")
#                     if road else None,

#                 "카카오_지번주소":
#                     jibun.get("address_name")
#                     if jibun else None,

#                 "카카오_우편번호":
#                     road.get("zone_no")
#                     if road else None,

#                 "좌표검색상태": "성공"
#             })

#         else:

#             results.append({
#                 "경도": None,
#                 "위도": None,
#                 "카카오_도로명주소": None,
#                 "카카오_지번주소": None,
#                 "카카오_우편번호": None,
#                 "좌표검색상태": "검색결과없음"
#             })

#     except Exception as e:

#         results.append({
#             "경도": None,
#             "위도": None,
#             "카카오_도로명주소": None,
#             "카카오_지번주소": None,
#             "카카오_우편번호": None,
#             "좌표검색상태": f"오류: {str(e)[:50]}"
#         })

#     time.sleep(0.05)


# # ---------------------------------------------------------
# # 5. 결과 결합
# # ---------------------------------------------------------

# result_df = pd.DataFrame(results)

# for col in result_df.columns:
#     warehouse_loc[col] = result_df[col]


# # ---------------------------------------------------------
# # 6. 최소 결과 확인
# # ---------------------------------------------------------

# print("[좌표 수집 결과]")

# print(
#     warehouse_loc["좌표검색상태"]
#     .value_counts(dropna=False)
# )

# print(
#     "\n좌표 확보:",
#     warehouse_loc["위도"].notna().sum(),
#     "/",
#     len(warehouse_loc)
# )

# display(
#     warehouse_loc[
#         [
#             "COMPANY_NAME",
#             "카카오검색주소",
#             "카카오_도로명주소",
#             "위도",
#             "경도",
#             "좌표검색상태"
#         ]
#     ]
# )


# # ---------------------------------------------------------
# # 7. Google Drive 저장
# # ---------------------------------------------------------

# save_path = (
#     API_DIR /
#     "대전_물류창고_카카오좌표.csv"
# )

# warehouse_loc.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)

- 43개 중 39개 좌표 혹보(90.7%)
- 4개 검색결과 없음 (아래)
- SK네트웍스(주) 대전지사 - 대덕구 대화동 411번지 3호
- 한국농수산식품유통공사 - 대덕구 와동 115번지 1호
- 한솔로지스틱스(주) 대전센터 - 대덕구 신일동 1674번지 2호
- 대신정기화물(주) - 유성구 대정동 302번지 3호

2-7. 좌표 미확보 4개 물류창고 재검색 및 보완
- 실패한 4곳만 카카오 키워드 검색

In [ ]:
# @title
# # =========================================================
# # 2-7. 좌표 미확보 4개 물류창고 재검색 및 보완
# # =========================================================

# from pathlib import Path
# import pandas as pd
# import requests
# import getpass
# import time

# API_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/02_API수집데이터"
# )

# # ---------------------------------------------------------
# # 1. 2-6 결과 불러오기
# # ---------------------------------------------------------

# path = API_DIR / "대전_물류창고_카카오좌표.csv"

# warehouse_loc = pd.read_csv(
#     path,
#     encoding="utf-8-sig"
# )

# # 좌표가 없는 4개만 선택
# failed = warehouse_loc[
#     warehouse_loc["위도"].isna()
# ].copy()

# print("재검색 대상:", len(failed), "개")


# # ---------------------------------------------------------
# # 2. Kakao REST API 키 입력
# # ---------------------------------------------------------

# KAKAO_REST_KEY = getpass.getpass(
#     "Kakao REST API 키를 입력하세요: "
# )

# headers = {
#     "Authorization": f"KakaoAK {KAKAO_REST_KEY}"
# }

# keyword_url = (
#     "https://dapi.kakao.com/v2/local/search/keyword.json"
# )


# # ---------------------------------------------------------
# # 3. 업체명 + 대전 지역명으로 실패 4개 재검색
# # ---------------------------------------------------------

# for idx, row in failed.iterrows():

#     # 업체명과 원주소를 함께 활용
#     query = f"{row['COMPANY_NAME']} 대전"

#     try:

#         response = requests.get(
#             keyword_url,
#             headers=headers,
#             params={"query": query},
#             timeout=10
#         )

#         response.raise_for_status()

#         docs = response.json().get("documents", [])

#         if len(docs) > 0:

#             # 대전 소재 결과 우선 선택
#             daejeon_docs = [
#                 d for d in docs
#                 if "대전" in (
#                     str(d.get("road_address_name", "")) +
#                     str(d.get("address_name", ""))
#                 )
#             ]

#             doc = (
#                 daejeon_docs[0]
#                 if len(daejeon_docs) > 0
#                 else docs[0]
#             )

#             warehouse_loc.loc[idx, "경도"] = float(doc["x"])
#             warehouse_loc.loc[idx, "위도"] = float(doc["y"])

#             warehouse_loc.loc[
#                 idx, "카카오_도로명주소"
#             ] = doc.get("road_address_name")

#             warehouse_loc.loc[
#                 idx, "카카오_지번주소"
#             ] = doc.get("address_name")

#             warehouse_loc.loc[
#                 idx, "좌표검색상태"
#             ] = "키워드재검색성공"

#         else:

#             warehouse_loc.loc[
#                 idx, "좌표검색상태"
#             ] = "재검색실패"

#     except Exception as e:

#         warehouse_loc.loc[
#             idx, "좌표검색상태"
#         ] = f"재검색오류: {str(e)[:40]}"

#     time.sleep(0.05)


# # ---------------------------------------------------------
# # 4. 결과 확인
# # ---------------------------------------------------------

# print("\n[최종 좌표 확보 상태]")

# print(
#     warehouse_loc["좌표검색상태"]
#     .value_counts(dropna=False)
# )

# print(
#     "\n최종 좌표 확보:",
#     warehouse_loc["위도"].notna().sum(),
#     "/",
#     len(warehouse_loc)
# )

# print("\n재검색 대상 결과:")

# display(
#     warehouse_loc.loc[
#         failed.index,
#         [
#             "COMPANY_NAME",
#             "COMPANY_ADDRESS",
#             "카카오_도로명주소",
#             "카카오_지번주소",
#             "위도",
#             "경도",
#             "좌표검색상태"
#         ]
#     ]
# )


# # ---------------------------------------------------------
# # 5. 최종 좌표 파일 저장
# # ---------------------------------------------------------

# save_path = (
#     API_DIR /
#     "대전_물류창고_카카오좌표_최종.csv"
# )

# warehouse_loc.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)

- 키워드재검색성공으로 나온 결과가 원래 주소와 구 자체 다름
1. 한국농수산식품유통공사
- 원본: 대덕구 와동 115-1
- 검색 결과: 서구 둔산동 942 -> 다른 장소
2. 대신정기화물(주)
- 원본: 유성구 대정동 302-3
- 검색 결과: 대덕구 오정동 343-6 -> 다른 장소

2-8. 미확보 물류창고 지번주소 표준화 및 좌표 재검색
- 2-7 코드는 사용X(폐기)
- 2-6 결과 파일부터 다시 불러옴

In [ ]:
# @title
# # =========================================================
# # 2-8. 미확보 물류창고 지번주소 표준화 및 좌표 재검색
# # =========================================================

# from pathlib import Path
# import pandas as pd
# import requests
# import getpass
# import re
# import time

# API_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/02_API수집데이터"
# )

# # ---------------------------------------------------------
# # 1. 잘못된 키워드 검색 결과가 들어가기 전
# #    2-6 결과부터 다시 불러오기
# # ---------------------------------------------------------

# path = API_DIR / "대전_물류창고_카카오좌표.csv"

# warehouse_loc = pd.read_csv(
#     path,
#     encoding="utf-8-sig"
# )

# failed_idx = warehouse_loc[
#     warehouse_loc["위도"].isna()
# ].index

# print("재처리 대상:", len(failed_idx), "개")


# # ---------------------------------------------------------
# # 2. 지번주소 표준화
# #
# # 예)
# # 411번지 3호  → 411-3
# # 115번지 1호  → 115-1
# # 1691번지     → 1691
# # ---------------------------------------------------------

# def normalize_lot_address(addr):

#     addr = str(addr)

#     # 공백 정리
#     addr = re.sub(r"\s+", " ", addr).strip()

#     # '본번 번지 부번 호' → '본번-부번'
#     addr = re.sub(
#         r"(\d+)\s*번지\s*(\d+)\s*호",
#         r"\1-\2",
#         addr
#     )

#     # '본번번지 부번호' 변형 대응
#     addr = re.sub(
#         r"(\d+)번지\s*(\d+)호",
#         r"\1-\2",
#         addr
#     )

#     # 남은 '번지', '호' 제거
#     addr = re.sub(r"\s*번지", "", addr)
#     addr = re.sub(r"\s*호", "", addr)

#     return re.sub(r"\s+", " ", addr).strip()


# warehouse_loc["지번표준검색주소"] = (
#     warehouse_loc["COMPANY_ADDRESS"]
#     .apply(normalize_lot_address)
# )


# # ---------------------------------------------------------
# # 3. Kakao REST API 키 입력
# # ---------------------------------------------------------

# KAKAO_REST_KEY = getpass.getpass(
#     "Kakao REST API 키를 입력하세요: "
# )

# headers = {
#     "Authorization": f"KakaoAK {KAKAO_REST_KEY}"
# }

# url = "https://dapi.kakao.com/v2/local/search/address.json"


# # ---------------------------------------------------------
# # 4. 실패한 4개만 표준 지번주소로 재검색
# # ---------------------------------------------------------

# for idx in failed_idx:

#     query = warehouse_loc.loc[
#         idx, "지번표준검색주소"
#     ]

#     try:

#         response = requests.get(
#             url,
#             headers=headers,
#             params={
#                 "query": query,
#                 "analyze_type": "similar"
#             },
#             timeout=10
#         )

#         response.raise_for_status()

#         docs = response.json().get(
#             "documents", []
#         )

#         if docs:

#             doc = docs[0]

#             road = doc.get("road_address")
#             jibun = doc.get("address")

#             warehouse_loc.loc[
#                 idx, "경도"
#             ] = float(doc["x"])

#             warehouse_loc.loc[
#                 idx, "위도"
#             ] = float(doc["y"])

#             warehouse_loc.loc[
#                 idx, "카카오_도로명주소"
#             ] = (
#                 road.get("address_name")
#                 if road else None
#             )

#             warehouse_loc.loc[
#                 idx, "카카오_지번주소"
#             ] = (
#                 jibun.get("address_name")
#                 if jibun else None
#             )

#             warehouse_loc.loc[
#                 idx, "좌표검색상태"
#             ] = "지번표준화재검색성공"

#         else:

#             warehouse_loc.loc[
#                 idx, "좌표검색상태"
#             ] = "지번표준화재검색실패"

#     except Exception as e:

#         warehouse_loc.loc[
#             idx, "좌표검색상태"
#         ] = f"재검색오류: {str(e)[:40]}"

#     time.sleep(0.05)


# # ---------------------------------------------------------
# # 5. 결과 확인
# # ---------------------------------------------------------

# print("\n최종 좌표 확보:",
#       warehouse_loc["위도"].notna().sum(),
#       "/",
#       len(warehouse_loc))

# print("\n재처리 결과:")

# display(
#     warehouse_loc.loc[
#         failed_idx,
#         [
#             "COMPANY_NAME",
#             "COMPANY_ADDRESS",
#             "지번표준검색주소",
#             "카카오_도로명주소",
#             "카카오_지번주소",
#             "위도",
#             "경도",
#             "좌표검색상태"
#         ]
#     ]
# )


# # ---------------------------------------------------------
# # 6. 저장
# # ---------------------------------------------------------

# save_path = (
#     API_DIR /
#     "대전_물류창고_카카오좌표_최종.csv"
# )

# warehouse_loc.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)

- 최종 좌표 확보: 43/43
- 처음 실패했던 4곳 지번 표준화 후 전부 정상 조회
- 원본 행정구와 재검색된 지번 주소 일치
- 최종 좌표 파일 Drive 저장 완료

2-9. 물류창고 위경도를 기상청 격자좌표 변환

In [ ]:
# @title
# # =========================================================
# # 2-9. 물류창고 위도·경도를 기상청 격자좌표(nx, ny)로 변환
# # =========================================================

# from pathlib import Path
# import pandas as pd
# import math

# API_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/02_API수집데이터"
# )

# PROCESSED_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
# )

# # ---------------------------------------------------------
# # 1. 2-8 최종 좌표 파일 불러오기
# # ---------------------------------------------------------

# path = API_DIR / "대전_물류창고_카카오좌표_최종.csv"

# warehouse = pd.read_csv(
#     path,
#     encoding="utf-8-sig"
# )


# # ---------------------------------------------------------
# # 2. 위도·경도 → 기상청 격자(nx, ny) 변환 함수
# #    기상청 단기예보 격자체계(Lambert Conformal Conic)
# # ---------------------------------------------------------

# def latlon_to_grid(lat, lon):

#     RE = 6371.00877      # 지구 반경(km)
#     GRID = 5.0           # 격자 간격(km)

#     SLAT1 = 30.0
#     SLAT2 = 60.0

#     OLON = 126.0
#     OLAT = 38.0

#     XO = 43
#     YO = 136

#     DEGRAD = math.pi / 180.0

#     re = RE / GRID
#     slat1 = SLAT1 * DEGRAD
#     slat2 = SLAT2 * DEGRAD
#     olon = OLON * DEGRAD
#     olat = OLAT * DEGRAD

#     sn = math.tan(
#         math.pi * 0.25 + slat2 * 0.5
#     ) / math.tan(
#         math.pi * 0.25 + slat1 * 0.5
#     )

#     sn = math.log(
#         math.cos(slat1) / math.cos(slat2)
#     ) / math.log(sn)

#     sf = math.tan(
#         math.pi * 0.25 + slat1 * 0.5
#     )

#     sf = (
#         math.pow(sf, sn)
#         * math.cos(slat1)
#         / sn
#     )

#     ro = math.tan(
#         math.pi * 0.25 + olat * 0.5
#     )

#     ro = (
#         re * sf
#         / math.pow(ro, sn)
#     )

#     ra = math.tan(
#         math.pi * 0.25 + lat * DEGRAD * 0.5
#     )

#     ra = (
#         re * sf
#         / math.pow(ra, sn)
#     )

#     theta = lon * DEGRAD - olon

#     if theta > math.pi:
#         theta -= 2.0 * math.pi

#     if theta < -math.pi:
#         theta += 2.0 * math.pi

#     theta *= sn

#     nx = int(
#         math.floor(
#             ra * math.sin(theta)
#             + XO
#             + 0.5
#         )
#     )

#     ny = int(
#         math.floor(
#             ro
#             - ra * math.cos(theta)
#             + YO
#             + 0.5
#         )
#     )

#     return nx, ny


# # ---------------------------------------------------------
# # 3. 43개 창고에 격자좌표 적용
# # ---------------------------------------------------------

# grid = warehouse.apply(
#     lambda row: latlon_to_grid(
#         row["위도"],
#         row["경도"]
#     ),
#     axis=1
# )

# warehouse["nx"] = [
#     x[0] for x in grid
# ]

# warehouse["ny"] = [
#     x[1] for x in grid
# ]


# # ---------------------------------------------------------
# # 4. 최소 검수
# # ---------------------------------------------------------

# print("[기상청 격자 변환 결과]")

# print("전체 창고:", len(warehouse))

# print(
#     "격자 결측:",
#     warehouse[["nx", "ny"]]
#     .isna()
#     .any(axis=1)
#     .sum()
# )

# print(
#     "고유 격자 수:",
#     warehouse[
#         ["nx", "ny"]
#     ]
#     .drop_duplicates()
#     .shape[0]
# )

# print("\n격자별 창고 수:")

# display(
#     warehouse
#     .groupby(["nx", "ny"])
#     .size()
#     .reset_index(name="창고수")
#     .sort_values(
#         "창고수",
#         ascending=False
#     )
# )

# print("\n창고별 좌표 예시:")

# display(
#     warehouse[
#         [
#             "COMPANY_NAME",
#             "위도",
#             "경도",
#             "nx",
#             "ny"
#         ]
#     ].head(10)
# )


# # ---------------------------------------------------------
# # 5. 전처리 데이터로 저장
# # ---------------------------------------------------------

# save_path = (
#     PROCESSED_DIR /
#     "대전_물류창고_좌표_기상청격자.csv"
# )

# warehouse.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)

- 43곳 전부 격자 결측 0
- 실제 필요한 기상청 고유 격자 11개
- 따라서 앞으로 단기예보 API를 43번 호출할 필요 없이 11개 격자만 조회

2-10 기상청 단기예보 API로 11개 고유 격자 예보 수집
- 격자별 예보를 조회하는 구조
- 현재 2026년 7월 9일 기준으로 갱신
- TMP(기온), REH(습도) 우선 수집

In [ ]:
# @title
# # =========================================================
# # 2-10. 기상청 단기예보 API로 11개 고유 격자 예보 수집
# # =========================================================

# from pathlib import Path
# import pandas as pd
# import requests
# import getpass
# from datetime import datetime, timedelta
# import time

# PROCESSED_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
# )

# API_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/02_API수집데이터"
# )

# # ---------------------------------------------------------
# # 1. 창고별 기상청 격자 파일 불러오기
# # ---------------------------------------------------------

# path = (
#     PROCESSED_DIR /
#     "대전_물류창고_좌표_기상청격자.csv"
# )

# warehouse = pd.read_csv(
#     path,
#     encoding="utf-8-sig"
# )

# # 중복 격자 제거 → 실제 조회 대상 11개
# grids = (
#     warehouse[["nx", "ny"]]
#     .drop_duplicates()
#     .reset_index(drop=True)
# )

# print("API 조회 대상 고유 격자:", len(grids), "개")


# # ---------------------------------------------------------
# # 2. 공공데이터포털 인증키 입력
# # ---------------------------------------------------------

# SERVICE_KEY = getpass.getpass(
#     "기상청 단기예보 API 인증키를 입력하세요: "
# )


# # ---------------------------------------------------------
# # 3. 가장 최근 사용 가능한 단기예보 발표시각 결정
# #
# # 단기예보 발표시각:
# # 02, 05, 08, 11, 14, 17, 20, 23시
# #
# # API 반영 지연을 고려해 현재시각보다 약간 이전 회차 사용
# # ---------------------------------------------------------

# now = datetime.now()

# base_hours = [2, 5, 8, 11, 14, 17, 20, 23]

# candidate = None

# for h in reversed(base_hours):

#     dt = now.replace(
#         hour=h,
#         minute=0,
#         second=0,
#         microsecond=0
#     )

#     # 발표 직후 API 반영 지연 고려
#     if dt <= now - timedelta(minutes=15):
#         candidate = dt
#         break

# # 오늘 회차가 아직 없으면 전날 23시
# if candidate is None:
#     yesterday = now - timedelta(days=1)

#     candidate = yesterday.replace(
#         hour=23,
#         minute=0,
#         second=0,
#         microsecond=0
#     )

# base_date = candidate.strftime("%Y%m%d")
# base_time = candidate.strftime("%H00")

# print("사용 발표일자:", base_date)
# print("사용 발표시각:", base_time)


# # ---------------------------------------------------------
# # 4. 기상청 단기예보 API 호출
# # ---------------------------------------------------------

# url = (
#     "https://apis.data.go.kr/1360000/"
#     "VilageFcstInfoService_2.0/getVilageFcst"
# )

# all_rows = []

# for i, row in grids.iterrows():

#     nx = int(row["nx"])
#     ny = int(row["ny"])

#     params = {
#         "serviceKey": SERVICE_KEY,
#         "pageNo": 1,
#         "numOfRows": 1000,
#         "dataType": "JSON",
#         "base_date": base_date,
#         "base_time": base_time,
#         "nx": nx,
#         "ny": ny
#     }

#     try:

#         response = requests.get(
#             url,
#             params=params,
#             timeout=20
#         )

#         response.raise_for_status()

#         data = response.json()

#         header = (
#             data
#             .get("response", {})
#             .get("header", {})
#         )

#         result_code = header.get("resultCode")
#         result_msg = header.get("resultMsg")

#         if result_code != "00":

#             print(
#                 f"[실패] ({nx},{ny}) "
#                 f"{result_code} / {result_msg}"
#             )

#             continue

#         items = (
#             data["response"]["body"]
#             ["items"]["item"]
#         )

#         for item in items:

#             # 체감온도 계산에 필요한
#             # 기온(TMP), 습도(REH)만 저장
#             if item["category"] in ["TMP", "REH"]:

#                 all_rows.append({
#                     "nx": nx,
#                     "ny": ny,
#                     "baseDate": item["baseDate"],
#                     "baseTime": item["baseTime"],
#                     "fcstDate": item["fcstDate"],
#                     "fcstTime": item["fcstTime"],
#                     "category": item["category"],
#                     "fcstValue": item["fcstValue"]
#                 })

#         print(
#             f"[{i+1}/{len(grids)}] "
#             f"격자 ({nx},{ny}) 수집 완료"
#         )

#     except Exception as e:

#         print(
#             f"[오류] ({nx},{ny}) : {e}"
#         )

#     time.sleep(0.1)


# # ---------------------------------------------------------
# # 5. 데이터프레임 생성
# # ---------------------------------------------------------

# forecast_long = pd.DataFrame(all_rows)

# forecast_long["fcstValue"] = pd.to_numeric(
#     forecast_long["fcstValue"],
#     errors="coerce"
# )


# # ---------------------------------------------------------
# # 6. TMP / REH를 한 행으로 변환
# # ---------------------------------------------------------

# forecast = (
#     forecast_long
#     .pivot_table(
#         index=[
#             "nx",
#             "ny",
#             "baseDate",
#             "baseTime",
#             "fcstDate",
#             "fcstTime"
#         ],
#         columns="category",
#         values="fcstValue",
#         aggfunc="first"
#     )
#     .reset_index()
# )

# forecast.columns.name = None


# # ---------------------------------------------------------
# # 7. 최소 검수
# # ---------------------------------------------------------

# print("\n[단기예보 수집 결과]")

# print("수집 행 수:", len(forecast))

# print(
#     "수집 격자 수:",
#     forecast[["nx", "ny"]]
#     .drop_duplicates()
#     .shape[0]
# )

# print(
#     "TMP 결측:",
#     forecast["TMP"].isna().sum()
# )

# print(
#     "REH 결측:",
#     forecast["REH"].isna().sum()
# )

# print(
#     "예보 기간:",
#     forecast["fcstDate"].min(),
#     "~",
#     forecast["fcstDate"].max()
# )

# display(
#     forecast.head(10)
# )


# # ---------------------------------------------------------
# # 8. 저장
# # ---------------------------------------------------------

# save_path = (
#     API_DIR /
#     f"기상청_단기예보_11개격자_{base_date}_{base_time}.csv"
# )

# forecast.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)

- API 인증키 호출 문제
- 2-10 코드 사용X(폐기)
- 2-11 코드로 수정

2-11. 기상청 API허브 기반 단기예보 격자자료 수집

In [ ]:
# @title
# # =========================================================
# # 2-11. 기상청 API허브 기반 단기예보 격자자료 수집
# # =========================================================

# from pathlib import Path
# import pandas as pd
# import numpy as np
# import requests
# import getpass
# from datetime import datetime, timedelta
# import time

# PROCESSED_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
# )

# API_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/02_API수집데이터"
# )

# # ---------------------------------------------------------
# # 1. 43개 창고의 기상청 격자정보 불러오기
# # ---------------------------------------------------------

# path = (
#     PROCESSED_DIR /
#     "대전_물류창고_좌표_기상청격자.csv"
# )

# warehouse = pd.read_csv(
#     path,
#     encoding="utf-8-sig"
# )

# grids = (
#     warehouse[["nx", "ny"]]
#     .drop_duplicates()
#     .reset_index(drop=True)
# )

# print("조회 대상 고유 격자:", len(grids), "개")


# # ---------------------------------------------------------
# # 2. 기상청 API허브 인증키 입력
# # ---------------------------------------------------------

# AUTH_KEY = getpass.getpass(
#     "기상청 API허브 인증키를 입력하세요: "
# )


# # ---------------------------------------------------------
# # 3. 가장 최근 사용 가능한 발표시각 결정
# #    단기예보: 02,05,08,11,14,17,20,23시
# # ---------------------------------------------------------

# now = datetime.now()

# base_hours = [2, 5, 8, 11, 14, 17, 20, 23]

# tmfc_dt = None

# for h in reversed(base_hours):

#     candidate = now.replace(
#         hour=h,
#         minute=0,
#         second=0,
#         microsecond=0
#     )

#     # 발표 직후 자료 생성 지연 고려
#     if candidate <= now - timedelta(minutes=20):
#         tmfc_dt = candidate
#         break

# if tmfc_dt is None:

#     tmfc_dt = (
#         now - timedelta(days=1)
#     ).replace(
#         hour=23,
#         minute=0,
#         second=0,
#         microsecond=0
#     )

# tmfc = tmfc_dt.strftime("%Y%m%d%H")

# print("사용 발표시간:", tmfc)


# # ---------------------------------------------------------
# # 4. 예보시간 생성
# #
# # 02~14시 발표 : 글피 자정까지
# # 17~23시 발표 : 그글피 자정까지
# # ---------------------------------------------------------

# if tmfc_dt.hour in [17, 20, 23]:
#     end_dt = (
#         tmfc_dt.replace(
#             hour=0,
#             minute=0
#         )
#         + timedelta(days=4)
#     )
# else:
#     end_dt = (
#         tmfc_dt.replace(
#             hour=0,
#             minute=0
#         )
#         + timedelta(days=3)
#     )

# # 발표 이후 첫 정시부터
# start_dt = (
#     tmfc_dt.replace(
#         minute=0,
#         second=0,
#         microsecond=0
#     )
#     + timedelta(hours=1)
# )

# forecast_times = []

# t = start_dt

# while t <= end_dt:

#     forecast_times.append(t)

#     # 공식 서비스 구조:
#     # 앞부분은 1시간 간격,
#     # 연장 예보기간은 3시간 간격으로 제공될 수 있으므로
#     # 우선 시간별 요청 후 없는 시각은 자동 제외
#     t += timedelta(hours=1)

# print(
#     "요청 예보시간:",
#     forecast_times[0].strftime("%Y-%m-%d %H:%M"),
#     "~",
#     forecast_times[-1].strftime("%Y-%m-%d %H:%M")
# )


# # ---------------------------------------------------------
# # 5. API 설정
# # ---------------------------------------------------------

# url = (
#     "https://apihub.kma.go.kr/api/typ01/"
#     "cgi-bin/url/nph-dfs_shrt_grd"
# )

# NX_FULL = 149
# NY_FULL = 253

# all_rows = []


# # ---------------------------------------------------------
# # 6. TMP / REH 전국 격자자료 호출 후
# #    필요한 11개 격자만 추출
# # ---------------------------------------------------------

# for n, fcst_dt in enumerate(forecast_times, start=1):

#     tmef = fcst_dt.strftime("%Y%m%d%H")

#     values_this_time = {}

#     for var in ["TMP", "REH"]:

#         try:

#             response = requests.get(
#                 url,
#                 params={
#                     "tmfc": tmfc,
#                     "tmef": tmef,
#                     "vars": var,
#                     "authKey": AUTH_KEY
#                 },
#                 timeout=30
#             )

#             if response.status_code != 200:
#                 print(
#                     f"[HTTP 오류] {tmef} {var} : "
#                     f"{response.status_code}"
#                 )
#                 continue

#             # 전국 격자자료 → 숫자 배열
#             arr = np.fromstring(
#                 response.text,
#                 dtype=np.float32,
#                 sep=","
#             )

#             # 정상 자료는 149 × 253 = 37,697개
#             if arr.size != NX_FULL * NY_FULL:

#                 # 자료가 없는 시각은 조용히 제외
#                 continue

#             arr = arr.reshape(
#                 NY_FULL,
#                 NX_FULL
#             )

#             values_this_time[var] = arr

#         except Exception as e:

#             print(
#                 f"[오류] {tmef} {var} : "
#                 f"{str(e)[:80]}"
#             )

#     # TMP와 REH가 모두 확보된 시각만 저장
#     if (
#         "TMP" not in values_this_time
#         or "REH" not in values_this_time
#     ):
#         continue

#     tmp_arr = values_this_time["TMP"]
#     reh_arr = values_this_time["REH"]

#     for _, g in grids.iterrows():

#         nx = int(g["nx"])
#         ny = int(g["ny"])

#         # 기상청 격자번호는 1부터 시작하므로
#         # numpy 배열에서는 -1 처리
#         tmp = tmp_arr[ny - 1, nx - 1]
#         reh = reh_arr[ny - 1, nx - 1]

#         # 비관측/결측값 처리
#         if tmp <= -99:
#             tmp = np.nan

#         if reh <= -99:
#             reh = np.nan

#         all_rows.append({
#             "발표시간": tmfc,
#             "예보일자": fcst_dt.strftime("%Y%m%d"),
#             "예보시각": fcst_dt.strftime("%H00"),
#             "nx": nx,
#             "ny": ny,
#             "TMP": float(tmp) if not np.isnan(tmp) else np.nan,
#             "REH": float(reh) if not np.isnan(reh) else np.nan
#         })

#     if n % 10 == 0 or n == len(forecast_times):
#         print(
#             f"[진행] {n}/{len(forecast_times)} 예보시각 처리"
#         )

#     time.sleep(0.03)


# # ---------------------------------------------------------
# # 7. 결과 데이터프레임 생성
# # ---------------------------------------------------------

# forecast = pd.DataFrame(all_rows)

# if forecast.empty:

#     raise RuntimeError(
#         "수집된 단기예보 자료가 없습니다. "
#         "API 인증키 또는 발표/예보시각을 확인하세요."
#     )


# # ---------------------------------------------------------
# # 8. 최소 검수
# # ---------------------------------------------------------

# print("\n[단기예보 수집 결과]")

# print("수집 행 수:", len(forecast))

# print(
#     "수집 격자 수:",
#     forecast[["nx", "ny"]]
#     .drop_duplicates()
#     .shape[0]
# )

# print(
#     "TMP 결측:",
#     forecast["TMP"].isna().sum()
# )

# print(
#     "REH 결측:",
#     forecast["REH"].isna().sum()
# )

# print(
#     "예보 기간:",
#     forecast["예보일자"].min(),
#     "~",
#     forecast["예보일자"].max()
# )

# print(
#     "고유 예보시각 수:",
#     forecast[
#         ["예보일자", "예보시각"]
#     ]
#     .drop_duplicates()
#     .shape[0]
# )

# display(
#     forecast.head(10)
# )


# # ---------------------------------------------------------
# # 9. 저장
# # ---------------------------------------------------------

# save_path = (
#     API_DIR /
#     f"기상청_API허브_단기예보_11개격자_{tmfc}.csv"
# )

# forecast.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)

- 응답 처리 방식 오류
- 2-11 코드 사용X(폐기)
- 2-12 코드로 수정

2-12. 기상청 API허브 단기예보 응답 파싱 수정
- 전체를 100번 넘게 호출 X
- 가장 가까운 예보시각 1개에서 TMP(기온)와 REH(습도)가 정상 수신되는지 먼저 확인

In [ ]:
# @title
# # =========================================================
# # 2-12. 기상청 API허브 단기예보 응답 파싱 수정
# #       - 예보시각 1개 TMP / REH 정상 수신 확인
# # =========================================================

# import requests
# import numpy as np
# import getpass
# from datetime import datetime, timedelta

# # ---------------------------------------------------------
# # 1. API 인증키 입력
# # ---------------------------------------------------------

# AUTH_KEY = getpass.getpass(
#     "기상청 API허브 인증키를 입력하세요: "
# )

# url = (
#     "https://apihub.kma.go.kr/api/typ01/"
#     "cgi-bin/url/nph-dfs_shrt_grd"
# )

# # ---------------------------------------------------------
# # 2. 최근 단기예보 발표시간 계산
# # ---------------------------------------------------------

# now = datetime.now()

# base_hours = [2, 5, 8, 11, 14, 17, 20, 23]

# tmfc_dt = None

# for h in reversed(base_hours):

#     candidate = now.replace(
#         hour=h,
#         minute=0,
#         second=0,
#         microsecond=0
#     )

#     if candidate <= now - timedelta(minutes=20):
#         tmfc_dt = candidate
#         break

# if tmfc_dt is None:

#     tmfc_dt = (
#         now - timedelta(days=1)
#     ).replace(
#         hour=23,
#         minute=0,
#         second=0,
#         microsecond=0
#     )

# tmfc = tmfc_dt.strftime("%Y%m%d%H")

# # 가장 가까운 미래 1시간 예보
# tmef_dt = tmfc_dt + timedelta(hours=1)
# tmef = tmef_dt.strftime("%Y%m%d%H")

# print("발표시간:", tmfc)
# print("시험 예보시간:", tmef)


# # ---------------------------------------------------------
# # 3. TMP / REH 각각 1회 호출
# # ---------------------------------------------------------

# results = {}

# for var in ["TMP", "REH"]:

#     response = requests.get(
#         url,
#         params={
#             "tmfc": tmfc,
#             "tmef": tmef,
#             "vars": var,
#             "authKey": AUTH_KEY
#         },
#         timeout=30
#     )

#     print(f"\n[{var}] HTTP 상태:", response.status_code)

#     if response.status_code != 200:
#         print(
#             "응답 내용:",
#             response.content.decode(
#                 "utf-8",
#                 errors="replace"
#             )[:300]
#         )
#         continue

#     # 공식 기상청 예제 방식:
#     # response.content를 직접 숫자 배열로 변환
#     arr = np.fromstring(
#         string=response.content,
#         dtype=np.float32,
#         count=253 * 149,
#         sep=","
#     )

#     print("읽힌 격자값 수:", arr.size)

#     if arr.size != 253 * 149:
#         print(
#             "정상 격자수(37697개)가 아닙니다."
#         )
#         print(
#             "응답 앞부분:",
#             response.content.decode(
#                 "utf-8",
#                 errors="replace"
#             )[:300]
#         )
#         continue

#     arr = arr.reshape(253, 149)

#     results[var] = arr

#     print(
#         "최소값:",
#         np.nanmin(arr),
#         "/ 최대값:",
#         np.nanmax(arr)
#     )


# # ---------------------------------------------------------
# # 4. 실제 대전 격자 한 곳 값 확인
# #    2-9에서 확인된 격자 중 하나 사용
# # ---------------------------------------------------------

# if "TMP" in results and "REH" in results:

#     test_nx = 68
#     test_ny = 101

#     tmp = results["TMP"][
#         test_ny - 1,
#         test_nx - 1
#     ]

#     reh = results["REH"][
#         test_ny - 1,
#         test_nx - 1
#     ]

#     print("\n[대전 시험 격자]")
#     print("격자:", test_nx, test_ny)
#     print("TMP:", tmp, "℃")
#     print("REH:", reh, "%")

#     print("\n✅ 단기예보 API 정상 수신")

# else:

#     print("\n❌ 단기예보 응답 확인 필요")

- TMP(기온) 응답: 37,607개 격자 정상
- REH(습도) 응답: 37,607개 격자 정상
- 대전 테스트 격자(68, 101)에서 30.0℃ / 75% 정상 추출
- 인증키, 발표시간, 인덱싱 방식까지 모두 확인

2-13. 11개 물류창고 격자의 전체 단기예보 수집
- TMP(기온), REH(습도)를 전체 예보기간에 대해 수집
- 전국 자료에서 필요한 11개 격자만 추출하여 Drive 저장

In [ ]:
# =========================================================
# 2-13. 11개 물류창고 격자의 전체 단기예보 수집
# =========================================================

from pathlib import Path
import pandas as pd
import numpy as np
import requests
import getpass
from datetime import datetime, timedelta
import time

# ---------------------------------------------------------
# 1. 폴더 및 격자정보 불러오기
# ---------------------------------------------------------

PROCESSED_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
)

API_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도/02_API수집데이터"
)

warehouse = pd.read_csv(
    PROCESSED_DIR / "대전_물류창고_좌표_기상청격자.csv",
    encoding="utf-8-sig"
)

grids = (
    warehouse[["nx", "ny"]]
    .drop_duplicates()
    .sort_values(["nx", "ny"])
    .reset_index(drop=True)
)

print("조회 대상 고유 격자:", len(grids), "개")


# ---------------------------------------------------------
# 2. 기상청 API허브 인증키
# ---------------------------------------------------------

AUTH_KEY = getpass.getpass(
    "기상청 API허브 인증키를 입력하세요: "
)

url = (
    "https://apihub.kma.go.kr/api/typ01/"
    "cgi-bin/url/nph-dfs_shrt_grd"
)


# ---------------------------------------------------------
# 3. 최근 사용 가능한 단기예보 발표시간 결정
# ---------------------------------------------------------

now = datetime.now()

base_hours = [2, 5, 8, 11, 14, 17, 20, 23]

tmfc_dt = None

for h in reversed(base_hours):

    candidate = now.replace(
        hour=h,
        minute=0,
        second=0,
        microsecond=0
    )

    # 자료 생성 지연 고려
    if candidate <= now - timedelta(minutes=20):
        tmfc_dt = candidate
        break

if tmfc_dt is None:

    tmfc_dt = (
        now - timedelta(days=1)
    ).replace(
        hour=23,
        minute=0,
        second=0,
        microsecond=0
    )

tmfc = tmfc_dt.strftime("%Y%m%d%H")

print("사용 발표시간:", tmfc)


# ---------------------------------------------------------
# 4. 전체 예보시간 생성
# ---------------------------------------------------------

# 02~14시 발표 → 글피 00시까지
# 17~23시 발표 → 그글피 00시까지

if tmfc_dt.hour in [17, 20, 23]:

    end_dt = (
        tmfc_dt.replace(
            hour=0,
            minute=0,
            second=0,
            microsecond=0
        )
        + timedelta(days=4)
    )

else:

    end_dt = (
        tmfc_dt.replace(
            hour=0,
            minute=0,
            second=0,
            microsecond=0
        )
        + timedelta(days=3)
    )

start_dt = (
    tmfc_dt + timedelta(hours=1)
).replace(
    minute=0,
    second=0,
    microsecond=0
)

forecast_times = pd.date_range(
    start=start_dt,
    end=end_dt,
    freq="h"
).to_pydatetime().tolist()

print(
    "예보 수집기간:",
    forecast_times[0].strftime("%Y-%m-%d %H:%M"),
    "~",
    forecast_times[-1].strftime("%Y-%m-%d %H:%M")
)

print(
    "예보시각 수:",
    len(forecast_times)
)


# ---------------------------------------------------------
# 5. TMP / REH 전체 예보 수집
# ---------------------------------------------------------

NX_FULL = 149
NY_FULL = 253
GRID_SIZE = NX_FULL * NY_FULL

all_rows = []

successful_times = 0
failed_times = []

for n, fcst_dt in enumerate(
    forecast_times,
    start=1
):

    tmef = fcst_dt.strftime("%Y%m%d%H")

    arrays = {}

    # TMP와 REH 각각 수집
    for var in ["TMP", "REH"]:

        try:

            response = requests.get(
                url,
                params={
                    "tmfc": tmfc,
                    "tmef": tmef,
                    "vars": var,
                    "authKey": AUTH_KEY
                },
                timeout=30
            )

            if response.status_code != 200:
                continue

            # 2-12에서 검증한 공식 파싱 방식
            arr = np.fromstring(
                string=response.content,
                dtype=np.float32,
                count=GRID_SIZE,
                sep=","
            )

            if arr.size != GRID_SIZE:
                continue

            arrays[var] = arr.reshape(
                NY_FULL,
                NX_FULL
            )

        except Exception:
            continue


    # TMP와 REH가 모두 있는 시각만 채택
    if (
        "TMP" not in arrays
        or "REH" not in arrays
    ):

        failed_times.append(tmef)
        continue


    # -----------------------------------------------------
    # 필요한 11개 격자만 추출
    # -----------------------------------------------------

    for _, g in grids.iterrows():

        nx = int(g["nx"])
        ny = int(g["ny"])

        tmp = float(
            arrays["TMP"][ny - 1, nx - 1]
        )

        reh = float(
            arrays["REH"][ny - 1, nx - 1]
        )

        # 기상청 결측값 처리
        if tmp <= -99:
            tmp = np.nan

        if reh <= -99:
            reh = np.nan

        all_rows.append({
            "발표시간": tmfc,
            "예보일자": fcst_dt.strftime("%Y%m%d"),
            "예보시각": fcst_dt.strftime("%H00"),
            "예보일시": fcst_dt,
            "nx": nx,
            "ny": ny,
            "TMP": tmp,
            "REH": reh
        })

    successful_times += 1


    # -----------------------------------------------------
    # 진행률 표시
    # -----------------------------------------------------

    if (
        n % 10 == 0
        or n == len(forecast_times)
    ):

        print(
            f"[진행] {n}/{len(forecast_times)} "
            f"예보시각 처리"
        )

    time.sleep(0.03)


# ---------------------------------------------------------
# 6. 데이터프레임 생성
# ---------------------------------------------------------

forecast = pd.DataFrame(all_rows)

if forecast.empty:

    raise RuntimeError(
        "단기예보 자료가 수집되지 않았습니다."
    )


# ---------------------------------------------------------
# 7. 최소 검수
# ---------------------------------------------------------

print("\n[단기예보 최종 수집 결과]")

print(
    "정상 수집 예보시각:",
    successful_times,
    "/",
    len(forecast_times)
)

print(
    "수집 행 수:",
    len(forecast)
)

print(
    "수집 격자 수:",
    forecast[["nx", "ny"]]
    .drop_duplicates()
    .shape[0]
)

print(
    "TMP 결측:",
    forecast["TMP"].isna().sum()
)

print(
    "REH 결측:",
    forecast["REH"].isna().sum()
)

print(
    "중복:",
    forecast.duplicated(
        subset=["예보일시", "nx", "ny"]
    ).sum()
)

print(
    "예보기간:",
    forecast["예보일시"].min(),
    "~",
    forecast["예보일시"].max()
)

if failed_times:
    print(
        "\n수집 실패 예보시각 수:",
        len(failed_times)
    )
    print(
        "실패 시각:",
        failed_times
    )
else:
    print(
        "\n모든 예보시각 정상 수집"
    )


display(
    forecast.head(10)
)


# ---------------------------------------------------------
# 8. Google Drive 저장
# ---------------------------------------------------------

save_path = (
    API_DIR /
    f"기상청_API허브_단기예보_11개격자_{tmfc}.csv"
)

forecast.to_csv(
    save_path,
    index=False,
    encoding="utf-8-sig"
)

print("\n저장 완료:")
print(save_path)

조회 대상 고유 격자: 11 개
기상청 API허브 인증키를 입력하세요: ··········
사용 발표시간: 2026072908
예보 수집기간: 2026-07-29 09:00 ~ 2026-08-01 00:00
예보시각 수: 64
[진행] 10/64 예보시각 처리
[진행] 20/64 예보시각 처리
[진행] 30/64 예보시각 처리
[진행] 40/64 예보시각 처리
[진행] 50/64 예보시각 처리
[진행] 60/64 예보시각 처리
[진행] 64/64 예보시각 처리

[단기예보 최종 수집 결과]
정상 수집 예보시각: 64 / 64
수집 행 수: 704
수집 격자 수: 11
TMP 결측: 0
REH 결측: 0
중복: 0
예보기간: 2026-07-29 09:00:00 ~ 2026-08-01 00:00:00

모든 예보시각 정상 수집

         발표시간      예보일자  예보시각                예보일시  nx   ny   TMP   REH
0  2026072908  20260729  0900 2026-07-29 09:00:00  66  100  27.0  90.0
1  2026072908  20260729  0900 2026-07-29 09:00:00  67   99  27.0  85.0
2  2026072908  20260729  0900 2026-07-29 09:00:00  67  100  27.0  85.0
3  2026072908  20260729  0900 2026-07-29 09:00:00  67  102  27.0  90.0
4  2026072908  20260729  0900 2026-07-29 09:00:00  67  103  28.0  90.0
5  2026072908  20260729  0900 2026-07-29 09:00:00  68   98  26.0  90.0
6  2026072908  20260729  0900 2026-07-29 09:00:00  68  100  28.0  85.0
7  2026072908  20260729  0900 2026-07-29 09:00:00  68  101  27.0  85.0
8  2026072908  20260729  0900 2026-07-29 09:00:00  68  102  27.0  85.0
9  2026072908  20260729  0900 2026-07-29 09:00:00  68  103  28.0  85.0

저장 완료:
/content/drive/MyDrive/대전_물류창고_폭염위험도/02_API수집데이터/기상청_API허브_단기예보_11개격자_2026072908.csv

- 43개 창고가 속한 11개 기상청 격자의 시간별 기온, 습도 예보 확보

2-14. 단기예보를 43개 물류창고에 연결
- 11개 격자 예보를 nx, ny 기준으로 43개 창고에 붙여 창고 x 시간 단위 데이터 생성

In [ ]:
# =========================================================
# 2-14. 단기예보를 43개 물류창고에 연결 - 수정
#       최신파일 자동탐색 대신 2-13 확정 파일 직접 사용
# =========================================================

from pathlib import Path
import pandas as pd

PROCESSED_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
)

API_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도/02_API수집데이터"
)

# ---------------------------------------------------------
# 1. 43개 창고 + 기상청 격자정보 불러오기
# ---------------------------------------------------------

warehouse_path = (
    PROCESSED_DIR /
    "대전_물류창고_좌표_기상청격자.csv"
)

warehouse = pd.read_csv(
    warehouse_path,
    encoding="utf-8-sig"
)


# ---------------------------------------------------------
# 2. 2-13에서 정상 수집·저장된 단기예보 파일 직접 불러오기
# ---------------------------------------------------------

forecast_path = (
    API_DIR /
    "기상청_API허브_단기예보_11개격자_2026072811.csv"
)

if not forecast_path.exists():
    raise FileNotFoundError(
        f"파일이 없습니다:\n{forecast_path}"
    )

forecast = pd.read_csv(
    forecast_path,
    encoding="utf-8-sig"
)

forecast["예보일시"] = pd.to_datetime(
    forecast["예보일시"]
)

print("사용 단기예보 파일:")
print(forecast_path.name)


# ---------------------------------------------------------
# 3. nx, ny 기준으로
#    11개 격자 예보 → 43개 개별 창고에 연결
# ---------------------------------------------------------

warehouse_forecast = warehouse.merge(
    forecast,
    on=["nx", "ny"],
    how="left"
)


# ---------------------------------------------------------
# 4. 최소 검수
# ---------------------------------------------------------

print("\n[창고별 단기예보 연결 결과]")

print(
    "창고 수:",
    warehouse_forecast["WARE_NO"].nunique()
)

print(
    "전체 행 수:",
    len(warehouse_forecast)
)

expected_rows = (
    len(warehouse) *
    forecast["예보일시"].nunique()
)

print(
    "예상 행 수:",
    expected_rows
)

print(
    "행 수 일치:",
    len(warehouse_forecast) == expected_rows
)

print(
    "TMP 결측:",
    warehouse_forecast["TMP"].isna().sum()
)

print(
    "REH 결측:",
    warehouse_forecast["REH"].isna().sum()
)

print(
    "창고×예보일시 중복:",
    warehouse_forecast.duplicated(
        subset=["WARE_NO", "예보일시"]
    ).sum()
)

print(
    "예보기간:",
    warehouse_forecast["예보일시"].min(),
    "~",
    warehouse_forecast["예보일시"].max()
)


# ---------------------------------------------------------
# 5. 일부 결과 확인
# ---------------------------------------------------------

display(
    warehouse_forecast[
        [
            "WARE_NO",
            "COMPANY_NAME",
            "위도",
            "경도",
            "nx",
            "ny",
            "예보일시",
            "TMP",
            "REH"
        ]
    ].head(12)
)


# ---------------------------------------------------------
# 6. 전처리 데이터 저장
# ---------------------------------------------------------

save_path = (
    PROCESSED_DIR /
    "대전_43개물류창고_시간별단기예보.csv"
)

warehouse_forecast.to_csv(
    save_path,
    index=False,
    encoding="utf-8-sig"
)

print("\n저장 완료:")
print(save_path)

사용 단기예보 파일:
기상청_API허브_단기예보_11개격자_2026072811.csv

[창고별 단기예보 연결 결과]
창고 수: 43
전체 행 수: 2623
예상 행 수: 2623
행 수 일치: True
TMP 결측: 0
REH 결측: 0
창고×예보일시 중복: 0
예보기간: 2026-07-28 12:00:00 ~ 2026-07-31 00:00:00

,WARE_NO,COMPANY_NAME,위도,경도,nx,ny,예보일시,TMP,REH
0,2000M63000000033,대전보세창고,36.447477,127.400315,67,103,2026-07-28 12:00:00,31.0,75.0
1,2000M63000000033,대전보세창고,36.447477,127.400315,67,103,2026-07-28 13:00:00,32.0,70.0
2,2000M63000000033,대전보세창고,36.447477,127.400315,67,103,2026-07-28 14:00:00,32.0,70.0
3,2000M63000000033,대전보세창고,36.447477,127.400315,67,103,2026-07-28 15:00:00,32.0,70.0
4,2000M63000000033,대전보세창고,36.447477,127.400315,67,103,2026-07-28 16:00:00,32.0,70.0
5,2000M63000000033,대전보세창고,36.447477,127.400315,67,103,2026-07-28 17:00:00,31.0,75.0
6,2000M63000000033,대전보세창고,36.447477,127.400315,67,103,2026-07-28 18:00:00,30.0,75.0
7,2000M63000000033,대전보세창고,36.447477,127.400315,67,103,2026-07-28 19:00:00,29.0,80.0
8,2000M63000000033,대전보세창고,36.447477,127.400315,67,103,2026-07-28 20:00:00,27.0,85.0
9,2000M63000000033,대전보세창고,36.447477,127.400315,67,103,2026-07-28 21:00:00,27.0,90.0
10,2000M63000000033,대전보세창고,36.447477,127.400315,67,103,2026-07-28 22:00:00,26.0,95.0
11,2000M63000000033,대전보세창고,36.447477,127.400315,67,103,2026-07-28 23:00:00,26.0,95.0

저장 완료:
/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/대전_43개물류창고_시간별단기예보.csv

- 창고 수 43
- 전체 행 수 2,623 = 43개 x 61시간
- 61시간 = 발표시각(260728 11시) ~ 예보기간(260728 12시 ~ 260731 00시)
- 7월 28일 12:00 ~ 23:00 = 12시간
- 7월 29일 00:00 ~ 23:00 = 24시간
- 7월 30일 00:00 ~ 23:00 = 24시간
- 7월 31일 00:00 = 1시간
- 12 + 24 + 24+ 1 = 61시간
- 발표시점에서 실제로 확보한 단기예보 시간 범위의 길이
(API 재실행시 발표시각 변경으로 항상 고정 X)

2-15. 창고별 시간별 여름철 체감온도 산출

In [ ]:
# @title
# # =========================================================
# # 2-15. 창고별 시간별 여름철 체감온도 산출
# # =========================================================

# from pathlib import Path
# import pandas as pd
# import numpy as np

# PROCESSED_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
# )

# # ---------------------------------------------------------
# # 1. 2-14 결과 불러오기
# # ---------------------------------------------------------

# path = (
#     PROCESSED_DIR /
#     "대전_43개물류창고_시간별단기예보.csv"
# )

# df = pd.read_csv(
#     path,
#     encoding="utf-8-sig"
# )

# df["예보일시"] = pd.to_datetime(
#     df["예보일시"]
# )


# # ---------------------------------------------------------
# # 2. 여름철 체감온도 계산
# #
# # 체감온도 산출을 위해
# # 섭씨 → 화씨 변환 후 Heat Index 계산
# # ---------------------------------------------------------

# def calc_heat_index_c(temp_c, rh):

#     # 섭씨 → 화씨
#     T = temp_c * 9 / 5 + 32

#     # Rothfusz regression
#     HI = (
#         -42.379
#         + 2.04901523 * T
#         + 10.14333127 * rh
#         - 0.22475541 * T * rh
#         - 0.00683783 * T**2
#         - 0.05481717 * rh**2
#         + 0.00122874 * T**2 * rh
#         + 0.00085282 * T * rh**2
#         - 0.00000199 * T**2 * rh**2
#     )

#     # 화씨 → 섭씨
#     HI_c = (HI - 32) * 5 / 9

#     return HI_c


# # ---------------------------------------------------------
# # 3. 체감온도 계산
# # ---------------------------------------------------------

# df["체감온도"] = df.apply(
#     lambda row: calc_heat_index_c(
#         row["TMP"],
#         row["REH"]
#     ),
#     axis=1
# )

# df["체감온도"] = df["체감온도"].round(1)


# # ---------------------------------------------------------
# # 4. 최소 검수
# # ---------------------------------------------------------

# print("[체감온도 산출 결과]")

# print(
#     "전체 행 수:",
#     len(df)
# )

# print(
#     "체감온도 결측:",
#     df["체감온도"].isna().sum()
# )

# print(
#     "체감온도 최소:",
#     df["체감온도"].min(),
#     "℃"
# )

# print(
#     "체감온도 최대:",
#     df["체감온도"].max(),
#     "℃"
# )

# print(
#     "체감온도 평균:",
#     round(df["체감온도"].mean(), 1),
#     "℃"
# )

# print("\n체감온도 상위 10개 시간:")

# display(
#     df[
#         [
#             "WARE_NO",
#             "COMPANY_NAME",
#             "예보일시",
#             "TMP",
#             "REH",
#             "체감온도"
#         ]
#     ]
#     .sort_values(
#         "체감온도",
#         ascending=False
#     )
#     .head(10)
# )


# # ---------------------------------------------------------
# # 5. 저장
# # ---------------------------------------------------------

# save_path = (
#     PROCESSED_DIR /
#     "대전_43개물류창고_시간별체감온도예보.csv"
# )

# df.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)

- 2-15에서 사용된 체감온도 산출식은 미국 NOAA 계열의 식
- 2-16에서 기상청 공식 자료 산출식으로 수정

2-16. 기상청 공식 여름철 체감온도 재산출

In [ ]:
# =========================================================
# 2-16. 기상청 공식 여름철 체감온도 재산출
# =========================================================

from pathlib import Path
import pandas as pd
import numpy as np

PROCESSED_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
)

# ---------------------------------------------------------
# 1. 2-14에서 만든 창고별 시간별 기온·습도 예보 불러오기
#
# 2-15에서 잘못 계산한 Heat Index 파일을 사용하지 않고,
# 원래 TMP·REH가 들어있는 2-14 파일에서 다시 계산
# ---------------------------------------------------------

path = (
    PROCESSED_DIR /
    "대전_43개물류창고_시간별단기예보.csv"
)

df = pd.read_csv(
    path,
    encoding="utf-8-sig"
)

df["예보일시"] = pd.to_datetime(
    df["예보일시"]
)


# ---------------------------------------------------------
# 2. Stull 추정식으로 습구온도(Tw) 계산
#
# Ta : 기온(℃)
# RH : 상대습도(%)
# np.arctan()은 라디안 기준이며 공식 적용에 그대로 사용
# ---------------------------------------------------------

def calc_wet_bulb_temperature(Ta, RH):

    Tw = (
        Ta
        * np.arctan(
            0.151977
            * np.sqrt(RH + 8.313659)
        )
        + np.arctan(Ta + RH)
        - np.arctan(RH - 1.67633)
        + 0.00391838
        * (RH ** 1.5)
        * np.arctan(0.023101 * RH)
        - 4.686035
    )

    return Tw


# ---------------------------------------------------------
# 3. 기상청 여름철 체감온도 계산
#
# ST =
# -0.2442
# + 0.55399*Tw
# + 0.45535*Ta
# - 0.0022*Tw^2
# + 0.00278*Tw*Ta
# + 3.0
# ---------------------------------------------------------

df["습구온도"] = calc_wet_bulb_temperature(
    df["TMP"],
    df["REH"]
)

df["체감온도"] = (
    -0.2442
    + 0.55399 * df["습구온도"]
    + 0.45535 * df["TMP"]
    - 0.0022 * (df["습구온도"] ** 2)
    + 0.00278 * df["습구온도"] * df["TMP"]
    + 3.0
)


# ---------------------------------------------------------
# 4. 소수점 정리
# ---------------------------------------------------------

df["습구온도"] = (
    df["습구온도"]
    .round(2)
)

df["체감온도"] = (
    df["체감온도"]
    .round(1)
)


# ---------------------------------------------------------
# 5. 최소 검수
# ---------------------------------------------------------

print("[기상청 공식 체감온도 산출 결과]")

print(
    "전체 행 수:",
    len(df)
)

print(
    "체감온도 결측:",
    df["체감온도"].isna().sum()
)

print(
    "체감온도 최소:",
    df["체감온도"].min(),
    "℃"
)

print(
    "체감온도 최대:",
    df["체감온도"].max(),
    "℃"
)

print(
    "체감온도 평균:",
    round(df["체감온도"].mean(), 1),
    "℃"
)


# ---------------------------------------------------------
# 6. 상위 체감온도 확인
# ---------------------------------------------------------

print("\n체감온도 상위 10개:")

display(
    df[
        [
            "WARE_NO",
            "COMPANY_NAME",
            "예보일시",
            "TMP",
            "REH",
            "습구온도",
            "체감온도"
        ]
    ]
    .sort_values(
        "체감온도",
        ascending=False
    )
    .head(10)
)


# ---------------------------------------------------------
# 7. 검증용 예시
#    33℃ / 70% → 약 34.3℃가 나오는지 확인
# ---------------------------------------------------------

test_Ta = 33
test_RH = 70

test_Tw = calc_wet_bulb_temperature(
    test_Ta,
    test_RH
)

test_ST = (
    -0.2442
    + 0.55399 * test_Tw
    + 0.45535 * test_Ta
    - 0.0022 * (test_Tw ** 2)
    + 0.00278 * test_Tw * test_Ta
    + 3.0
)

print("\n[공식 검증 예시]")
print("기온:", test_Ta, "℃")
print("습도:", test_RH, "%")
print("습구온도:", round(test_Tw, 2), "℃")
print("체감온도:", round(test_ST, 1), "℃")


# ---------------------------------------------------------
# 8. 최종 저장
# ---------------------------------------------------------

save_path = (
    PROCESSED_DIR /
    "대전_43개물류창고_시간별체감온도예보_기상청공식.csv"
)

df.to_csv(
    save_path,
    index=False,
    encoding="utf-8-sig"
)

print("\n저장 완료:")
print(save_path)

[기상청 공식 체감온도 산출 결과]
전체 행 수: 2623
체감온도 결측: 0
체감온도 최소: 25.3 ℃
체감온도 최대: 34.3 ℃
체감온도 평균: 29.9 ℃

체감온도 상위 10개:

,WARE_NO,COMPANY_NAME,예보일시,TMP,REH,습구온도,체감온도
269,2010A63000001044,씨제이대한통운(주),2026-07-29 13:00:00,33.0,70.0,28.39,34.3
1489,2019S63000000001,롯데글로벌로지스(주),2026-07-29 13:00:00,33.0,70.0,28.39,34.3
2466,2025A63000000415,백년축산,2026-07-29 14:00:00,33.0,70.0,28.39,34.3
941,2012S63000000015,(주)한진 대전지점,2026-07-29 14:00:00,33.0,70.0,28.39,34.3
2136,2024A63000001623,주식회사 해우미트,2026-07-28 13:00:00,33.0,70.0,28.39,34.3
1429,2019A63000001505,엘리트,2026-07-29 14:00:00,33.0,70.0,28.39,34.3
1526,2020F63000001114,대전광역시서구전통시장상인협동조합,2026-07-28 13:00:00,33.0,70.0,28.39,34.3
245,2010A63000001044,씨제이대한통운(주),2026-07-28 13:00:00,33.0,70.0,28.39,34.3
2039,2023S63000000003,쿠팡로지스틱스서비스 유한회사 대전1모바일캠프,2026-07-29 14:00:00,33.0,70.0,28.39,34.3
2075,2024A63000000374,(주)블랙해머,2026-07-28 13:00:00,33.0,70.0,28.39,34.3

[공식 검증 예시]
기온: 33 ℃
습도: 70 %
습구온도: 28.39 ℃
체감온도: 34.3 ℃

저장 완료:
/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/대전_43개물류창고_시간별체감온도예보_기상청공식.csv

- 전체 2,623행
- 체감온도 결측 0
- 최소 25.3℃
- 최대 34.3℃
- 평균 29.9℃
- 검증 예시 33℃ / 70% -> 34.3℃
- 기상청 기준 33℃ 이상 -> 매 2시간 이내 20분 이상 휴식
- 35℃ 이상 -> 매시간 15분 휴식과 옥외 작업 최소화 및 중지 권고 제시
- 위험 등급 31/33/35/38 기준으로 선정

2-17. 대전 중기기온 예보 4~10일 수집
- 기상청 공식 API허브에서 중기예보는 4~10일 하루 2회(06시,18시) 생산
- 중기기온은 대전코드 11C20401로 조회
- 대전의 4~10일 후 일별 최저, 최고 기온과 예측범위 저장
- 중기예보에는 습도x. 따라서 체감온도 억지 계산이 아닌 장기 폭염 가능일 미리 선별

In [ ]:
# =========================================================
# 2-17. 대전 중기기온 예보 4~10일 수집
# =========================================================

from pathlib import Path
import pandas as pd
import requests
import getpass
from datetime import datetime, timedelta

API_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도/02_API수집데이터"
)

API_DIR.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------
# 1. 기상청 API허브 인증키 입력
# ---------------------------------------------------------

AUTH_KEY = getpass.getpass(
    "기상청 API허브 인증키를 입력하세요: "
)

# ---------------------------------------------------------
# 2. 최근 사용 가능한 중기예보 발표시각 결정
#
# 중기예보 발표: 매일 06시 / 18시
# 최근 24시간 자료만 조회 가능
# ---------------------------------------------------------

now = datetime.now()

if now.hour >= 19:
    tmfc_dt = now.replace(
        hour=18,
        minute=0,
        second=0,
        microsecond=0
    )

elif now.hour >= 7:
    tmfc_dt = now.replace(
        hour=6,
        minute=0,
        second=0,
        microsecond=0
    )

else:
    tmfc_dt = (
        now - timedelta(days=1)
    ).replace(
        hour=18,
        minute=0,
        second=0,
        microsecond=0
    )

tmFc = tmfc_dt.strftime("%Y%m%d%H00")

print("사용 발표시각:", tmFc)


# ---------------------------------------------------------
# 3. 대전 중기기온 API 호출
#
# 대전 중기기온 예보구역코드: 11C20401
# ---------------------------------------------------------

url = (
    "https://apihub.kma.go.kr/api/typ02/openApi/"
    "MidFcstInfoService/getMidTa"
)

params = {
    "pageNo": 1,
    "numOfRows": 10,
    "dataType": "JSON",
    "regId": "11C20401",
    "tmFc": tmFc,
    "authKey": AUTH_KEY
}

response = requests.get(
    url,
    params=params,
    timeout=30
)

print("HTTP 상태:", response.status_code)

response.raise_for_status()

data = response.json()


# ---------------------------------------------------------
# 4. API 응답 확인
# ---------------------------------------------------------

header = (
    data
    .get("response", {})
    .get("header", {})
)

result_code = header.get("resultCode")
result_msg = header.get("resultMsg")

print(
    "API 결과:",
    result_code,
    "/",
    result_msg
)

if result_code != "00":
    raise RuntimeError(
        f"중기예보 API 오류: "
        f"{result_code} / {result_msg}"
    )


# ---------------------------------------------------------
# 5. 첫 번째 결과 추출
# ---------------------------------------------------------

items = (
    data["response"]["body"]
    ["items"]["item"]
)

if not items:
    raise RuntimeError(
        "중기기온 자료가 없습니다."
    )

item = items[0]


# ---------------------------------------------------------
# 6. 4~10일 예보를 날짜별 행으로 변환
# ---------------------------------------------------------

rows = []

for day in range(4, 11):

    forecast_date = (
        tmfc_dt.date()
        + timedelta(days=day)
    )

    rows.append({
        "발표시각": tmFc,
        "예보일": forecast_date,

        "최저기온": item.get(
            f"taMin{day}"
        ),

        "최저기온_하한": item.get(
            f"taMin{day}Low"
        ),

        "최저기온_상한": item.get(
            f"taMin{day}High"
        ),

        "최고기온": item.get(
            f"taMax{day}"
        ),

        "최고기온_하한": item.get(
            f"taMax{day}Low"
        ),

        "최고기온_상한": item.get(
            f"taMax{day}High"
        )
    })


mid_temp = pd.DataFrame(rows)


# ---------------------------------------------------------
# 7. 숫자형 변환
# ---------------------------------------------------------

temp_cols = [
    "최저기온",
    "최저기온_하한",
    "최저기온_상한",
    "최고기온",
    "최고기온_하한",
    "최고기온_상한"
]

for col in temp_cols:

    mid_temp[col] = pd.to_numeric(
        mid_temp[col],
        errors="coerce"
    )


# ---------------------------------------------------------
# 8. 최소 검수
# ---------------------------------------------------------

print("\n[대전 중기기온 수집 결과]")

print(
    "수집 일수:",
    len(mid_temp)
)

print(
    "예보기간:",
    mid_temp["예보일"].min(),
    "~",
    mid_temp["예보일"].max()
)

print(
    "최저기온 결측:",
    mid_temp["최저기온"].isna().sum()
)

print(
    "최고기온 결측:",
    mid_temp["최고기온"].isna().sum()
)

print(
    "기간 내 최고 예상기온:",
    mid_temp["최고기온"].max(),
    "℃"
)

display(mid_temp)


# ---------------------------------------------------------
# 9. 저장
# ---------------------------------------------------------

save_path = (
    API_DIR /
    f"기상청_API허브_대전_중기기온_{tmFc}.csv"
)

mid_temp.to_csv(
    save_path,
    index=False,
    encoding="utf-8-sig"
)

print("\n저장 완료:")
print(save_path)

기상청 API허브 인증키를 입력하세요: ··········
사용 발표시각: 202607290600
HTTP 상태: 200
API 결과: 00 / NORMAL_SERVICE

[대전 중기기온 수집 결과]
수집 일수: 7
예보기간: 2026-08-02 ~ 2026-08-08
최저기온 결측: 0
최고기온 결측: 0
기간 내 최고 예상기온: 37 ℃

           발표시각         예보일  최저기온  최저기온_하한  최저기온_상한  최고기온  최고기온_하한  최고기온_상한
0  202607290600  2026-08-02    24        1        1    36        0        1
1  202607290600  2026-08-03    24        1        1    36        1        1
2  202607290600  2026-08-04    25        0        1    37        0        1
3  202607290600  2026-08-05    25        1        1    37        1        1
4  202607290600  2026-08-06    24        0        1    36        0        1
5  202607290600  2026-08-07    24        0        1    36        0        1
6  202607290600  2026-08-08    24        0        1    36        0        1

저장 완료:
/content/drive/MyDrive/대전_물류창고_폭염위험도/02_API수집데이터/기상청_API허브_대전_중기기온_202607290600.csv

- 중기기온 7일치 확보
- 기간: 2026-08-01 ~ 2026-08-07
- 최저/최고 기온 결측 0
- 최고 예상 기온: 36℃
- 중기 조기경보에서 우선 주목할 날짜로 볼 수 있음

In [ ]:
# =========================================================
# 2-18. 대전·세종·충남 중기육상예보 수집
# =========================================================

from pathlib import Path
import pandas as pd
import requests
import getpass
from datetime import datetime, timedelta

API_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도/02_API수집데이터"
)

# ---------------------------------------------------------
# 1. API 인증키
# ---------------------------------------------------------

AUTH_KEY = getpass.getpass(
    "기상청 API허브 인증키를 입력하세요: "
)

# ---------------------------------------------------------
# 2. 2-17과 동일한 중기예보 발표시각 사용
# ---------------------------------------------------------

now = datetime.now()

if now.hour >= 19:
    tmfc_dt = now.replace(
        hour=18, minute=0, second=0, microsecond=0
    )
elif now.hour >= 7:
    tmfc_dt = now.replace(
        hour=6, minute=0, second=0, microsecond=0
    )
else:
    tmfc_dt = (
        now - timedelta(days=1)
    ).replace(
        hour=18, minute=0, second=0, microsecond=0
    )

tmFc = tmfc_dt.strftime("%Y%m%d%H00")

print("사용 발표시각:", tmFc)

# ---------------------------------------------------------
# 3. 중기육상예보 호출
#
# 대전·세종·충남 권역
# ---------------------------------------------------------

url = (
    "https://apihub.kma.go.kr/api/typ02/openApi/"
    "MidFcstInfoService/getMidLandFcst"
)

params = {
    "pageNo": 1,
    "numOfRows": 10,
    "dataType": "JSON",
    "regId": "11C20000",
    "tmFc": tmFc,
    "authKey": AUTH_KEY
}

response = requests.get(
    url,
    params=params,
    timeout=30
)

print("HTTP 상태:", response.status_code)

response.raise_for_status()

data = response.json()

header = (
    data
    .get("response", {})
    .get("header", {})
)

print(
    "API 결과:",
    header.get("resultCode"),
    "/",
    header.get("resultMsg")
)

if header.get("resultCode") != "00":
    raise RuntimeError(
        f"중기육상예보 API 오류: "
        f"{header.get('resultCode')} / "
        f"{header.get('resultMsg')}"
    )

items = (
    data["response"]["body"]
    ["items"]["item"]
)

if not items:
    raise RuntimeError(
        "중기육상예보 자료가 없습니다."
    )

item = items[0]

# ---------------------------------------------------------
# 4. 4~10일 날짜별 정리
# ---------------------------------------------------------

rows = []

for day in range(4, 11):

    forecast_date = (
        tmfc_dt.date()
        + timedelta(days=day)
    )

    if day <= 7:

        rows.append({
            "발표시각": tmFc,
            "예보일": forecast_date,

            "오전_강수확률":
                item.get(f"rnSt{day}Am"),

            "오후_강수확률":
                item.get(f"rnSt{day}Pm"),

            "오전_날씨":
                item.get(f"wf{day}Am"),

            "오후_날씨":
                item.get(f"wf{day}Pm")
        })

    else:

        rows.append({
            "발표시각": tmFc,
            "예보일": forecast_date,

            "오전_강수확률":
                item.get(f"rnSt{day}"),

            "오후_강수확률":
                item.get(f"rnSt{day}"),

            "오전_날씨":
                item.get(f"wf{day}"),

            "오후_날씨":
                item.get(f"wf{day}")
        })


mid_land = pd.DataFrame(rows)

# ---------------------------------------------------------
# 5. 숫자형 변환
# ---------------------------------------------------------

for col in [
    "오전_강수확률",
    "오후_강수확률"
]:
    mid_land[col] = pd.to_numeric(
        mid_land[col],
        errors="coerce"
    )

# ---------------------------------------------------------
# 6. 최소 검수
# ---------------------------------------------------------

print("\n[중기육상예보 수집 결과]")

print(
    "수집 일수:",
    len(mid_land)
)

print(
    "예보기간:",
    mid_land["예보일"].min(),
    "~",
    mid_land["예보일"].max()
)

print(
    "강수확률 결측:",
    mid_land[
        ["오전_강수확률", "오후_강수확률"]
    ].isna().sum().sum()
)

print(
    "날씨 결측:",
    mid_land[
        ["오전_날씨", "오후_날씨"]
    ].isna().sum().sum()
)

display(mid_land)

# ---------------------------------------------------------
# 7. 저장
# ---------------------------------------------------------

save_path = (
    API_DIR /
    f"기상청_API허브_대전_중기육상예보_{tmFc}.csv"
)

mid_land.to_csv(
    save_path,
    index=False,
    encoding="utf-8-sig"
)

print("\n저장 완료:")
print(save_path)

기상청 API허브 인증키를 입력하세요: ··········
사용 발표시각: 202607290600
HTTP 상태: 200
API 결과: 00 / NORMAL_SERVICE

[중기육상예보 수집 결과]
수집 일수: 7
예보기간: 2026-08-02 ~ 2026-08-08
강수확률 결측: 0
날씨 결측: 0

           발표시각         예보일  오전_강수확률  오후_강수확률 오전_날씨 오후_날씨
0  202607290600  2026-08-02       10       10    맑음    맑음
1  202607290600  2026-08-03       10       10    맑음    맑음
2  202607290600  2026-08-04       10       10    맑음    맑음
3  202607290600  2026-08-05       10       10    맑음    맑음
4  202607290600  2026-08-06       10       10    맑음    맑음
5  202607290600  2026-08-07       10       10    맑음    맑음
6  202607290600  2026-08-08       10       10    맑음    맑음

저장 완료:
/content/drive/MyDrive/대전_물류창고_폭염위험도/02_API수집데이터/기상청_API허브_대전_중기육상예보_202607290600.csv

- 8/1~8/7 모두 강수확률 10%
- 오전/오후 전부 맑음
- 최고기온 35~36℃ -> 고온 지속 가능성이 꽤 높은 구간

2-19. 중기기온 + 중기육상예보 결합 및 4~10일 조기경보 생성

In [ ]:
# @title
# # =========================================================
# # 2-19. 중기기온 + 중기육상예보 결합 및
# #       4~10일 고온 조기경보 생성
# # =========================================================

# from pathlib import Path
# import pandas as pd

# API_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/02_API수집데이터"
# )

# PROCESSED_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
# )

# # ---------------------------------------------------------
# # 1. 2-17 중기기온 불러오기
# # ---------------------------------------------------------

# temp_path = (
#     API_DIR /
#     "기상청_API허브_대전_중기기온_202607280600.csv"
# )

# mid_temp = pd.read_csv(
#     temp_path,
#     encoding="utf-8-sig"
# )

# mid_temp["예보일"] = pd.to_datetime(
#     mid_temp["예보일"]
# )


# # ---------------------------------------------------------
# # 2. 2-18 중기육상예보 불러오기
# # ---------------------------------------------------------

# land_path = (
#     API_DIR /
#     "기상청_API허브_대전_중기육상예보_202607280600.csv"
# )

# mid_land = pd.read_csv(
#     land_path,
#     encoding="utf-8-sig"
# )

# mid_land["예보일"] = pd.to_datetime(
#     mid_land["예보일"]
# )


# # ---------------------------------------------------------
# # 3. 예보일 기준 결합
# # ---------------------------------------------------------

# mid = mid_temp.merge(
#     mid_land[
#         [
#             "예보일",
#             "오전_강수확률",
#             "오후_강수확률",
#             "오전_날씨",
#             "오후_날씨"
#         ]
#     ],
#     on="예보일",
#     how="left"
# )


# # ---------------------------------------------------------
# # 4. 중기 고온 조기경보 등급
# #
# # 체감온도 기준이 아니라
# # 일 최고기온 기준의 사전 경보용 분류
# #
# # < 30℃   : 낮음
# # 30~<33℃ : 주의
# # 33~<35℃ : 높음
# # >=35℃   : 매우높음
# # ---------------------------------------------------------

# def classify_mid_risk(tmax):

#     if tmax < 30:
#         return "낮음"

#     elif tmax < 33:
#         return "주의"

#     elif tmax < 35:
#         return "높음"

#     else:
#         return "매우높음"


# mid["중기고온경보"] = (
#     mid["최고기온"]
#     .apply(classify_mid_risk)
# )


# # ---------------------------------------------------------
# # 5. 단순 수치 점수도 생성
# # ---------------------------------------------------------

# score_map = {
#     "낮음": 1,
#     "주의": 2,
#     "높음": 3,
#     "매우높음": 4
# }

# mid["중기고온점수"] = (
#     mid["중기고온경보"]
#     .map(score_map)
# )


# # ---------------------------------------------------------
# # 6. 최소 검수
# # ---------------------------------------------------------

# print("[4~10일 중기 조기경보 결과]")

# print(
#     "수집 일수:",
#     len(mid)
# )

# print(
#     "결측:",
#     mid[
#         [
#             "최고기온",
#             "오전_강수확률",
#             "오후_강수확률"
#         ]
#     ].isna().sum().sum()
# )

# print("\n경보등급 분포:")

# print(
#     mid["중기고온경보"]
#     .value_counts()
# )

# display(
#     mid[
#         [
#             "예보일",
#             "최저기온",
#             "최고기온",
#             "오전_날씨",
#             "오후_날씨",
#             "오전_강수확률",
#             "오후_강수확률",
#             "중기고온경보",
#             "중기고온점수"
#         ]
#     ]
# )


# # ---------------------------------------------------------
# # 7. 저장
# # ---------------------------------------------------------

# save_path = (
#     PROCESSED_DIR /
#     "대전_4일10일_중기고온조기경보.csv"
# )

# mid.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)

- 7일 모두 결측 0
- 8/1 ~ 8/7 최고기온 35 ~ 36℃
- 오전/오후 모두 맑음, 강수확률 10%
- 우리가 만든 중기 조기경보 기준에서 7일 모두 '매우높움'
- 조기경보 기준
1) 최고기온 < 30℃ -> 낮음
2) 30℃ ~ 33℃ -> 주의
3) 33℃ ~ 35℃ -> 높음
4) 35℃ 이상 -> 매우높음
- 단기예보: 기상청 공식 체감온도 기준으로 위험등급
- 중기예보: 최고기온 자체와 예측범위를 보여주고 "고온 가능일"만 표시
- 1개월 전망: 평년 대비 높은 기온 확률로 장기 경향 표시

*** 기상청 1개월 전망 주별 고온 가능성 정리 ***
- 최신 1개월 전망 자료를 공식 페이지에서 확인
- 1개월 전망에는 보통 주별로
1) 평균기온이 평년보다 낮을/비슷할/높을 확률
2) 강수량이 평년보다 적을/비슷할/많을 확률
3) 주별 기압계 및 기온 전망 설명
- 최종 분석에 쓸 내용
1) 0~3일: 창고별 시간대 체감온도 정밀위험
2) 4~10일: 중기 최고기온 기반 고온 가능일
3) 11일~약 1개월: 주별 '평년보다 높은 기온 가능성 전망'

2-20. 1개월 전망 주별 기온, 강수량 구조화

In [ ]:
# @title
# # =========================================================
# # 2-20. 기상청 1개월 전망 주별 기온·강수량 구조화
# # =========================================================

# from pathlib import Path
# import pandas as pd

# PROCESSED_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
# )

# PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

# # ---------------------------------------------------------
# # 1. 기상청 1개월 전망 PDF 내용 구조화
# #
# # 대상 지역:
# # 대전·세종·충청남도
# #
# # 발표:
# # 2026-07-23 11:00
# # ---------------------------------------------------------

# month1 = pd.DataFrame([
#     {
#         "발표시각": "2026-07-23 11:00",
#         "예보시작일": "2026-08-03",
#         "예보종료일": "2026-08-09",
#         "평년기온_하한": 25.9,
#         "평년기온_상한": 27.3,
#         "기온_낮음확률": 10,
#         "기온_비슷확률": 30,
#         "기온_높음확률": 60,
#         "평년강수량_하한": 20.9,
#         "평년강수량_상한": 51.0,
#         "강수_적음확률": 30,
#         "강수_비슷확률": 50,
#         "강수_많음확률": 20,
#         "주별전망": (
#             "북태평양고기압의 영향을 받아 덥고 습하겠으며, "
#             "북쪽에서 다가오는 저기압의 영향을 받을 때가 있겠음"
#         )
#     },
#     {
#         "발표시각": "2026-07-23 11:00",
#         "예보시작일": "2026-08-10",
#         "예보종료일": "2026-08-16",
#         "평년기온_하한": 25.2,
#         "평년기온_상한": 26.8,
#         "기온_낮음확률": 10,
#         "기온_비슷확률": 40,
#         "기온_높음확률": 50,
#         "평년강수량_하한": 12.6,
#         "평년강수량_상한": 67.2,
#         "강수_적음확률": 40,
#         "강수_비슷확률": 40,
#         "강수_많음확률": 20,
#         "주별전망": (
#             "북태평양고기압의 영향을 받아 덥고 습하겠으며, "
#             "대기불안정에 의해 비가 내릴 때가 있겠음"
#         )
#     },
#     {
#         "발표시각": "2026-07-23 11:00",
#         "예보시작일": "2026-08-17",
#         "예보종료일": "2026-08-23",
#         "평년기온_하한": 24.6,
#         "평년기온_상한": 25.8,
#         "기온_낮음확률": 10,
#         "기온_비슷확률": 30,
#         "기온_높음확률": 60,
#         "평년강수량_하한": 22.1,
#         "평년강수량_상한": 59.5,
#         "강수_적음확률": 30,
#         "강수_비슷확률": 50,
#         "강수_많음확률": 20,
#         "주별전망": (
#             "북태평양고기압의 영향을 받아 덥고 습하겠으며, "
#             "서쪽에서 다가오는 저기압의 영향을 받을 때가 있겠음"
#         )
#     },
#     {
#         "발표시각": "2026-07-23 11:00",
#         "예보시작일": "2026-08-24",
#         "예보종료일": "2026-08-30",
#         "평년기온_하한": 23.4,
#         "평년기온_상한": 24.6,
#         "기온_낮음확률": 10,
#         "기온_비슷확률": 40,
#         "기온_높음확률": 50,
#         "평년강수량_하한": 27.0,
#         "평년강수량_상한": 70.6,
#         "강수_적음확률": 30,
#         "강수_비슷확률": 50,
#         "강수_많음확률": 20,
#         "주별전망": (
#             "북태평양고기압의 영향을 받겠으며, "
#             "서쪽에서 다가오는 저기압의 영향을 받을 때가 있겠음"
#         )
#     }
# ])

# # ---------------------------------------------------------
# # 2. 날짜형 변환
# # ---------------------------------------------------------

# month1["발표시각"] = pd.to_datetime(
#     month1["발표시각"]
# )

# month1["예보시작일"] = pd.to_datetime(
#     month1["예보시작일"]
# )

# month1["예보종료일"] = pd.to_datetime(
#     month1["예보종료일"]
# )

# # ---------------------------------------------------------
# # 3. 장기 고온 가능성 표시
# #
# # 공식 확률값 자체를 사용하며,
# # 별도의 임의 위험등급은 만들지 않음
# # ---------------------------------------------------------

# month1["평년보다_높은기온_가능성"] = (
#     month1["기온_높음확률"]
# )

# # ---------------------------------------------------------
# # 4. 최소 검수
# # ---------------------------------------------------------

# print("[1개월 전망 구조화 결과]")

# print(
#     "주 수:",
#     len(month1)
# )

# print(
#     "전망기간:",
#     month1["예보시작일"].min().date(),
#     "~",
#     month1["예보종료일"].max().date()
# )

# print(
#     "기온확률 합계 오류:",
#     (
#         month1[
#             [
#                 "기온_낮음확률",
#                 "기온_비슷확률",
#                 "기온_높음확률"
#             ]
#         ].sum(axis=1) != 100
#     ).sum()
# )

# print(
#     "강수확률 합계 오류:",
#     (
#         month1[
#             [
#                 "강수_적음확률",
#                 "강수_비슷확률",
#                 "강수_많음확률"
#             ]
#         ].sum(axis=1) != 100
#     ).sum()
# )

# display(
#     month1[
#         [
#             "예보시작일",
#             "예보종료일",
#             "평년기온_하한",
#             "평년기온_상한",
#             "기온_낮음확률",
#             "기온_비슷확률",
#             "기온_높음확률",
#             "평년보다_높은기온_가능성",
#             "주별전망"
#         ]
#     ]
# )

# # ---------------------------------------------------------
# # 5. 저장
# # ---------------------------------------------------------

# save_path = (
#     PROCESSED_DIR /
#     "대전세종충남_1개월전망_20260723.csv"
# )

# month1.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)

[1개월 전망 구조화 결과]
주 수: 4
전망기간: 2026-08-03 ~ 2026-08-30
기온확률 합계 오류: 0
강수확률 합계 오류: 0

,예보시작일,예보종료일,평년기온_하한,평년기온_상한,기온_낮음확률,기온_비슷확률,기온_높음확률,평년보다_높은기온_가능성,주별전망
0,2026-08-03,2026-08-09,25.9,27.3,10,30,60,60,"북태평양고기압의 영향을 받아 덥고 습하겠으며, 북쪽에서 다가오는 저기압의 영향을 받..."
1,2026-08-10,2026-08-16,25.2,26.8,10,40,50,50,"북태평양고기압의 영향을 받아 덥고 습하겠으며, 대기불안정에 의해 비가 내릴 때가 있겠음"
2,2026-08-17,2026-08-23,24.6,25.8,10,30,60,60,"북태평양고기압의 영향을 받아 덥고 습하겠으며, 서쪽에서 다가오는 저기압의 영향을 받..."
3,2026-08-24,2026-08-30,23.4,24.6,10,40,50,50,"북태평양고기압의 영향을 받겠으며, 서쪽에서 다가오는 저기압의 영향을 받을 때가 있겠음"

저장 완료:
/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/대전세종충남_1개월전망_20260723.csv

- 4개 주 모두 정상 구조화
- 기간: 2026-08-03 ~ 2026-08-30
- 기온 확률 합계 오류 0
- 강수 확률 합계 오류 0
- 모든 주에서 평년보다 높은 기온 확률이 50 ~ 60%
- 특히 8/3 ~ 8/9, 8/17 ~ 8/23은 높은 기온 확률 60%

# **2단계 결론**
- 대전 물류창고 43곳 위치 모두 확보
- 43곳 모두 11개 격자와 연결하여 창고별 시간대 기상예보 구축
- 단기예보: 기온과 습도를 이용해 기상청 공식 체감온도 계산 (창고별 시간대 정밀 위험도)
- 중기예보: 4 ~ 10일 고온 가능성 (일별 고온 가능성)
- 1개월 전망: 약 한달의 장기 기온 경향 파악 (주별 고온 경향을 제공하는 다단계 기상예측)

# **3. 물류부하 데이터 정제 및 연결**

3-1. 43개 물류창고 우편번호 확보 및 검수
- 택배물량 자료는 우편번호 단위
- 기존 카카오 좌표 파일의 우편번호 우선 사용
- 빠진 창고는 카카오 주소 API로 다시 조회

In [ ]:
# =========================================================
# 3-1. 43개 물류창고 우편번호 확보 및 검수
# =========================================================

from pathlib import Path
import pandas as pd
import requests
import getpass
import re
import time

API_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도/02_API수집데이터"
)

PROCESSED_DIR = Path(
    "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
)

# ---------------------------------------------------------
# 1. 최종 좌표 파일 불러오기
# ---------------------------------------------------------

warehouse_path = (
    API_DIR /
    "대전_물류창고_카카오좌표_최종.csv"
)

warehouse = pd.read_csv(
    warehouse_path,
    encoding="utf-8-sig",
    dtype=str
)

print("불러온 창고 수:", len(warehouse))
print("현재 열:", warehouse.columns.tolist())


# ---------------------------------------------------------
# 2. 기존 우편번호 열 확인
# ---------------------------------------------------------

possible_zip_cols = [
    "카카오_우편번호",
    "우편번호",
    "zone_no",
    "zoneNo"
]

existing_zip_col = next(
    (
        col for col in possible_zip_cols
        if col in warehouse.columns
    ),
    None
)

if existing_zip_col is None:
    warehouse["우편번호"] = pd.NA
else:
    warehouse["우편번호"] = warehouse[existing_zip_col]


# 우편번호를 숫자만 남긴 5자리 문자열로 정리
warehouse["우편번호"] = (
    warehouse["우편번호"]
    .astype("string")
    .str.replace(r"\D", "", regex=True)
    .str.zfill(5)
)

# 빈 값이 zfill 때문에 잘못 변환되는 것을 방지
invalid_zip = (
    warehouse["우편번호"].isna()
    | (warehouse["우편번호"].str.len() != 5)
    | (warehouse["우편번호"] == "00<NA>")
)

warehouse.loc[invalid_zip, "우편번호"] = pd.NA


# ---------------------------------------------------------
# 3. 주소 표준화 함수
#
# 예:
# 411번지 3호 → 411-3
# ---------------------------------------------------------

def normalize_lot_address(address):

    if pd.isna(address):
        return None

    address = str(address).strip()

    address = re.sub(
        r"(\d+)\s*번지\s*(\d+)\s*호",
        r"\1-\2",
        address
    )

    address = re.sub(
        r"(\d+)\s*번지",
        r"\1",
        address
    )

    address = re.sub(r"\s+", " ", address)

    return address.strip()


warehouse["우편번호검색주소"] = (
    warehouse["COMPANY_ADDRESS"]
    .apply(normalize_lot_address)
)


# ---------------------------------------------------------
# 4. 우편번호 미확보 창고만 카카오 API 재조회
# ---------------------------------------------------------

missing_before = warehouse["우편번호"].isna().sum()

print("\n재조회 전 우편번호 미확보:", missing_before)

if missing_before > 0:

    KAKAO_REST_KEY = getpass.getpass(
        "카카오 REST API 키를 입력하세요: "
    )

    url = (
        "https://dapi.kakao.com/v2/local/search/address.json"
    )

    headers = {
        "Authorization": f"KakaoAK {KAKAO_REST_KEY}"
    }

    for idx in warehouse[
        warehouse["우편번호"].isna()
    ].index:

        query = warehouse.loc[
            idx,
            "우편번호검색주소"
        ]

        try:
            response = requests.get(
                url,
                headers=headers,
                params={"query": query},
                timeout=20
            )

            response.raise_for_status()

            documents = response.json().get(
                "documents",
                []
            )

            if documents:

                result = documents[0]

                road_address = (
                    result.get("road_address")
                    or {}
                )

                zone_no = road_address.get(
                    "zone_no"
                )

                if zone_no:
                    warehouse.loc[
                        idx,
                        "우편번호"
                    ] = str(zone_no).zfill(5)

                    warehouse.loc[
                        idx,
                        "우편번호검색상태"
                    ] = "성공"

                else:
                    warehouse.loc[
                        idx,
                        "우편번호검색상태"
                    ] = "도로명주소_우편번호없음"

            else:
                warehouse.loc[
                    idx,
                    "우편번호검색상태"
                ] = "검색결과없음"

        except Exception as e:

            warehouse.loc[
                idx,
                "우편번호검색상태"
            ] = f"오류:{type(e).__name__}"

        time.sleep(0.1)

else:
    warehouse["우편번호검색상태"] = "기존값사용"


# ---------------------------------------------------------
# 5. 우편번호 최종 형식 정리
# ---------------------------------------------------------

warehouse["우편번호"] = (
    warehouse["우편번호"]
    .astype("string")
    .str.replace(r"\D", "", regex=True)
    .str.zfill(5)
)

warehouse.loc[
    warehouse["우편번호"].str.len() != 5,
    "우편번호"
] = pd.NA


# ---------------------------------------------------------
# 6. 택배물량 파일의 우편번호와 실제 연결 가능한지 확인
# ---------------------------------------------------------

parcel_path = (
    Path(
        "/content/drive/MyDrive/대전_물류창고_폭염위험도/01_원본데이터"
    )
    / "과학기술정보통신부 우정사업본부_전국 우편번호(배달지 기준)별 택배물량_20231231.csv"
)

parcel = pd.read_csv(
    parcel_path,
    encoding="cp949",
    dtype={"우편번호": str}
)

parcel["우편번호"] = (
    parcel["우편번호"]
    .astype("string")
    .str.replace(r"\D", "", regex=True)
    .str.zfill(5)
)

parcel_zip_set = set(
    parcel["우편번호"].dropna()
)

warehouse["택배물량_우편번호일치"] = (
    warehouse["우편번호"]
    .isin(parcel_zip_set)
)


# ---------------------------------------------------------
# 7. 최소 검수
# ---------------------------------------------------------

print("\n[물류창고 우편번호 확보 결과]")

print(
    "전체 창고 수:",
    len(warehouse)
)

print(
    "우편번호 확보:",
    warehouse["우편번호"].notna().sum()
)

print(
    "우편번호 미확보:",
    warehouse["우편번호"].isna().sum()
)

print(
    "고유 우편번호 수:",
    warehouse["우편번호"].nunique()
)

print(
    "택배물량 자료와 일치:",
    warehouse["택배물량_우편번호일치"].sum()
)

print(
    "택배물량 자료와 불일치:",
    (~warehouse["택배물량_우편번호일치"]).sum()
)

display(
    warehouse[
        [
            "WARE_NO",
            "COMPANY_NAME",
            "COMPANY_ADDRESS",
            "우편번호",
            "우편번호검색상태",
            "택배물량_우편번호일치"
        ]
    ]
)


# ---------------------------------------------------------
# 8. 저장
# ---------------------------------------------------------

save_path = (
    PROCESSED_DIR /
    "대전_43개물류창고_우편번호_확보.csv"
)

warehouse.to_csv(
    save_path,
    index=False,
    encoding="utf-8-sig"
)

print("\n저장 완료:")
print(save_path)

불러온 창고 수: 43
현재 열: ['WARE_NO', 'COMPANY_NAME', 'COMPANY_ADDRESS', 'STORAGE_ITEM', 'STORAGE_AREA', 'GENERAL_AREA', 'FROZEN_AREA', '검색주소', '도로명주소', '지번주소', '우편번호', 'admCd', 'rnMgtSn', 'udrtYn', 'buldMnnm', 'buldSlno', '경도', '위도', '주소검색상태', '카카오검색주소', '카카오_도로명주소', '카카오_지번주소', '카카오_우편번호', '좌표검색상태', '지번표준검색주소']

재조회 전 우편번호 미확보: 43
카카오 REST API 키를 입력하세요: ··········

[물류창고 우편번호 확보 결과]
전체 창고 수: 43
우편번호 확보: 39
우편번호 미확보: 4
고유 우편번호 수: 22
택배물량 자료와 일치: 39
택배물량 자료와 불일치: 4

,WARE_NO,COMPANY_NAME,COMPANY_ADDRESS,우편번호,우편번호검색상태,택배물량_우편번호일치
0,2000M63000000033,대전보세창고,대전광역시 대덕구 문평동로 41-16 (문평동),34302,성공,True
1,2006F63000000187,동원로엑스(주)대전물류센타,대전광역시 대덕구 방두말1길 12(상서동),34343,성공,True
2,2008A63000001455,씨제이대한통운(주),"대전광역시 대덕구 신탄진로 1, 대한통운 창고동 3층 (읍내동)",34352,성공,True
3,2010A63000000160,(주)동원홈푸드,대전광역시 대덕구 대화로 36 (대화동),34364,성공,True
4,2010A63000001044,씨제이대한통운(주),대전광역시 대덕구 대덕대로1447번길 39 (문평동),34301,성공,True
5,2010F63000000532,씨제이대한통운(주),"대전광역시 대덕구 대덕대로1447번길 39(가동 문평동, 씨제이대한통운택배허브터미널)",34301,성공,True
6,2011F63000000903,(주)한익스프레스,대전광역시 대덕구 대화로32번길 335(1층 대화동),34361,성공,True
7,2012S63000000005,SK네트웍스(주) 대전지사,대전광역시 대덕구 대화동 411번지 3호,34367,성공,True
8,2012S63000000006,씨제이대한통운(주) 문평동지점,대전광역시 대덕구 문평동 140번지,34301,성공,True
9,2012S63000000007,씨제이대한통운(주) 읍내동지점,대전광역시 대덕구 읍내동 100번지,34352,성공,True
10,2012S63000000008,한국농수산식품유통공사,대전광역시 대덕구 와동 115번지 1호,34346,성공,True
11,2012S63000000009,롯데글로벌로지스주식회사,대전광역시 대덕구 대화동 40번지 40호,34365,성공,True
12,2012S63000000010,한솔로지스틱스(주) 대전센타,대전광역시 대덕구 신일동 1674번지 2호,34326,성공,True
13,2012S63000000011,한솔로지스틱스(주) 신탄진센타,대전광역시 대덕구 신일동 1691번지,34326,성공,True
14,2012S63000000014,(주)한진 대전중부지점,대전광역시 대덕구 대화동 40번지 25호,34366,성공,True
15,2012S63000000015,(주)한진 대전지점,대전광역시 유성구 대정동 301-1 (주)한진대전택배터미널,34219,성공,True
16,2012S63000000016,대신정기화물(주),대전광역시 유성구 대정동 302번지 3호,34219,성공,True
17,2014M63000000423,한솔로지스틱스 신탄진CY,"대전광역시 대덕구 평촌2길 59 (평촌동, 시설장비사무소)",34341,성공,True
18,2015A63000000426,(주)빙그레,"대전광역시 대덕구 신탄진로115번안길 26, (주)빙그레 1층 (신대동)",34351,성공,True
19,2015S63000000003,대전물류(주),대전광역시 동구 구도동 380번지,34708,성공,True
20,2015S63000000005,주식회사 대승물산,대전광역시 동구 구도동 341번지,34708,성공,True
21,2016S63000000001,한솔로지스틱스 주식회사,대전광역시 대덕구 평촌동 24번지 3호,<NA>,도로명주소_우편번호없음,False
22,2018S63000000003,주식회사 넥센,대전광역시 대덕구 대화동 40-30 넥센타이어,<NA>,도로명주소_우편번호없음,False
23,2019A63000001505,엘리트,"대전광역시 중구 대둔산로300번길 36, 1,2층 (사정동)",<NA>,검색결과없음,False
24,2019S63000000001,롯데글로벌로지스(주),대전광역시 대덕구 문평동 78-4 롯데제과(주),34301,성공,True
25,2020F63000001114,대전광역시서구전통시장상인협동조합,대전광역시 서구 도솔로296번길 39(대전 서구 전통시장 공동물류창고 1층 일부분호...,35294,성공,True
26,2020S63000000001,동원로엑스(주),대전광역시 대덕구 상서동 171-1,34343,성공,True
27,2021S63000000001,(주)에이치씨인터내셔널,대전광역시 동구 구도동 345번지,34708,성공,True
28,2022S63000000002,쿠팡로지스틱스서비스 유한회사 대전2캠프,대전광역시 대덕구 대화동 262-1,34369,성공,True
29,2022S63000000003,쿠팡로지스틱스서비스 유한회사 대전2미니캠프,대전광역시 대덕구 상서동 331-1,34344,성공,True
30,2022S63000000004,주식회사 베니스,대전광역시 동구 하소동 926번지,34712,성공,True
31,2023S63000000001,도시산업개발,대전광역시 동구 하소동 894-1,34712,성공,True
32,2023S63000000002,(주)비지에프로지스 대전센터,대전광역시 유성구 대정동 301-2 (주)비지에프리테일대전물류센터,34219,성공,True
33,2023S63000000003,쿠팡로지스틱스서비스 유한회사 대전1모바일캠프,대전광역시 유성구 대정동 302-1 오성철강(주) 가동,34219,성공,True
34,2024A63000000374,(주)블랙해머,"대전광역시 중구 대종로333번길 61, 1층 (부사동)",35023,성공,True
35,2024A63000001623,주식회사 해우미트,대전광역시 대덕구 오정로42번길 59-2 (오정동),34439,성공,True
36,2024A63000001643,쿠팡 대전1 신선센터,"대전광역시 동구 안골로 33, 3,4층 (구도동)",<NA>,검색결과없음,False
37,2024S63000000001,CJ대한통운(주) 대전생수센터,대전광역시 동구 하소동 913번지 대전킴벌리하소동창고 1동,34712,성공,True
38,2024S63000000002,쿠팡로지스틱스서비스 유한회사(대전2서브허브 외 1),대전광역시 동구 구도동 397번지,34708,성공,True
39,2025A63000000329,동원로엑스(주) 대전센터,"대전광역시 대덕구 방두말1길 12, (주)동원F&B (상서동)",34343,성공,True
40,2025A63000000415,백년축산,"대전광역시 유성구 대정북로 68, 대정동창고시설 B101호 (대정동)",34219,성공,True
41,2025S63000000001,로젠주식회사,대전광역시 동구 구도동 368번지,34708,성공,True
42,2026C63000000024,머크 주식회사 대전 바이오프로세싱생산센터,대전광역시 유성구 국제과학18로 85 머크 바이오프로세싱생산센터,34002,성공,True

저장 완료:
/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/대전_43개물류창고_우편번호_확보.csv

- 전체 43개 중 39개 우편번호 확보
- 미확보 4개
- 확보된 39개는 택배물량 자료와 모두 일치
- 미확보 원인
1) 주소 API 결과에 road_address 없음
2) 주소 검색 자체가 되지 않음

3-2. 좌표 기반 미확보 우편번호 보완

In [ ]:
# @title
# # =========================================================
# # 3-2. 좌표 기반 미확보 물류창고 우편번호 보완
# # =========================================================

# from pathlib import Path
# import pandas as pd
# import requests
# import getpass
# import time

# API_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/02_API수집데이터"
# )

# PROCESSED_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
# )

# # ---------------------------------------------------------
# # 1. 3-1 결과 불러오기
# # ---------------------------------------------------------

# warehouse_path = (
#     PROCESSED_DIR /
#     "대전_43개물류창고_우편번호_확보.csv"
# )

# warehouse = pd.read_csv(
#     warehouse_path,
#     encoding="utf-8-sig",
#     dtype={"우편번호": str}
# )

# print("전체 창고 수:", len(warehouse))
# print(
#     "보완 전 우편번호 미확보:",
#     warehouse["우편번호"].isna().sum()
# )


# # ---------------------------------------------------------
# # 2. 좌표가 문자형으로 저장된 경우 숫자형 변환
# # ---------------------------------------------------------

# warehouse["경도"] = pd.to_numeric(
#     warehouse["경도"],
#     errors="coerce"
# )

# warehouse["위도"] = pd.to_numeric(
#     warehouse["위도"],
#     errors="coerce"
# )


# # ---------------------------------------------------------
# # 3. 카카오 좌표→주소 변환 API
# #
# # 주소 문자열이 검색되지 않더라도,
# # 확보된 위도·경도 위치의 도로명주소에서
# # 5자리 우편번호를 다시 조회
# # ---------------------------------------------------------

# missing_idx = warehouse[
#     warehouse["우편번호"].isna()
# ].index

# if len(missing_idx) > 0:

#     KAKAO_REST_KEY = getpass.getpass(
#         "카카오 REST API 키를 입력하세요: "
#     )

#     url = (
#         "https://dapi.kakao.com/v2/local/"
#         "geo/coord2address.json"
#     )

#     headers = {
#         "Authorization": f"KakaoAK {KAKAO_REST_KEY}"
#     }

#     for idx in missing_idx:

#         x = warehouse.loc[idx, "경도"]
#         y = warehouse.loc[idx, "위도"]

#         if pd.isna(x) or pd.isna(y):

#             warehouse.loc[
#                 idx,
#                 "우편번호보완상태"
#             ] = "좌표없음"

#             continue

#         try:

#             response = requests.get(
#                 url,
#                 headers=headers,
#                 params={
#                     "x": x,
#                     "y": y,
#                     "input_coord": "WGS84"
#                 },
#                 timeout=20
#             )

#             response.raise_for_status()

#             documents = response.json().get(
#                 "documents",
#                 []
#             )

#             if not documents:

#                 warehouse.loc[
#                     idx,
#                     "우편번호보완상태"
#                 ] = "좌표주소결과없음"

#                 continue

#             result = documents[0]

#             road_address = (
#                 result.get("road_address")
#                 or {}
#             )

#             zone_no = road_address.get(
#                 "zone_no"
#             )

#             if zone_no:

#                 warehouse.loc[
#                     idx,
#                     "우편번호"
#                 ] = str(zone_no).zfill(5)

#                 warehouse.loc[
#                     idx,
#                     "우편번호보완상태"
#                 ] = "좌표기반성공"

#                 warehouse.loc[
#                     idx,
#                     "좌표기반_도로명주소"
#                 ] = road_address.get(
#                     "address_name"
#                 )

#             else:

#                 warehouse.loc[
#                     idx,
#                     "우편번호보완상태"
#                 ] = "도로명주소_우편번호없음"

#         except Exception as e:

#             warehouse.loc[
#                 idx,
#                 "우편번호보완상태"
#             ] = f"오류:{type(e).__name__}"

#         time.sleep(0.1)

# else:

#     warehouse["우편번호보완상태"] = "보완불필요"


# # ---------------------------------------------------------
# # 4. 우편번호 형식 재정리
# # ---------------------------------------------------------

# warehouse["우편번호"] = (
#     warehouse["우편번호"]
#     .astype("string")
#     .str.replace(r"\D", "", regex=True)
#     .str.zfill(5)
# )

# warehouse.loc[
#     warehouse["우편번호"].str.len() != 5,
#     "우편번호"
# ] = pd.NA


# # ---------------------------------------------------------
# # 5. 택배물량 우편번호와 재검수
# # ---------------------------------------------------------

# parcel_path = (
#     Path(
#         "/content/drive/MyDrive/대전_물류창고_폭염위험도/01_원본데이터"
#     )
#     / "과학기술정보통신부 우정사업본부_전국 우편번호(배달지 기준)별 택배물량_20231231.csv"
# )

# parcel = pd.read_csv(
#     parcel_path,
#     encoding="cp949",
#     dtype={"우편번호": str}
# )

# parcel["우편번호"] = (
#     parcel["우편번호"]
#     .astype("string")
#     .str.replace(r"\D", "", regex=True)
#     .str.zfill(5)
# )

# parcel_zip_set = set(
#     parcel["우편번호"].dropna()
# )

# warehouse["택배물량_우편번호일치"] = (
#     warehouse["우편번호"]
#     .isin(parcel_zip_set)
# )


# # ---------------------------------------------------------
# # 6. 최소 검수
# # ---------------------------------------------------------

# print("\n[좌표 기반 우편번호 보완 결과]")

# print(
#     "우편번호 확보:",
#     warehouse["우편번호"].notna().sum()
# )

# print(
#     "우편번호 미확보:",
#     warehouse["우편번호"].isna().sum()
# )

# print(
#     "택배물량 자료와 일치:",
#     warehouse["택배물량_우편번호일치"].sum()
# )

# print(
#     "택배물량 자료와 불일치:",
#     (~warehouse["택배물량_우편번호일치"]).sum()
# )

# display(
#     warehouse.loc[
#         missing_idx,
#         [
#             "WARE_NO",
#             "COMPANY_NAME",
#             "COMPANY_ADDRESS",
#             "경도",
#             "위도",
#             "좌표기반_도로명주소",
#             "우편번호",
#             "우편번호보완상태",
#             "택배물량_우편번호일치"
#         ]
#     ]
# )


# # ---------------------------------------------------------
# # 7. 최종 저장
# # ---------------------------------------------------------

# save_path = (
#     PROCESSED_DIR /
#     "대전_43개물류창고_우편번호_최종.csv"
# )

# warehouse.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)

전체 창고 수: 43
보완 전 우편번호 미확보: 4
카카오 REST API 키를 입력하세요: ··········

[좌표 기반 우편번호 보완 결과]
우편번호 확보: 39
우편번호 미확보: 4
택배물량 자료와 일치: 39
택배물량 자료와 불일치: 4

KeyError: "['좌표기반_도로명주소'] not in index"

- 좌표 기반 역변환으로 4개 우편번호 보완X
- road_address가 없어서 zone_no를 못 받은걸로 보임
- 3-2번 코드 사용x(폐기)

3-3. 공식 도로명주소 검색 API를 이용한 미확보 우편번호 보완

In [ ]:
# @title
# # =========================================================
# # 3-3. 공식 도로명주소 검색 API를 이용한
# #      미확보 우편번호 보완
# # =========================================================

# from pathlib import Path
# import pandas as pd
# import requests
# import getpass
# import re
# import time

# PROCESSED_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
# )

# RAW_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/01_원본데이터"
# )

# # ---------------------------------------------------------
# # 1. 3-1 결과 불러오기
# # ---------------------------------------------------------

# warehouse_path = (
#     PROCESSED_DIR /
#     "대전_43개물류창고_우편번호_확보.csv"
# )

# warehouse = pd.read_csv(
#     warehouse_path,
#     encoding="utf-8-sig",
#     dtype={"우편번호": str}
# )

# print("전체 창고 수:", len(warehouse))
# print(
#     "보완 전 우편번호 미확보:",
#     warehouse["우편번호"].isna().sum()
# )

# # 출력용 열을 미리 생성하여 KeyError 방지
# warehouse["도로명API_검색어"] = pd.NA
# warehouse["도로명API_도로명주소"] = pd.NA
# warehouse["도로명API_지번주소"] = pd.NA
# warehouse["우편번호보완상태"] = pd.NA


# # ---------------------------------------------------------
# # 2. 검색어 정제
# #
# # 괄호 안 건물명, 층·호 정보 등을 줄여
# # 주소 API 검색 성공률을 높임
# # ---------------------------------------------------------

# def clean_address_keyword(address):

#     if pd.isna(address):
#         return None

#     text = str(address).strip()

#     # 괄호 및 괄호 안 설명 제거
#     text = re.sub(r"\([^)]*\)", " ", text)

#     # 층·호·동 등 상세 설명 제거
#     text = re.sub(
#         r",?\s*\d+(?:,\d+)*층.*$",
#         "",
#         text
#     )

#     # '번지', '호' 표기 정리
#     text = re.sub(
#         r"(\d+)\s*번지\s*(\d+)\s*호",
#         r"\1-\2",
#         text
#     )
#     text = re.sub(
#         r"(\d+)\s*번지",
#         r"\1",
#         text
#     )

#     text = re.sub(r"\s+", " ", text)

#     return text.strip()


# # ---------------------------------------------------------
# # 3. 공식 도로명주소 검색 API 호출
# # ---------------------------------------------------------

# JUSO_KEY = getpass.getpass(
#     "도로명주소 검색 API 승인키를 입력하세요: "
# )

# url = (
#     "https://business.juso.go.kr/"
#     "addrlink/addrLinkApi.do"
# )

# missing_idx = warehouse[
#     warehouse["우편번호"].isna()
# ].index

# for idx in missing_idx:

#     keyword = clean_address_keyword(
#         warehouse.loc[idx, "COMPANY_ADDRESS"]
#     )

#     warehouse.loc[
#         idx,
#         "도로명API_검색어"
#     ] = keyword

#     params = {
#         "confmKey": JUSO_KEY,
#         "currentPage": 1,
#         "countPerPage": 10,
#         "keyword": keyword,
#         "resultType": "json"
#     }

#     try:

#         response = requests.get(
#             url,
#             params=params,
#             timeout=30
#         )

#         response.raise_for_status()

#         data = response.json()

#         common = (
#             data
#             .get("results", {})
#             .get("common", {})
#         )

#         error_code = common.get("errorCode")
#         error_message = common.get("errorMessage")

#         if error_code != "0":

#             warehouse.loc[
#                 idx,
#                 "우편번호보완상태"
#             ] = f"API오류:{error_code}_{error_message}"

#             continue

#         results = (
#             data
#             .get("results", {})
#             .get("juso", [])
#         )

#         if not results:

#             warehouse.loc[
#                 idx,
#                 "우편번호보완상태"
#             ] = "검색결과없음"

#             continue

#         # 대전광역시 결과만 남김
#         daejeon_results = [
#             result for result in results
#             if str(result.get("roadAddr", "")).startswith(
#                 "대전광역시"
#             )
#         ]

#         if not daejeon_results:

#             warehouse.loc[
#                 idx,
#                 "우편번호보완상태"
#             ] = "대전지역결과없음"

#             continue

#         # 첫 번째 대전 주소 사용
#         result = daejeon_results[0]

#         zip_no = str(
#             result.get("zipNo", "")
#         ).strip()

#         warehouse.loc[
#             idx,
#             "도로명API_도로명주소"
#         ] = result.get("roadAddr")

#         warehouse.loc[
#             idx,
#             "도로명API_지번주소"
#         ] = result.get("jibunAddr")

#         if len(zip_no) == 5:

#             warehouse.loc[
#                 idx,
#                 "우편번호"
#             ] = zip_no

#             warehouse.loc[
#                 idx,
#                 "우편번호보완상태"
#             ] = "공식주소API성공"

#         else:

#             warehouse.loc[
#                 idx,
#                 "우편번호보완상태"
#             ] = "우편번호없음"

#     except Exception as e:

#         warehouse.loc[
#             idx,
#             "우편번호보완상태"
#         ] = f"오류:{type(e).__name__}"

#     time.sleep(0.1)


# # ---------------------------------------------------------
# # 4. 우편번호 형식 정리
# # ---------------------------------------------------------

# warehouse["우편번호"] = (
#     warehouse["우편번호"]
#     .astype("string")
#     .str.replace(r"\D", "", regex=True)
#     .str.zfill(5)
# )

# warehouse.loc[
#     warehouse["우편번호"].str.len() != 5,
#     "우편번호"
# ] = pd.NA


# # ---------------------------------------------------------
# # 5. 택배물량 자료와 재검수
# # ---------------------------------------------------------

# parcel_path = (
#     RAW_DIR /
#     "과학기술정보통신부 우정사업본부_전국 우편번호(배달지 기준)별 택배물량_20231231.csv"
# )

# parcel = pd.read_csv(
#     parcel_path,
#     encoding="cp949",
#     dtype={"우편번호": str}
# )

# parcel["우편번호"] = (
#     parcel["우편번호"]
#     .astype("string")
#     .str.replace(r"\D", "", regex=True)
#     .str.zfill(5)
# )

# parcel_zip_set = set(
#     parcel["우편번호"].dropna()
# )

# warehouse["택배물량_우편번호일치"] = (
#     warehouse["우편번호"]
#     .isin(parcel_zip_set)
# )


# # ---------------------------------------------------------
# # 6. 최소 검수
# # ---------------------------------------------------------

# print("\n[공식 주소 API 우편번호 보완 결과]")

# print(
#     "우편번호 확보:",
#     warehouse["우편번호"].notna().sum()
# )

# print(
#     "우편번호 미확보:",
#     warehouse["우편번호"].isna().sum()
# )

# print(
#     "택배물량 자료와 일치:",
#     warehouse["택배물량_우편번호일치"].sum()
# )

# print(
#     "택배물량 자료와 불일치:",
#     (~warehouse["택배물량_우편번호일치"]).sum()
# )

# display(
#     warehouse.loc[
#         missing_idx,
#         [
#             "WARE_NO",
#             "COMPANY_NAME",
#             "COMPANY_ADDRESS",
#             "도로명API_검색어",
#             "도로명API_도로명주소",
#             "도로명API_지번주소",
#             "우편번호",
#             "우편번호보완상태",
#             "택배물량_우편번호일치"
#         ]
#     ]
# )


# # ---------------------------------------------------------
# # 7. 최종 저장
# # ---------------------------------------------------------

# save_path = (
#     PROCESSED_DIR /
#     "대전_43개물류창고_우편번호_최종.csv"
# )

# warehouse.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)

전체 창고 수: 43
보완 전 우편번호 미확보: 4
도로명주소 검색 API 승인키를 입력하세요: ··········

[공식 주소 API 우편번호 보완 결과]
우편번호 확보: 42
우편번호 미확보: 1
택배물량 자료와 일치: 42
택배물량 자료와 불일치: 1

,WARE_NO,COMPANY_NAME,COMPANY_ADDRESS,도로명API_검색어,도로명API_도로명주소,도로명API_지번주소,우편번호,우편번호보완상태,택배물량_우편번호일치
21,2016S63000000001,한솔로지스틱스 주식회사,대전광역시 대덕구 평촌동 24번지 3호,대전광역시 대덕구 평촌동 24-3,<NA>,<NA>,<NA>,검색결과없음,False
22,2018S63000000003,주식회사 넥센,대전광역시 대덕구 대화동 40-30 넥센타이어,대전광역시 대덕구 대화동 40-30 넥센타이어,대전광역시 대덕구 대화로52번안길 55 (대화동),대전광역시 대덕구 대화동 40-30 넥센타이어,34365,공식주소API성공,True
23,2019A63000001505,엘리트,"대전광역시 중구 대둔산로300번길 36, 1,2층 (사정동)",대전광역시 중구 대둔산로300번길 36,대전광역시 중구 대둔산로300번길 36 (사정동),대전광역시 중구 사정동 442-3,35057,공식주소API성공,True
36,2024A63000001643,쿠팡 대전1 신선센터,"대전광역시 동구 안골로 33, 3,4층 (구도동)",대전광역시 동구 안골로 33,대전광역시 동구 안골로 33 (구도동),대전광역시 동구 구도동 397,34708,공식주소API성공,True

저장 완료:
/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/대전_43개물류창고_우편번호_최종.csv

- 우편번호 42/43 확보
- 확보된 42개 모두 택배물량 자료와 연결
- 미확보 1곳: 한솔로지스틱스 신탄진CY, 대덕구 평촌동 24-3
- 좌표상 가장 가까운 우편번호 확보 후 창고를 찾아 주소 검토 예정

3-4. 동일 물류거점 중복 후보 일괄 검수
- 43곳의 물류창고 중 주소 표기만 조금 다르고 동일 창고인 것 같은 거점이 확인됨

In [ ]:
# @title
# # =========================================================
# # 3-4. 동일 물류거점 중복 후보 일괄 검수
# # =========================================================

# from pathlib import Path
# import pandas as pd
# import numpy as np
# import re
# from itertools import combinations

# PROCESSED_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
# )

# # ---------------------------------------------------------
# # 1. 3-3 결과 불러오기
# # ---------------------------------------------------------

# path = (
#     PROCESSED_DIR /
#     "대전_43개물류창고_우편번호_최종.csv"
# )

# warehouse = pd.read_csv(
#     path,
#     encoding="utf-8-sig",
#     dtype={
#         "WARE_NO": str,
#         "우편번호": str
#     }
# )

# warehouse["위도"] = pd.to_numeric(
#     warehouse["위도"],
#     errors="coerce"
# )

# warehouse["경도"] = pd.to_numeric(
#     warehouse["경도"],
#     errors="coerce"
# )

# print("불러온 등록행 수:", len(warehouse))


# # ---------------------------------------------------------
# # 2. 주소 표준화 함수
# #
# # 괄호·번지·호·공백 등의 표현 차이를 줄여
# # 동일 부지 후보를 찾기 위한 비교용 주소 생성
# # ---------------------------------------------------------

# def normalize_address(address):

#     if pd.isna(address):
#         return ""

#     text = str(address).strip()

#     # 괄호와 괄호 안 설명 제거
#     text = re.sub(r"\([^)]*\)", " ", text)

#     # 번지·호 표현을 하이픈 형태로 통일
#     text = re.sub(
#         r"(\d+)\s*번지\s*(\d+)\s*호",
#         r"\1-\2",
#         text
#     )

#     text = re.sub(
#         r"(\d+)\s*번지",
#         r"\1",
#         text
#     )

#     # 층·동·창고동 등 세부 시설정보 일부 제거
#     text = re.sub(
#         r",?\s*(?:가동|나동|다동|라동|마동|바동|"
#         r"\d+(?:,\d+)*층|B?\d+호).*$",
#         "",
#         text,
#         flags=re.IGNORECASE
#     )

#     # 공백과 특수문자 정리
#     text = re.sub(r"[,]", " ", text)
#     text = re.sub(r"\s+", " ", text)

#     return text.strip()


# warehouse["표준화_원본주소"] = (
#     warehouse["COMPANY_ADDRESS"]
#     .apply(normalize_address)
# )

# # 이용 가능한 주소 열들을 하나로 모아 비교
# address_cols = [
#     "COMPANY_ADDRESS",
#     "카카오_도로명주소",
#     "카카오_지번주소",
#     "도로명API_도로명주소",
#     "도로명API_지번주소"
# ]

# for col in address_cols:

#     if col not in warehouse.columns:
#         warehouse[col] = pd.NA

#     warehouse[f"표준화_{col}"] = (
#         warehouse[col]
#         .apply(normalize_address)
#     )


# # ---------------------------------------------------------
# # 3. 거리 계산 함수
# # ---------------------------------------------------------

# def haversine_m(lat1, lon1, lat2, lon2):

#     radius = 6371000.0

#     lat1, lon1, lat2, lon2 = map(
#         np.radians,
#         [lat1, lon1, lat2, lon2]
#     )

#     dlat = lat2 - lat1
#     dlon = lon2 - lon1

#     a = (
#         np.sin(dlat / 2) ** 2
#         + np.cos(lat1)
#         * np.cos(lat2)
#         * np.sin(dlon / 2) ** 2
#     )

#     return 2 * radius * np.arcsin(np.sqrt(a))


# # ---------------------------------------------------------
# # 4. 모든 창고 쌍 비교
# #
# # 후보 조건:
# # ① 동일한 표준화 주소
# # ② 좌표 간 거리 30m 이하
# # ③ 동일 우편번호이면서 거리 100m 이하
# #
# # 후보만 추출하며 아직 자동 통합하지 않음
# # ---------------------------------------------------------

# candidate_rows = []

# standardized_cols = [
#     f"표준화_{col}"
#     for col in address_cols
# ]

# for idx1, idx2 in combinations(
#     warehouse.index,
#     2
# ):

#     row1 = warehouse.loc[idx1]
#     row2 = warehouse.loc[idx2]

#     reasons = []

#     # 주소가 하나라도 정확히 일치하는지 확인
#     common_addresses = set()

#     for col in standardized_cols:

#         addr1 = row1[col]
#         addr2 = row2[col]

#         if (
#             addr1
#             and addr2
#             and addr1 == addr2
#         ):
#             common_addresses.add(addr1)

#     if common_addresses:
#         reasons.append("표준화주소일치")

#     # 좌표 거리 계산
#     distance_m = np.nan

#     if (
#         pd.notna(row1["위도"])
#         and pd.notna(row1["경도"])
#         and pd.notna(row2["위도"])
#         and pd.notna(row2["경도"])
#     ):

#         distance_m = haversine_m(
#             row1["위도"],
#             row1["경도"],
#             row2["위도"],
#             row2["경도"]
#         )

#         if distance_m <= 30:
#             reasons.append("좌표30m이내")

#     # 같은 우편번호이고 100m 이내인지 확인
#     same_zip = (
#         pd.notna(row1["우편번호"])
#         and pd.notna(row2["우편번호"])
#         and row1["우편번호"] == row2["우편번호"]
#     )

#     if (
#         same_zip
#         and pd.notna(distance_m)
#         and distance_m <= 100
#     ):
#         reasons.append("동일우편번호_100m이내")

#     if reasons:

#         candidate_rows.append({
#             "행1_INDEX": idx1,
#             "행1_WARE_NO": row1["WARE_NO"],
#             "행1_창고명": row1["COMPANY_NAME"],
#             "행1_주소": row1["COMPANY_ADDRESS"],
#             "행1_우편번호": row1["우편번호"],

#             "행2_INDEX": idx2,
#             "행2_WARE_NO": row2["WARE_NO"],
#             "행2_창고명": row2["COMPANY_NAME"],
#             "행2_주소": row2["COMPANY_ADDRESS"],
#             "행2_우편번호": row2["우편번호"],

#             "거리_m": (
#                 round(distance_m, 1)
#                 if pd.notna(distance_m)
#                 else np.nan
#             ),

#             "동일주소": " / ".join(
#                 sorted(common_addresses)
#             ),

#             "중복후보근거": " + ".join(reasons)
#         })


# candidates = pd.DataFrame(candidate_rows)


# # ---------------------------------------------------------
# # 5. 강한 후보 우선 정렬
# #
# # 근거가 2개 이상이거나 좌표가 30m 이내인 후보를
# # 우선 검토하기 쉽게 정렬
# # ---------------------------------------------------------

# if not candidates.empty:

#     candidates["근거개수"] = (
#         candidates["중복후보근거"]
#         .str.count(r"\+")
#         + 1
#     )

#     candidates = candidates.sort_values(
#         [
#             "근거개수",
#             "거리_m"
#         ],
#         ascending=[
#             False,
#             True
#         ],
#         na_position="last"
#     ).reset_index(drop=True)


# # ---------------------------------------------------------
# # 6. 최소 검수 및 출력
# # ---------------------------------------------------------

# print("\n[동일 물류거점 중복 후보 검수 결과]")

# print(
#     "전체 등록행 수:",
#     len(warehouse)
# )

# print(
#     "중복 후보 쌍 수:",
#     len(candidates)
# )

# if candidates.empty:

#     print("중복 후보가 없습니다.")

# else:

#     print("\n후보 근거별 개수:")

#     print(
#         candidates["중복후보근거"]
#         .value_counts()
#     )

#     display(
#         candidates[
#             [
#                 "행1_WARE_NO",
#                 "행1_창고명",
#                 "행1_주소",
#                 "행2_WARE_NO",
#                 "행2_창고명",
#                 "행2_주소",
#                 "거리_m",
#                 "행1_우편번호",
#                 "행2_우편번호",
#                 "중복후보근거"
#             ]
#         ]
#     )


# # ---------------------------------------------------------
# # 7. 후보 결과 저장
# # ---------------------------------------------------------

# save_path = (
#     PROCESSED_DIR /
#     "대전_물류창고_동일거점_중복후보.csv"
# )

# candidates.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)

불러온 등록행 수: 43

[동일 물류거점 중복 후보 검수 결과]
전체 등록행 수: 43
중복 후보 쌍 수: 1

후보 근거별 개수:
중복후보근거
표준화주소일치    1
Name: count, dtype: int64

,행1_WARE_NO,행1_창고명,행1_주소,행2_WARE_NO,행2_창고명,행2_주소,거리_m,행1_우편번호,행2_우편번호,중복후보근거
0,2010A63000001044,씨제이대한통운(주),대전광역시 대덕구 대덕대로1447번길 39 (문평동),2010F63000000532,씨제이대한통운(주),"대전광역시 대덕구 대덕대로1447번길 39(가동 문평동, 씨제이대한통운택배허브터미널)",NaN,34301,34301,표준화주소일치

저장 완료:
/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/대전_물류창고_동일거점_중복후보.csv

3-5. 주소 변형 교차 비교 기반 동일 물류거점 재검수

In [ ]:
# @title
# # =========================================================
# # 3-5. 주소 변형 교차 비교 기반 동일 물류거점 재검수
# # =========================================================

# from pathlib import Path
# import pandas as pd
# import numpy as np
# import re
# from itertools import combinations

# PROCESSED_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
# )

# # ---------------------------------------------------------
# # 1. 3-3 결과 불러오기
# # ---------------------------------------------------------

# path = (
#     PROCESSED_DIR /
#     "대전_43개물류창고_우편번호_최종.csv"
# )

# warehouse = pd.read_csv(
#     path,
#     encoding="utf-8-sig",
#     dtype={
#         "WARE_NO": str,
#         "우편번호": str
#     }
# )

# warehouse["위도"] = pd.to_numeric(
#     warehouse["위도"],
#     errors="coerce"
# )

# warehouse["경도"] = pd.to_numeric(
#     warehouse["경도"],
#     errors="coerce"
# )

# print("불러온 등록행 수:", len(warehouse))


# # ---------------------------------------------------------
# # 2. 주소 표준화 함수
# # ---------------------------------------------------------

# def normalize_address(address):

#     if pd.isna(address):
#         return ""

#     text = str(address).strip()

#     # 괄호 및 상세 건물 설명 제거
#     text = re.sub(r"\([^)]*\)", " ", text)

#     # 번지·호 표준화
#     text = re.sub(
#         r"(\d+)\s*번지\s*(\d+)\s*호",
#         r"\1-\2",
#         text
#     )

#     text = re.sub(
#         r"(\d+)\s*번지",
#         r"\1",
#         text
#     )

#     # 층·동·호 등 상세시설 설명 제거
#     text = re.sub(
#         r",?\s*(?:가동|나동|다동|라동|마동|바동|"
#         r"창고동.*|\d+(?:,\d+)*층.*|B?\d+호.*)$",
#         "",
#         text,
#         flags=re.IGNORECASE
#     )

#     text = re.sub(r"[,]", " ", text)
#     text = re.sub(r"\s+", " ", text)

#     return text.strip()


# # ---------------------------------------------------------
# # 3. 행별 모든 주소 변형을 하나의 집합으로 생성
# #
# # 서로 다른 주소 열끼리도 교차 비교하기 위함
# # ---------------------------------------------------------

# address_cols = [
#     "COMPANY_ADDRESS",
#     "검색주소",
#     "도로명주소",
#     "지번주소",
#     "카카오검색주소",
#     "카카오_도로명주소",
#     "카카오_지번주소",
#     "지번표준검색주소",
#     "도로명API_검색어",
#     "도로명API_도로명주소",
#     "도로명API_지번주소"
# ]

# for col in address_cols:
#     if col not in warehouse.columns:
#         warehouse[col] = pd.NA


# def build_address_set(row):

#     address_set = set()

#     for col in address_cols:

#         value = normalize_address(
#             row[col]
#         )

#         if value:
#             address_set.add(value)

#     return address_set


# warehouse["주소변형집합"] = warehouse.apply(
#     build_address_set,
#     axis=1
# )


# # ---------------------------------------------------------
# # 4. 거리 계산 함수
# # ---------------------------------------------------------

# def haversine_m(lat1, lon1, lat2, lon2):

#     radius = 6371000.0

#     lat1, lon1, lat2, lon2 = map(
#         np.radians,
#         [lat1, lon1, lat2, lon2]
#     )

#     dlat = lat2 - lat1
#     dlon = lon2 - lon1

#     a = (
#         np.sin(dlat / 2) ** 2
#         + np.cos(lat1)
#         * np.cos(lat2)
#         * np.sin(dlon / 2) ** 2
#     )

#     return (
#         2
#         * radius
#         * np.arcsin(np.sqrt(a))
#     )


# # ---------------------------------------------------------
# # 5. 모든 등록행 쌍 재비교
# #
# # 후보 조건:
# # ① 모든 주소 변형 중 하나 이상 교차 일치
# # ② 좌표 30m 이내
# # ③ 동일 우편번호이면서 좌표 100m 이내
# # ---------------------------------------------------------

# candidate_rows = []

# for idx1, idx2 in combinations(
#     warehouse.index,
#     2
# ):

#     row1 = warehouse.loc[idx1]
#     row2 = warehouse.loc[idx2]

#     reasons = []

#     common_addresses = (
#         row1["주소변형집합"]
#         & row2["주소변형집합"]
#     )

#     if common_addresses:
#         reasons.append(
#             "주소변형_교차일치"
#         )

#     distance_m = np.nan

#     if (
#         pd.notna(row1["위도"])
#         and pd.notna(row1["경도"])
#         and pd.notna(row2["위도"])
#         and pd.notna(row2["경도"])
#     ):

#         distance_m = haversine_m(
#             row1["위도"],
#             row1["경도"],
#             row2["위도"],
#             row2["경도"]
#         )

#         if distance_m <= 30:
#             reasons.append(
#                 "좌표30m이내"
#             )

#     same_zip = (
#         pd.notna(row1["우편번호"])
#         and pd.notna(row2["우편번호"])
#         and row1["우편번호"]
#         == row2["우편번호"]
#     )

#     if (
#         same_zip
#         and pd.notna(distance_m)
#         and distance_m <= 100
#     ):
#         reasons.append(
#             "동일우편번호_100m이내"
#         )

#     if reasons:

#         candidate_rows.append({
#             "행1_INDEX": idx1,
#             "행1_WARE_NO": row1["WARE_NO"],
#             "행1_창고명": row1["COMPANY_NAME"],
#             "행1_주소": row1["COMPANY_ADDRESS"],

#             "행2_INDEX": idx2,
#             "행2_WARE_NO": row2["WARE_NO"],
#             "행2_창고명": row2["COMPANY_NAME"],
#             "행2_주소": row2["COMPANY_ADDRESS"],

#             "행1_우편번호": row1["우편번호"],
#             "행2_우편번호": row2["우편번호"],

#             "거리_m": (
#                 round(distance_m, 1)
#                 if pd.notna(distance_m)
#                 else np.nan
#             ),

#             "교차일치주소": " / ".join(
#                 sorted(common_addresses)
#             ),

#             "중복후보근거": " + ".join(
#                 reasons
#             )
#         })


# candidates = pd.DataFrame(
#     candidate_rows
# )

# if not candidates.empty:

#     candidates["근거개수"] = (
#         candidates["중복후보근거"]
#         .str.count(r"\+")
#         + 1
#     )

#     candidates = candidates.sort_values(
#         ["근거개수", "거리_m"],
#         ascending=[False, True],
#         na_position="last"
#     ).reset_index(drop=True)


# # ---------------------------------------------------------
# # 6. 검수 결과 출력
# # ---------------------------------------------------------

# print(
#     "\n[주소 교차 비교 중복 후보 결과]"
# )

# print(
#     "전체 등록행 수:",
#     len(warehouse)
# )

# print(
#     "중복 후보 쌍 수:",
#     len(candidates)
# )

# if not candidates.empty:

#     display(
#         candidates[
#             [
#                 "행1_WARE_NO",
#                 "행1_창고명",
#                 "행1_주소",
#                 "행2_WARE_NO",
#                 "행2_창고명",
#                 "행2_주소",
#                 "거리_m",
#                 "행1_우편번호",
#                 "행2_우편번호",
#                 "교차일치주소",
#                 "중복후보근거"
#             ]
#         ]
#     )


# # ---------------------------------------------------------
# # 7. 결과 저장
# # ---------------------------------------------------------

# save_path = (
#     PROCESSED_DIR /
#     "대전_물류창고_동일거점_중복후보_재검수.csv"
# )

# candidates.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)

불러온 등록행 수: 43

[주소 교차 비교 중복 후보 결과]
전체 등록행 수: 43
중복 후보 쌍 수: 3

,행1_WARE_NO,행1_창고명,행1_주소,행2_WARE_NO,행2_창고명,행2_주소,거리_m,행1_우편번호,행2_우편번호,교차일치주소,중복후보근거
0,2006F63000000187,동원로엑스(주)대전물류센타,대전광역시 대덕구 방두말1길 12(상서동),2025A63000000329,동원로엑스(주) 대전센터,"대전광역시 대덕구 방두말1길 12, (주)동원F&B (상서동)",NaN,34343,34343,대전광역시 대덕구 방두말1길 12,주소변형_교차일치
1,2010A63000001044,씨제이대한통운(주),대전광역시 대덕구 대덕대로1447번길 39 (문평동),2010F63000000532,씨제이대한통운(주),"대전광역시 대덕구 대덕대로1447번길 39(가동 문평동, 씨제이대한통운택배허브터미널)",NaN,34301,34301,대전광역시 대덕구 대덕대로1447번길 39,주소변형_교차일치
2,2024A63000001643,쿠팡 대전1 신선센터,"대전광역시 동구 안골로 33, 3,4층 (구도동)",2024S63000000002,쿠팡로지스틱스서비스 유한회사(대전2서브허브 외 1),대전광역시 동구 구도동 397번지,NaN,34708,34708,대전광역시 동구 구도동 397,주소변형_교차일치

저장 완료:
/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/대전_물류창고_동일거점_중복후보_재검수.csv

- 3개 중복군 확정
1) 동원로엑스 2행 -> 1거점
2) CJ대한통운 문평동 3행 -> 1거점
3) 쿠팡 구도동 2행 -> 1거점
- 총 43행 -> 39개 분석 거점

3-6. 중복 등록행 통합 및 39개 최종 분석 거점 생성

In [ ]:
# @title
# # =========================================================
# # 3-6. 중복 등록행 통합 및 39개 최종 분석 거점 생성
# # =========================================================

# from pathlib import Path
# import pandas as pd
# import numpy as np

# PROCESSED_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
# )

# # ---------------------------------------------------------
# # 1. 3-3 최종 우편번호 파일 불러오기
# # ---------------------------------------------------------

# path = (
#     PROCESSED_DIR /
#     "대전_43개물류창고_우편번호_최종.csv"
# )

# warehouse = pd.read_csv(
#     path,
#     encoding="utf-8-sig",
#     dtype={
#         "WARE_NO": str,
#         "우편번호": str
#     }
# )

# print("통합 전 등록행 수:", len(warehouse))


# # ---------------------------------------------------------
# # 2. 확정 중복군 정의
# #
# # 각 리스트에 포함된 등록번호는
# # 동일 물리적 물류거점으로 통합
# # ---------------------------------------------------------

# duplicate_groups = {
#     "LOC_CJ_MUNPYEONG": [
#         "2010A63000001044",
#         "2010F63000000532",
#         "2012S63000000006"
#     ],

#     "LOC_DONGWON_SANGSEO": [
#         "2006F63000000187",
#         "2025A63000000329"
#     ],

#     "LOC_COUPANG_GUDO": [
#         "2024A63000001643",
#         "2024S63000000002"
#     ]
# }

# representative_info = {
#     "LOC_CJ_MUNPYEONG": {
#         "대표거점명": "CJ대한통운 문평동 물류거점",
#         "대표주소": "대전광역시 대덕구 대덕대로1447번길 39"
#     },

#     "LOC_DONGWON_SANGSEO": {
#         "대표거점명": "동원로엑스 대전물류센터",
#         "대표주소": "대전광역시 대덕구 방두말1길 12"
#     },

#     "LOC_COUPANG_GUDO": {
#         "대표거점명": "쿠팡 구도동 물류거점",
#         "대표주소": "대전광역시 동구 안골로 33"
#     }
# }


# # ---------------------------------------------------------
# # 3. 각 등록행에 분석거점 ID 부여
# #
# # 중복군에 포함되지 않은 행은
# # WARE_NO를 이용해 개별 거점으로 유지
# # ---------------------------------------------------------

# ware_to_location = {}

# for location_id, ware_list in duplicate_groups.items():

#     for ware_no in ware_list:

#         ware_to_location[ware_no] = location_id


# warehouse["분석거점ID"] = warehouse["WARE_NO"].map(
#     ware_to_location
# )

# warehouse["분석거점ID"] = warehouse[
#     "분석거점ID"
# ].fillna(
#     "LOC_" + warehouse["WARE_NO"].astype(str)
# )


# # ---------------------------------------------------------
# # 4. 숫자형 열 정리
# # ---------------------------------------------------------

# numeric_cols = [
#     "위도",
#     "경도",
#     "STORAGE_AREA",
#     "GENERAL_AREA",
#     "FROZEN_AREA"
# ]

# for col in numeric_cols:

#     if col in warehouse.columns:

#         warehouse[col] = pd.to_numeric(
#             warehouse[col],
#             errors="coerce"
#         )


# # ---------------------------------------------------------
# # 5. 보조 함수
# # ---------------------------------------------------------

# def first_valid(series):

#     valid = series.dropna()

#     if len(valid) == 0:
#         return pd.NA

#     return valid.iloc[0]


# def unique_text(series):

#     values = (
#         series
#         .dropna()
#         .astype(str)
#         .str.strip()
#     )

#     values = [
#         value
#         for value in values.unique()
#         if value
#     ]

#     return " | ".join(values)


# def max_valid(series):

#     numeric = pd.to_numeric(
#         series,
#         errors="coerce"
#     )

#     if numeric.notna().sum() == 0:
#         return np.nan

#     return numeric.max()


# # ---------------------------------------------------------
# # 6. 분석거점별 통합
# #
# # 좌표·우편번호:
# #   동일 거점 내 첫 번째 정상값 사용
# #
# # 면적:
# #   중복 합산을 피하기 위해 최댓값 사용
# #
# # 원본 등록번호·사업장명·주소:
# #   모두 문자열로 보존
# # ---------------------------------------------------------

# location_rows = []

# for location_id, group in warehouse.groupby(
#     "분석거점ID",
#     sort=False
# ):

#     is_duplicate_group = (
#         location_id in duplicate_groups
#     )

#     if is_duplicate_group:

#         rep_name = representative_info[
#             location_id
#         ]["대표거점명"]

#         rep_address = representative_info[
#             location_id
#         ]["대표주소"]

#     else:

#         rep_name = first_valid(
#             group["COMPANY_NAME"]
#         )

#         rep_address = first_valid(
#             group["COMPANY_ADDRESS"]
#         )

#     location_rows.append({
#         "분석거점ID": location_id,
#         "대표거점명": rep_name,
#         "대표주소": rep_address,

#         "원본등록행수": len(group),
#         "원본_WARE_NO목록": unique_text(
#             group["WARE_NO"]
#         ),
#         "원본_사업장명목록": unique_text(
#             group["COMPANY_NAME"]
#         ),
#         "원본_주소목록": unique_text(
#             group["COMPANY_ADDRESS"]
#         ),

#         "우편번호": first_valid(
#             group["우편번호"]
#         ),
#         "위도": first_valid(
#             group["위도"]
#         ),
#         "경도": first_valid(
#             group["경도"]
#         ),

#         "대표_보관면적": max_valid(
#             group["STORAGE_AREA"]
#         ),
#         "대표_일반면적": max_valid(
#             group["GENERAL_AREA"]
#         ),
#         "대표_냉동면적": max_valid(
#             group["FROZEN_AREA"]
#         ),

#         "원본_보관면적목록": unique_text(
#             group["STORAGE_AREA"]
#         ),
#         "원본_일반면적목록": unique_text(
#             group["GENERAL_AREA"]
#         ),
#         "원본_냉동면적목록": unique_text(
#             group["FROZEN_AREA"]
#         ),

#         "중복통합여부": (
#             "통합"
#             if len(group) > 1
#             else "개별"
#         )
#     })


# locations = pd.DataFrame(location_rows)


# # ---------------------------------------------------------
# # 7. 최소 검수
# # ---------------------------------------------------------

# print("\n[최종 분석 거점 생성 결과]")

# print(
#     "통합 전 등록행 수:",
#     len(warehouse)
# )

# print(
#     "최종 분석 거점 수:",
#     len(locations)
# )

# print(
#     "중복 통합 거점 수:",
#     (locations["중복통합여부"] == "통합").sum()
# )

# print(
#     "개별 유지 거점 수:",
#     (locations["중복통합여부"] == "개별").sum()
# )

# print(
#     "원본 등록행 수 합계:",
#     locations["원본등록행수"].sum()
# )

# print(
#     "우편번호 미확보 거점:",
#     locations["우편번호"].isna().sum()
# )

# print(
#     "좌표 미확보 거점:",
#     locations[
#         ["위도", "경도"]
#     ].isna().any(axis=1).sum()
# )


# # ---------------------------------------------------------
# # 8. 통합된 거점만 확인
# # ---------------------------------------------------------

# print("\n[중복 통합 거점 확인]")

# display(
#     locations[
#         locations["중복통합여부"] == "통합"
#     ][
#         [
#             "분석거점ID",
#             "대표거점명",
#             "대표주소",
#             "원본등록행수",
#             "원본_WARE_NO목록",
#             "원본_사업장명목록",
#             "우편번호",
#             "위도",
#             "경도"
#         ]
#     ]
# )


# # ---------------------------------------------------------
# # 9. 전체 최종 거점 저장
# # ---------------------------------------------------------

# save_path = (
#     PROCESSED_DIR /
#     "대전_최종_물류거점_39개.csv"
# )

# locations.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)

통합 전 등록행 수: 43

[최종 분석 거점 생성 결과]
통합 전 등록행 수: 43
최종 분석 거점 수: 39
중복 통합 거점 수: 3
개별 유지 거점 수: 36
원본 등록행 수 합계: 43
우편번호 미확보 거점: 1
좌표 미확보 거점: 39

[중복 통합 거점 확인]

,분석거점ID,대표거점명,대표주소,원본등록행수,원본_WARE_NO목록,원본_사업장명목록,우편번호,위도,경도
1,LOC_DONGWON_SANGSEO,동원로엑스 대전물류센터,대전광역시 대덕구 방두말1길 12,2,2006F63000000187 | 2025A63000000329,동원로엑스(주)대전물류센타 | 동원로엑스(주) 대전센터,34343,<NA>,<NA>
4,LOC_CJ_MUNPYEONG,CJ대한통운 문평동 물류거점,대전광역시 대덕구 대덕대로1447번길 39,3,2010A63000001044 | 2010F63000000532 | 2012S630...,씨제이대한통운(주) | 씨제이대한통운(주) 문평동지점,34301,<NA>,<NA>
34,LOC_COUPANG_GUDO,쿠팡 구도동 물류거점,대전광역시 동구 안골로 33,2,2024A63000001643 | 2024S63000000002,쿠팡 대전1 신선센터 | 쿠팡로지스틱스서비스 유한회사(대전2서브허브 외 1),34708,<NA>,<NA>

저장 완료:
/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/대전_최종_물류거점_39개.csv

- 좌표 미확보 39개
- 3-3의 위경도 열에 값이 제대로 이어지지 않았기 때문
- 2-0의 검증된 좌표 격자 파일을 다시 연결 예정

3-7. 최종 39개 거점 좌표 및 기상청 격자 재연결

In [ ]:
# @title
# # =========================================================
# # 3-7. 최종 39개 거점 좌표·기상청 격자 재연결
# # =========================================================

# from pathlib import Path
# import pandas as pd
# import numpy as np

# PROCESSED_DIR = Path(
#     "/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터"
# )

# # ---------------------------------------------------------
# # 1. 3-6에서 만든 39개 거점 파일 불러오기
# # ---------------------------------------------------------

# location_path = (
#     PROCESSED_DIR /
#     "대전_최종_물류거점_39개.csv"
# )

# locations = pd.read_csv(
#     location_path,
#     encoding="utf-8-sig",
#     dtype={
#         "분석거점ID": str,
#         "원본_WARE_NO목록": str,
#         "우편번호": str
#     }
# )

# print("최종 거점 수:", len(locations))


# # ---------------------------------------------------------
# # 2. 2-9의 검증된 창고 좌표·기상청 격자 파일 불러오기
# # ---------------------------------------------------------

# coord_path = (
#     PROCESSED_DIR /
#     "대전_물류창고_좌표_기상청격자.csv"
# )

# coords = pd.read_csv(
#     coord_path,
#     encoding="utf-8-sig",
#     dtype={"WARE_NO": str}
# )

# print("좌표 원자료 행 수:", len(coords))
# print("좌표 원자료 열:", coords.columns.tolist())


# # ---------------------------------------------------------
# # 3. 실제 좌표·격자 열 이름 자동 확인
# # ---------------------------------------------------------

# longitude_candidates = [
#     "경도", "longitude", "lon", "x"
# ]

# latitude_candidates = [
#     "위도", "latitude", "lat", "y"
# ]

# grid_x_candidates = [
#     "격자X", "격자_X", "nx", "기상청격자X"
# ]

# grid_y_candidates = [
#     "격자Y", "격자_Y", "ny", "기상청격자Y"
# ]


# def find_column(df, candidates):

#     for col in candidates:

#         if col in df.columns:
#             return col

#     return None


# lon_col = find_column(
#     coords,
#     longitude_candidates
# )

# lat_col = find_column(
#     coords,
#     latitude_candidates
# )

# grid_x_col = find_column(
#     coords,
#     grid_x_candidates
# )

# grid_y_col = find_column(
#     coords,
#     grid_y_candidates
# )

# print("\n확인된 경도 열:", lon_col)
# print("확인된 위도 열:", lat_col)
# print("확인된 격자X 열:", grid_x_col)
# print("확인된 격자Y 열:", grid_y_col)

# if lon_col is None or lat_col is None:

#     raise KeyError(
#         "2-9 좌표 파일에서 위도·경도 열을 찾지 못했습니다."
#     )

# if grid_x_col is None or grid_y_col is None:

#     raise KeyError(
#         "2-9 좌표 파일에서 기상청 격자 열을 찾지 못했습니다."
#     )


# # ---------------------------------------------------------
# # 4. 숫자형 변환
# # ---------------------------------------------------------

# for col in [
#     lon_col,
#     lat_col,
#     grid_x_col,
#     grid_y_col
# ]:

#     coords[col] = pd.to_numeric(
#         coords[col],
#         errors="coerce"
#     )


# # ---------------------------------------------------------
# # 5. 원본 WARE_NO 목록을 행 단위로 분리
# #
# # 예:
# # A | B | C → 3개 행
# # ---------------------------------------------------------

# location_ware = (
#     locations[
#         [
#             "분석거점ID",
#             "원본_WARE_NO목록"
#         ]
#     ]
#     .assign(
#         WARE_NO=lambda x:
#         x["원본_WARE_NO목록"]
#         .str.split(r"\s*\|\s*", regex=True)
#     )
#     .explode("WARE_NO")
# )

# location_ware["WARE_NO"] = (
#     location_ware["WARE_NO"]
#     .astype(str)
#     .str.strip()
# )


# # ---------------------------------------------------------
# # 6. WARE_NO 기준 좌표·격자 연결
# # ---------------------------------------------------------

# coord_base = coords[
#     [
#         "WARE_NO",
#         lon_col,
#         lat_col,
#         grid_x_col,
#         grid_y_col
#     ]
# ].copy()

# coord_base = coord_base.rename(
#     columns={
#         lon_col: "경도_원자료",
#         lat_col: "위도_원자료",
#         grid_x_col: "격자X_원자료",
#         grid_y_col: "격자Y_원자료"
#     }
# )

# location_ware = location_ware.merge(
#     coord_base,
#     on="WARE_NO",
#     how="left"
# )


# # ---------------------------------------------------------
# # 7. 통합 거점별 대표 좌표·격자 선정
# #
# # 동일 물리적 거점은 좌표가 같거나 매우 유사하므로
# # 중앙값을 사용해 대표 좌표를 산출
# # ---------------------------------------------------------

# location_coord = (
#     location_ware
#     .groupby(
#         "분석거점ID",
#         as_index=False
#     )
#     .agg(
#         위도=("위도_원자료", "median"),
#         경도=("경도_원자료", "median"),
#         격자X=("격자X_원자료", "first"),
#         격자Y=("격자Y_원자료", "first"),
#         좌표연결등록행수=(
#             "위도_원자료",
#             "count"
#         )
#     )
# )


# # ---------------------------------------------------------
# # 8. 기존 잘못된 좌표 열 제거 후 다시 연결
# # ---------------------------------------------------------

# locations = locations.drop(
#     columns=[
#         "위도",
#         "경도",
#         "격자X",
#         "격자Y"
#     ],
#     errors="ignore"
# )

# locations = locations.merge(
#     location_coord,
#     on="분석거점ID",
#     how="left"
# )


# # ---------------------------------------------------------
# # 9. 최소 검수
# # ---------------------------------------------------------

# print("\n[39개 거점 좌표 재연결 결과]")

# print(
#     "최종 분석 거점 수:",
#     len(locations)
# )

# print(
#     "좌표 미확보 거점:",
#     locations[
#         ["위도", "경도"]
#     ].isna().any(axis=1).sum()
# )

# print(
#     "격자 미확보 거점:",
#     locations[
#         ["격자X", "격자Y"]
#     ].isna().any(axis=1).sum()
# )

# print(
#     "고유 기상청 격자 수:",
#     locations[
#         ["격자X", "격자Y"]
#     ].drop_duplicates().shape[0]
# )

# print(
#     "우편번호 미확보 거점:",
#     locations["우편번호"].isna().sum()
# )

# display(
#     locations[
#         locations["중복통합여부"] == "통합"
#     ][
#         [
#             "분석거점ID",
#             "대표거점명",
#             "대표주소",
#             "원본등록행수",
#             "위도",
#             "경도",
#             "격자X",
#             "격자Y",
#             "우편번호"
#         ]
#     ]
# )


# # ---------------------------------------------------------
# # 10. 수정된 최종 파일 저장
# # ---------------------------------------------------------

# save_path = (
#     PROCESSED_DIR /
#     "대전_최종_물류거점_39개_좌표격자완료.csv"
# )

# locations.to_csv(
#     save_path,
#     index=False,
#     encoding="utf-8-sig"
# )

# print("\n저장 완료:")
# print(save_path)

최종 거점 수: 39
좌표 원자료 행 수: 43
좌표 원자료 열: ['WARE_NO', 'COMPANY_NAME', 'COMPANY_ADDRESS', 'STORAGE_ITEM', 'STORAGE_AREA', 'GENERAL_AREA', 'FROZEN_AREA', '검색주소', '도로명주소', '지번주소', '우편번호', 'admCd', 'rnMgtSn', 'udrtYn', 'buldMnnm', 'buldSlno', '경도', '위도', '주소검색상태', '카카오검색주소', '카카오_도로명주소', '카카오_지번주소', '카카오_우편번호', '좌표검색상태', '지번표준검색주소', 'nx', 'ny']

확인된 경도 열: 경도
확인된 위도 열: 위도
확인된 격자X 열: nx
확인된 격자Y 열: ny

[39개 거점 좌표 재연결 결과]
최종 분석 거점 수: 39
좌표 미확보 거점: 0
격자 미확보 거점: 0
고유 기상청 격자 수: 11
우편번호 미확보 거점: 1

,분석거점ID,대표거점명,대표주소,원본등록행수,위도,경도,격자X,격자Y,우편번호
1,LOC_DONGWON_SANGSEO,동원로엑스 대전물류센터,대전광역시 대덕구 방두말1길 12,2,36.429692,127.425247,68,102,34343
4,LOC_CJ_MUNPYEONG,CJ대한통운 문평동 물류거점,대전광역시 대덕구 대덕대로1447번길 39,3,36.449322,127.407882,68,103,34301
34,LOC_COUPANG_GUDO,쿠팡 구도동 물류거점,대전광역시 동구 안골로 33,2,36.268957,127.473655,69,99,34708

저장 완료:
/content/drive/MyDrive/대전_물류창고_폭염위험도/03_전처리데이터/대전_최종_물류거점_39개_좌표격자완료.csv

- 최종 분석 거점: 39개
- 좌표 미확보: 0개
- 격자 미확보: 0개
- 고유 기상청 격자: 11개
- 우편번호 미확보: 1개